### ISSUE TITLE
login failed with error 'pytz_deprecation_shim'

### ISSUE THREAD

**Issue by evisanzay** [ecederstrand/exchangelib#1002]
When I try to login using the lib I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/exchangelib/ewsdatetime.py", line 272, in from_timezone
    return {
KeyError: 'pytz_deprecation_shim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/mailwatch.py", line 5, in <module>
    account = Account('john@example.com', credentials=credentials, autodiscover=True)
  File "/usr/local/lib/python3.10/site-packages/exchangelib/account.py", line 103, in __init__
    self.default_timezone = EWSTimeZone.localzone()
  File "/usr/local/lib/python3.10/site-packages/exchangelib/ewsdatetime.py", line 290, in localzone
    return cls.from_timezone(tz)
  File "/usr/local/lib/python3.10/site-packages/exchangelib/ewsdatetime.py", line 280, in from_timezone
    raise TypeError('Unsupported tzinfo type: %r' % tz)
TypeError: Unsupported tzinfo type: _PytzShimTimezone(zoneinfo.ZoneInfo(key='Etc/UTC'), 'Etc/UTC')

I get this trying to connect with your example code:

----------------------
from exchangelib import Credentials, Account

credentials = Credentials('$$$', '$$$')
account = Account('$$$', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)
------------------------

**Comment by BasPH** [comment]
Bumped into this too. Turns out the exact version it was added in `tzlocal` is version `4.0b3`, so setting an upper bound `tzlocal<=4.0b2` works around the issue.

**Comment by LeoUfimtsev** [comment]
> I'm facing this same issue. Here's a very temporary fix you might find helpful until this is resolved. The trick is explicitly setting the timezone in the Account object creation, so that is doesn't have to be resolved by tzlocal (which is the module responsible for this error)
> 
> ```python
> from exchangelib ACCOUNT, UTC, DELEGATE
> 
> return Account(
>         primary_smtp_address=event["email_address"],
>         config=config,
>         autodiscover=False,
>         access_type=DELEGATE,
>         default_timezone=UTC
>     )
> ```

Thank you very much for your comment. I was stuck on this for a while. It solved my issue.

As a note for future readers, the above has minor bugs. Here's working snippets:

```
from exchangelib import UTC, DELEGATE, EWSTimeZone
#account = Account(USER_EMAIL, config=config, access_type=DELEGATE, default_timezone=UTC)
USER_TZ_STR = 'America/Toronto'
 account = Account(USER_EMAIL, config=config, access_type=DELEGATE,   default_timezone=EWSTimeZone(USER_TZ_STR))
```
