### ISSUE TITLE
errors using account.inbox.filter()

### ISSUE THREAD

**Issue by bschnei** [ecederstrand/exchangelib#1035]
I am getting an error when calling `account.inbox.filter()` in version 4.7.0 that I do not receive in version 4.6.2. After a successful login using the `Account()` constructor with `autodiscover=True`, the following call raises an exception:

`account.inbox.filter(datetime_received__gte=since_date, sender=from_address)`

`since_date` is a datetime object with a value of `2021-12-16 00:00:00-08:00`
`from_address` is a valid email address string

Full traceback follows:

```
Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 196, in get_session
    session = self._session_pool.get(block=False)
  File "C:\Program Files\Python38\lib\queue.py", line 167, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 246, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 208, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 332, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 282, in _get_response
    session = self.protocol.get_session()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 200, in get_session
    self.increase_poolsize()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 170, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 271, in create_session
    if self.auth_type == NTLM and self.credentials.type == self.credentials.EMAIL:
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 81, in auth_type
    self.config.auth_type = self.get_auth_type()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 107, in get_auth_type
    auth_type, api_version_hint = get_service_authtype(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\transport.py", line 137, in get_service_authtype
    _back_off_if_needed(retry_policy.back_off_until)
AttributeError: 'NoneType' object has no attribute 'back_off_until'
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 196, in get_session
    session = self._session_pool.get(block=False)
  File "C:\Program Files\Python38\lib\queue.py", line 167, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\account.py", line 221, in inbox
    return self.root.get_default_folder(Inbox)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\account.py", line 285, in root
    return Root.get_distinguished(account=self)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\roots.py", line 109, in get_distinguished
    return cls.resolve(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\base.py", line 430, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\collections.py", line 313, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\collections.py", line 376, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\get_folder.py", line 39, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 226, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 246, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 208, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 332, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 282, in _get_response
    session = self.protocol.get_session()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 200, in get_session
    self.increase_poolsize()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 170, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 271, in create_session
    if self.auth_type == NTLM and self.credentials.type == self.credentials.EMAIL:
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 81, in auth_type
    self.config.auth_type = self.get_auth_type()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 107, in get_auth_type
    auth_type, api_version_hint = get_service_authtype(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\transport.py", line 137, in get_service_authtype
    _back_off_if_needed(retry_policy.back_off_until)
AttributeError: 'NoneType' object has no attribute 'back_off_until'
```

_Originally posted by @bschnei in https://github.com/ecederstrand/exchangelib/issues/1034#issuecomment-1013382179_

**Comment by ecederstrand** [comment]
Thanks for the bug report!

**Comment by ecederstrand** [comment]
v4.7.1 was released earlier today.
