### ISSUE TITLE
Timezone "CEST" not found

### ISSUE THREAD

**Issue by greuff** [ecederstrand/exchangelib#1076]
exchangelib 4.7.2, Python 3.9.2 (Debian Bullseye)

During fetching events I'm getting the error:

```
exchangelib.errors.UnknownTimeZone: No time zone found with key CEST
```

It is indeed the case that there is no `CEST` file in my `tzdata/zoneinfo` directory. Is there a way to override this? Thank you in advance!

**Comment by greuff** [comment]
Sure, thanks for taking the time to look into this. Here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/lib/python3.9/importlib/resources.py", line 91, in open_binary
    return reader.open_resource(resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/tzdata/zoneinfo/CEST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 214, in __new__
    instance = super().__new__(cls, *args, **kwargs)
  File "/usr/lib/python3.9/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key CEST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tw/teococal/main.py", line 26, in <module>
    for item in account.calendar.view(start=start, end=end):
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/queryset.py", line 273, in __iter__
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/queryset.py", line 348, in _item_yielder
    for i in iterable:
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/account.py", line 719, in fetch
    yield from self._consume_item_service(
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/account.py", line 408, in _consume_item_service
    is_empty, items = peek(items)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/util.py", line 149, in peek
    first = next(iterable)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/folders/collections.py", line 211, in find_items
    yield from FindItem(account=self.account, page_size=page_size).call(
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/services/common.py", line 252, in _elems_to_objs
    for elem in elems:
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/services/common.py", line 814, in _paged_call
    pages = self._get_pages(payload_func, kwargs, len(paging_infos))
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/services/common.py", line 910, in _get_pages
    payload = payload_func(**kwargs)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/services/find_item.py", line 104, in get_payload
    view_type = calendar_view.to_xml(version=self.account.version)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/properties.py", line 309, in to_xml
    self.clean(version=version)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/properties.py", line 893, in clean
    super().clean(version=version)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/properties.py", line 290, in clean
    setattr(self, f.name, f.clean(val, version=version))
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/fields.py", line 695, in clean
    value = self.value_cls.from_datetime(value)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 122, in from_datetime
    tz = EWSTimeZone.from_timezone(d.tzinfo)
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 277, in from_timezone
    return {
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 256, in from_datetime
    return cls(tz.tzname(None))
  File "/home/tw/.local/share/virtualenvs/teococal-Vw025WAc/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 216, in __new__
    raise UnknownTimeZone(e.args[0])
exchangelib.errors.UnknownTimeZone: No time zone found with key CEST
```

**Comment by ecederstrand** [comment]
Thanks! Please enable [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and post the XML for one of the `CalendarItem` elements that mentions the `CEST` timezone. Make sure to remove any sensitive information from the XML before you post it.

**Comment by greuff** [comment]
Here is the log. Unfortunately it doesn't mention "CEST" or "CalendarItem" anywhere. But the XML objects are in there: [log.txt](https://github.com/ecederstrand/exchangelib/files/8410030/log.txt)

For completeness, here is the whole script:

```
import logging
# This handler will pretty-print and syntax highlight the request and response
# XML documents
from exchangelib.util import PrettyXmlHandler
from exchangelib import Credentials, Account, Configuration, DELEGATE, FaultTolerance
import datetime
import ics
from exchangelib.winzone import MS_TIMEZONE_TO_IANA_MAP

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

MS_TIMEZONE_TO_IANA_MAP['Customized Time Zone'] = 'Europe/Vienna'

local_timezone = datetime.datetime.now().astimezone().tzinfo
start = datetime.datetime.now(local_timezone).replace(hour=0, minute=0, second=0, microsecond=0) - datetime.timedelta(days=30)
end = start + datetime.timedelta(days=3*30)
logging.debug(f"syncing from {start} to {end}")

credentials = Credentials('EMEA\\xxx', 'xxx')
config = Configuration(service_endpoint='https://xxx/EWS/Exchange.asmx', credentials=credentials, retry_policy=FaultTolerance(max_wait=1800))
account = Account(primary_smtp_address='xxx@xxx.com', config=config, autodiscover=False, access_type=DELEGATE)

cal = ics.Calendar()

for item in account.calendar.view(start=start, end=end):

	logging.debug(f"{item.start} to {item.end}: {item.subject}")

	e = ics.Event()
	e.name = item.subject
	e.begin = datetime.datetime.fromisoformat(item.start.isoformat())
	e.end = datetime.datetime.fromisoformat(item.end.isoformat())
	if item.text_body is not None:
		e.description = item.text_body.replace('\r', '')
	if item.location is not None:
		e.url = item.location
	if item.is_all_day:
		e.make_all_day()
	cal.events.add(e)

print(cal)
```

**Comment by ecederstrand** [comment]
Ah, so it's the `start` and `end` attributes to `calendar.view()` that are problematic. Try passing a `tzinfo` object that is compatible with exchangelib:

```python
from exchangelib import EWSTimeZone
start = datetime.datetime.now(tz=account.default_timezone)
# or
start = datetime.datetime.now(tz=EWSTimeZone(key='Europe/Copenhagen'))
```

**Comment by greuff** [comment]
That was it! Thank you very much!
