### ISSUE TITLE
DNS timeout after code has worked for months.

### ISSUE THREAD

**Issue by bostevensspinakr** [ecederstrand/exchangelib#1083]
Hey, love your package! It's so much easier than working with Gmail.

**Describe the bug**
Code that has worked for months stopped working today. DNS times out.

**To Reproduce**
```
credentials = Credentials(username=OUTLOOK_EMAIL, password=OUTLOOK_PASS)

outlook_account = Account(
    primary_smtp_address=OUTLOOK_EMAIL,
    credentials=credentials,
    autodiscover=True,
    access_type=DELEGATE,
)
```

**Expected behavior**
I expected to log in and read emails.

**Log output**
```
Traceback (most recent call last):
  File "C:\Users\boste\coding\bnsfl_invoice_upload\src\bnsfl_invoice_upload\action\main.py", line 8, in <module>
    from bnsfl_invoice_upload.action.download_and_send_outlook import (
  File "C:\Users\boste\coding\bnsfl_invoice_upload\src\bnsfl_invoice_upload\action\download_and_send_outlook.py", line 24, in <module>
    outlook_account = Account(
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\account.py", line 179, in __init__
    self.ad_response, self.protocol = Autodiscovery(
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 123, in discover
    ad_response = self._step_1(hostname=domain)
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 408, in _step_1
    is_valid_response, ad = self._attempt_response(url=url)
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 323, in _attempt_response
    auth_type, r = self._get_unauthenticated_response(url=url)
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 234, in _get_unauthenticated_response
    if not self._is_valid_hostname(hostname):
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 360, in _is_valid_hostname
    self.resolver.resolve(hostname)
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\dns\resolver.py", line 1066, in resolve
    timeout = self._compute_timeout(start, lifetime,
  File "C:\Users\boste\coding\bnsfl_invoice_upload\venv\lib\site-packages\dns\resolver.py", line 879, in _compute_timeout
    raise LifetimeTimeout(timeout=duration, errors=errors)
dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.005582571029663 seconds: Server 172.30.1.49 UDP port 53 answered The DNS operation timed out.
```

**Additional context**
For example, Python and exchangelib versions.
```
python 3.9.9
Package                Version     Location
---------------------- ----------- ----------------------------------------------
async-generator        1.10
atomicwrites           1.4.0
attrs                  21.4.0
bnsfl-invoice-upload   0.4.0       c:\users\boste\coding\bnsfl_invoice_upload\src
cached-property        1.5.2
certifi                2021.10.8
cffi                   1.15.0
colorama               0.4.4
cryptography           36.0.1
defusedxml             0.7.1
dnspython              2.2.0
easyocr                1.4.1
exchangelib            4.7.2
h11                    0.13.0
idna                   3.3
imageio                2.9.0
iniconfig              1.1.1
isodate                0.6.1
lxml                   4.7.1
networkx               2.6.3
ntlm-auth              1.5.0
numpy                  1.22.2
oauthlib               3.2.0
opencv-python          4.5.5.64
opencv-python-headless 4.5.5.62
outcome                1.1.0
packaging              21.3
pdf2image              1.16.0
Pillow                 8.2.0
pip                    21.2.4
pluggy                 1.0.0
py                     1.11.0
pycparser              2.21
Pygments               2.11.2
pyOpenSSL              22.0.0
pyparsing              3.0.7
PyPDF2                 1.27.4
pytesseract            0.3.8
pytest                 7.0.1
python-bidi            0.4.2
pytz-deprecation-shim  0.1.0.post0
PyWavelets             1.2.0
PyYAML                 6.0
requests               2.27.1
requests-ntlm          1.1.0
requests-oauthlib      1.3.1
scikit-image           0.19.1
scipy                  1.8.0
selenium               4.1.0
setuptools             58.1.0
six                    1.16.0
sniffio                1.2.0
sortedcontainers       2.4.0
tenacity               8.0.1
tifffile               2022.2.9
tomli                  2.0.1
torch                  1.10.2
torchvision            0.11.3
trio                   0.19.0
trio-websocket         0.9.2
typing_extensions      4.0.1
tzdata                 2021.5
tzlocal                4.1
urllib3                1.26.8
wsproto                1.0.0
```

**Comment by ecederstrand** [comment]
That looks like a problem with your DNS server? `172.30.1.49` is not responding within the default timeout of 5 seconds.

**Comment by bostevensspinakr** [comment]
I'm not sure why this would be. I've changed no code, and I can still access my Outlook through the browser. Any ideas?

**Comment by bostevensspinakr** [comment]
If I haven't explicitly cached the IP address of the mailserver, is there a chance that it's being cached? I'm wondering if the IP address / port number has changed.

**Comment by ecederstrand** [comment]
Autodiscovery is not used through the browser. That's why Outlook still works. Is this an O365 account? If so, you don't need to use autodiscover.

WRT the problem at hand, your DNS server at `172.30.1.49` is either not responding, or very slow to respond. Depending on which operating system you're on, you can try something like `whois your_domain.com` in a terminal to see if that works.

**Comment by bostevensspinakr** [comment]
Thanks. I changed my instantiation of Account to:

```
credentials = Credentials(username=OUTLOOK_EMAIL, password=OUTLOOK_PASS)
config = Configuration(server='outlook.office.com', credentials=credentials)

outlook_account = Account(
    primary_smtp_address=OUTLOOK_EMAIL,
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)
```

I then got errors about invalid credentials, as I tried different URLs for `server`. I figured I had the wrong server. This whole time, I was still logged in in my browser. I logged out, tried logging in through the 365 site (since you mentioned 365), and they told me my password had expired and required a reset. After resetting my password, everything worked normally again.

Why would this throw a DNSTimeout Error?

**Comment by ecederstrand** [comment]
It's impossible to say, really, without access to the real email domain and the system you're testing from. It could be anything from a local config problem in your OS to network issues to an autodiscover config issue.

I'm glad you got it sorted!
