### ISSUE TITLE
Could not connect on a shared mailbox, everything works fine on a personal one

### ISSUE THREAD

**Issue by hdbiza** [ecederstrand/exchangelib#1091]
Hi,
I'm using an account with two mailboxes : 
--> Personnal mailbox : test@domain.com
--> Shared mailbox : shared_test@domain.com

Everything works fine when trying to connect to the personal one.
when trying to connect to the shared one, i get the following error :

Traceback (most recent call last):                                                                                     File "C:\Users\hdbiza\OneDrive - BOUYGUES TELECOM\Bureau\Bureau\Python\ExchangeUtils.py", line 5, in <module>          exchange_account = Account(                                                                                        File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\account.py", line 181, in __init__                                            ).discover()                                                                                                       File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 140, in discover                             return self.discover()                                                                                             File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 130, in discover                             ad_response = self._step_1(hostname=domain)                                                                        File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 419, in _step_1                              return self._step_2(hostname=hostname)                                                                             File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 435, in _step_2                              return self._step_3(hostname=hostname)                                                                             File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 470, in _step_3                              return self._step_4(hostname=hostname)                                                                             File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 497, in _step_4                              return self._step_6()                                                                                              File "C:\Users\hdbiza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\exchangelib\autodiscover\discovery.py", line 551, in _step_6                              raise AutoDiscoverFailed(                                                                                        exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed for email shared_test@BDIGITAL.mail.onmicrosoft.com. If you think this is an error, consider doing an official test at https://testconnectivity.microsoft.com 

here is my code :

```python
from exchangelib import DELEGATE, Credentials, Account

exchange_account = Account(
    primary_smtp_address = 'shared_test@domain.com',
    credentials = Credentials(username = 'domain\\account_username', password = 'account_password'),
    autodiscover = True,
    access_type = DELEGATE
)
print(exchange_account.inbox.tree())
```

Please note also that this code worked fine for several weeks until yesterday.
I have no idea what change had been made that made it not working anymore.

Please note that both mailboxes can be accessed using outlook. Both exchange connections are OK on outlook.

**Comment by ecederstrand** [comment]
Did you follow the recommendation in the error message to test at https://testconnectivity.microsoft.com?

Also, if both accounts are located on Office365, then there's no need to do autodiscover. Just set the EWS server directly. See https://ecederstrand.github.io/exchangelib/#optimizing-connections

**Comment by hdbiza** [comment]
Hi,
Thank you for your quick response,
I was able to connect with no problems when specifying the ews server directly 👍 .

But :), i'm getting the following error when trying to retreive for example the root tree of the shared account :

![image](https://user-images.githubusercontent.com/65900638/174017997-76333839-2c6e-4e0f-b679-91fbbb4798b9.png)


When using the personal account with ews server, everything is ok. All informations on all folders are retreived with no issue.

Please note that the exact same error appears when trying to get anything from the account (sent, inbox, root, drafts, contacts...)


Thank you for your help 👍

**Comment by hdbiza** [comment]
yes indeed, I think that the shared account is located in different place than the personal one. will check with the EWS administrator. Thank you ! I'll mark this issue as closed
