### ISSUE TITLE
Invalid credentials issues

### ISSUE THREAD

**Issue by BhavyaJainBHF** [ecederstrand/exchangelib#1099]
**Describe the bug**
When using exchangelib for accessing outlook mail to autosave the .pdf attachments I was able to login and fetch mails till yesterday but it fails today.

**To Reproduce**
Following piece of code:
```python
credentials = Credentials('user_name@domain.com', 'user_password')
account = Account('user_name@domain.com', credentials=credentials, autodiscover=True)
local_path = r'folder_path'
folder = account.root/'Top of Information Store'/'Inbox'
since = UTC_NOW() - timedelta(hours=24)
````
When debugging expectation is raised while fetching the 'folder' variable.

**Expected behavior**
Should be able to access mails and attachments as earlier.

**Log output**
 File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Bhavya\Desktop\Projects\PDF Extractor\o365MailReading.py", line 9, in <module>
    folder = account.root/'Top of Information Store'/'Inbox'
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\account.py", line 349, in root
    return Root.get_distinguished(account=self)
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\folders\roots.py", line 115, in get_distinguished
    return cls.resolve(
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\folders\base.py", line 513, in resolve    
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\folders\collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\folders\collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\common.py", line 245, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\common.py", line 265, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\common.py", line 227, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\common.py", line 343, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\services\common.py", line 297, in _get_response
    r, session = post_ratelimited(
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\util.py", line 917, in post_ratelimited   
    protocol.retry_policy.raise_response_errors(r)  # Always raises an exception
  File "C:\Users\Bhavya\AppData\Local\Programs\Python\Python310\lib\site-packages\exchangelib\protocol.py", line 676, in raise_response_errors
    raise UnauthorizedError(f"Invalid credentials for {response.url}")
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx

**Additional context**
Python - 3.10.4

**Comment by ecederstrand** [comment]
Authentication errors are almost impossible to debug on a public site.

If you were able to fetch data with these credentials, then the credentials themselves are correct. So this is possibly an intermittent error, or your user has read but not write access to service or the specific account.

**Comment by BhavyaJainBHF** [comment]
I was able to save PDFs when it ran last time before error so it doesn't appear to be permission or access issue too. If it's intermittent error is there a way we can understand the cause ?

**Comment by ecederstrand** [comment]
Maybe your permissions changed? Or your credentials expired? The only way to know would be to contact your Exchange server admins and have them debug the issue. exchangelib doesn't get more information from the server than what is mentioned in the `UnauthorizedError` exception.

**Comment by BhavyaJainBHF** [comment]
Will check with Exchange server admins, thanks.
