### ISSUE TITLE
KeyError: Root: An Internal Server Error occured

### ISSUE THREAD

**Issue by PrajjawalBanati** [ecederstrand/exchangelib#1113]
While fetching the folder properties of a mailbox (created using PowerShell) I am receiving an internal server error. I am using an Office365 tenant.

ExchangeLib Version on my machine ```4.7.4```

Logs:-

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\automationpackage\Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 340, in get_mailbox_properties
    root = account.root.walk()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\account.py", line 349, in root
    return Root.get_distinguished(account=self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\folders\roots.py", line 115, in get_distinguished
    return cls.resolve(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\folders\base.py", line 513, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\folders\collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\folders\collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 245, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 265, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 227, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 356, in _get_response_xml
    return self._get_soap_messages(body=body, **parse_opts)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 455, in _get_soap_messages
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 496, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
```
This error comes intermittently.

Why this error is coming ? Is there any way we can fix this issue ? Any help will be appreciated.

Thanks

**Comment by ecederstrand** [comment]
The error comes from the Exchange server. It's a very generic error message and there's no additional information attached, unfortunately. Usually, this is an intermittent problem. If it persists, you need to get hold of your Exchange admins to find out what is causing this.

**Comment by PrajjawalBanati** [comment]
But we would have our own exchange server in case of OnPrem or Hybrid environment. That's not the case. I am using Office 365 tenant solution in which the exchange server is hosted online and managed by microsoft itself.

**Comment by ecederstrand** [comment]
Then you need to get hold of Microsoft of the problem does not go away by itself.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's something that can be improved in exchangelib.

**Comment by PrajjawalBanati** [comment]
Hi again, 
This time the same error is coming while sending the mails to the mailboxes. Is it again the issue from the Microsoft end ?

```
    self.exchangeMailObject.exchange_lib.send_email(mailbox_list=self.mailbox_list)
  File "C:\Users\Administrator\automationpackage\Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 195, in wrapper
    return_val = func(*args, **kwargs)
  File "C:\Users\Administrator\automationpackage\Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 795, in send_email
    message.send_and_save()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\items\message.py", line 122, in send_and_save
    self._create(message_disposition=SEND_AND_SAVE_COPY, send_meeting_invitations=send_meeting_invitations)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\util.py", line 45, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\items\item.py", line 185, in _create
    return CreateItem(account=self.account).get(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 163, in get
    res = list(self.call(**kwargs))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 187, in _elems_to_objs
    for elem in elems:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 245, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 265, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 637, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 559, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorQuotaExceeded: Cannot submit message. (raised from: ErrorInternalServerError('An internal server error occurred. The operation failed.'))
```

The mailbox where I am sending the mail is an E3 license user mailbox. 
The solution is Office 365. 
Exchange Lib version is 4.7.6.

This time is the reason again same?

**Comment by ecederstrand** [comment]
Yes, it's the same error as before. Unfortunately, there's no additional information n the error message to indicere what the reason could be.
