### ISSUE TITLE
Request fails in docker container, succeeds out of it.

### ISSUE THREAD

**Issue by VBobCat** [ecederstrand/exchangelib#1142]
**Describe the bug**
Request works in host server, but fails in docker container.

**To Reproduce**
The code below works OK when run in my linux VPS, from command line, in a python venv:
```python
from datetime import date, datetime
from os import getenv
from typing import Iterable
from exchangelib import Account, Configuration, Credentials


def run():
    username = getenv("ADFS_USERNAME")
    password = getenv("ADFS_PASSWORD")
    credentials = Credentials(
        username=username,
        password=password,
    )
    service_endpoint = getenv("ADFS_SVC_ENDPOINT")
    auth_type = getenv('ADFS_AUTH_TYPE')
    config = Configuration(
        credentials=credentials,
        service_endpoint=service_endpoint,
        auth_type=auth_type,
    )
    access_type = getenv('ADFS_ACCESS_TYPE')
    account = Account(
        primary_smtp_address=username,
        config=config,
        autodiscover=False,
        access_type=access_type,
    )
    for item in account.inbox.all().order_by('-datetime_received')[:10]:
        print(item.subject, item.sender, item.datetime_received)
```
But it fails when running inside a docker container on the same server. Here's Dockerfile:
```
FROM python:3.10-bullseye

USER root
RUN export DEBIAN_FRONTEND=noninteractive

# install linux dependencies
RUN apt-get update \
    && apt-get install apt-utils -f -q -y  \
    && apt-get dist-upgrade -f -q -y \
    && apt-get install \
        libffi-dev \
        iputils-ping \
        locales \
        postgresql-client \
        unixodbc-dev \
        -f -q -y \
    && apt-get autoremove -y \
    && apt-get autoclean -y \
    && localedef -i pt_BR -f UTF-8 pt_BR.UTF-8 \
    && date
ENV LANG=pt_BR.utf8
ENV TZ=America/Sao_Paulo
RUN dpkg-reconfigure locales
ENV IN_DOCKER_CONTAINER=TRUE
ENV COMPOSE_HTTP_TIMEOUT=180

# setup python environment
ENV PYTHONUNBUFFERED=TRUE
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN python -m pip install --upgrade pip && \
    python -m pip install --upgrade setuptools wheel gunicorn

# install source code and dependencies
WORKDIR /usr/src/backend
COPY ./requirements.txt /usr/src/backend/requirements.txt
RUN pip install --use-deprecated=legacy-resolver -r requirements.txt
COPY . /usr/src/backend
```

**Expected behavior**
I expected the code to run alike in both situations.

**Log output**
This is the exception I get inside docker container:
```
Traceback (most recent call last):
  File "/usr/src/backend/manage.py", line 21, in <module>
    main()
  File "/usr/src/backend/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.10/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super().run_from_argv(argv)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.10/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super().execute(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.10/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django_extensions/management/commands/runscript.py", line 281, in handle
    run_script(script_mod, *script_args)
  File "/opt/venv/lib/python3.10/site-packages/django_extensions/management/commands/runscript.py", line 159, in run_script
    exit_code = mod.run(*script_args)
  File "/usr/src/backend/backend_ews/scripts/test_ews.py", line 42, in run
    account = Account(
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/account.py", line 204, in __init__
    self.version = self.protocol.version.copy()
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/protocol.py", line 485, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/version.py", line 233, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 188, in _elems_to_objs
    for elem in elems:
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 246, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 266, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 228, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 343, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/services/common.py", line 298, in _get_response
    r, session = post_ratelimited(
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/util.py", line 915, in post_ratelimited
    protocol.retry_policy.raise_response_errors(r)  # Always raises an exception
  File "/opt/venv/lib/python3.10/site-packages/exchangelib/protocol.py", line 690, in raise_response_errors
    raise UnauthorizedError(f"Invalid credentials for {response.url}")
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx

```

**Additional context**
* exchangelib version = 4.8.0
* VPS OS = Ubuntu 18.04.6 LTS
* VPS Python = Python 3.10.8
* Container OS = Debian GNU/Linux 11 (bullseye)
* Container Python = Python 3.10.8
* Docker Engine - Community, Version: 20.10.21

**Comment by ecederstrand** [comment]
May seem obvious, but have you verified that the correct environment variables are passed all the way through Docker and Django to the script run by our management command?

**Comment by VBobCat** [comment]
> 

Sorry, I forgot to say that I checked that possibility before registering this issue. Both cases load the same .env file: with python-dotenv when running directly, and with docker-compose when running in container. I even printed the contents to screen (which I understandably can't disclose here) and it's all ok on that matter.

**Comment by VBobCat** [comment]
There's something I just discovered. The error disappears if I add `network_mode: "host"` to the docker service in docker-compose.yml. It returns if I change it to `network_mode: "bridge"`. I mean, I'm sure the problem is not intrinsic of exchangelib. I just want to understand exactly what's going on and config my containers the best way possible. Thanks in advace for any help.

**Comment by ecederstrand** [comment]
If you enable [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and compare the HTTP requests in the working and non-working cases, you may be able to figure out what's going on.

I also think this question i better suited in a Docker-focused forum since it's not specific to exchangelib. I'm closing this issue, but feel free to post the answer here when you find out, so others can benefit.
