### ISSUE TITLE
Filter With Subject & Body with Nested Folders

### ISSUE THREAD

**Issue by sonivi** [ecederstrand/exchangelib#1148]
**Describe the bug**
filtering multiple nested folder we get the queryset object but when checking the count on queryset object i.e. qs.count() gives below error
sometime its gives:
`exchangelib.errors.ErrorTimeoutExpired: The request timed out.`
`exchangelib.errors.ErrorInternalServerTransientError: An internal server error occurred. Try again later.`

**To Reproduce**
```python
from exchangelib import Credentials, Configuration, DELEGATE, Account, FolderCollection, Q
subject_to_search = "abc"
credentials = Credentials(username=r"test_domain\test_user", password='test_password')
config = Configuration(credentials=credentials, service_endpoint='https://mail.test.com/EWS/Exchange.asmx')
a = Account(primary_smtp_address= 'test_mailbox@domain.com', config=config, autodiscover=False, access_type=DELEGATE)

l = list(a.inbox.glob('**/*'))
l.append(a.inbox)
q = Q(subject__icontains=subject_to_search) | Q(body__icontains=subject_to_search)
qs = FolderCollection(account=a, folders=l).filter(q)
qs.count()
```

```
DEBUG:exchangelib.services.common:Getting page at offset 0 (max_items None)
DEBUG:exchangelib.services.common:Calling service FindItem
DEBUG:exchangelib.services.common:Trying API version Exchange2013_SP1
DEBUG:exchangelib.protocol:Server mail.test.com: Got session immediately
DEBUG:exchangelib.protocol:Server mail.test.com: Got session 50596
DEBUG:exchangelib.util:Session 50596 thread 273940: retry 0 timeout 120 POST'ing to https://mail.test.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Resetting dropped connection: mail.test.com
DEBUG:urllib3.connectionpool:https://mail.test.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://mail.test.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.services.common:Got page with offset 0, item_count 0, last_page True
DEBUG:exchangelib.services.common:Got page with offset 0, item_count 0, last_page True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..\python3.8\lib\site-packages\exchangelib\queryset.py", line 544, in count
    return len(list(new_qs.__iter__()))
  File "..\python3.8\lib\site-packages\exchangelib\queryset.py", line 273, in __iter__
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "..\python3.8\lib\site-packages\exchangelib\queryset.py", line 348, in _item_yielder
    for i in iterable:
  File "..\python3.8\lib\site-packages\exchangelib\folders\collections.py", line 211, in find_items
    yield from FindItem(account=self.account, page_size=page_size).call(
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 252, in _elems_to_objs
    for elem in elems:
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 814, in _paged_call
    pages = self._get_pages(payload_func, kwargs, len(paging_infos))
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 911, in _get_pages
    page_elems = list(self._get_elements(payload=payload))
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 330, in _get_elements
    yield from self._response_generator(payload=payload)
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 294, in <genexpr>
    return (self._get_page(message) for message in response)
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 885, in _get_page
    paging_elem = self._get_element_container(message=message, name=self.paging_container_name)
  File "..\python3.8\lib\site-packages\exchangelib\services\common.py", line 632, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorTimeoutExpired: The request timed out.
```

**Expected behavior**
we need to get count of queryset

**Log output**
Given in above

**Additional context**
Using below version:
exchangelib==4.7.2
Python3.8.6

**Comment by sonivi** [comment]
we have around 6000+ folders in total. is there any precise way to find it
I tried splitting folders into batch of 100 and then searching it using FolderCollection but again its give timeout error.

`qs = FolderCollection(account=a, folders=l[:100]).filter(q)`

**Comment by ecederstrand** [comment]
`filter()` does not make any attempt at splitting up a request when it's called on a large number of folders. So your strategy of splitting up your search in batches of folders is the way to go. Probably 100 folders is too much for the server. Try going down to 10 instead, and increase only as long as you don't get a timeout.

The FindItem service that the above query uses does not support deep traversal, unfortunately. But some mailboxes have specific folders for searching, e.g. the "AllItems" folder. You could try querying that folder instead, to avoud making specific queries in all 6000 folders.

**Comment by sonivi** [comment]
My requirement is mail with 'abc' subject and 'abc' body can be located anywhere within the Inbox folder & its subfolder.
And Inbox have sub folder around 6k+. is there any precise way to find that mail ?
Please suggest

**Comment by ecederstrand** [comment]
As I wrote, either search the "AllItems" folder, if you have one, and check the folder if the folder of the returned items is a subfolder of Inbox. Or do as you are already doing, but split the search in smaller batches of folders.

**Comment by ecederstrand** [comment]
Closing, since I don't think there's anything to fix in exchangelib. Feel free to re-open if you disagree.
