### ISSUE TITLE
Folder type is misidentified if its name is in the list of localized folder names

### ISSUE THREAD

**Issue by bn-crandom** [ecederstrand/exchangelib#1156]
**Describe the bug**
In a copy and paste frenzy, one of our QA engineers created a mutant mailbox with message folders with names like "Calendar" and "Contacts" .  We filter folders by their container class and their contents by message class, so this doesn't cause a problem.  However, when we try to query such a folder for its messages and include message-only fields like "sender", we get an exception that the field isn't supported because e.g. "Contacts" is of `Contacts` instead of BaseFolder`.

As a workaround, we clear out the locale on startup, which prevents exchangelib from using the folder's localized name to indicate its type:
```
locale.setlocale(locale.LC_ALL, (None, None))
```
I realize this is a little brutish, but we don't use locale otherwise, and it works fine.

**To Reproduce**
Create a message folder in a mailbox named "Contacts", add messages, and try to enumerate that folder's contents with a query set that includes "sender".

**Expected behavior**
If a folder's name matches the localized name of a well-known folder, check the folder's container type (i.e. `folder_class`).  If it doesn't match what's expected for that well-known folder, ignore it.  Alternatively, if a well-known folder is expected at the root of the mailbox, e.g. the real "Contacts" folder, but the folder in question isn't at that location, ignore it.

**Log output**
```
022-06-21 20:28:14,555: INFO    4245/140038464760144 processor.py:241: Processing folder: <omitted>/Benchmark Folders/Mister SaturnBase-5/28/2022 10:41:00 AM/Primary Mailbox/Benchmark Folders/Primary Mailbox/Calendar (None, <class 'exchangelib.folders.known_folders.Calendar'>)
2022-06-21 20:28:14,563: ERROR   4245/140038464760144 processor.py:251: Failed to process folder '<omitted>/Benchmark Folders/Mister SaturnBase-5/28/2022 10:41:00 AM/Primary Mailbox/Benchmark Folders/Primary Mailbox/Calendar': ValueError("Unknown field path 'sender' on folders (Calendar(Root(<exchangelib.account.Account object at 0x7f5d3eef0650>, '[self]', 'root', 11, 0, 59, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAAAAEBAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAAVp6cY'), 'Calendar', 0, 0, 1, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAFvj8qAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAATF3+S'),) in only()")
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/exchangelib/queryset.py", line 441, in only
    only_fields = tuple(self._get_field_path(arg) for arg in args)
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/exchangelib/queryset.py", line 441, in <genexpr>
    only_fields = tuple(self._get_field_path(arg) for arg in args)
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/exchangelib/queryset.py", line 117, in _get_field_path
    raise InvalidField(f"Unknown field path {field_path!r} on folders {self.folder_collection.folders}")
exchangelib.fields.InvalidField: Unknown field path 'sender' on folders (Calendar(Root(<exchangelib.account.Account object at 0x7f5d3eef0650>, '[self]', 'root', 11, 0, 59, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAAAAEBAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAAVp6cY'), 'Calendar', 0, 0, 1, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAFvj8qAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAATF3+S'),)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/application/pyxint/processor.py", line 244, in process_folder
    self.process_folder_contents(folder)
  File "/application/pyxint/processor.py", line 265, in process_folder_contents
    for item in self.query_items(folder, qs):
  File "/application/pyxint/mail_importer.py", line 50, in query_items
    return qs.only("datetime_created", "subject", "message_id", "size", "item_class", "sender", "received_by", "received_representing", "mime_content")
  File "/root/.pyenv/versions/3.7.8/lib/python3.7/site-packages/exchangelib/queryset.py", line 443, in only
    raise ValueError(f"{e.args[0]} in only()")
ValueError: Unknown field path 'sender' on folders (Calendar(Root(<exchangelib.account.Account object at 0x7f5d3eef0650>, '[self]', 'root', 11, 0, 59, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAAAAEBAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAAVp6cY'), 'Calendar', 0, 0, 1, None, 'AAMkADcwZmNkNzU5LTk3MjUtNDcxYS1hOWJhLTI0NDc0ZTFlZTgwOAAuAAAAAAAcGaItgfqNSalSn1mY0f5YAQALWi0K+cBXRZsxAobPUGZyAAAFvj8qAAA=', 'AQAAABYAAAALWi0K+cBXRZsxAobPUGZyAAATF3+S'),) in only()
```

**Additional context**
For example, Python and exchangelib versions.
Python 3.7.8
exchangelib 4.7.3

**Comment by ecederstrand** [comment]
Thanks for the report!

This should be fairly easy to recreate in a test case. Funnily enough, the localized name hack was added to work around an issue with Exchange admins going on a different copy-paste frenzy :-)

**Comment by ecederstrand** [comment]
I tried to recreate this but did not succeed:

```python
# Create a folder in Inbox with a misleading name
f = Messages(parent=account.inbox, name="Calendar").save()
# Check that it's still detected as a Messages folder
account.root.clear_cache()
test_folder = self.account.inbox / "Calendar"
test_folder.delete()
assert type(test_folder) == Messages
assert test_folder.folder_class == Messages.CONTAINER_CLASS
```

Is there a detail I'm missing?

**Comment by bn-crandom** [comment]
@ecederstrand , what locale is set in your environment?

**Comment by ecederstrand** [comment]
Had some time to get back to this. Here's a reproducer:

```python
account.locale = "da_DK"
# Create a folder in Inbox with a misleading name
misleading_name = Calendar.LOCALIZED_NAMES["da_DK"][0]
Messages(parent=account.inbox, name=misleading_name).save()
# Check that it's still detected as a Messages folder
account.root.clear_cache()
test_folder = account.inbox / misleading_name
assert type(test_folder) == Messages. # Fails
```

**Comment by bn-crandom** [comment]
For clarification, you were able to reproduce this, then?  Thanks, Erik!

**Comment by ecederstrand** [comment]
Yup, I have a test case that fails and am looking into possible fixes now.

**Comment by ecederstrand** [comment]
There are still some corner cases here. For example, a standard `Messages` folder called `"Junk-E-Mail"` and locale "de_DE" would be identified as a `JunkEmail` folder class because the two classes share the same `IPF.Note` folder class. But the consequences should be minimail, if any.

**Comment by bn-crandom** [comment]
Understood.  Thanks for fixing this, Erik!
