### ISSUE TITLE
Stopped connecting to exchange server (on premises)

### ISSUE THREAD

**Issue by ray73864** [ecederstrand/exchangelib#1170]
All of a sudden, this morning (Western Australian time), my python script to connect to our on premises exchange server 2019 stopped working.

I did an 'apt get' and 'apt upgrade' this morning which included upgrades for OpenSSL and libopenssl-dev.

I copied the script over to my development server (all directories required and files) as well as made sure all the python modules were installed, and ran it, and it connected just fine, so I know it isn't the exchange server with the problem.

The only difference between the development server and production server is that the development server runs Debian 11 while the production server runs Debian 10.

I turned debug mode on, and the output is (I also told the python script to clear the cache via clear_cache(), that way hopefully nothing in the cache was causing an issue.

```
DEBUG:exchangelib.autodiscover.discovery:Waiting for autodiscover_cache lock
DEBUG:exchangelib.autodiscover.discovery:autodiscover_cache lock acquired
DEBUG:exchangelib.autodiscover.discovery:Cache miss for key ('example.com.au', Credentials('DOMAIN\\stockavail', '********'))
INFO:exchangelib.autodiscover.discovery:Step 1: Trying autodiscover on 'https://example.com.au/Autodiscover/Autodiscover.xml' with email 'stockavail@example.com.au'
DEBUG:exchangelib.autodiscover.discovery:Attempting to get a valid response from https://example.com.au/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.autodiscover.discovery:Checking if example.com.au can be looked up in DNS
DEBUG:exchangelib.autodiscover.discovery:Failed to get a response: 'example.com.au' has no DNS entry
INFO:exchangelib.autodiscover.discovery:Step 2: Trying autodiscover on 'https://autodiscover.example.com.au/Autodiscover/Autodiscover.xml' with email 'stockavail@example.com.au'
DEBUG:exchangelib.autodiscover.discovery:Attempting to get a valid response from https://autodiscover.example.com.au/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.autodiscover.discovery:Checking if autodiscover.example.com.au can be looked up in DNS
DEBUG:exchangelib.autodiscover.discovery:Trying to get response from https://autodiscover.example.com.au/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): autodiscover.example.com.au:443
DEBUG:urllib3.connectionpool:https://autodiscover.example.com.au:443 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'exchangelib/4.7.1 (python-requests/2.21.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '366'}
DEBUG:exchangelib.transport:Response headers: {'Cache-Control': 'private', 'Server': 'Microsoft-IIS/8.5', 'request-id': '64838847-6776-44a9-ac38-d07895482eb0', 'X-CasErrorCode': 'UnauthenticatedRequest', 'X-AspNet-Version': '4.0.30319', 'X-OWA-Version': '15.1.2176.14', 'WWW-Authenticate': 'Basic realm="autodiscover.example.com.au", Negotiate, NTLM', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'MAIL', 'Date': 'Wed, 22 Feb 2023 01:58:13 GMT', 'Content-Length': '0'}
DEBUG:exchangelib.transport:realm: autodiscover.example.com.au
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Increasing session pool size from 0 to 1
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Created session 27666
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Waiting for session
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Got session 27666
DEBUG:exchangelib.util:Session 27666 thread 140463180535616: retry 0 timeout 10 POST'ing to https://autodiscover.example.com.au/Autodiscover/Autodiscover.xml after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): autodiscover.example.com.au:443
DEBUG:urllib3.connectionpool:https://autodiscover.example.com.au:443 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://autodiscover.example.com.au:443 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 401 0
ERROR:exchangelib.util:BufferError: Object is not writable.
Retry: 0
Waited: 10
Timeout: 10
Session: 27666
Thread: 140463180535616
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7fc01c129208>
URL: https://autodiscover.example.com.au/Autodiscover/Autodiscover.xml
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7fc01c129240>
Allow redirects: False
Streaming: False
Response time: 0.021906355395913124
Status code: 503
Request headers: {'Content-Type': 'text/xml; charset=utf-8', 'Accept-Encoding': 'gzip, deflate'}
Response headers: {}
Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<Autodiscover xmlns="http://schemas.microsoft.com/exchange/autodiscover/outlook/requestschema/2006"><Request><EMailAddress>stockavail@example.com.au</EMailAddress><AcceptableResponseSchema>http://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a</AcceptableResponseSchema></Request></Autodiscover>'
Response XML: b''
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Retiring session 27666
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Created session 27956
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Releasing session 27956
Traceback (most recent call last):
  File "/root/stock/exchange.py", line 30, in <module>
    account = Account('stockavail@example.com.au', credentials=credentials, autodiscover=True)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/account.py", line 117, in __init__
    email=primary_smtp_address, credentials=credentials
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/autodiscover/discovery.py", line 117, in discover
    ad_response = self._step_1(hostname=domain)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/autodiscover/discovery.py", line 398, in _step_1
    return self._step_2(hostname=hostname)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/autodiscover/discovery.py", line 411, in _step_2
    is_valid_response, ad = self._attempt_response(url=url)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/autodiscover/discovery.py", line 320, in _attempt_response
    r = self._get_authenticated_response(protocol=ad_protocol)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/autodiscover/discovery.py", line 291, in _get_authenticated_response
    headers=headers, data=data, allow_redirects=False, stream=False)
  File "/usr/local/lib/python3.7/dist-packages/exchangelib/util.py", line 818, in post_ratelimited
    stream=stream)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_ntlm/requests_ntlm.py", line 151, in response_hook
    kwargs
  File "/usr/local/lib/python3.7/dist-packages/requests_ntlm/requests_ntlm.py", line 121, in retry_using_http_NTLM_auth
    server_certificate_hash=server_certificate_hash
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/ntlm.py", line 235, in create_authenticate_message
    msg = self._context.step(self._challenge_token)
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/ntlm.py", line 102, in step
    cbt_data=self.cbt_data
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/messages.py", line 359, in __init__
    rc4_handle.update(self.exported_session_key)
  File "/usr/local/lib/python3.7/dist-packages/ntlm_auth/rc4.py", line 23, in update
    return self._encryptor.update(value)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data, require_writable=True), len(data)
BufferError: Object is not writable.
DEBUG:exchangelib.protocol:Server autodiscover.example.com.au: Closing sessions
```

An excerpt from the code, I've stripped out everything not relating to the actual connecting to the server, since once it is connected, it just downloads attachments, names them correctly, then uploads them to an on-premises SFTP server.

```
import codecs
import os
import os.path
import re
import shutil
import logging

from exchangelib import Account, Credentials, FileAttachment, ItemAttachment, Message, Q
from exchangelib.util import PrettyXmlHandler
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter

from pathlib import Path

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

credentials = Credentials(username='DOMAIN\\stockavail', password='*****')
account = Account('stockavail@example.com.au', credentials=credentials, autodiscover=True)

account.root.refresh()
```

I know it has to be something stupidly simple I am missing, I just can't seem to figure it out.

For now I have my script running on my development server as a cronjob, and have turned the cronjob off on the production server, but this isn't ideal.

**Comment by ray73864** [comment]
Just as an extra, these are the updates that got applied to the server this morning:

isc-dhcp-client/oldstable 4.4.1-2+deb10u3 amd64 [upgradable from: 4.4.1-2+deb10u2]
isc-dhcp-common/oldstable 4.4.1-2+deb10u3 amd64 [upgradable from: 4.4.1-2+deb10u2]
libc-ares2/oldstable 1.14.0-1+deb10u2 amd64 [upgradable from: 1.14.0-1+deb10u1]
libmariadb3/oldstable 1:10.3.38-0+deb10u1 amd64 [upgradable from: 1:10.3.36-0+deb10u2]
libssl-dev/oldstable 1.1.1n-0+deb10u4 amd64 [upgradable from: 1.1.1n-0+deb10u3]
libssl1.1/oldstable 1.1.1n-0+deb10u4 amd64 [upgradable from: 1.1.1n-0+deb10u3]
mariadb-common/oldstable 1:10.3.38-0+deb10u1 all [upgradable from: 1:10.3.36-0+deb10u2]
openssl/oldstable 1.1.1n-0+deb10u4 amd64 [upgradable from: 1.1.1n-0+deb10u3]
python-cryptography/oldstable 2.6.1-3+deb10u3 amd64 [upgradable from: 2.6.1-3+deb10u2]
python3-cryptography/oldstable 2.6.1-3+deb10u3 amd64 [upgradable from: 2.6.1-3+deb10u2]

I made a snapshot of the server in VMWare, so worst case scenario is this Sunday I can just restore from that snapshot, would rather not though, since

**Comment by ecederstrand** [comment]
This is an error from within the `cryptography` package, so it makes sense that it broke when you updated that package. I would suggest that you open an issue in the `cryptography` issue tracker instead since it's not really specific to exchangelib.

**Comment by ray73864** [comment]
Thanks for that.

With the help of the people over there, we found that Debian had pushed a newer update. I knew they already had, I was just extremely hesitant to upgrade to it after the issues I had with the previous upgrade.
