### ISSUE TITLE
EWSService._raise_soap_errors() AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Andrey-Danilenko** [ecederstrand/exchangelib#1178]
**Describe the bug**
Code from EWSService._raise_soap_errors() method:
https://github.com/ecederstrand/exchangelib/blob/32992f087ee95d6efdc292580c4b2630abb9c6bb/exchangelib/services/common.py#L525-L526
The code strips the result of the get_xml_attr() function without checking that it can be None.
https://github.com/ecederstrand/exchangelib/blob/32992f087ee95d6efdc292580c4b2630abb9c6bb/exchangelib/util.py#L173
It looks like a bug because actual signature for `get_xml_attr(...) -> Optional[str]`. It means we can't use strip() without check is it null or not.

**To Reproduce**
I don't know, how to reproduce it. For me it happens when I am walking through exchangelib.Account().root.walk().

**Expected behavior**
The error detail must have a not null message. But if it does, the code must check whether it is null or not before applying operations to it.

**Log output**
`self.account` below is an exchangelib.Account object.
<details>
  <summary>Stack trace</summary>

```
Traceback (most recent call last):
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/myproject/sync_mail.py", line 107, in sync_user
    source_class(user, email, domain, credentials, full).sync_mailbox()
  File "/myproject/exchange.py", line 89, in __init__
    self.fetch_folders()
  File "/myproject/exchange.py", line 114, in fetch_folders
    for folder in self.account.root.walk():
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/account.py", line 343, in root
    return Root.get_distinguished(account=self)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/roots.py", line 114, in get_distinguished
    return cls.resolve(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/base.py", line 502, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 285, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 305, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 269, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 399, in _get_response_xml
    return self._get_soap_messages(body=body, **parse_opts)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 496, in _get_soap_messages
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 517, in _raise_soap_errors
    msg = get_xml_attr(detail, f"{{{ENS}}}Message").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/myproject/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/myproject/sync_mail.py", line 54, in handle
    self.sync_exchange(domain, users, full, oauth2=True)
  File "/myproject/sync_mail.py", line 100, in sync_exchange
    self.sync_user(ExchangeMailSource, domain, credentials, user, email, full)
  File "/myproject/sync_mail.py", line 107, in sync_user
    source_class(user, email, domain, credentials, full).sync_mailbox()
  File "/myproject/exchange.py", line 89, in __init__
    self.fetch_folders()
  File "/myproject/exchange.py", line 114, in fetch_folders
    for folder in self.account.root.walk():
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/account.py", line 343, in root
    return Root.get_distinguished(account=self)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/roots.py", line 114, in get_distinguished
    return cls.resolve(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/base.py", line 502, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/folders/collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 285, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 305, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 269, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 399, in _get_response_xml
    return self._get_soap_messages(body=body, **parse_opts)
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 496, in _get_soap_messages
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/myproject/.pyenv/versions/3.10.9/envs/varys/lib/python3.10/site-packages/exchangelib/services/common.py", line 517, in _raise_soap_errors
    msg = get_xml_attr(detail, f"{{{ENS}}}Message").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

</details>

**Additional context**
python ver 3.10.9
exchangelib ver 4.9.0

**Comment by ecederstrand** [comment]
Have you seen this is an actual stack trace? I can only see this happening when the XML document has a `Message` element but it has no text.

**Comment by Andrey-Danilenko** [comment]
> Have you seen this is an actual stack trace? I can only see this happening when the XML document has a `Message` element but it has no text.

Yes I have. It's actual. Also i've found in sentry, that `ResponseCode` was `ErrorMailboxConfiguration`.

**Comment by Mogost** [comment]
Wow. I'm amazed at your speed.
