### ISSUE TITLE
Get folders

### ISSUE THREAD

**Issue by clEclE36** [ecederstrand/exchangelib#1182]
**Describe the bug**
The same code to work on directories, between 4.9.0 and 5.1.0, returns nothing with `parent.children` or raises an error with `parent / folder` in 5.1.0.
Is there a difference in the directory search between 4.9.0 and 5.1.0 ?
I did not see any in the release note.

**To Reproduce**
`account.inbox.children` returns nothing in 5.1.0, but returns the 3 expected directories in 4.9.0.
Same result with `account.root.children` : nothing in 5.1.0, but the expected directories in 4.9.0 (61 directories).
the way `account.inbox / an_existing_folder (or an_non_existing_folder)` raises an ErrorAccessDenied in both cases.

**Expected behavior**
The same result as in 4.9.0.

**Log output**
In 4.9.0 :
`account.inbox.children` returns a FolderCollection with 3 folders tuple ("temp", "error", "processed", are the names of the directories).
`account.inbox / "temp"` returns 1 Folder (or raises a ErrorFolderNotFound if doesn't exist, normal).

In 5.1.0 :
`account.inbox.children` returns a FolderCollection where FolderCollection.folders is an empty tuple but does not raise an error.
`account.inbox / "temp"` always raises an ErrorAccessDenied => "Access denied. Check the credentials and try again, A non-system login does not allow access to the Audits folder.".

**Additional context**
Python 3.9
Server Exchange 2016 on-premise

A line with logging :
> API version "Exchange2016" worked but server reports version "V2017_07_11". Using "Exchange2016"

**Comment by ecederstrand** [comment]
Thanks for the report!

This is something the test suite tests quite intensively, so it's surprising to me that this would fail in the new version. Can you please [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and compare the XML documents sent in 4.9.0 and 5.0.1?

**Comment by clEclE36** [comment]
Thanks for your follow up and sorry for the delay in returning !

Here are some differences that I thought were relevant.
If you want the full console release, I can send it to you.


------------------------------------------------
**Version 4.9.0 :**
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 24100
Thread: 3980

**A few lines further on**
DEBUG:exchangelib.protocol:No retry with fail-fast policy      -->      **(not written in version 5.0.1)**

**A few lines further on**
DEBUG:exchangelib.util:Session 24100 thread 3980: retry 0 timeout 120 POST'ing to https://******.******/Exchange.asmx after 10s wait

DEBUG:exchangelib.folders.queryset:GetFolder not allowed on folder Audits (Audits). Non-complex fields must be fetched with FindFolder      -->       **(not written in version 5.0.1)**
------------------------------------------------

------------------------------------------------
**Version 5.0.1 :**
DEBUG:exchangelib.util:Timeout: 120
Session: 30478
Thread: 15744

**A few lines further on**
DEBUG:exchangelib.util:Session 30478 thread 15744 timeout 120: POST'ing to https://******.******/Exchange.asmx after 0s sleep
------------------------------------------------


Audits folder is the one concerned by the exception in 5.0.1.
The 4.9.0 seems to see the non-authorization but just points it out.

**Comment by chrullrich** [comment]
I have a very similar issue in 5.0.1 (full exceptions below, note it's "System folder", not "Audits folder") with an Exchange that connects like this:

```
DEBUG:exchangelib.util.xml:Request XML: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:a="http://schemas.microsoft.com/exchange/2010/Autodiscover"
    xmlns:wsa="http://www.w3.org/2005/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Header>
    <a:RequestedServerVersion>Exchange2016</a:RequestedServerVersion>
    <wsa:Action>http://schemas.microsoft.com/exchange/2010/Autodiscover/Autodiscover/GetUserSettings</wsa:Action>
    <wsa:To>https://autodiscover.************/autodiscover/autodiscover.svc</wsa:To>
  </s:Header>
  <s:Body>
    <a:GetUserSettingsRequestMessage>
      <a:Request>
        <a:Users>
          <a:User>
            <a:Mailbox>*********************@**************</a:Mailbox>
          </a:User>
        </a:Users>
        <a:RequestedSettings>
          <a:Setting>UserDN</a:Setting>
          <a:Setting>MailboxDN</a:Setting>
          <a:Setting>UserDisplayName</a:Setting>
          <a:Setting>AutoDiscoverSMTPAddress</a:Setting>
          <a:Setting>ExternalEwsUrl</a:Setting>
          <a:Setting>EwsSupportedSchemas</a:Setting>
        </a:RequestedSettings>
      </a:Request>
    </a:GetUserSettingsRequestMessage>
  </s:Body>
</s:Envelope>
Response XML: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:a="http://www.w3.org/2005/08/addressing">
  <s:Header>
    <a:Action s:mustUnderstand="1">http://schemas.microsoft.com/exchange/2010/Autodiscover/Autodiscover/GetUserSettingsResponse</a:Action>
    <h:ServerVersionInfo
    xmlns:h="http://schemas.microsoft.com/exchange/2010/Autodiscover"
    xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
      <h:MajorVersion>15</h:MajorVersion>
      <h:MinorVersion>1</h:MinorVersion>
      <h:MajorBuildNumber>2507</h:MajorBuildNumber>
      <h:MinorBuildNumber>23</h:MinorBuildNumber>
      <h:Version>Exchange2015</h:Version>
    </h:ServerVersionInfo>
  </s:Header>
  <s:Body>
    <GetUserSettingsResponseMessage xmlns="http://schemas.microsoft.com/exchange/2010/Autodiscover">
      <Response
    xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <ErrorCode>NoError</ErrorCode>
        <ErrorMessage/>
        <UserResponses>
          <UserResponse>
            <ErrorCode>NoError</ErrorCode>
            <ErrorMessage>No error.</ErrorMessage>
            <RedirectTarget i:nil="true"/>
            <UserSettingErrors/>
            <UserSettings>
              <UserSetting i:type="StringSetting">
                <Name>UserDisplayName</Name>
                <Value>*********************</Value>
              </UserSetting>
              <UserSetting i:type="StringSetting">
                <Name>UserDN</Name>
                <Value>/o=******/ou=First Administrative Group/cn=Recipients/cn=***********</Value>
              </UserSetting>
              <UserSetting i:type="StringSetting">
                <Name>AutoDiscoverSMTPAddress</Name>
                <Value>*********************@**************</Value>
              </UserSetting>
              <UserSetting i:type="StringSetting">
                <Name>EwsSupportedSchemas</Name>
                <Value>Exchange2007, Exchange2007_SP1, Exchange2010, Exchange2010_SP1, Exchange2010_SP2, Exchange2013, Exchange2013_SP1, Exchange2015</Value>
              </UserSetting>
              <UserSetting i:type="StringSetting">
                <Name>MailboxDN</Name>
                <Value>/o=******/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=************************************@**************/cn=Microsoft Private MDB</Value>
              </UserSetting>
              <UserSetting i:type="StringSetting">
                <Name>ExternalEwsUrl</Name>
                <Value>https://*********************/EWS/Exchange.asmx</Value>
              </UserSetting>
            </UserSettings>
          </UserResponse>
        </UserResponses>
      </Response>
    </GetUserSettingsResponseMessage>
  </s:Body>
</s:Envelope>
DEBUG:exchangelib.util:Session 77569 thread 7040: Useful response from https://autodiscover.************/autodiscover/autodiscover.svc
DEBUG:exchangelib.protocol:Server autodiscover.************: Releasing session 77569
DEBUG:exchangelib.version:API version "Exchange2016" worked but server reports version "Exchange2015". Using "Exchange2015"
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
  File "***\venv\lib\site-packages\exchangelib\version.py", line 269, in __str__
    return f"Build={self.build}, API={self.api_version}, Fullname={self.fullname}"
  File "***\venv\lib\site-packages\exchangelib\version.py", line 173, in fullname
    raise ValueError(f"Full name for API version {self.api_version} build {self.build} is unknown")
ValueError: Full name for API version Exchange2015 build 15.1.2507.23 is unknown
Call stack:
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in connect_ews
  File "***\venv\lib\site-packages\exchangelib\account.py", line 167, in __init__
    ).discover()
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 120, in discover
    ad = self._step_1(hostname=domain)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 332, in _step_1
    return self._step_2(hostname=hostname)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 348, in _step_2
    return self._step_3(hostname=hostname)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 384, in _step_3
    return self._step_4(hostname=hostname)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 414, in _step_4
    is_valid_response, ad = self._attempt_response(url=redirect_url)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\discovery.py", line 253, in _attempt_response
    user_response = protocol.get_user_settings(user=self.email)
  File "***\venv\lib\site-packages\exchangelib\autodiscover\protocol.py", line 39, in get_user_settings
    return GetUserSettings(protocol=self).get(
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 164, in get
    res = list(self.call(**kwargs))
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 225, in _elems_to_objs
    for elem in elems:
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 308, in _get_elements
    yield from self._response_generator(payload=payload)
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 271, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 415, in _get_response_xml
    self._update_api_version(api_version=api_version, header=header, **parse_opts)
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 462, in _update_api_version
    log.debug("Found new version (%s -> %s)", self._version_hint, head_version)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "***\venv\lib\site-packages\exchangelib\util.py", line 613, in emit
    return super().emit(record)
Message: 'Found new version (%s -> %s)'
Arguments: (Version(Build(15, 20, 0, 0), 'Exchange2016'), Version(Build(15, 1, 2507, 23), 'Exchange2015'))
DEBUG:exchangelib.autodiscover.discovery:Adding cache entry for key ('**************', Credentials('********************', '********')): https://autodiscover.************/autodiscover/autodiscover.svc
INFO:exchangelib.autodiscover.discovery:Step 5: Checking response
DEBUG:exchangelib.autodiscover.discovery:Released autodiscover_cache_lock
DEBUG:exchangelib.account:Added account: *********************@**************
```

```
2023-04-13 07:14:01,506 [INFO] __main__: Starting
2023-04-13 07:14:08,180 [ERROR] __main__: Access is denied. Check credentials and try again., Non-system logon cannot access System folder.
Traceback (most recent call last):
  File "***\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "************************************************************", line 138, in get_nested_folder
    fld = fld / p
  File "***\venv\lib\site-packages\exchangelib\folders\base.py", line 777, in __truediv__
    for c in self.children:
  File "***\venv\lib\site-packages\exchangelib\folders\collections.py", line 49, in __iter__
    yield from self.folders
  File "***\venv\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "***\venv\lib\site-packages\exchangelib\folders\collections.py", line 43, in folders
    return tuple(self._folders)
  File "***\venv\lib\site-packages\exchangelib\folders\roots.py", line 98, in get_children
    for f in self._folders_map.values():
  File "***\venv\lib\site-packages\exchangelib\folders\roots.py", line 176, in _folders_map
    for f in (
  File "***\venv\lib\site-packages\exchangelib\folders\queryset.py", line 146, in _query
    for f, complex_f in zip(resolveable_folders, complex_folders):
  File "***\venv\lib\site-packages\exchangelib\folders\collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "***\venv\lib\site-packages\exchangelib\services\get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 287, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 308, in _get_elements
    yield from self._response_generator(payload=payload)
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 684, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "***\venv\lib\site-packages\exchangelib\services\common.py", line 606, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again., Non-system logon cannot access System folder.
```

**Comment by ecederstrand** [comment]
@chrullrich This looks like the same issue. Can you try out my suggestion in the previous comment?

**Comment by chrullrich** [comment]
Response XML from `<m:FindFolder>`:

```
              <t:Folder>
                <t:FolderId Id="AQMkADI1ZWUANGZkNi1mYTMxLTRlYTYtYjg0YS02NzBhMGE0Zjc2YzkALgAAA+Is5zC6Me5IqQeqMB1e8AQBABW3JUmhTG1HoPUaYkLzxy8AAAKAtAAAAA==" ChangeKey="AQAAABYAAAAVtyVJoUxtR6D1GmJC88cvAAAAAIC3"/>
                <t:ParentFolderId Id="AAMkADI1ZWU0ZmQ2LWZhMzEtNGVhNi1iODRhLTY3MGEwYTRmNzZjOQAuAAAAAADiLOcwujHuSKkHqjAdXvAEAQCMJgliCfqWRrBmYbyqdWf4AAAADmGLAAA=" ChangeKey="AQAAAA=="/>
                <t:DisplayName>System</t:DisplayName>
                <t:TotalCount>0</t:TotalCount>
                <t:ChildFolderCount>0</t:ChildFolderCount>
```

    DEBUG:exchangelib.folders.base:folder.name=System, folder.folder_class=None, root.account.locale=en_US
    DEBUG:exchangelib.folders.base:Fallback to class Folder (folder_class None, name System)

(The first line is new.)

`System` is in `NON_DELETABLE_FOLDERS`, so `folder_cls_from_folder_name()` should find it, but it does not have a `folder_class` in the Exchange response, so that is never called. After exchangelib has enumerated one kind of metadata for all folders in the mailbox using `<FindFolder>`, it then sends a `<GetFolder>` that includes the folder ID for System, and the request ends like this (`System` was the next folder ID in the request after the one with the last successful result):

```
        <m:GetFolderResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Folders>
            <t:SearchFolder>
              <t:FolderId Id="AAMkADI1ZWU0ZmQ2LWZhMzEtNGVhNi1iODRhLTY3MGEwYTRmNzZjOQAuAAAAAADiLOcwujHuSKkHqjAdXvAEAQCMJgliCfqWRrBmYbyqdWf4AAAADmGOAAA=" ChangeKey="BwAAABYAAAAj5yeHPPNpTL8Pvoc2R4zIAAAAAACE"/>
              <t:DisplayName>Spooler Queue</t:DisplayName>
            </t:SearchFolder>
          </m:Folders>
        </m:GetFolderResponseMessage>
        <m:GetFolderResponseMessage ResponseClass="Error">
          <m:MessageText>Access is denied. Check credentials and try again., Non-system logon cannot access System folder.</m:MessageText>
          <m:ResponseCode>ErrorAccessDenied</m:ResponseCode>
          <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          <m:Folders/>
        </m:GetFolderResponseMessage>
        <m:GetFolderResponseMessage ResponseClass="Warning">
          <m:MessageText>Item was not processed as a result of a previous error.</m:MessageText>
          <m:ResponseCode>ErrorBatchProcessingStopped</m:ResponseCode>
          <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          <m:Folders/>
        </m:GetFolderResponseMessage>
```

**Comment by ecederstrand** [comment]
Ok, that's very useful. `Fallback to class Folder (folder_class None, name System)` tells us that the folder is not identified properly as a `System` folder. Can you update your post to contain the full `<t:Folder>` element including the closing element, just for completeness?

**Comment by ecederstrand** [comment]
Thanks! Very helpful. I'll have a patch for this shortly.

**Comment by clEclE36** [comment]
I love it !
I run into a problem, I throw the baby out the window and when I come back, I have a responsible adult 😄 

Thanks for your follow up @chrullrich @ecederstrand  :)
