### ISSUE TITLE
Problem with certificate based authentication

### ISSUE THREAD

**Issue by jsuto** [ecederstrand/exchangelib#1183]
**Describe the bug**

I get the below exceptions when trying certitifate based authentication against o365.

**To Reproduce**

Created a self signed certificate, and added it to azure ad app registration, also configured "full_access_as_app".

```
openssl req -x509 -subj "/C=US/ST=CA/L=Springfield/O=Dis/CN=myhost.aaa.fu" -nodes -new -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650
```

The python code:

```python
from exchangelib import Configuration, BaseProtocol, CBA, TLSClientAuth
from exchangelib import DELEGATE, IMPERSONATION, Account

TLSClientAuth.cert_file = 'cert.pem'
BaseProtocol.HTTP_ADAPTER_CLS = TLSClientAuth
config = Configuration(server='outlook.office365.com', auth_type=CBA)
email = 'm365admin@x111d.onmicrosoft.com'

a = Account(primary_smtp_address=email, config=config, access_type=IMPERSONATION, autodiscover=False)
```

**Expected behavior**

It should work :-)

**Log output**

```
TransportError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
Retry: 0
Waited: 10
Timeout: 120
Session: 83371
Thread: 139940891247040
Auth type: None
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.TLSClientAuth object at 0x7f468469c850>
Streaming: False
Response time: 0.11935502802953124
Status code: 503
Request headers: {}
Response headers: {}
Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ConvertId DestinationFormat="EntryId"><m:SourceIds><t:AlternateId Id="DUMMY" Format="EwsId" Mailbox="DUMMY"/></m:SourceIds></m:ConvertId></s:Body></s:Envelope>'
Response XML: b''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 418, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3895)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/util.py", line 838, in post_ratelimited
    r = session.post(**kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sj/devel/piler-ee/util/./ews.py", line 20, in <module>
    a = Account(primary_smtp_address=email, config=config, access_type=IMPERSONATION, autodiscover=False)
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/account.py", line 198, in __init__
    self.version = self.protocol.version.copy()
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/protocol.py", line 464, in version
    self.config.version = Version.guess(self, api_version_hint=self.api_version_hint)
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/version.py", line 220, in guess
    list(ConvertId(protocol=protocol).call([AlternateId(id="DUMMY", format=EWS_ID, mailbox="DUMMY")], ENTRY_ID))
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 223, in _elems_to_objs
    for elem in elems:
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 285, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 305, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 269, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 386, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/services/common.py", line 337, in _get_response
    r, session = post_ratelimited(
  File "/home/sj/.local/lib/python3.10/site-packages/exchangelib/util.py", line 841, in post_ratelimited
    raise TransportError(str(e))
exchangelib.errors.TransportError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
```

**Additional context**

python 3.10.6
exchangelib 4.9.0

I can reach the below URL just fine:

```bash
$ curl -i https://outlook.office365.com/EWS/Exchange.asmx
HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/10.0
request-id: 6b8661e6-3f37-32c8-ed4a-29505486e004
Alt-Svc: h3=":443",h3-29=":443"
X-WSSecurity-Enabled: True
X-WSSecurity-For: Logon
X-FederationTrustTokenIssuerUri: urn:federation:MicrosoftOnline
X-WSSecurity-SymmetricKey-Enabled: True
X-WSSecurity-X509Cert-Enabled: True
X-OAuth-Enabled: True
X-FirstHopCafeEFZ: FRA
X-FEProxyInfo: FR2P281CA0030.DEUP281.PROD.OUTLOOK.COM
X-FEEFZInfo: FRA
X-Powered-By: ASP.NET
X-FEServer: FR2P281CA0030
WWW-Authenticate: Basic Realm=""
Date: Mon, 03 Apr 2023 17:29:57 GMT
Content-Length: 0
```

**Comment by ecederstrand** [comment]
I don't think this is an exchangelib issue as such. I found this post that may help? https://github.com/jupyter/notebook/issues/507#issuecomment-145390380

**Comment by jsuto** [comment]
I'm not sure. The mentioned user put the private key to the pem file. However, Azure AD expects only the certificate alone in the pem file, and doesn't accept a pem with the key and the certificate.

What else could I check?

**Comment by ecederstrand** [comment]
I'm closing this issue because I don't think it's an issue with exchangelib itself, but rather with a combination of openssl and Azure.  That said, feel free to update this issue if you do find a solution to your issue.
