### ISSUE TITLE
TransportError caused by SSLError with Account authentication on Python 3.10 but not 3.9

### ISSUE THREAD

**Issue by GillesJ** [ecederstrand/exchangelib#1205]
**Describe the bug**
With the following code:

```
from exchangelib import Credentials, Account, Configuration, IMPERSONATION, NTLM

credentials = Credentials(cfg.mailbox_username, cfg.mailbox_password)
config = Configuration(service_endpoint=cfg.service_endpoint_url, credentials=credentials,
                       auth_type=NTLM, max_connections=5)
account = Account(cfg.mailbox, credentials=credentials, autodiscover=False, config=config,
                       access_type=IMPERSONATION)
```

I am getting the following error on a python 3.10.11 environment with only exchangelib==5.0.3 installed.

```
exchangelib.errors.TransportError: HTTPSConnectionPool(host='owa.example.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))  
```

However, it works as expected with python 3.9.16.

**To Reproduce**
cf above.

**Expected behavior**
Account auth succeeds and no error is produced.

**Log output**
```
Traceback (most recent call last):                                                                                                                                                 File "/home/gilles/repos/test_exchangelib_3.10/../mail-worker/test_exchange.py", line 24, in <module>                                                                              account = Account(cfg.mailbox, credentials=credentials, autodiscover=False, config=config,                                                                                     File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/account.py", line 190, in __init__                   self.version = self.protocol.version.copy()                                                                                                                                    File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/protocol.py", line 470, in version                   self.config.version = Version.guess(self, api_version_hint=self.api_version_hint)                                                                                              File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/version.py", line 200, in guess                      list(ConvertId(protocol=protocol).call([AlternateId(id="DUMMY", format=EWS_ID, mailbox="DUMMY")], ENTRY_ID))                                                                   File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 225, in _elems_to_objs     for elem in elems:                                                                                                                                                             File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 287, in _chunked_get_elements                                                                                                                                                                               yield from self._get_elements(payload=payload_func(chunk, **kwargs))                                                                                                           File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 308, in _get_elements      yield from self._response_generator(payload=payload)                                                                                                                           File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 271, in _response_generator                                                                                                                                                                                 response = self._get_response_xml(payload=payload)                                                                                                                             File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 404, in _get_response_xml                                                                                                                                                                                   r = self._get_response(payload=payload, api_version=api_version)                                                                                                               File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/services/common.py", line 355, in _get_response      r, session = post_ratelimited(                                                                                                                                                 File "/home/gilles/.cache/pypoetry/virtualenvs/test-exchangelib-3-10-QifeQ0D3-py3.10/lib/python3.10/site-packages/exchangelib/util.py", line 828, in post_ratelimited              raise TransportError(str(e))                                                                                                                                                 exchangelib.errors.TransportError: HTTPSConnectionPool(host='owa.example.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'))) 
```

**Additional context**
For example, Python and exchangelib versions.

Not working:
[tool.poetry.dependencies]
python = "^3.10"
exchangelib = "^5.0.3"

working:
[tool.poetry.dependencies]
python = "^3.9"
exchangelib = "^5.0.3"

If needed I can attach the poetry lock files.

**Comment by GillesJ** [comment]
Just tested with python 3.11.2, same error is produced.

**Comment by ecederstrand** [comment]
Your Python installation is unable to create a successful SSL connection to the server. This is not an issue with exchangelib as such - you would probably get the same error if you did `import requests; requests.get("https://owa.example.com")`.  It's possible that the remote server has an SSL setup that the newer Python considers insecure. See e.g. https://bugs.python.org/issue45487

**Comment by GillesJ** [comment]
Thanks for the quick response, that indeed does seem to be the problem.

Apparently you can override this behaviour by passing in an builtin ssl context object, as in [this imaplib example](https://stackoverflow.com/questions/71006708/getting-sslv3-alert-handshake-failure-when-trying-to-connect-to-imap):
```
import imaplib
import ssl
ctx = ssl.create_default_context()
ctx.set_ciphers('DEFAULT')
imapSrc = imaplib.IMAP4_SSL('mail.safemail.it', ssl_context = ctx)
```

Is there a supported way in the exchangelib to pass an SSL context?

**Comment by ecederstrand** [comment]
To customize TLS validation, see https://ecederstrand.github.io/exchangelib/#proxies-and-custom-tls-validation

**Comment by GillesJ** [comment]
Using a custom HTTPAdapter seems to work.

Here's the workaround code for reference:
```
import requests
import ssl
from exchangelib.protocol import BaseProtocol
from exchangelib import Credentials, Account, Configuration, IMPERSONATION, NTLM

class CustomAdapter(requests.adapters.HTTPAdapter):
    def init_poolmanager(self, *args, **kwargs):
        ssl_context = ssl.create_default_context()
        ssl_context.set_ciphers('DEFAULT')
        kwargs['ssl_context'] = ssl_context

        return super().init_poolmanager(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = CustomAdapter

credentials = Credentials(cfg.mailbox_username, cfg.mailbox_password)
config = Configuration(service_endpoint=cfg.service_endpoint_url, credentials=credentials,
                       auth_type=NTLM, max_connections=5)
account = Account(cfg.mailbox, credentials=credentials, autodiscover=False, config=config,
                       access_type=IMPERSONATION)
```

**Comment by GillesJ** [comment]
https://github.com/ecederstrand/exchangelib/issues/1205#issuecomment-1587646420
