### ISSUE TITLE
replacing returned utc timezone for calendar.view output to different tz

### ISSUE THREAD

**Issue by nohir0** [ecederstrand/exchangelib#1208]
**Describe the bug**
Calendar view output is returned with UTC timezone information.
I want to modify the returned EWSDateTime objects (I assume they are) to my local timezone.
Following approach seemed to work in previous versions, but at least in exchangelib==5.0.3 it throws 'EWSTimeZone' has no attribute 'timezone'
I also tried different other approaches using pytz timezone or `appointment.end.replace(tzinfo=pytz.timezone('Europe/Berlin'))` , but none of the known solutions for me worked. How to modify the calendar.view output into different timezone?

**To Reproduce**
```python
    credentials = Credentials(username=EWS_IMP_USER, password=EWS_IMP_PASS)
    config = Configuration(server=EWS_EXCH_SERVER, credentials=credentials)
    account = Account(primary_smtp_address=email_address, credentials=credentials,
                      autodiscover=False, config=config, access_type=IMPERSONATION)

    yesterday = datetime.today().date() - timedelta(days=0)
    yyear = yesterday.year
    ymonth = yesterday.month
    yday = yesterday.day
    
    tomorrow = datetime.today().date() + timedelta(days=2)
    tyear = tomorrow.year
    tmonth = tomorrow.month
    tday = tomorrow.day

    yesterdayEWS = EWSDateTime(yyear, ymonth, yday, 0, 0, tzinfo=EWSTimeZone('Europe/Berlin'))
    tomorrowEWS = EWSDateTime(tyear, tmonth, tday, 0, 0, tzinfo=EWSTimeZone('Europe/Berlin'))

    calendar = account.calendar.view(
        start=yesterdayEWS,
        end=tomorrowEWS,
    )

        tz = EWSTimeZone.timezone('Europe/Berlin')
        a = appointment.start.astimezone(tz)
        print(a)
```

**Expected behavior**
EWSTimeZone object expected to have a timezone method...

**Log output**
`  File "/home/gans/bin/slack/bolt-apps/exchange-calendar-search/app.py", line 100, in repeat_text
    tz = EWSTimeZone.timezone('Europe/Berlin')
AttributeError: type object 'EWSTimeZone' has no attribute 'timezone'`

**Additional context**
exchangelib==5.0.3

Thanks for attention and sorry for this question being naive, but timezone modification bothers me a lot :P

**Comment by nohir0** [comment]
Here to add my second approach using 'astimezone' together with pytz, but this is also not possible because:
`AttributeError: 'EWSDate' object has no attribute 'astimezone'`

```
        local_tz = pytz.timezone('Europe/Berlin')
        start_time = appointment.start.astimezone(pytz.UTC)
        end_time = appointment.end.astimezone(pytz.UTC)
        start_time = datetime(start_time.year, start_time.month, start_time.day,
                              start_time.hour, start_time.minute, start_time.second,
                              tzinfo=pytz.UTC).astimezone(local_tz)
        end_time = datetime(end_time.year, end_time.month, end_time.day,
                            end_time.hour, end_time.minute, end_time.second,
                            tzinfo=pytz.UTC).astimezone(local_tz)
        print(start_time)
        print(end_time)
```

Throws:
`    start_time = appointment.start.astimezone(pytz.UTC)
AttributeError: 'EWSDate' object has no attribute 'astimezone'`

**Comment by nohir0** [comment]
and my third and so far last approach comes to an end with:

```
        local_tz = pytz.timezone('Europe/Berlin')
        server_tz = pytz.timezone(account.default_timezone)
        timezone_diff = local_tz.utcoffset(datetime.now()) - server_tz.utcoffset(datetime.now())
        start_time = appointment.start + timezone_diff
        end_time = appointment.end + timezone_diff
        print(start_time)
        print(end_time)
```


Throws:
```
ERROR:slack_bolt.App:Failed to run listener function (error: 'EWSTimeZone' object has no attribute 'upper')
Traceback (most recent call last):
  File "/mnt/c/Users/gans/Documents/bin/slack/bolt-apps/exchange-calendar-search/.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/mnt/c/Users/gans/Documents/bin/slack/bolt-apps/exchange-calendar-search/.venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/home/gans/bin/slack/bolt-apps/exchange-calendar-search/app.py", line 113, in repeat_text
    server_tz = pytz.timezone(account.default_timezone)
  File "/mnt/c/Users/gans/Documents/bin/slack/bolt-apps/exchange-calendar-search/.venv/lib/python3.10/site-packages/pytz/__init__.py", line 170, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'EWSTimeZone' object has no attribute 'upper'
```

**Comment by ecederstrand** [comment]
If you want to change the timezone of an `EWSDateTime` object, use its `.astimezone()` method:

```python
tz = EWSTimeZone("Europe/Copenhagen")
dt = EWSDateTime(2000, 1, 2, 3, 4, 5, tzinfo=tz)
utc_tz = EWSTimeZone("UTC")
dt.astimezone(utc_tz)
```

**Comment by nohir0** [comment]
Indeed, I tried that but throws an exception in my code as shown below.
For me it looks like the calender.view method seems to return a "EWSDate" object instead of an "EWSDateTime" object and for that reason it is not possible to use "astimezone" on that to change the the timezone?

Code:
```
    yesterdayEWS = EWSDateTime(yyear, ymonth, yday, 0, 0, tzinfo=EWSTimeZone('Europe/Berlin'))
    tomorrowEWS = EWSDateTime(tyear, tmonth, tday, 0, 0, tzinfo=EWSTimeZone('Europe/Berlin'))

    credentials = Credentials(username=EWS_IMP_USER, password=EWS_IMP_PASS)
    config = Configuration(server=EWS_EXCH_SERVER, credentials=credentials)
    account = Account(primary_smtp_address=email_address, credentials=credentials,
                      autodiscover=False, config=config, access_type=IMPERSONATION)

    calendar = account.calendar.view(
        start=yesterdayEWS,
        end=tomorrowEWS,
    )

    for appointment in calendar:
        start_time = appointment.start
        end_time = appointment.end
        start_time = start_time.astimezone(EWSTimeZone("Europe/Berlin"))
        end_time = end_time.astimezone(EWSTimeZone("Europe/Berlin"))
```

Exception
```
Traceback (most recent call last):
  File /.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/.venv/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "app.py", line 115, in repeat_text
    start_time = start_time.astimezone(EWSTimeZone("Europe/Berlin"))
AttributeError: 'EWSDate' object has no attribute 'astimezone'
```

**Comment by ecederstrand** [comment]
A calendar item can be a full-day event. In that case, start and end will be EWSDate objects.

**Comment by nohir0** [comment]
Understood, right this is a basic fact I did not catch :P
Covered this now in my code.
Thanks a lot for answering this beginner question @ecederstrand , it may help others...
