### ISSUE TITLE
get mailbox item count return serverbusy: caused by closed connectoin 

### ISSUE THREAD

**Issue by Yuen01too** [ecederstrand/exchangelib#1237]
**Describe the bug**
from exchangelib import Account, DELEGATE, OAuth2Credentials, Configuration, Version
from exchangelib.version import EXCHANGE_O365
import time

credentials = OAuth2Credentials(
    client_id="xxx",
    client_secret="xxx",
    tenant_id="xxx",
)

# 初始化 Configuration
config = Configuration(credentials=credentials, service_endpoint="https://outlook.office365.com", version=Version(build=EXCHANGE_O365),)

# 初始化 Account
account = Account("abc@xxx.com", config=config, access_type=DELEGATE)

#waiting for 5 seconds
time.sleep(5) 

#search subject with hello
hello_emails = account.inbox.filter(subject__startswith='hello')
n = hello_emails.count()

#print result
print(n)

**Expected behavior**
Item count should return instead it prompt server busy error and connection closed  

**Log output**
& C:/Python311/python.exe "c:/Users/SAM/ExchangeData.py"
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
           ~~~~~~~~^^^^^^
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\SAM\ExchangeData.py", line 21, in <module>
    n = account.root.walk()
        ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
                                     ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\account.py", line 335, in root
    return Root.get_distinguished(account=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\folders\roots.py", line 113, in get_distinguished
    return cls.resolve(account=account, folder=DistinguishedFolderId(id=cls.DISTINGUISHED_FOLDER_ID))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\folders\base.py", line 510, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\folders\collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Python311\Lib\site-packages\exchangelib\folders\collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\Python311\Lib\site-packages\exchangelib\services\get_folder.py", line 43, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 287, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 317, in _get_elements
    self._handle_backoff(e)
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 446, in _handle_backoff
    raise e
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 308, in _get_elements
    yield from self._response_generator(payload=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 271, in _response_generator
    response = self._get_response_xml(payload=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 404, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\services\common.py", line 355, in _get_response
    r, session = post_ratelimited(
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\exchangelib\util.py", line 874, in post_ratelimited
    protocol.retry_policy.raise_response_errors(r)
  File "C:\Python311\Lib\site-packages\exchangelib\protocol.py", line 687, in raise_response_errors
    raise ErrorServerBusy("Caused by closed connection")
exchangelib.errors.ErrorServerBusy: Caused by closed connection

**Comment by ecederstrand** [comment]
This means the server is busy and cannot currently handle more connections. You can configure a retry policy, as described in the documentation, or wait until the server is able to handle connections again.
