### ISSUE TITLE
"AttributeError: 'item_id', 'changekey' are invalid kwargs for this class" on Invite item

### ISSUE THREAD

**Issue by ticapix** [ecederstrand/exchangelib#124]
Hi,

When I'm listing my sent emails, when it reaches an invite forward, it fails with this error

```
$ ./main.py
{'subject': 'RE: xxxxxxxxxxxxxxxxx', 'datetime_sent': EWSDateTime(2017, 4, 20, 13, 26, 22, tzinfo=<UTC>)}
{'subject': 'RE: xxxxxxxxxxxxxxxxx', 'datetime_sent': EWSDateTime(2017, 4, 20, 13, 9, 58, tzinfo=<UTC>)}
{'subject': 'RE: xxxxxxxxxxxxxxxxx', 'datetime_sent': EWSDateTime(2017, 4, 20, 12, 12, 27, tzinfo=<UTC>)}
Traceback (most recent call last):
  File "./main.py", line 33, in <module>
    for item in account.sent.all().values('subject', 'datetime_sent')[:5]:
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/queryset.py", line 248, in __iter__
    for val in result_formatter(self._query()):
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/queryset.py", line 314, in _as_values
    for i in iterable:
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/folders.py", line 285, in find_items
    item = self.item_model_from_tag(i.tag).from_xml(elem=i)
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/items.py", line 324, in from_xml
    return cls(item_id=item_id, changekey=changekey, **kwargs)
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/items.py", line 127, in __init__
    super(Item, self).__init__(**kwargs)
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/properties.py", line 41, in __init__
    raise AttributeError("%s are invalid kwargs for this class" % ', '.join("'%s'" % k for k in kwargs.keys()))
AttributeError: 'item_id', 'changekey' are invalid kwargs for this class
```

Code
```python
#!/usr/bin/env python3

from exchangelib import Account, Credentials

primary_smtp_address = 'xxxxx'
username = primary_smtp_address
password = 'xxxxx'
credentials = Credentials(username=username, password=password)
account = Account(primary_smtp_address=primary_smtp_address, credentials=credentials, autodiscover=True, access_type=DELEGATE)

for item in account.sent.all().values('subject', 'datetime_sent')[:5]:
	print(item)
```

Should I filter by 'type' or is that a bug ?

Thanks

**Comment by ecederstrand** [comment]
Can you try the latest code from GitHub? This was supposedly fixed a couple of days ago

**Comment by ticapix** [comment]
Hi,

Indeed, it's already fixed in master :)

The buggy version I'm using is 1.9.2

(btw, super great job with that library !!)

**Comment by ecederstrand** [comment]
Thanks. My test server only has one account, so the meeting request code is untested because that requires someone to invite :-)
