### ISSUE TITLE
exchangelib.errors.UnauthorizedError: Invalid credentials for https://[domain].de/EWS/Exchange.asmx

### ISSUE THREAD

**Issue by LKleemann** [ecederstrand/exchangelib#1297]
**Describe the Problem**
A clear and concise description of what the problem is. If applicable, describe how other clients like Outlook or OWA behave.
Unfortunately, I cannot establish a connection between the ExchangeLib and the Exchange server. This is the latest ExchangeLib and an Exchange Server 2019. I always get the response: exchangelib.errors.UnauthorizedError: Invalid credentials for https://[domain].de/EWS/Exchange.asmx

**Additional context**
For example, Python and exchangelib versions.
I can log on to the OWA with the same access data, and I can also log on manually to Exchange.asmx. The web page "You have created a service.

To test this service, you need to create a client and use it to access the service. You can do this using the "svcutil.exe tool" on the command line using the following syntax:"

The password can therefore not have expired.

I look forward to a few solutions from you and wish you a pleasant evening.

**Comment by ecederstrand** [comment]
Which auth type are you using to access the Exchange server? If your username an password is correct, then it's likely that you are connecting with an auth type that the EWS service does not support.

**Comment by LKleemann** [comment]
Thank you very much for your quick response. I am using the Auth type "Basic". This Auth type is also activated internally. What is the best way to check whether the "Basic" Auth type is still activated?

Many thanks for your support

**Comment by LKleemann** [comment]
Thank you very much for your support. Right, I had the wrong Auth type here.

![chrome_5xdSAfqKhe](https://github.com/ecederstrand/exchangelib/assets/43823472/bd5176e6-bd21-40e5-8b79-ccec4ed3b1f4)

Here you can see the settings for authentication in the ECP. So I need NTLM.

Unfortunately, I get the following error message:

exchangelib.errors.TransportError: No valid version headers found in response (ErrorServerBusy("Reraised from ErrorInternalServerTransientError(Reraised from KeyError('www-authenticate'))"))

Can you please help me again here?

Many thanks in advance.

**Comment by ecederstrand** [comment]
Please post the full stack trace, and the code you use to connect to the server.

**Comment by LKleemann** [comment]
## Traceback
```
Traceback (most recent call last):
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/util.py", line 833, in post_ratelimited
    r = session.post(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests_ntlm/requests_ntlm.py", line 168, in response_hook
    return self.retry_using_http_NTLM_auth(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests_ntlm/requests_ntlm.py", line 133, in retry_using_http_NTLM_auth
    auth_header_value = response2.headers[auth_header_field]
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'www-authenticate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 308, in _get_elements
    yield from self._response_generator(payload=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 271, in _response_generator
    response = self._get_response_xml(payload=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 404, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 355, in _get_response
    r, session = post_ratelimited(
                 ^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/util.py", line 852, in post_ratelimited
    raise ErrorInternalServerTransientError(f"Reraised from {e.__class__.__name__}({e})")
exchangelib.errors.ErrorInternalServerTransientError: Reraised from KeyError('www-authenticate')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/version.py", line 202, in guess
    list(ConvertId(protocol=protocol).call([AlternateId(id="DUMMY", format=EWS_ID, mailbox="DUMMY")], ENTRY_ID))
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 225, in _elems_to_objs
    for elem in elems:
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 287, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 340, in _get_elements
    self._handle_backoff(ErrorServerBusy(f"Reraised from {e.__class__.__name__}({e})", back_off=wait))
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/services/common.py", line 446, in _handle_backoff
    raise e
exchangelib.errors.ErrorServerBusy: Reraised from ErrorInternalServerTransientError(Reraised from KeyError('www-authenticate'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lkleemann/development/IntranetSystem/server/src/python/exchange/exchangeService.py", line 44, in <module>
    IntranetExchangeConnection = IntranetExchangeConnectionFile.IntranetExchangeConnection()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/development/IntranetSystem/server/src/python/exchange/functions/exchangeConnection.py", line 19, in __init__
    self.mailAccount_Intranet = Account(
                                ^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/account.py", line 205, in __init__
    self.version = self.protocol.version.copy()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/protocol.py", line 480, in version
    self.config.version = Version.guess(self, api_version_hint=self.api_version_hint)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lkleemann/.local/lib/python3.12/site-packages/exchangelib/version.py", line 206, in guess
    raise TransportError(f"No valid version headers found in response ({e!r})")
exchangelib.errors.TransportError: No valid version headers found in response (ErrorServerBusy("Reraised from ErrorInternalServerTransientError(Reraised from KeyError('www-authenticate'))"))
```

***

## Connection to Server

```
self.credentials = Credentials(
            username='Test.User@[domain].de', password='[password]')
        
self.config = Configuration(server="[server]",
    credentials=self.credentials, auth_type="NTLM"
)
#  retry_policy=FaultTolerance(max_wait=3600),

self.mailAccount= Account(
    primary_smtp_address='Test.User@[domain].de', config=self.config,
    autodiscover=False, access_type=DELEGATE
)
```

**Comment by ecederstrand** [comment]
This means that the server you are connecting to does not announce NTLM AUTH in its HTTP response headers. Either you are not connecting to the right server, or your server does not support NTLM auth after all.

**Comment by LKleemann** [comment]
Perfect, thank you very much for your support.
