### ISSUE TITLE
Error getting folders for v5.2.1+ (server 2010sp3 upd.29)

### ISSUE THREAD

**Issue by Barsovski** [ecederstrand/exchangelib#1306]
Exchange Server 2010 SP3 (upd.29)
Python 3.9

**Describe the bug**
exchangelib v5.1.0 - tree() all build
exchangelib v5.2.0 - authorization error
exchangelib v5.2.1+ - `ErrorSchemaValidation("The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed`.

**To Reproduce**
```
from exchangelib.version import VERSIONS, Version
from exchangelib import Credentials, Configuration, NTLM, Account, DELEGATE


bb_info = []
for b in [x[0] for x in VERSIONS]:
    info = None
    try:
        account = Account(
            primary_smtp_address=data.email,
            config=Configuration(
                version=Version(build=b),
                server=data.server, 
                credentials=Credentials(
                    username=f'{XXX}\\{XXX}',
                    password='XXX'
                ),
                auth_type=NTLM,
            ),
            access_type=DELEGATE,
            autodiscover=False,
        )
        info = account.root.tree()
                
    except Exception as e:
        info = e
    bb_info.append([b, info])
```

**Expected behavior**
Array of account.root.tree() for all Builds

**Log output**
```
[2024-05-13 12:42:00,107: INFO/ForkPoolWorker-9] Task test[ae352f9a-83e3-47a3-896e-c51cc95bec32] succeeded in 0.047411821000423515s: {'result': 'error', 'info': {'calendar_pk': 2, 'error_info': 'The request failed schema validation. The \'FieldURI\' attribute is invalid - The value \'folder:DistinguishedFolderId\' is invalid according to its datatype \'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType\' - The Enumeration constraint failed. (line: 2 position: 562)', 'error_stack': 'Traceback (most recent call last):
2024-05-13T09:42:00.107233238Z   File "/usr/local/lib/python3.9/site-packages/cached_property.py", line 70, in __get__
2024-05-13T09:42:00.107235454Z     return obj_dict[name]
2024-05-13T09:42:00.107236966Z KeyError: \'root\'
2024-05-13T09:42:00.107238457Z 
2024-05-13T09:42:00.107239868Z During handling of the above exception, another exception occurred:
2024-05-13T09:42:00.107241417Z 
2024-05-13T09:42:00.107243006Z Traceback (most recent call last):
2024-05-13T09:42:00.107244656Z   File "/app/ec/tasks.py", line 138, in update_c_data
2024-05-13T09:42:00.107247161Z     data = collect_c_data(c, date_s, date_e)
2024-05-13T09:42:00.107249642Z   File "/app/ec/tasks.py", line 193, in collect_c_data
2024-05-13T09:42:00.107253615Z     account.root.tree()
2024-05-13T09:42:00.107256002Z   File "/usr/local/lib/python3.9/site-packages/cached_property.py", line 74, in __get__
2024-05-13T09:42:00.107257691Z     return obj_dict.setdefault(name, self.func(obj))
```
```
['15.20.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.2.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.1.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.20.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.20.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.0.847.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['15.0.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['14.3.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['14.2.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['14.1.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
['14.0.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
[ '8.3.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
[ '8.2.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
[ '8.1.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"], 
[ '8.0.0.0',	"The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)"]

```

**Comment by ecederstrand** [comment]
This is surprising. `folderDistinguishedFolderId` is mentioned in https://learn.microsoft.com/en-us/dotnet/api/exchangewebservices.unindexedfielduritype?view=exchange-ews-proxy

It's possible that the field was not available in Exchange 2010, however.

**Comment by Barsovski** [comment]
> This is surprising. `folderDistinguishedFolderId` is mentioned in https://learn.microsoft.com/en-us/dotnet/api/exchangewebservices.unindexedfielduritype?view=exchange-ews-proxy
> 
> It's possible that the field was not available in Exchange 2010, however.
> 
> Can you please post the full stack trace leading to the `ErrorSchemaValidation`?

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/snap/pycharm-professional/327/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 4, in <module>
  File "/home/user/PycharmProjects/test_exchange/ec/tasks.py", line 139, in update_c_data
    data = collect_c_data(calendar, date_s, date_e)
  File "/home/user/PycharmProjects/test_exchange/ec/tasks.py", line 194, in collect_c_data
    account.root.tree()
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/account.py", line 350, in root
    return Root.get_distinguished(account=self)
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/folders/roots.py", line 113, in get_distinguished
    return cls.resolve(
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/folders/base.py", line 516, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/folders/collections.py", line 335, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/folders/collections.py", line 403, in get_folders
    yield from GetFolder(account=self.account).call(
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/get_folder.py", line 51, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 287, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 308, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 271, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 417, in _get_response_xml
    return self._get_soap_messages(body=body, **parse_opts)
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 505, in _get_soap_messages
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/home/user/PycharmProjects/test_exchange/venv/lib/python3.9/site-packages/exchangelib/services/common.py", line 545, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorSchemaValidation: The request failed schema validation. The 'FieldURI' attribute is invalid - The value 'folder:DistinguishedFolderId' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enumeration constraint failed. (line: 2 position: 562)
```

**Comment by ecederstrand** [comment]
Thanks for the stack trace! The referenced should fix your issue.
