### ISSUE TITLE
ValueError: Item must have an account

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#133]
Hi, 

I'm trying to add new calendar entries and got the following a ValueError:

I'm trying the following:
```
folder = account.root.get_folder_by_name('Kalender')
item = CalendarItem(folder=folder, subject='Foo')
item.save()
```

I also tried with `folder = account.calendar`. Same Error:
```
Traceback (most recent call last):
  File "sven/cli.py", line 52, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
Password: 
Traceback (most recent call last):
  File "sven/cli.py", line 52, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "sven/cli.py", line 46, in main
    item.save()
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 153, in save
    item = self._create(message_disposition=SAVE_ONLY, send_meeting_invitations=send_meeting_invitations)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 163, in _create
    raise ValueError('Item must have an account')
ValueError: Item must have an account
```

**Comment by ecederstrand** [comment]
There's an error in the README. You need to pass both a `folder` an an `account` argument to `CalendarItem`.

**Comment by fruitloop** [comment]
Thanks that worked

________________________________

**Comment by ecederstrand** [comment]
Reopening just so I remember to fix the docs :-)

**Comment by asanta27** [comment]
@fruitloop @ecederstrand could you please post a correct example? It doesn't appear the docs have been updated yet. 

I am not sure what you mean by passing both a folder and account argument to a CalendarItem.

**Comment by asanta27** [comment]
Never mind, I got it!

`tz = EWSTimeZone.timezone('Europe/Copenhagen')

item = CalendarItem(account=myaccount,
                    folder=myaccount.calendar,  # account & folder required.
                    subject='foo',
                    start = tz.localize(EWSDateTime(2017, 6, 3)), # start & end required
                    end=tz.localize(EWSDateTime(2017, 6, 4)))

item.save()  # This gives the item an item_id and a changekey
item.subject = 'bar'
item.save()  # When the items has an item_id, this will update the item`
