### ISSUE TITLE
Getting KeyError at 'User credentials'

### ISSUE THREAD

**Issue by salmansamie** [ecederstrand/exchangelib#189]
Hi Erik,
I am getting KeyError at 'User credentials'. I have tried following the exchangelib documentation and  stackoverflow solutions. I have checked my credentials which are perfectly fine.
Below is my code:

```
credentials = Credentials(
    username='msdomain\XXXX',
    password='YYYY')

'''
version = Version(build=Build(15, 0, 12, 34))
config = Configuration(
    server='mxb-001c3501.gslb.pphosted.com',
    credentials=credentials,
    version=version,
    auth_type=NTLM
)


account = Account(
    primary_smtp_address='user@company_domain.com',
    config=config,
    autodiscover=False,
    access_type=DELEGATE
)
'''

ews_url = 'https://outlook.office365.com/EWS/Exchange.asmx'

config = Configuration(service_endpoint=ews_url, credentials=credentials, auth_type=NTLM)
account = Account(
    primary_smtp_address='user@company_domain.com', config=config, autodiscover=False, access_type=DELEGATE
)

```
And, I get the following error:

```
Traceback (most recent call last):
  File "/Users/sami/PycharmProjects/jira_auto/utils/mailer_d/mailer_exchlib.py", line 1, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/exchangelib/__init__.py", line 4, in <module>
    from .account import Account
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/exchangelib/account.py", line 12, in <module>
    from .autodiscover import discover
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 24, in <module>
    from future.moves.queue import LifoQueue
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/future/standard_library/__init__.py", line 808, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/Users/sami/PycharmProjects/tesoro-arty/venv-tesoro-arty/lib/python3.6/site-packages/future/standard_library/__init__.py", line 779, in __enter__
    module = __import__(m, level=0)
  File "/Users/sami/PycharmProjects/jira_auto/test.py", line 11, in <module>
    print(conf_parser()[0], conf_parser()[1])
  File "/Users/sami/PycharmProjects/jira_auto/test.py", line 9, in conf_parser
    return config['User credentials']['username'], config['User credentials']['password']
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'User credentials'

Process finished with exit code 1

```

Is there any other indication of whats going wrong?

**Comment by ecederstrand** [comment]
The `KeyError` comes from within your own `conf_parser()` function:

```python
config['User credentials']['username'], config['User credentials']['password']
```
This code isn't in the example you posted, so you seem to have some confusion over what code you're actually running. Anyway, an exchangelib `Configuration` object can't be indexed like you're trying to.

**Comment by dpasut** [comment]
Hey, I know this is really old, but I came across a similar issue today at work. 

```
 File "/usr/local/lib/python3.7/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/usr/local/lib/python3.7/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/Users/<user>/Desktop/outlook/test.py", line 19, in <module>
    credentials = EWS.Credentials(
AttributeError: module 'exchangelib' has no attribute 'Credentials'
```

When running the script `send_email.py`, which references **no** other files in it's current folder, it runs as expected, and an email is sent as intended. 

However, once you put a file `test.py` in the same directory, that script is also executed.

**Comment by ecederstrand** [comment]
This is not an exchangelib issue. You have been bitten by https://stackoverflow.com/a/49692407/219640

**Comment by dpasut** [comment]
You're right. Thanks for pointing me in the right direction!
