### ISSUE TITLE
connection error on shitty mobile connection

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#195]
I'm online over my phone and the connection is not that great.
ping tells me that I've got a package loss of about 50 to 60%.

That's probably the error. Is there a way to expand the max-tries or timeouts?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x108eb8710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //outlook.office365.com/EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x108eb8710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tasks.py", line 19, in <module>
    if __name__ == '__main__': main()
  File "tasks.py", line 9, in main
    config = Configuration(server='https://outlook.office365.com', credentials=credentials)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/configuration.py", line 48, in __init__
    version=version
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 169, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 202, in __init__
    verify=self.verify_ssl, name=self.credentials.username)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/transport.py", line 124, in get_service_authtype
    verify=verify)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //outlook.office365.com/EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x108eb8710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by ecederstrand** [comment]
You could hack exchangelib to accept a custom timeout or increase the retry limit, but you could also just wrap your own code in this:

```python
while True:
    try:
        config = Configuration(...)
        break
    except requests.exceptions.ConnectionError:
        pass
```

**Comment by fruitloop** [comment]
The loop makes sense, I'll try that the next time my internet connection sucks again ;)

I make a call like this:
```
credentials = ServiceAccount(username='roland@planitz.at', password='topsecret')
config = Configuration(server='mail.example.com', credentials=credentials)
account = Account(primary_smtp_address='john@example.com', config=config,
                  autodiscover=False, access_type=DELEGATE)
```

But I should call it like this?
```
ews_url = 'set that from >account.protocol.service_endpoint< once'
ews_auth_type = 'set that from >account.protocol.auth_type< once'
email = 'roland@planitz.at'

credentials = ServiceAccount(username=email, password='topsecret')
config = Configuration(service_endpoint=ews_url, credentials=credentials, auth_type=ews_auth_type)
account = Account(primary_smtp_address=email, config=config, autodiscover=False, access_type=DELEGATE)
```

**Comment by ecederstrand** [comment]
You can do both. The latter should result in no HTTP requests being sent when you create the `Configuration` object, so that's an alternative to the loop.

**Comment by ecederstrand** [comment]
@fruitloop It seems we can close this one?

**Comment by fruitloop** [comment]
Thanks, I couldn't test it yey but it seems that there is enough information here.
I'll just reopen the issue if I can't figure it out from here.
