### ISSUE TITLE
TypeError: Incorrect padding

### ISSUE THREAD

**Issue by Jaycolas** [ecederstrand/exchangelib#211]
Hi, 

I met below error when looping the item in mailbox folder?
Could you please kindly take a look at it?
Thanks!

Traceback (most recent call last):
  File "\\nshen-gv\workspace\nshen\Projects\AutoDispatcher\email_getter.py", line 97, in <module>
    for item in all_items:
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\queryset.py", line 161, in __iter__
    for val in result_formatter(self._query()):
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\queryset.py", line 228, in _as_items
    for i in iterable:
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\account.py", line 425, in fetch
    item = validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self)
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\items.py", line 331, in from_xml
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.supported_fields()}
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\items.py", line 331, in <dictcomp>
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.supported_fields()}
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\site-packages\exchangelib\fields.py", line 420, in from_xml
    return base64.b64decode(val)
  File "C:\Users\nshen\AppData\Local\Continuum\Anaconda2\lib\base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by ecederstrand** [comment]
Are you using extended properties with binary content? If not, this is probably an email with invalid Base64-encoded mime content. You can test this by not requesting mime content (use the `only()` method):

```python
for item in my_account.imbox.all().only('subject', 'body', ...): # All fields you need except 'mime_content'
    print(item)
```

**Comment by Jaycolas** [comment]
Thank you man! I will try it out

**Comment by ecederstrand** [comment]
Unless the problematic email contains confidential information, please post the content of the `MimeContent` element here so we can find out why the `Incorrect padding` error is happening and either find a workaround to parse the data anyway, or print a warning and ignore the value.

**Comment by Jaycolas** [comment]
Hi, man, sorry to ask, how to enable the debug logging

**Comment by ecederstrand** [comment]
See https://github.com/ecederstrand/exchangelib#troubleshooting :-)

**Comment by ecederstrand** [comment]
There are some suggestions for recovering from `Incorrect padding` errors here: https://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding

But I'd really like to see the actual data before making any workarounds.

**Comment by ecederstrand** [comment]
Closing due to timeout. Feel free to reopen if you find the `MimeContent` contents, or if you need more help :-)
