### ISSUE TITLE
AttributeError: 'America/New_York' object has no attribute 'ms_id'

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#212]
Hello,

I'm trying to write a script to check a mailbox for new messages and send out a meeting/appointment based on data in message body. When I attempt to save() the meeting, I get the following error:

**AttributeError: 'America/New_York' object has no attribute 'ms_id'**

I get the error whether I use pytz .localize or datetime .replace.

I am working in a M$ Win7 environment and I am retrieving the local timezone using pytz.timezone with tzlocal.get_localzone.

My Python version is 2.7.11.

My exchangelib version is 1.9.4.

Google searches for the error proved fruitless as I only got hits on the code in github.

Here is the traceback:

Traceback (most recent call last):
  File "C:/Users/M82129/Git/Vendor Circut Notification/testVCN.py", line 56, in <module>
    vcn_appt.save()
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 162, in save
    item = self._create(message_disposition=SAVE_ONLY, send_meeting_invitations=send_meeting_invitations)
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 176, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 260, in bulk_create
    send_meeting_invitations=send_meeting_invitations,
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 254, in <genexpr>
    i if isinstance(i, Exception)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 450, in _pool_requests
    elems = r.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
AttributeError: 'America/New_York' object has no attribute 'ms_id'

Process finished with exit code 1

Any ideas?

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
You need to use an exchangelib timezone to localize your datetime values. Plain pytz timezones and Python datetimes will not work:

```python
from exchangelib import EWSDateTime, EWSTimeZone
tz = EWSTimeZone.timezone('America/New_York')
# Or auto-detect:
tz = EWSTimeZone.localzone()

localized_dt = tz.localize(EWSDateTime(2017, 8, 22, 7, 5, 0))
```

**Comment by rjwiii** [comment]
That worked. Thanks
