### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by vernichon** [ecederstrand/exchangelib#23]
Hello,

Can you please, say me if it's possible to install the exchangelib library on Windows and/or Mac os  ?

I have tried on Mac os but I have an error

✘-1 ~/Projects/PycharmProjects/exchangelib [master|✔]
10:41 $ sudo python2.7 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to exchangelib.egg-info/requires.txt
writing exchangelib.egg-info/PKG-INFO
writing top-level names to exchangelib.egg-info/top_level.txt
writing dependency_links to exchangelib.egg-info/dependency_links.txt
reading manifest file 'exchangelib.egg-info/SOURCES.txt'
writing manifest file 'exchangelib.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.12-intel/egg
creating build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/__init__.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/account.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/autodiscover.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/configuration.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/credentials.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/errors.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/ewsdatetime.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/folders.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/protocol.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/restriction.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/services.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/transport.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/util.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
copying build/lib/exchangelib/version.py -> build/bdist.macosx-10.12-intel/egg/exchangelib
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/account.py to account.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/account.py", line 100
    raise ErrorFolderNotFound('No useable default %s folders' % fld_class.__name__) from e
                                                                                       ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/autodiscover.py to autodiscover.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/autodiscover.py", line 156
    raise AutoDiscoverCircularRedirect('Redirect to same email address: %s' % email) from e
                                                                                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/configuration.py to configuration.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/credentials.py to credentials.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/errors.py to errors.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/ewsdatetime.py to ewsdatetime.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/ewsdatetime.py", line 92
    raise ValueError('Please add an entry for "%s" in PYTZ_TO_MS_TZMAP' % tz.zone) from e
                                                                                      ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/folders.py to folders.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/protocol.py to protocol.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/protocol.py", line 127
    raise TransportError("Server '%s' does not exist" % self.server) from e
                                                                        ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/restriction.py to restriction.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/services.py to services.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/services.py", line 112
    raise SOAPError('SOAP response is not XML: %s' % e) from e
                                                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/transport.py to transport.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/transport.py", line 131
    raise ValueError("Authentication type '%s' not supported" % auth_type) from e
                                                                              ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/util.py to util.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/util.py", line 159
    raise ParseError('%s\nOffending text: [...]%s[...]' % (str(e), offending_excerpt)) from e
                                                                                          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/exchangelib/version.py to version.pyc
  File "build/bdist.macosx-10.12-intel/egg/exchangelib/version.py", line 262
    raise EWSWarning('Unknown XML response from %s (response: %s)' % (protocol.service_endpoint, r.text)) from e
                                                                                                             ^
SyntaxError: invalid syntax

creating build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/PKG-INFO -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/not-zip-safe -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/requires.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying exchangelib.egg-info/top_level.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
creating 'dist/exchangelib-1.6.2-py2.7.egg' and adding 'build/bdist.macosx-10.12-intel/egg' to it
removing 'build/bdist.macosx-10.12-intel/egg' (and everything under it)
Processing exchangelib-1.6.2-py2.7.egg
removing '/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg
Extracting exchangelib-1.6.2-py2.7.egg to /Library/Python/2.7/site-packages
  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/account.py", line 100
    raise ErrorFolderNotFound('No useable default %s folders' % fld_class.__name__) from e
                                                                                       ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/autodiscover.py", line 156
    raise AutoDiscoverCircularRedirect('Redirect to same email address: %s' % email) from e
                                                                                        ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/ewsdatetime.py", line 92
    raise ValueError('Please add an entry for "%s" in PYTZ_TO_MS_TZMAP' % tz.zone) from e
                                                                                      ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/protocol.py", line 127
    raise TransportError("Server '%s' does not exist" % self.server) from e
                                                                        ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/services.py", line 112
    raise SOAPError('SOAP response is not XML: %s' % e) from e
                                                           ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/transport.py", line 131
    raise ValueError("Authentication type '%s' not supported" % auth_type) from e
                                                                              ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/util.py", line 159
    raise ParseError('%s\nOffending text: [...]%s[...]' % (str(e), offending_excerpt)) from e
                                                                                          ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg/exchangelib/version.py", line 262
    raise EWSWarning('Unknown XML response from %s (response: %s)' % (protocol.service_endpoint, r.text)) from e
                                                                                                             ^
SyntaxError: invalid syntax

exchangelib 1.6.2 is already the active version in easy-install.pth

Installed /Library/Python/2.7/site-packages/exchangelib-1.6.2-py2.7.egg
Processing dependencies for exchangelib==1.6.2
Searching for dnspython3>=1.12.0
Reading https://pypi.python.org/simple/dnspython3/
Downloading https://pypi.python.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip#md5=ae5118c48c26161a74a8e092b109aa33
Best match: dnspython3 1.15.0
Processing dnspython3-1.15.0.zip
Writing /tmp/easy_install-P2bUEJ/dnspython3-1.15.0/setup.cfg
Running dnspython3-1.15.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-P2bUEJ/dnspython3-1.15.0/egg-dist-tmp-glk1xa
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'Programming Language :: Python :: 3 :: Only',
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Library/Python/2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Library/Python/2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1125, in best_match
    return self.obtain(req, installer)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1137, in obtain
    return installer(requirement)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Library/Python/2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 249, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 168, in save_modules
    saved_exc.resume()
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 143, in resume
    six.reraise(type, exc, self._tb)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
    yield
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 246, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 276, in run
    return func()
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 245, in runner
    _execfile(setup_script, ns)
  File "/Library/Python/2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-P2bUEJ/dnspython3-1.15.0/setup.py", line 25
    """+"="*78, file=sys.stdout)
                    ^
SyntaxError: invalid syntax

**Comment by ecederstrand** [comment]
exchangelib works fine OSX and should work on Windows, although I have not tried. But it's a Python3-only package, which is the cause of your errors.

@wolfhechel is working on a backport in #22 so hopefully we will support Python2 soon. You can use his fork until then if you need Python2 support.
