### ISSUE TITLE
ValueError thrown after polling for extended amount of time

### ISSUE THREAD

**Issue by t0astt** [ecederstrand/exchangelib#232]
I'm running a check for new mail every 5 seconds. I'm running into an issue where after a certain amount of iterations (not yet known how many), a ValueError exception is thrown.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/komand-0.3.5-py3.4.egg/komand/trigger.py", line 89, in run
    self.trigger.run(params)
  File "/usr/local/lib/python3.4/site-packages/microsoft_exchange_komand_plugin-0.1.0-py3.4.egg/komand_microsoft_exchange/triggers/email_received.py", line 153, in run
    for message in folder.filter(is_read=False).only('attachments', 'sender', 'subject', 'body'):
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/queryset.py", line 187, in __iter__
    for val in result_formatter(self._query()):
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/queryset.py", line 263, in _as_items
    for i in iterable:
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/account.py", line 405, in fetch
    is_empty, ids = peek(ids)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/util.py", line 92, in peek
    first = next(iterable)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/folders.py", line 324, in find_items
    for i in items:
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/services.py", line 297, in _paged_call
    payload = payload_func(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/services.py", line 794, in get_payload
    set_xml_value(parentfolderids, self.folders, version=self.account.version)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/util.py", line 178, in set_xml_value
    elem.append(v.to_xml(version=version))
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/folders.py", line 370, in to_xml
    self.clean(version=version)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/folders.py", line 122, in clean
    super(Folder, self).clean(version=version)
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/properties.py", line 50, in clean
    setattr(self, f.name, f.clean(val, version=version))
  File "/usr/local/lib/python3.4/site-packages/exchangelib-1.10.0-py3.4.egg/exchangelib/fields.py", line 520, in clean
    raise ValueError("'%s' value '%s' exceeds length %s" % (self.name, value, self.max_length))
ValueError: 'changekey' value 'AQAAALYAAAABAAAArgAAAAEAAACmAAAAAQAAAJ4AAAABAAAAlgAAAAEAAACOAAAAAQAAAIYAAAABAAAAfgAAAAEAAAB2AAAAAQAAAG4AAAABAAAAZgAAAAEAAABeAAAAAQAAAFYAAAABAAAATgAAAAEAAABGAAAAAQAAAD4AAAABAAAANgAAAAEAAAAuAAAAAQAAACYAAAABAAAAHgAAAAEAAAAWAAAA49uDEsFY7UCiqDVBDKNrbQAAAAA38Q==' exceeds length 255
DEBUG:exchangelib.autodiscover:Domain kex.pdev.r7ops.com: Closing sessions
DEBUG:exchangelib.protocol:Server secure.autodiscover.emailsrvr.com: Closing sessions
DEBUG:exchangelib.protocol:Server secure.autodiscover.emailsrvr.com: Closing sessions
DEBUG:exchangelib.protocol:Server mex09.emailsrvr.com: Closing sessions
```

**Comment by ecederstrand** [comment]
We previously assumed 255 chars was enough to hold the change key value. That is clearly not enough. 713a2ce should fix your issue.

**Comment by t0astt** [comment]
@ecederstrand Thank you for the very quick fix - it is much appreciated! 👍
