### ISSUE TITLE
Value exceeds length 255 when saving email

### ISSUE THREAD

**Issue by nebriv** [ecederstrand/exchangelib#236]
Hello,

When saving an email (after marking it as read) I am receiving this message. This doesn't occur for all emails, it looks like its based on the message IDs. I've redacted the domain with xs matching the same number.

Traceback (most recent call last):
  File "file.py", line 197, in get_emails
    email.save()
  File "/usr/local/lib/python2.7/site-packages/exchangelib/items.py", line 167, in save
    send_meeting_invitations=send_meeting_invitations
  File "/usr/local/lib/python2.7/site-packages/exchangelib/items.py", line 225, in _update
    send_meeting_invitations_or_cancellations=send_meeting_invitations)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/account.py", line 318, in bulk_update
    suppress_read_receipts=suppress_read_receipts,
  File "/usr/local/lib/python2.7/site-packages/exchangelib/account.py", line 312, in <genexpr>
    i if isinstance(i, Exception) else Item.id_from_xml(i)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 446, in _pool_requests
    elems = r.get()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: 'references' value '<A64A2FAF0477094EABD67605A51A52B50235AFBF72@xxxxxxxxx.xxxxx.net>,<A64A2FAF0477094EABD67605A51A52B50235B05B9F@xxxxxxxxx.xxxxx.net> <DM3PR14MB0651A8CEE13F5A0955A55391DD960@DM3PR14MB0651.namprd14.prod.outlook.com>,<DM5PR1401MB1914D4EAC8C3077DE75A511CB2970@DM5PR1401MB1914.namprd14.prod.outlook.com>' exceeds length 255

Let me know if any other information or troubleshooting steps are required.

Thanks!

**Comment by nebriv** [comment]
This might be resolved with the fixes associated #232 
Testing now.

**Comment by nebriv** [comment]
Resolved by changing the following line to IdField instead of TextField (as done in the resolution for #232 ) - however I'm unsure if this would cause any issues down the road.

https://github.com/ecederstrand/exchangelib/blob/9f9cad6e8a8cbc9b6b4174ec80bbc345a2814c47/exchangelib/items.py#L547

**Comment by ecederstrand** [comment]
Thanks for the report. I'm writing a test to check all text fields for this behaviour and will be patching this later today.
