### ISSUE TITLE
ErrorNameResolutionNoResults after update from 1.10.0 to 1.10.1

### ISSUE THREAD

**Issue by MartinThoma** [ecederstrand/exchangelib#242]
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 935, in handle_one_response
        self.run_application()
      File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 908, in run_application
        self.result = self.application(self.environ, self.start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/raven/middleware.py", line 98, in __call__
        iterable = self.application(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/math/Github/abc/web/am_internal_services/app.py", line 996, in show_customer_view
        smtp_address=smtp_address)
      File "/home/math/Github/abc/web/am_internal_services/exchange_utils.py", line 77, in login
        exchange_cfg = Configuration(server=server, credentials=credentials)
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 46, in __init__
        version=version
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/protocol.py", line 177, in __call__
        raise e
    ErrorNameResolutionNoResults: Es wurden keine Ergebnisse gefunden.
    Tue Sep 12 13:47:42 2017 {'REMOTE_PORT': '52260', 'HTTP_HOST': 'localhost:8082', 'REMOTE_ADDR': '::1', (hidden keys: 25)} failed with ErrorNameResolutionNoResults

**Comment by MartinThoma** [comment]
I just confirmed. Going back to `exchangelib==1.10.0` fixed the issue.

**Comment by ecederstrand** [comment]
Thanks! `Version._guess_version_from_service()` needs to work even though `ResolveNames.call()` throws `ErrorNameResolutionNoResults`. Not trivial to fix, though.

**Comment by ecederstrand** [comment]
@MartinThoma Can you test if adding this before anything else in your code fixes the error?

```python
from exchangelib.services import ResolveNames
from exchangelib.errors import ErrorNameResolutionMultipleResults, ErrorNameResolutionNoResults
ResolveNames.WARNINGS_TO_IGNORE_IN_RESPONSE = ErrorNameResolutionMultipleResults, ErrorNameResolutionNoResults
```

**Comment by ecederstrand** [comment]
Don't bother, it's most likely not going to work.

**Comment by MartinThoma** [comment]
It's not working^^

    2017-09-12 15:00:21,878 INFO API version "Exchange2013_SP1" worked but server reports version "V2_8". Using "Exchange2013_SP1"
    2017-09-12 15:00:21,878 WARNING Failed to create cached protocol with key (u'https://mail.foobar.com/EWS/Exchange.asmx', Credentials(u'FOOBAR\\FOOBAR.FOOBAR', u'********')): Es wurden keine Ergebnisse gefunden.
    2017-09-12 15:00:21,888 ERROR 'Configuration' object has no attribute 'protocol'
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/raven/utils/serializer/manager.py", line 76, in transform
        return repr(value)
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 54, in __repr__
        return self.__class__.__name__ + repr((self.protocol,))
    AttributeError: 'Configuration' object has no attribute 'protocol'
    2017-09-12 15:00:22,055 DEBUG Sending message of length 6982 to https://sentry.io/api/215878/store/
    2017-09-12 15:00:22,061 ERROR 'Configuration' object has no attribute 'protocol'
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/raven/utils/serializer/manager.py", line 76, in transform
        return repr(value)
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 54, in __repr__
        return self.__class__.__name__ + repr((self.protocol,))
    AttributeError: 'Configuration' object has no attribute 'protocol'
    2017-09-12 15:00:22,064 DEBUG Sending message of length 7792 to https://sentry.io/api/215878/store/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 935, in handle_one_response
        self.run_application()
      File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 908, in run_application
        self.result = self.application(self.environ, self.start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/raven/middleware.py", line 98, in __call__
        iterable = self.application(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/math/Github/FOOBAR/web/FOOBAR/app.py", line 996, in show_customer_view
        smtp_address=smtp_address)
      File "/home/math/Github/FOOBAR/web/FOOBAR/exchange_utils.py", line 80, in login
        exchange_cfg = Configuration(server=server, credentials=credentials)
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 46, in __init__
        version=version
      File "/usr/local/lib/python2.7/dist-packages/exchangelib/protocol.py", line 177, in __call__
        raise e
    ErrorNameResolutionNoResults: Es wurden keine Ergebnisse gefunden.
    Tue Sep 12 15:00:22 2017 {'REMOTE_PORT': '56178', 'HTTP_HOST': 'localhost:8082', 'REMOTE_ADDR': '::1', (hidden keys: 25)} failed with ErrorNameResolutionNoResults
