### ISSUE TITLE
Find all Conversations in a folder for a given ConversationId

### ISSUE THREAD

**Issue by karanatree** [ecederstrand/exchangelib#261]
I want to get all messages with the same conversation_id, but
the following code

```python
items = folder_xyz.all().filter(datetime_received__gte=today_before)[:1]

for item in items:
     items_inside= folder_xyz.filter(conversation_id= item.conversation_id)
```

Gives error

```python
Traceback (most recent call last):
  File "C:\~\exchangelib\restriction.py", line 202, in clean
    value_to_xml_text(self.value)
  File "C:\~\exchangelib\util.py", line 159, in value_to_xml_text
    raise NotImplementedError('Unsupported type: %s (%s)' % (type(value), value))
NotImplementedError: Unsupported type: <class 'exchangelib.properties.ConversationId'> (ConversationId(id='AAQkAGNjNzRiZTRlLThjVGItNDVkZS1hYmMyLWViOGQzMGNmMTUyMAAQANqeNNplWk+Nmr8V3BTY+io='))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/~/outlook_api_test/try.py", line 63, in <module>

 items_inside= folder_xyz(conversation_id= item.conversation_id)
  File "C:\~\exchangelib\folders.py", line 339, in filter
    return QuerySet(self).filter(*args, **kwargs)
  File "C:\~\exchangelib\queryset.py", line 349, in filter
    q = Q(*args, **kwargs)
  File "C:\~\exchangelib\restriction.py", line 102, in __init__
    self.clean()
  File "C:\~\exchangelib\restriction.py", line 204, in clean
    raise ValueError('Value "%s" for filter on field path "%s" is unsupported' % (self.value, self.field_path))
ValueError: Value "ConversationId(id='AAQkAGNjNzRiZTRlLThjVGItNDVkZS1hYmMyLWViOGQzMGNmMTUyMAAQANqeNNplWk+Nmr8V3BTY+io=')" for filter on field path "conversation_id" is unsupported
```

**Comment by ecederstrand** [comment]
`filter()` doesn't know how to convert a `ConversationId` object to an XML search string yet. Try using `item.conversation_id.id` as a search value instead.

**Comment by karanatree** [comment]
> items = folder_xyz.all().filter(datetime_received__gte=today_before)[:1]
> 
> for item in items:
>      items_inside= folder_xyz.filter(conversation_id= item.conversation_id

gives the error

TypeError: Field 'conversation_id' value 'AAQkAGNjNzRiZTRlLThjMGItNDVkZS1hYmMyLWViOGQzMGNmMTUyMAAQAP2wIIP8ABpNvXwAeVuHHZI=' must be of type <class 'exchangelib.properties.ConversationId'>

**Comment by ecederstrand** [comment]
Thanks for the extra testing, and sorry for the breakage :-)
