### ISSUE TITLE
Tasks Subfolder

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#267]
Hi, 

I am using Office365 mostly with my iPad and NineFolders for Android.
On the iPad there is a way to create a new "List" which seems to be a 
subfolder of Tasks. NineFolders on Android shows me the different Lists
and I can create Tasks there, however your library seems to only get the
default List when I'm trying to access tasks.

Is there a way to get all Task lists?

**Comment by ecederstrand** [comment]
Have you tried `print(account.root.tree())` to check if the tasks folders are there? `account.tasks` only points to the default tasks folder.

**Comment by fruitloop** [comment]
I have this code:
```
cred = ServiceAccount( username=sys.argv[1], password=sys.argv[2],)
account = Account( primary_smtp_address=sys.argv[1], credentials=cred, autodiscover=True, access_type=DELEGATE,)

folder = account.calendar.get_folder_by_name(sys.argv[3])
print(folder)
print()
print(account.root.tree())
```

which gives me:
```
Calendar (Privacy Week)

Traceback (most recent call last):
  File "dada.py", line 24, in <module>
    if __name__ == "__main__": main()
  File "dada.py", line 22, in main
    print(account.root.tree())
AttributeError: 'Root' object has no attribute 'tree'
```

So in the first example I do use `account.calendar` as kind of a starting point to search for a calendar name beneath it (since there is a folder in my inbox which has the same name)

**Comment by ecederstrand** [comment]
You need to upgrade your version of exchangelib. The `tree()` method was added recently.

**Comment by fruitloop** [comment]
I ran `pip install --force exchangelib` and still get the error.
Am I doing something wrong?

**Comment by ecederstrand** [comment]
You need v1.10.4, I believe. I usually  use `pip install -U exchangelib` to upgrade.

**Comment by fruitloop** [comment]
Thanks, the `--force` didn't do anything. With `install -U` it updated fine and now everything works.
I also like the message telling me how to get a named folder other than `get_folder_by_name`
`tree()` also works fine. And yes just like with calendars there are subfolders.
