### ISSUE TITLE
Trouble connecting to server -- Timeout Error

### ISSUE THREAD

**Issue by tshah11** [ecederstrand/exchangelib#271]
Hello,

I have been trying to connect to my exchange server using exchangelib but continue to receive connection errors. I am just now brushing back up on my python skills and am wondering if I may be doing something plainly wrong in my code.

This is the portion of my code creating a connection to exchange server and attempting to print emails:

```python
from datetime import timedelta
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, HTMLBody, Build, Version

creds = Credentials(username='domain\\Administrator', password='password')

config = Configuration(server='https://machinename.domain.com', credentials=creds)

account = Account(primary_smtp_address='administrator@domain.com', config=config,
          autodiscover=False, access_type=DELEGATE)

unread = account.inbox.filter(is_read=True)
	
print (unread)
```
-----------------------------------------------------------------------------------------------------------------

The errors in full are below:
```python
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Python34\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005190748>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //machine.domain.com/EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005190748>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 27, in <module>
    config = Configuration(server='https://rp11-excng.rp11.com', credentials=creds)
  File "C:\Python34\lib\site-packages\exchangelib\configuration.py", line 46, in __init__
    version=version
  File "C:\Python34\lib\site-packages\exchangelib\protocol.py", line 172, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\exchangelib\protocol.py", line 204, in __init__
    name=self.credentials.username)
  File "C:\Python34\lib\site-packages\exchangelib\transport.py", line 133, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //machine.domain.com/EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005190748>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```
-------------------------------------------------------------------------------------------------------------------

It is also a point of note that I am using the script on the server side for exchange.

**Comment by ecederstrand** [comment]
When you specify the server, you should only give the hostname, i.e. `Configuration(server='machinename.domain.com')`. If you need to specify the exact URL for some reason, use `Configuration(service_endpoint='https://example.com/EWS/Exchange.asmx')` instead.

**Comment by tshah11** [comment]
Hello Ecederstrand,

I ran the code with the change where this line:

Configuration(server='https://machinename.domain.com', credentials=creds)

is changed to this line:

Configuration(server='machinename.domain.com', credentials=creds)

and the following errors appear: 

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python34\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Python34\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test2.py", line 27, in <module>
    config = Configuration(server='rp11-excng.rp11.com', credentials=creds)
  File "C:\Python34\lib\site-packages\exchangelib\configuration.py", line 46, in __init__
    version=version
  File "C:\Python34\lib\site-packages\exchangelib\protocol.py", line 172, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\exchangelib\protocol.py", line 204, in __init__
    name=self.credentials.username)
  File "C:\Python34\lib\site-packages\exchangelib\transport.py", line 133, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

-------------------------------------------------------------------------------------------------------------------

It seems like the connection is being closed by the server. Is there anything additional needed for configuration to allow exchangelib a connection to the server? I may be wrong with my interpretation here.

Also I did try using the full link with your secondary option but the errors resulted in the same timeout error as my initial post. I tested the full link "https://example.com/EWS/Exchange.asmx" on the browser and an exchange service was successfully created once the appropriate authentication fields were entered.

Any help would be appreciated!

**Comment by tshah11** [comment]
One more noteworthy finding is that there is no traffic for the administrative user (the user being used in the script for the creds) in the EWS logs. I don't know if the server is blocking the request altogether or if theres any option on ECP to change that but if you know any information that would be helpful!

**Comment by ecederstrand** [comment]
The server shuts the connection when we're just trying to find out what authentiation method to use.

Are you sure `rp11-excng.rp11.com` is the correct server? Can you use autodiscover on this email address? If all else fails, try setting th auth method and possibly server version explicitly, as described in https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by tshah11** [comment]
I tried setting up version and auth method but I am getting the same error. Is NTLM the only form of auth method here? I run autodiscover but here's the set of errors i get for this run:

Traceback (most recent call last):
  File "test2.py", line 28, in <module>
    account = Account(primary_smtp_address='administrator@theamail.ca', credentials=creds, autodiscover=True, access_type=DELEGATE)
  File "C:\Python34\lib\site-packages\exchangelib\account.py", line 66, in __init__
    credentials=credentials)
  File "C:\Python34\lib\site-packages\exchangelib\autodiscover.py", line 214, in discover
    email=email)
  File "C:\Python34\lib\site-packages\exchangelib\autodiscover.py", line 248, in _try_autodiscover
    return _try_autodiscover(e.server, credentials, email)
  File "C:\Python34\lib\site-packages\exchangelib\autodiscover.py", line 262, in _try_autodiscover
    raise_from(AutoDiscoverFailed('All steps in the autodiscover protocol failed'), None)
  File "C:\Python34\lib\site-packages\future\utils\__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

I'm still wondering what could be blocking it on the server end...ever come across the auto discover error above though?

**Comment by ecederstrand** [comment]
`AutoDiscoverFailed` means that either autodiscover is configured incorrectly for this domain, or there are bugs in our implementation. You can verify this at http://testconnectivity.microsoft.com. If it succeeds, then we have a bug somewhere.

exchangelib supports NTLM, Basic and Digest authentication. There are open issues about OAuth, Kerberos and 2-factor auth.

**Comment by ecederstrand** [comment]
Hi @tshah11 Did you manage to connect to your server? If so, please add a quick note here about the solution and close the issue :-)
