### ISSUE TITLE
Failed to get auth type from service

### ISSUE THREAD

**Issue by diakbar** [ecederstrand/exchangelib#276]
Hi All,

I just tried this cool exchange python script. First time its works, but after adding some line, it doesn't work anymore. I got following error:
`exchangelib.errors.TransportError: Failed to get auth type from service`

My Code is like this:

```python
from datetime import timedelta
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
import sys, getopt

##### FOR LOGGING #####
import logging
from exchangelib.util import PrettyXmlHandler

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

credentials = Credentials(username='DOMAIN\\username', password='p4ssw0rd')
config = Configuration(server='webmail.myserver.co.id', credentials=credentials)
my_account = Account(primary_smtp_address='myname@myserver.co.id', config=config,
                         autodiscover=False, access_type=DELEGATE)
m = Message(
        account=my_account,
        subject=subject,
        body=bodytext,
        to_recipients=list_to
        # cc_recipients=['carl@example.com', 'denice@example.com'],  # Simple strings work, too
        # bcc_recipients=[Mailbox(email_address='erik@example.com'), 'felicity@example.com'],  # Or a mix of both
    )
m.send()
```

Am I missing something ?

**Comment by ecederstrand** [comment]
You're not missing anything obvious.

The code responsible for the error message is https://github.com/ecederstrand/exchangelib/blob/b3e14eaeebceea50b7a9cf28a635d714410ac37d/exchangelib/transport.py#L119 We're just trying to find out which authentication methods this the server supports. There's not a whole lot of useful debug output there, so you may have to add some diagnostic messages to find out what's going on.

**Comment by diakbar** [comment]
here's output after I enable logging.
```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '(u'https://webmail.myserver.co.id/EWS/Exchange.asmx', Credentials('DOMAIN\\makb', u'********'))'
DEBUG:exchangelib.transport:Getting service auth type for https://webmail.myserver.co.id/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): webmail.myserver.co.id
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '457', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2015_SP1" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '461', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2015" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '457', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2013_SP1" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '461', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2013" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '457', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '461', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP1" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmailmyserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '461', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '457', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007_SP1" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '461', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>DOMAIN\makb</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://webmail.myserver.co.id/EWS/Exchange.asmx
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://webmail.myserver.co.id:443 "POST /EWS/Exchange.asmx HTTP/1.1" 503 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '457', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.3', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 26 Oct 2017 04:16:20 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5'}
WARNING:exchangelib.protocol:Failed to create cached protocol with key (u'https://webmail.myserver.co.id/EWS/Exchange.asmx', Credentials('DOMAIN\\makb', u'********')): Failed to get auth type from service
DEBUG:exchangelib.protocol:Server webmail.myserver.co.id: Closing sessions
Traceback (most recent call last):
  File "sendemail.py", line 62, in <module>
    main(sys.argv[1:])
  File "sendemail.py", line 59, in main
    print sendEmail(file=file, to=to, subject="Statistic", sender="MySender")
  File "sendemail.py", line 27, in sendEmail
    config = Configuration(server='webmail.myserver.co.id', credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/protocol.py", line 177, in __call__
    raise e
exchangelib.errors.TransportError: Failed to get auth type from service
```

**Comment by ecederstrand** [comment]
Your server is returning HTTP 503 (Service Unavailable) for all requests to `https://webmail.myserver.co.id/EWS/Exchange.asmx` so I'm not sure there's much we can do except wait for the server to come back up.

**Comment by diakbar** [comment]
Hi @ecederstrand I just checked it again and somehow its worked, maybe there's some delay/rejection and it will unblock again. For the record the domain name is not real, i can't published the real one because some issues. Anyway great support thanks.

**Comment by ecederstrand** [comment]
Glad to help. Please reopen if you think this is an issue related to exchangelib.

**Comment by deepaksinghtopwal** [comment]
HI Erik,
i am also receiving the same error while connecting to a Office365 outlook account.
Could you please help me with this.

Error :     raise TransportError('Failed to get auth type from service')
exchangelib.errors.TransportError: Failed to get auth type from service

given below is a sample code :
creds = Credentials(
                    username='abcd@xyz-xyz.com', # Format of the email account i am trying to access
                    password= 'xyzxyzxyz' 
                    )

config = Configuration(
                    server='abcd@xyz-xyz.com', # (Same as email id , Also tried 'outlook.office365.com', 'smtp.office365.com')
                    credentials=creds
                    )

account = Account(
                    primary_smtp_address='abcd@xyz-xyz.com', # same as email id
                    autodiscover=False,
                    config = config,
                    access_type=DELEGATE
                    )

emails_in_inbox = len(account.inbox.all())
print(emails_in_inbox)


Errors i am receiving by changing different server names :

server = 'abcd@xyz-xyz.com' (Same as the email id)
    raise TransportError('Failed to get auth type from service')
exchangelib.errors.TransportError: Failed to get auth type from service


server = 'smtp.office365.com'
 raise UnauthorizedError('Wrong username or password for %s' % response.url)
exchangelib.errors.UnauthorizedError: Wrong username or password for https://smtp.office365.com/EWS/Exchange.asmx


server = 'outlook.office365.com'
    raise UnauthorizedError('Wrong username or password for %s' % response.url)
exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

**Comment by ecederstrand** [comment]
This is almost definitely a problem with your credentials. For O365, the username is always your primary SMTP address. `'xyz-xyz.com\abcd@xyz-xyz.com'` does not look correct. For O365, you should be able to use autodiscover, but `server='abcd@xyz-xyz.com'` is definitely wrong. `server` must be a hostname, not an email address. For O365, I believe the hostname is always `outlook.office365.com`.
