### ISSUE TITLE
Exchangelib 1.10.4 - O365 crash due to get_elements thread

### ISSUE THREAD

**Issue by ponmuthu** [ecederstrand/exchangelib#285]
Kindly please help to fix this issue.

when i try to get "Inbox" get_elements using stackstorm exchange sensor which uses exchangelib.1.10.4 , getting below error.

Python - 2.7.5
Exchangelib - 1.10.4
O365 APi Version from Response - MajorVersion="15" MinorVersion="20" MajorBuildNumber="218" MinorBuildNumber="12" Version="V2017_10_09"

Debug logs:
DEBUG [-] Session 15690 thread 36956112: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
2017-11-07 02:34:59,610 DEBUG [-] Server outlook.office365.com: Releasing session 15690
2017-11-07 02:34:59,611 DEBUG [-] Trying API version Exchange2016 for account <Email ID>
2017-11-07 02:34:59,611 DEBUG [-] FindItem: Got page with next offset None (last_page True)
2017-11-07 02:34:59,612 DEBUG [-] Processing items in chunks of 100
2017-11-07 02:34:59,612 DEBUG [-] Starting GetItem._get_elements worker 1 for 1 items
2017-11-07 02:34:59,613 DEBUG [-] Waiting for GetItem._get_elements result 1 of 1
2017-11-07 02:34:59,613 ERROR [-] Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 338, in _handle_tasks
    if thread._state:
AttributeError: '_MainThread' object has no attribute '_state'

**Comment by ecederstrand** [comment]
I'm sorry but there is no information in the stack trace which indicates what the problem could be.

I see that this has already been reported as https://github.com/StackStorm/st2/issues/3818, which links to https://github.com/eventlet/eventlet/issues/147 which says that multiprocessing.Pool is incompatible with eventlets (that StackStorm apparently uses) on Python2.7. In that case, your best bet is to try on Python3 instead.

For now, I'll assume this is an issue with StackStorm (or eventlet) and not exchangelib itself.

**Comment by ponmuthu** [comment]
@ecederstrand 

Sorry !!  I couldn't copy entire debug log here , it allows limited words only.

I mailed you entire debug log & As per my understanding i am getting thread crash exception from _get_elements in services.py

Kindly please check your mail for complete log.

2017-11-07 02:34:59,610 DEBUG [-] Session 15690 thread 36956112: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
2017-11-07 02:34:59,610 DEBUG [-] Server outlook.office365.com: Releasing session 15690
2017-11-07 02:34:59,611 DEBUG [-] Trying API version Exchange2016 for account cribot@cognizantgoc.com
2017-11-07 02:34:59,611 DEBUG [-] FindItem: Got page with next offset None (last_page True)
2017-11-07 02:34:59,612 DEBUG [-] Processing items in chunks of 100
2017-11-07 02:34:59,612 DEBUG [-] Starting GetItem._get_elements worker 1 for 1 items
**2017-11-07 02:34:59,613 DEBUG [-] Waiting for GetItem._get_elements result 1 of 1**
2017-11-07 02:34:59,613 ERROR [-] Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 338, in _handle_tasks
    if thread._state:
AttributeError: '_MainThread' object has no attribute '_state'

**Comment by ecederstrand** [comment]
I understand that you have clients and deadlines, but I have pointed out to you that this is most certainly not an exchangelib issue. You haven't proved anything to the contrary.

However, I'll gladly contract with the Danish branch of Cognizant to get https://github.com/eventlet/eventlet/issues/147 patched or provide a workaround for you. Please contact me for hourly rates. My email address is in my bio.

**Comment by ponmuthu** [comment]
@ecederstrand - what is your expectation on this & how many hours required to fix this ?

**Comment by ecederstrand** [comment]
Taking offline. You'll have an email in 10 minutes.

**Comment by ecederstrand** [comment]
Hi @ponmuthu I never heard back from you. Did you get this fixed? If so, can we close this issue?
