### ISSUE TITLE
Forbidden Error 403

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#293]
I have given server during configuration step.
It is using http and not https and i am getting forbidden error.can you please help
  
  credentials = ServiceAccount(username='automation\\backupadmin'  , password='abc!12')
    version = Version(build=Build(15, 0, 12, 34))
    config = Configuration(credentials=credentials,
                           server='STEXNG-NEW.automation.commvault.com', version=version,
                           has_ssl=False,
                           auth_type=NTLM)
    account = Account(primary_smtp_address='CLEANUPMB8@automation.commvault.com', config=config, access_type=IMPERSONATION)

**_Error:_**

(11/13/2017 16:41:37 864 MainThread) DEBUG [exchangelib.services:get_payload@894] - Getting folder Root (root)
(11/13/2017 16:41:37 894 MainThread) WARNING [exchangelib.services:_get_elements@113] - EWS http://STEXNG-NEW.automation.commvault.com/EWS/Exchange.asmx, account CLEANUPMB8@automation.commvault.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 76, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 140, in _get_response_xml
    allow_redirects=False)
  File "C:\Python27\lib\site-packages\exchangelib\util.py", line 486, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Python27\lib\site-packages\exchangelib\util.py", line 546, in _raise_response_errors
    raise TransportError('Unknown failure\n' + log_msg % log_vals)
TransportError: Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 27018
Thread: 17808
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x00000000049E72B0>
URL: http://stexng-new.automation.commvault.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x00000000049E72E8>
Allow redirects: False
Response time: 0.0
Status code: 403
Request headers: {'Content-Length': '1273', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.4', 'Connection': 'Keep-Alive', 'Content-Type': u'text/xml; charset=utf-8'}
Response headers: {'Date': 'Mon, 13 Nov 2017 21:41:37 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'STEXNG-NEW', 'Server': 'Microsoft-IIS/8.5'}
Request data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2013" /><t:ExchangeImpersonation><t:ConnectingSID><t:PrimarySmtpAddress>CLEANUPMB8@automation.commvault.com</t:PrimarySmtpAddress></t:ConnectingSID></t:ExchangeImpersonation><t:TimeZoneContext><t:TimeZoneDefinition Id="Eastern Standard Time" /></t:TimeZoneContext></s:Header><s:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount" /><t:FieldURI FieldURI="folder:EffectiveRights" /><t:FieldURI FieldURI="folder:FolderClass" /><t:FieldURI FieldURI="folder:DisplayName" /><t:FieldURI FieldURI="folder:ParentFolderId" /><t:FieldURI FieldURI="folder:TotalCount" /><t:FieldURI FieldURI="folder:UnreadCount" /></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>CLEANUPMB8@automation.commvault.com</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></s:Body></s:Envelope>
Response data:

**Comment by shireen91** [comment]
And if use service_endpoint instead of server, Its just hanging, can you please help
    config = Configuration(credentials=credentials,
                           service_endpoint='https://STEXNG-NEW.automation.commvault.com/EWS/Exchange.asmx', version=version,
                           has_ssl=False,
                           auth_type=NTLM)

**Comment by shireen91** [comment]
Hi,

Can you please how to solve this issue? and if i am doing something wrong?

**Comment by ecederstrand** [comment]
Are you sure that your Exchange server is located on port 80? That means you're communicating in clear text. That seems very odd. Also, you could try to use autodiscover to reach the host, in case any of your configuration settings are wrong.

**Comment by ecederstrand** [comment]
Finally, if the password in the first post is real, then I would suggest you change the password immediately.

**Comment by ecederstrand** [comment]
Closing due to inactivity. Feel free to reopen if you have more information.
