### ISSUE TITLE
last_modified_time / _start_timezone

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#310]
Hi, 

I have a problem regarding timezones. After almost two months of searching I think I can narrow it down to these two error messages:

```
INFO:exchangelib.fields:Encountered naive datetime 2017-12-06 21:10:44 on field last_modified_time. Assuming timezone Europe/Vienna
WARNING:exchangelib.fields:Cannot convert value 'Customized Time Zone' on field '_start_timezone' to type <class 'exchangelib.ewsdatetime.EWSTimeZone'> (unknown timezone ID)
WARNING:exchangelib.fields:Cannot convert value 'Customized Time Zone' on field '_end_timezone' to type <class 'exchangelib.ewsdatetime.EWSDTimeZone'> (unknown timezone ID)
```

My Problem now:
- I create an event (works just fine, timezone correct and all)
- I change the body of the event (nothing else changes) and somehow the timezone gets screwed up.

Is there a way to "add" my timezone ID so that it can be correctly mapped to Europe/Vienna?

**Comment by ecederstrand** [comment]
I've never encountered a timezone like that before. Can you post the response XML that contains the `Customized Time Zone` string? See https://github.com/ecederstrand/exchangelib#troubleshooting on how to do that.

**Comment by fruitloop** [comment]
Hi, I tried this:
```
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler])
```

and got this:
```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1794, in basicConfig
    if h.formatter is None:
AttributeError: type object 'PrettyXmlHandler' has no attribute 'formatter'
```

however, printing a calendar item it gives me this:
```
CalendarItem(
  mime_content=b'BEGIN:VCALENDAR\r\nMETHOD:PUBLISH\r\nPRODID:Microsoft Exchange Server 2010\r\nVERSION:2.0\r\nBEGIN:VTIMEZONE\r\nTZID:(UTC+01:00) Amsterdam\\, Berlin\\, Bern\\, Rome\\, Stockholm\\, Vienna\r\nBEGIN:STANDARD\r\nDTSTART:16010101T030000\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T020000\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nORGANIZER;CN=Roland Planitz:MAILTO:roland@planitz.at\r\nDESCRIPTION;LANGUAGE=en-GB:Saldo: 60 min\\nUrlaub: 0/0 [-10 unplanned]\r\nUID:040000008200E00074C5B7101A82E00800000000A406FDCDB492D201000000000000000\r\n 010000000F0C48DFCD106CE499B0C3ED117496950\r\nSUMMARY;LANGUAGE=en-GB:REWE (Probemonat)\r\nDTSTART;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna":2\r\n 0170306T090000\r\nDTEND;TZID="(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna":201\r\n 70306T153000\r\nCLASS:PUBLIC\r\nPRIORITY:5\r\nDTSTAMP:20170725T183108Z\r\nTRANSP:OPAQUE\r\nSTATUS:CONFIRMED\r\nSEQUENCE:0\r\nLOCATION;LANGUAGE=en-GB:Industriezentrum N\xc3\x96-S\xc3\xbcd\\, Str. 3\\, Obj. 16\\, 2355\r\n  Wiener Neudorf\r\nX-MICROSOFT-CDO-APPT-SEQUENCE:0\r\nX-MICROSOFT-CDO-OWNERAPPTID:2115177380\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nX-MICROSOFT-CDO-ALLDAYEVENT:FALSE\r\nX-MICROSOFT-CDO-IMPORTANCE:1\r\nX-MICROSOFT-CDO-INSTTYPE:0\r\nX-MICROSOFT-DONOTFORWARDMEETING:FALSE\r\nX-MICROSOFT-DISALLOW-COUNTER:FALSE\r\nX-MICROSOFT-LOCATIONDISPLAYNAME:Industriezentrum N\xc3\x96-S\xc3\xbcd\\, Str. 3\\, Obj. 1\r\n 6\\, 2355 Wiener Neudorf\r\nX-MICROSOFT-LOCATIONSOURCE:None\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n', 
  item_id='AAMkADBmZDc0MzU4LTlhN2EtNDkyMy05OWY0LTgwMjE1ODQyY2E5MQBGAAAAAADE/kQSv1FXRYrrtZdg72pWBwAdcD+SXh7+RLW5Pkwkt2rrAAH2BPQNAAAdcD+SXh7+RLW5Pkwkt2rrAAH2Bl4xAAA=',
  changekey='DwAAABYAAAAdcD+SXh7+RLW5Pkwkt2rrAAJPb9md',
  parent_folder_id=ParentFolderId(id='AAMkADBmZDc0MzU4LTlhN2EtNDkyMy05OWY0LTgwMjE1ODQyY2E5MQAuAAAAAADE/kQSv1FXRYrrtZdg72pWAQAdcD+SXh7+RLW5Pkwkt2rrAAH2BPQNAAA=',
  changekey='AQAAAA=='),
  item_class='IPM.Appointment',
  subject='REWE (Probemonat)',
  sensitivity='Normal',
  text_body='Saldo: 60 min\nUrlaub: 0/0 [-10 unplanned]',
  body='Saldo: 60 min\nUrlaub: 0/0 [-10 unplanned]',
  attachments=[],
  datetime_received=EWSDateTime(2017, 3, 1, 17, 53, 59, tzinfo=<UTC>),
  size=5690,
  importance='Normal',
  is_submitted=False,
  is_draft=False,
  is_from_me=False,
  is_resend=False,
  is_unmodified=False,
  datetime_sent=EWSDateTime(2017, 3, 1, 17, 53, 59, tzinfo=<UTC>),
  datetime_created=EWSDateTime(2017, 3, 1, 17, 53, 59, tzinfo=<UTC>),
  reminder_due_by=EWSDateTime(2017, 3, 6, 8, 0, tzinfo=<UTC>),
  reminder_is_set=False,
  reminder_minutes_before_start=15,
  has_attachments=False,
  culture='en-GB',
  effective_rights=EffectiveRights(create_associated=False, create_contents=False, create_hierarchy=False, delete=True, modify=True, read=True, view_private_items=True),
  last_modified_name='Roland Planitz',
  last_modified_time=EWSDateTime(2017, 7, 25, 18, 31, 8, tzinfo=<UTC>),
  is_associated=False,
  conversation_id=ConversationId(id='AAQkADBmZDc0MzU4LTlhN2EtNDkyMy05OWY0LTgwMjE1ODQyY2E5MQAQAENmU5mpOalAg94Yv8yK3Zk=', changekey=None),
  uid='040000008200E00074C5B7101A82E00800000000A406FDCDB492D201000000000000000010000000F0C48DFCD106CE499B0C3ED117496950',
  start=EWSDateTime(2017, 3, 6, 8, 0, tzinfo=<UTC>),
  end=EWSDateTime(2017, 3, 6, 14, 30, tzinfo=<UTC>),
  is_all_day=False,
  legacy_free_busy_status='Busy',
  location='Industriezentrum NÖ-Süd, Str. 3, Obj. 16, 2355 Wiener Neudorf',
  is_meeting=False,
  is_cancelled=False,
  is_recurring=False,
  meeting_request_was_sent=False,
  is_response_requested=True,
  type='Single',
  my_response_type='Organizer',
  organizer=Mailbox(name='Roland Planitz', email_address='roland@planitz.at', mailbox_type='Mailbox', item_id=None),
  conflicting_meeting_count=1,
  adjacent_meeting_count=0,
  duration='PT6H30M',
  appointment_sequence_number=0,
  _start_timezone=<DstTzInfo 'Europe/Zurich' BMT+0:30:00 STD>,
  _end_timezone=<DstTzInfo 'Europe/Zurich' BMT+0:30:00 STD>,
  allow_new_time_proposal=True,
  is_online_meeting=False
)
```

does that help?

**Comment by ecederstrand** [comment]
You're missing the parens after `PrettyXmlHandler` in this line:

```python
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler])
```

It should be:

```python
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
```

**Comment by fruitloop** [comment]
that helped thanks ;)

now I get these results:
```
<t:StartTimeZone Name="" Id="Customized Time Zone">
  <t:Periods>
    <t:Period Bias="-PT1H" Name="Standard" Id="trule:Microsoft/Registry/Customized Time Zone/1-Standard"/>
    <t:Period Bias="-PT2H" Name="Daylight" Id="trule:Microsoft/Registry/Customized Time Zone/1-Daylight"/>
  </t:Periods>
  <t:TransitionsGroups>
    <t:TransitionsGroup Id="0">
      <t:RecurringDayTransition>
        <t:To Kind="Period">trule:Microsoft/Registry/Customized Time Zone/1-Daylight</t:To>
        <t:TimeOffset>PT2H</t:TimeOffset>
        <t:Month>3</t:Month>
        <t:DayOfWeek>Sunday</t:DayOfWeek>
        <t:Occurrence>-1</t:Occurrence>
      </t:RecurringDayTransition>
      <t:RecurringDayTransition>
        <t:To Kind="Period">trule:Microsoft/Registry/Customized Time Zone/1-Standard</t:To>
        <t:TimeOffset>PT3H</t:TimeOffset>
        <t:Month>10</t:Month>
        <t:DayOfWeek>Sunday</t:DayOfWeek>
        <t:Occurrence>-1</t:Occurrence>
      </t:RecurringDayTransition>
    </t:TransitionsGroup>
  </t:TransitionsGroups>
  <t:Transitions>
    <t:Transition>
      <t:To Kind="Group">0</t:To>
    </t:Transition>
  </t:Transitions>
</t:StartTimeZone>
<t:EndTimeZone Name="" Id="Customized Time Zone">
  <t:Periods>
    <t:Period Bias="-PT1H" Name="Standard" Id="trule:Microsoft/Registry/Customized Time Zone/1-Standard"/>
    <t:Period Bias="-PT2H" Name="Daylight" Id="trule:Microsoft/Registry/Customized Time Zone/1-Daylight"/>
  </t:Periods>
  <t:TransitionsGroups>
    <t:TransitionsGroup Id="0">
      <t:RecurringDayTransition>
        <t:To Kind="Period">trule:Microsoft/Registry/Customized Time Zone/1-Daylight</t:To>
        <t:TimeOffset>PT2H</t:TimeOffset>
        <t:Month>3</t:Month>
        <t:DayOfWeek>Sunday</t:DayOfWeek>
        <t:Occurrence>-1</t:Occurrence>
      </t:RecurringDayTransition>
      <t:RecurringDayTransition>
        <t:To Kind="Period">trule:Microsoft/Registry/Customized Time Zone/1-Standard</t:To>
        <t:TimeOffset>PT3H</t:TimeOffset>
        <t:Month>10</t:Month>
        <t:DayOfWeek>Sunday</t:DayOfWeek>
        <t:Occurrence>-1</t:Occurrence>
      </t:RecurringDayTransition>
    </t:TransitionsGroup>
  </t:TransitionsGroups>
  <t:Transitions>
    <t:Transition>
      <t:To Kind="Group">0</t:To>
    </t:Transition>
  </t:Transitions>
</t:EndTimeZone>
```

Sounds like a mess, but I guess the offset should be usable somehow?

**Comment by ecederstrand** [comment]
Ouch! The only ways I can think of to fix this generally would be to take the DST rules and look for an exact match in all `pytz` timezones. Or create a custom `pytz` timezone class using the rules in the XML. Both solutions are extremely painful.

If you already know what this timezone corresponds to in `pytz`, you could add a custom translation in your own code. Something like this should work:

```python
from exchangelib.winzone import MS_TIMEZONE_TO_PYTZ_MAP

MS_TIMEZONE_TO_PYTZ_MAP['Customized Time Zone'] = 'Europe/Vienna'

# Your code here
```

This assumes that `Customized Time Zone` always points to the same timezone, of course.

**Comment by fruitloop** [comment]
that sounds bad, 
so the only clean version would be to contact the app developers and ask them not to screw up that bad?

in the meantime: your code gives me:
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from exchangelib.winzone import MS_TIMEZONE_TO_PYTZT_MAP
ImportError: cannot import name 'MS_TIMEZONE_TO_PYTZT_MAP'
```

also, is there a way to include the 'period bias' somehow to be able to use more
than one timezone? (at least until I have a clean way to do so)

**Comment by ecederstrand** [comment]
Try copy-pasting my example instead. Your traceback is due to a spelling error.

I have no idea why anyone would need to use other timezones than those defined by IANA or the Olson database, but for some reason a custom timezone was created on your Exchange server, and the calendar items use that. I'm not sure you'll get anywhere by contacting Microsoft about changing EWS, but you could try. It seems a bit over the top to allow defining a custom timezone or every single item in Exchange.

I'm not sure what you mean by this:

> is there a way to include the 'period bias' somehow to be able to use more
than one timezone? 

My workaround assumes that `Customized Time Zone` will always translate to the same `pytz` timezone. If that's not the case, then a solution is going to be very ugly.

**Comment by ecederstrand** [comment]
Ah, OK. If Nine Folders is doing this, then it makes sense to contact them.

Yes, the more robust solution would be to use all information in the custom timezone to do the mapping, but you would need to use all offset values and transition dates, of which there could be more than just two (because the transitions have changed historically or in the future). Hence my comment about this being non-trivial in the general case.

In your situation, I think the workaround above will do the job.

**Comment by fruitloop** [comment]
ok, thanks for this workaround. At the time I'm only in one timezone ;)
for the moment the timezones work now (no more messing up my calendar)

and I'll contact Nine Folders and report back if I have news.

**Comment by fruitloop** [comment]
Somehow the timezones still won't work the way I expect them to.

I'm in 'Europe/Vienna' and the my script adds events in 'UTC' with the offset, so that they look like they are in the right timezone.

**Comment by ecederstrand** [comment]
It's a bit unclear to me what the exact problem is. What *should* happen is:

1. You create or fetch a `CalendarItem`
2. You set `item.start` to a timezone-aware `EWSDateTime` instance (EWSTimeZone.timezone('Europe/Vienna').localize(EWSDateTime(2017, 1, 2, 3, 4, 5)))
3. You call `item.save()`
4. Next time you fetch the item, `item.start` should be the same, but in UTC (beause we convert all datetimes to UTC when we fetch them). `item._start_timezone` should be `EWSTimeZone.timezone('Europe/Vienna')` or something compatible with this timezone.

**Comment by fruitloop** [comment]
I prepared the following test code:
```
tz = EWSTimeZone.timezone('Europe/Vienna')
events = get_events(function_to_get_events_from_right_calendar_from_only_that_day)

# CalendarItem(
  #   account=account,
  #   folder=folder,
  #   subject='0900-1000',
  #   start=tz.localize(EWSDateTime.from_datetime(datetime.datetime(2017,12,11,9,0))),
  #   end=tz.localize(EWSDateTime.from_datetime(datetime.datetime(2017,12,11,10,0))),
  #   body='foo',
  # ).save()
  for e in events:
    e.body = datetime.datetime.now()
    e.is_online_meeting = None
    e.save()
  for e in events:
    print(e.subject)
    print(e.start.astimezone(tz))
    print(e.end.astimezone(tz))
    print(e._start_timezone)
    print(e._end_timezone)
    print(e.body)
    print()
```
I manually created an event and then I ran the script with the first block not commented out (to create an event) which gave me this:
```
0900-1000
2017-12-11 09:00:00+01:00
2017-12-11 10:00:00+01:00
UTC
UTC
2017-12-12 16:17:09.373405

Demo 0800-1300
2017-12-11 09:00:00+01:00
2017-12-11 14:00:00+01:00
UTC
UTC
2017-12-12 16:17:10.048080
```

then I commented the create part out and ran it again, which gave me this:
```
0900-1000
2017-12-11 10:00:00+01:00
2017-12-11 11:00:00+01:00
UTC
UTC
2017-12-12 16:18:52.534882

Demo 0800-1300
2017-12-11 09:00:00+01:00
2017-12-11 14:00:00+01:00
UTC
UTC
2017-12-12 16:18:52.738754
```
notice how the time jumped in the first event

In my calendar both events show up one hour later then they state in the subject.

**Comment by fruitloop** [comment]
any ideas?

**Comment by ecederstrand** [comment]
No, sorry. I haven't had time to investigate yet.

**Comment by tarikbenmerar** [comment]
@ecederstrand  @fruitloop I had the same issue and Ihad have done the work around mentionned here. The time zone is not really custom, just the server setting an id to precise that is not set by the user. To my knowledge, this issue only concerns exchange servers not Outlook  365 and it is very important to resolve.

Anyway, as the issue fix is very important to an application I am working on, how can I proceed ? I have a rough idea of how to resolve it without getting into the complexities of the Time Zone Definition.

Thanks,

**Comment by fruitloop** [comment]
I haven't really looked into that any further, but I am using **Outlook 365**

**Comment by ecederstrand** [comment]
@tarikbenmerar There are two issues mentioned here - the `Customized Time Zone` that we don't handle automatically, and the timezone offset problem mentioned later in the thread. I don't see how to fix the former without doing really messy work that I'm not inclined to do myself, at least. Regarding the latter issue, I still haven't sat down and figured out what's going, and if this is an actual issue or a case of wrong expectations that needs to be documented better.

**Comment by tarikbenmerar** [comment]
@ecederstrand for the timezone issue I have an idea of a way to do it without messy code. I will try to get some progress in the following day. And for the offset as I have been diving to these related issues is that if timezone is not set recurrent events may differ when handled in UTC particularly with daylight saving (But I am not sure if it is directly related to the one mentioned here). It took us some time to uncover it. @fruitloop I didn't know it could happen with Outlook 365.

**Comment by ecederstrand** [comment]
I can reproduce this, but only if the item is updated in a loop:

```python
tz = EWSTimeZone.timezone('Europe/Vienna')
start = tz.localize(EWSDateTime(2017,12,11,9,0))
end = tz.localize(EWSDateTime(2017,12,11,10,0))
print('Creating calendar item with start %s end %s' % (start, end))
item = CalendarItem(
   folder=a.calendar,
   start=start,
   end=end,
   categories=['XXX'],
).save()
print('Updating item')
for i in a.calendar.filter(categories__contains=['XXX']):
    i.save()
for i in a.calendar.filter(categories__contains=['XXX']):
    print('Fresh item')
    print(i.start.astimezone(tz))
    print(i.end.astimezone(tz))
    print(i._start_timezone)
    print(i._end_timezone)
    i.delete()
```

If I do a more simple version without a loop, then updating works without issues:

```python
tz = EWSTimeZone.timezone('Europe/Vienna')
start = tz.localize(EWSDateTime(2017,12,11,9,0))
end = tz.localize(EWSDateTime(2017,12,11,10,0))
print('Creating calendar item with start %s end %s' % (start, end))
item = CalendarItem(
   folder=a.calendar,
   start=start,
   end=end,
   categories=['XXX'],
).save()
print('Updating item')
item.save()
item.refresh()
print('Fresh item')
print(item.start.astimezone(tz))
print(item.end.astimezone(tz))
print(item._start_timezone)
print(item._end_timezone)
item.delete()
```

**Comment by ecederstrand** [comment]
At this point, I'm assuming this is a bug in EWS. I send this XML to update the start and end dates in UTC:

```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2013_SP1"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="Romance Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:UpdateItem ConflictResolution="AutoResolve" MessageDisposition="SaveOnly" SendMeetingInvitationsOrCancellations="SendToNone" SuppressReadReceipts="true">
      <m:ItemChanges>
        <t:ItemChange>
          <t:ItemId ChangeKey="DwAA" Id="AAMkADQy="/>
          <t:Updates>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:Start"/>
              <t:CalendarItem>
                <t:Start>2017-12-11T08:00:00Z</t:Start>
              </t:CalendarItem>
            </t:SetItemField>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:End"/>
              <t:CalendarItem>
                <t:End>2017-12-11T09:00:00Z</t:End>
              </t:CalendarItem>
            </t:SetItemField>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:StartTimeZone"/>
              <t:CalendarItem>
                <t:StartTimeZone Id="UTC" Name=""/>
              </t:CalendarItem>
            </t:SetItemField>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:EndTimeZone"/>
              <t:CalendarItem>
                <t:EndTimeZone Id="UTC" Name=""/>
              </t:CalendarItem>
            </t:SetItemField>
          </t:Updates>
        </t:ItemChange>
      </m:ItemChanges>
    </m:UpdateItem>
  </s:Body>
</s:Envelope>
```

But when I request the same item, I get this:
```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo
    xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0" MajorBuildNumber="1365" MinorBuildNumber="1" Version="V2_23"/>
  </s:Header>
  <s:Body
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:FindItemResponse
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:FindItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:RootFolder IndexedPagingOffset="1" TotalItemsInView="1" IncludesLastItemInRange="true">
            <t:Items>
              <t:CalendarItem>
                <t:ItemId Id="AAMkADQy=" ChangeKey="DwAA"/>
                <t:Start>2017-12-11T10:00:00+01:00</t:Start>
                <t:End>2017-12-11T11:00:00+01:00</t:End>
                <t:StartTimeZone Name="(UTC) Coordinated Universal Time" Id="UTC">
                [...]
                </t:StartTimeZone>
                <t:EndTimeZone Name="(UTC) Coordinated Universal Time" Id="UTC">
                [...]
                </t:EndTimeZone>
              </t:CalendarItem>
            </t:Items>
          </m:RootFolder>
        </m:FindItemResponseMessage>
      </m:ResponseMessages>
    </m:FindItemResponse>
  </s:Body>
</s:Envelope>
```

Time has shifted 1 hour...
