### ISSUE TITLE
Connecting via forward proxy fails. 

### ISSUE THREAD

**Issue by hamedghasemieh** [ecederstrand/exchangelib#330]
I am trying to connect to an exchange server via a forward proxy name, say, https://my_frwd_proxy:1234. However, I can not pass the configuration phase. Here is the code: 
```
creds = ServiceAccount(username=my_username, password=my_password, max_wait=time_out) 
exch_config = Configuration(server='my_frwd_proxy:1234', credentials=creds)
```
I have already tested to connect to the actual server without the proxy and everything works just fine.
Can something gone wrong during the hand shake via the proxy?

Here is the full debug log. As you can see the exchangelib is even able to get the version of the server, however, later server refuses to respond anything. 

```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://my_frwd_proxy:1234/EWS/Exchange.asmx', ServiceAccount('my_user_name', '********'))'
DEBUG:exchangelib.transport:Getting service auth type for https://my_frwd_proxy:1234/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Requesting b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>my_user_name</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>' from https://my_frwd_proxy:1234/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my_frwd_proxy
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '451'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/8.0', 'Date': 'Tue, 23 Jan 2018 12:54:19 GMT', 'Set-cookie': 'exchangecookie=cookiehex...; expires=Wed, 23-Jan-2019 12:54:19 GMT; path=/; HttpOnly', 'Www-authenticate': 'Negotiate, NTLM', 'X-powered-by': 'ASP.NET', 'Content-length': '0'}
DEBUG:exchangelib.transport:Auth type is NTLM
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 7070
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 20865
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 12096
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 29964
DEBUG:exchangelib.transport:Getting docs auth type for https://my_frwd_proxy:1234/EWS/types.xsd
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my_frwd_proxy
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/8.0', 'Date': 'Tue, 23 Jan 2018 12:54:19 GMT', 'Www-authenticate': 'Negotiate, NTLM', 'X-powered-by': 'ASP.NET', 'Content-length': '0'}
DEBUG:exchangelib.version:Asking server for version info
DEBUG:exchangelib.version:Getting https://my_frwd_proxy:1234/EWS/types.xsd with auth type HttpNtlmAuth
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my_frwd_proxy
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "GET /EWS/types.xsd HTTP/1.1" 200 24146
DEBUG:exchangelib.version:Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Authorization': 'NTLM NTLMstring'}
DEBUG:exchangelib.version:Response code: 200
DEBUG:exchangelib.version:Response headers: {'Server': 'Microsoft-IIS/8.0', 'Date': 'Tue, 23 Jan 2018 12:54:19 GMT', 'Content-type': 'text/xml', 'Content-encoding': 'gzip', 'Last-modified': 'Tue, 05 Feb 2013 22:00:32 GMT', 'Accept-ranges': 'bytes', 'Etag': '"009537ec3ce1:0"', 'Vary': 'Accept-Encoding', 'Persistent-auth': 'true', 'X-powered-by': 'ASP.NET', 'Content-length': '24146'}
DEBUG:exchangelib.version:Shortname according to https://my_frwd_proxy:1234/EWS/types.xsd: Exchange2010_SP2
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Waiting for session
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Got session 29964
DEBUG:exchangelib.util:Session 29964 thread 140084985317120: retry 0 timeout 120 POST'ing to https://my_frwd_proxy:1234/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my_frwd_proxy
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 29964
Thread: 140084985317120
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f67ee8ef978>
URL: https://my_frwd_proxy:1234/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f67ee8efd68>
Allow redirects: False
Response time: 0.06718067405745387
Status code: 401
Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '455', 'Authorization': 'NTLM NTLMstring', 'Cookie': 'exchangecookie=cookiehex...; expires=Wed, 23-Jan-2019 12:54:19 GMT; path=/; HttpOnly'}
Response headers: {'Server': 'Microsoft-IIS/8.0', 'Date': 'Tue, 23 Jan 2018 12:54:19 GMT', 'Www-authenticate': 'Negotiate, NTLM', 'X-powered-by': 'ASP.NET', 'Content-length': '0'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
  </s:Header>
  <s:Body>
    <m:ResolveNames ReturnFullContactData="false">
      <m:UnresolvedEntry>my_user_name</m:UnresolvedEntry>
    </m:ResolveNames>
  </s:Body>
</s:Envelope>

Response data: b''

INFO:exchangelib.util:Session 29964 thread 140084985317120: Connection error on URL https://my_frwd_proxy:1234/EWS/Exchange.asmx (code 401). Cool down 10 secs
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Renewing session 29964
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 3830
DEBUG:exchangelib.util:Session 3830 thread 140084985317120: retry 1 timeout 120 POST'ing to https://my_frwd_proxy:1234/EWS/Exchange.asmx after 20s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): my_frwd_proxy
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.util:Retry: 1
Waited: 20
Timeout: 120
Session: 3830
Thread: 140084985317120
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f67efca4be0>
URL: https://my_frwd_proxy:1234/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f67ef4fc518>
Allow redirects: False
Response time: 0.054711611941456795
Status code: 401
Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '455', 'Authorization': 'NTLM NTLM String', 'Cookie': 'exchangecookie=cookiehex...; expires=Wed, 23-Jan-2019 12:54:30 GMT; path=/; HttpOnly'}
Response headers: {'Server': 'Microsoft-IIS/8.0', 'Date': 'Tue, 23 Jan 2018 12:54:29 GMT', 'Www-authenticate': 'Negotiate, NTLM', 'X-powered-by': 'ASP.NET', 'Content-length': '0'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
  </s:Header>
  <s:Body>
    <m:ResolveNames ReturnFullContactData="false">
      <m:UnresolvedEntry>my_user_name</m:UnresolvedEntry>
    </m:ResolveNames>
  </s:Body>
</s:Envelope>

Response data: b''

WARNING:exchangelib.util:URL https://my_frwd_proxy:1234/EWS/Exchange.asmx: Max timeout reached
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Retiring session 3830
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Created session 24057
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Releasing session 24057
WARNING:exchangelib.protocol:Failed to create cached protocol with key ('https://my_frwd_proxy:1234/EWS/Exchange.asmx', ServiceAccount('my_user_name', '********')): URL https://my_frwd_proxy:1234/EWS/Exchange.asmx: Max timeout reached
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    EmailController().start()
  File "/home/my_user_name/ariba/main/controllers/EmailController.py", line 22, in __init__
    self.exchange_server_gate = ExchangeServerGate()
  File "/home/my_user_name/ariba/main/logic/ExchangerServerGate.py", line 65, in __init__
    exch_config = Configuration(server=server, credentials=creds)
  File "/home/my_user_name/ariba/main/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/home/my_user_name/ariba/main/exchangelib/protocol.py", line 181, in __call__
    raise e
  File "/home/my_user_name/ariba/main/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/home/my_user_name/ariba/main/exchangelib/protocol.py", line 229, in __init__
    self.version = Version.guess(self)
  File "/home/my_user_name/ariba/main/exchangelib/version.py", line 202, in guess
    return cls._guess_version_from_service(protocol=protocol, hint=api_version)
  File "/home/my_user_name/ariba/main/exchangelib/version.py", line 235, in _guess_version_from_service
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
  File "/home/my_user_name/ariba/main/exchangelib/services.py", line 1166, in call
    contact_data_shape=contact_data_shape,
  File "/home/my_user_name/ariba/main/exchangelib/services.py", line 76, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/home/my_user_name/ariba/main/exchangelib/services.py", line 140, in _get_response_xml
    allow_redirects=False)
  File "/home/my_user_name/ariba/main/exchangelib/util.py", line 469, in post_ratelimited
    if _may_retry_on_error(r, protocol, wait):
  File "/home/my_user_name/ariba/main/exchangelib/util.py", line 518, in _may_retry_on_error
    raise RateLimitError('URL %s: Max timeout reached' % r.url)
exchangelib.errors.RateLimitError: URL https://my_frwd_proxy:1234/EWS/Exchange.asmx: Max timeout reached
DEBUG:exchangelib.protocol:Server my_frwd_proxy:2102: Closing sessions
```

**Comment by ecederstrand** [comment]
I believe a solution for connecting via proxies was posted in https://github.com/ecederstrand/exchangelib/issues/156#issuecomment-341255713

**Comment by hamedghasemieh** [comment]
I have seen this.
So this is not a regular proxy, but a forward proxy which simply redirects all web traffic from https://my_fwd_proxy:1234/* to https://exchangeserver/*

Essentially the difference in response in doing the direct call to exchangeserver vs my_fwd_proxy is from line 33: 

```
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
**DEBUG:urllib3.connectionpool:https://my_frwd_proxy:1234 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0**
```

In the direct exchangeserver case this becomes a 401 -> 401 -> 200 OK. But with the proxy we get the chain 401 -> 401 -> 401 and it never authorizes.

**Comment by ecederstrand** [comment]
Ah, OK. Can other Exchange clients authenticate? Which authentication method are you using?

**Comment by hamedghasemieh** [comment]
No one can authenticate via proxy. 
We do not set the argument `auth_type` in `Configuration`, and we do not have any problem with the direct connection.

**Comment by ecederstrand** [comment]
Okay, so if no-one else can connect via the proxy, using other Exchange clients such as Outlook, then it's probably not an issue with exchangelib?

**Comment by hamedghasemieh** [comment]
I meant authentication via proxy using exchangelib. 
The problem is that we can not run an Outlook client, for instance, on the machine we have. But I am trying other means now. 
I will update you on this.

**Comment by ecederstrand** [comment]
Hi @hamedghasemieh Did you find a solution to your problem?

**Comment by ecederstrand** [comment]
Ok, thanks for the clarification!

**Comment by zhzure** [comment]
> Hi Yes the problem is resolved. Nothing was wrong with exchangelib.

hi, I have encounter the exactly issue like you, can you share about how you solve it ? I couldn't authorize via proxy to exchange with EWS protocol, but if I directly connect to exchange server with EWS protocol , everything is fine. It's troubling me so many days

**Comment by nonbutAworker** [comment]
> Hi Yes the problem is resolved. Nothing was wrong with exchangelib.

hi, I have encounter the exactly issue like you, can you share about how you solve it ? I couldn't authorize via proxy to exchange with EWS protocol, but if I directly connect to exchange server with EWS protocol , everything is fine. It's troubling me so many days
