### ISSUE TITLE
   MemoryError problem 

### ISSUE THREAD

**Issue by wuhiha** [ecederstrand/exchangelib#349]
When I fetch  many emails, in total about 600MB of size, this error occurs: 

```python
for item in account.inbox.all().order_by('-datetime_received')[:1000]:


Traceback (most recent call last):
  File "owatest.py", line 20, in <module>
    for item in account.inbox.all().order_by('-datetime_received')[:65]:
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/queryset.py", line 197, in __iter__
    for val in result_formatter(self._query()):
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/queryset.py", line 272, in _as_items
    for i in iterable:
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/account.py", line 534, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_fields, shape=IdOnly):
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/services.py", line 454, in _pool_requests
    elems = r.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/services.py", line 434, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/services.py", line 76, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/services.py", line 144, in _get_response_xml
    soap_response_payload = to_xml(r.text)
  File "/tool/exchange/lib/python3.5/site-packages/exchangelib/util.py", line 247, in to_xml
    root = parse(io.BytesIO(no_bom_text.encode('utf-8')), magical_parser)
MemoryError
```

**Comment by ecederstrand** [comment]
This is dependent on the amount of memory on your machine. We could definitely be more memory efficient in this path - e.g. using streaming downloads, streaming XML parsing etc. But a 600 MB email is going to hurt in almost any email client.

Is the data located in the email body, or in attachments?

**Comment by wuhiha** [comment]
Yes, many attachments within my email.

**Comment by wuhiha** [comment]
Is it possible to save every emai on disk while downloading intead of caching in memory? @ecederstrand

**Comment by ecederstrand** [comment]
Well, you can disable internal caching of the query by using `.iterator()`.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you still think this is an error in exchangelib.
