### ISSUE TITLE
Efficiently chunk large sets of data

### ISSUE THREAD

**Issue by ampkeegan** [ecederstrand/exchangelib#354]
Hi! I am working on a tool to export data from a very large O365 mailbox, on the order of hundreds of thousands of emails, contacts, and calendar events. According to the documentation, slicing in subsets is efficient. However I'm seeing this is significantly slower than just getting the full folder.

I want to do this with the end goal of exporting _n_ items, taking action on those items, then while that runs starting export of the next _n_ items. I do not want to export everything, then take action on the entire set. 

Here's how I'm slicing. 

```python
contacts = account.contacts.all()
calCount = contacts.count()
currentCount = 0
pageSize = 10
print("Getting all contacts with pageSize: " + str(pageSize))
while currentCount <= calCount:
    diff = currentCount + pageSize -1
    print("Getting pages " + str(currentCount) + " - " + str(diff) + " out of " + str(calCount))
    contactsSlice = contacts[currentCount:diff]
    for item in contactsSlice:
        pass
    currentCount = diff +1
```

Results with varying pagesize:
```
Keegans-MBP:app keegan$ time python test.py
Getting all contacts with pageSize: 10
Getting pages 0 - 9 out of 214
Getting pages 10 - 19 out of 214
...
Getting pages 210 - 219 out of 214

real	0m19.291s
user	0m2.312s
sys	0m0.226s
```
```
Keegans-MBP:app keegan$ time python test.py
Getting all contacts with pageSize: 25
Getting pages 0 - 24 out of 214
...
Getting pages 200 - 224 out of 214

real	0m13.095s
user	0m1.699s
sys	0m0.191s
```
```
Keegans-MBP:app keegan$ time python test.py
Getting all contacts with pageSize: 300
Getting pages 0 - 299 out of 214

real	0m6.413s
user	0m1.435s
sys	0m0.182s
```

T

**Comment by ampkeegan** [comment]
Awesome, thanks! Unfortunately that hasn't solved my initial problem, maybe I should have opened with that. When requesting Calendars, I get the following:

> exchangelib.errors.ErrorServerBusy: The server cannot service this request right now. Try again later.

Here's my code, I've tried modifying pageSize to be 10 up to 500 with the same result:
``` python
pageSize = 100
count = 0
totalCount = account.calendar.all().count()
print("Total Calendar Count: " + str(totalCount))
for contactsSlice in chunkify(account.calendar.all().iterator(), pageSize):
    print("Getting page " + str(count))
    count = count + pageSize
```
It always fails on page 700.
The full trace, if it helps:
```
Keegans-MacBook-Pro:app keegan$ python test.py 
Total Calendar Count: 2961
Getting page 0
Getting page 100
Getting page 200
Getting page 300
Getting page 400
Getting page 500
Getting page 600
Getting page 700
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    for contactsSlice in chunkify(account.calendar.all().iterator(), pageSize):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/util.py", line 72, in chunkify
    for i in iterable:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/account.py", line 534, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_fields, shape=IdOnly):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 430, in _pool_requests
    for chunk in chunkify(items, self.CHUNKSIZE):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/util.py", line 72, in chunkify
    for i in iterable:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/folders.py", line 435, in find_items
    for i in items:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 318, in _paged_call
    response = self._get_response_xml(payload=payload)
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 148, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 192, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 215, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorServerBusy: The server cannot service this request right now. Try again later.
```

**Comment by ecederstrand** [comment]
You may be hit by rate-limiting policies on the server, requiring you to slow down the rate of requests against the server, or you may simply be hitting the server with expensive requests that put a strain on the server. These are the typical scenarios where I have seen `ErrorServerBusy` popping up.

You can paper over these issues by using a `ServiceAccount` instead of the `Credentials` class. See https://github.com/ecederstrand/exchangelib#setup-and-connecting

Also, if you only intend to use some specific fields of a contact, you can use `.only()` to greatly reduce the volume and complexity of the request.

**Comment by ampkeegan** [comment]
Unfortunately I'm already using a service account.

However using .only() worked perfectly. Hopefully I can get by without requesting the entire object.

Thanks, I'll close this now.

**Comment by ecederstrand** [comment]
Thanks for the update.

Can I get you to do do one last test which is to log the response code, response headers and the response XML of the response that raises the `ErrorServerBusy` error? I'd like to see if we can let `ErrorServerBusy` trigger the rate-limiting loop (as described in #356).

**Comment by ampkeegan** [comment]
Aside from this:
```python
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
```
What do I need to do to get debug logging?

**Comment by ecederstrand** [comment]
That should be enough. It should print something along the lines of:

```
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 5383
Thread: 140022370600704
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f597644f438>
URL: https://example.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f597644f358>
Allow redirects: False
Response time: 0.0318952369998442
Status code: 200
Request headers: {'Accept-Encoding': 'compress, gzip', [...]}
Response headers: {'X-BEServer': 'EXMBX22', 'Cache-Control': 'private', [...]}
Request data: <?xml version='1.0' encoding='utf-8'?> [...]
Response data: <?xml version='1.0' encoding='utf-8'?> [...]
```

**Comment by ampkeegan** [comment]
Here it is. It reliably happens on the Offset="800" request.

```
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 1588
Thread: 140735116792576
Auth type: <requests.auth.HTTPBasicAuth object at 0x10af25208>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x10af02f28>
Allow redirects: False
Response time: 0.43808456894475967
Status code: 500
Request headers: {'User-Agent': 'python-requests/2.11.1', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Cookie': 'exchangecookie=xxxx', 'Content-Length': '1051', 'Authorization': 'Basic xxxx='}
Response headers: {'Cache-Control': 'private', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/xml; charset=utf-8', 'Server': 'Microsoft-IIS/10.0', 'request-id': 'xxxx', 'X-CalculatedBETarget': 'CY4PR1701MB1926.namprd17.prod.outlook.com', 'X-BackEndHttpStatus': '500', 'Set-Cookie': 'exchangecookie=0xxx; path=/', 'x-EwsHandler': 'FindItem', 'X-AspNet-Version': '4.0.30319', 'X-DiagInfo': 'CY4PR1701MB1926', 'X-BEServer': 'CY4PR1701MB1926', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'BN6PR13CA0022', 'Date': 'Wed, 07 Mar 2018 14:05:00 GMT'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2016"/>
    <t:ExchangeImpersonation>
      <t:ConnectingSID>
        <t:PrimarySmtpAddress>REDACTED</t:PrimarySmtpAddress>
      </t:ConnectingSID>
    </t:ExchangeImpersonation>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="Eastern Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
      </m:ItemShape>
      <m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="100" Offset="800"/>
      <m:ParentFolderIds>
        <t:DistinguishedFolderId Id="calendar">
          <t:Mailbox>
            <t:EmailAddress>REDACTED</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>

Response data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <s:Fault>
      <faultcode
    xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorServerBusy</faultcode>
      <faultstring xml:lang="en-US">The server cannot service this request right now. Try again later.</faultstring>
      <detail>
        <e:ResponseCode
    xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorServerBusy</e:ResponseCode>
        <e:Message
    xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The server cannot service this request right now. Try again later.</e:Message>
        <t:MessageXml
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
          <t:Value Name="BackOffMilliseconds">297749</t:Value>
        </t:MessageXml>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>


DEBUG:exchangelib.util:Got status code 500 but trying to parse content anyway
DEBUG:exchangelib.util:Session 1588 thread 140735116792576: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server outlook.office365.com: Releasing session 1588
DEBUG:exchangelib.services:Trying API version Exchange2016 for account REDACTED
Traceback (most recent call last):
  File "logtest.py", line 33, in <module>
    for x in account.calendar.all():
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/queryset.py", line 197, in __iter__
    for val in result_formatter(self._query()):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/queryset.py", line 272, in _as_items
    for i in iterable:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/account.py", line 534, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_fields, shape=IdOnly):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 430, in _pool_requests
    for chunk in chunkify(items, self.CHUNKSIZE):
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/util.py", line 72, in chunkify
    for i in iterable:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/folders.py", line 435, in find_items
    for i in items:
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 318, in _paged_call
    response = self._get_response_xml(payload=payload)
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 148, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 192, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/Users/keegan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/exchangelib/services.py", line 215, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorServerBusy: The server cannot service this request right now. Try again later.
```

**Comment by ecederstrand** [comment]
Ah, just what I needed. Thanks!

The server is polite enough to return the response with a status code 500 that we can test for, and also gives us a `BackOffMilliseconds` value that we can adhere to. I'll close this issue and implement the solution in #356

**Comment by mandarvaze** [comment]
I came here looking for "Efficiently chunk large sets of data", while the discussion later turned to ServerBusy error.

I'm leaving my comment for others who come here looking for the same.

----

one of the comment by @ecederstrand in above discussion says : 

> Slicing using `[n:m]` syntax is reasonably efficient in that it only fetches approximately `m` items instead of the full folder contents. But we're still getting the first `n` items and then **discarding** them. So your algorithm is essentially O(n²)

But it is no longer correct, after slicing using `[n:m]` was made efficient in Oct 2018 (comment above is from March 2018)

README now  says that `[10:20]` now fetches only 10 items
