### ISSUE TITLE
Test GetSearchableMailboxes support

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#375]
88552bcc401d25a92d74760668560a0ced2dfdb1 adds initial support for `GetSearchableMailboxes` support, but I have no way to test the service, as my test server always returns `exchangelib.errors.ErrorAccessDenied: The caller has not assigned any of the RBAC roles requested in the management role header.`.

If you have sufficient privileges on your server, please test the service by running:

```python
c = Credentials('username', 'password')
a = Account(primary_smtp_address='user@example.com', credentials=c, autodiscover=True)

for item in a.protocol.get_searchable_mailboxes():
    print(item)
```

We may need to implement the `ManagementRole` SOAP header: https://msdn.microsoft.com/en-us/library/office/jj191277(v=exchg.150).aspx

**Comment by ninSmith** [comment]
I got:

```
Traceback (most recent call last):
  File "initial.py", line 5, in <module>
    a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib-1.11.4-py3.5.egg/exchangelib/account.py", line 60, in __init__
    raise ValueError("primary_smtp_address '%s' is not an email address" % primary_smtp_address)
ValueError: primary_smtp_address 'bg0088' is not an email address
```

Same error if I add the domain to username.
Am I doing something wrong ?

**Comment by ecederstrand** [comment]
That can only happen if `c.username` is not an email address. Try replacing `c.username` with the email address of the user.

**Comment by ninSmith** [comment]
Erf I have same error as you.
If you know what privileges need to be added to the user to test the feature I can add them and pursue the test.

**Comment by ecederstrand** [comment]
According to http://gsexdev.blogspot.com/2012/11/using-ediscovery-to-search-mailboxes.html the user must be a member of the Discovery Management RBAC role. There's more here: https://technet.microsoft.com/en-us/library/jj200692(v=exchg.150).aspx.

**Comment by ninSmith** [comment]
Here's the output:

```
SearchableMailbox(guid='1865a524-6d90-47d5-abc0-5e65d2040a6b', is_external=False, is_membership_group=True)
SearchableMailbox(guid='57e7ef38-3fcf-4914-a82c-ed455aeabd89', is_external=False, is_membership_group=True)
SearchableMailbox(guid='2378af7f-2288-4758-9fc9-cf819fc8df2e', is_external=False, is_membership_group=True)
SearchableMailbox(guid='ff98b26d-b415-4bcd-b92c-31a572193040', is_external=False, is_membership_group=True)
SearchableMailbox(guid='5a039ba7-55bc-4226-b615-8fdff9d4b4eb', is_external=False, is_membership_group=True)
SearchableMailbox(guid='b910c686-8d9a-43fb-a394-1fca3f249a61', is_external=False, is_membership_group=True)
SearchableMailbox(guid='87d08749-141d-4f73-bff9-54ea43d5d490', is_external=False, is_membership_group=True)
SearchableMailbox(guid='cc5d6f4f-b775-4b8c-857d-d1347baba14c', is_external=False, is_membership_group=True)
SearchableMailbox(guid='b253e1bc-d153-4b38-838a-aad10b7db0cd', is_external=False, is_membership_group=True)
SearchableMailbox(guid='234fa1d1-e4b8-4e1f-b67a-44b206922416', is_external=False, is_membership_group=True)
SearchableMailbox(guid='204c4e6d-6c50-44af-9621-c0bfdf0477a5', is_external=False, is_membership_group=True)
SearchableMailbox(guid='99c5e4c5-1b2d-4581-8f38-d8982cc2707e', is_external=False, is_membership_group=True)
SearchableMailbox(guid='27eb4278-60e5-44dd-8e58-a6f5ed8006b1', is_external=False, is_membership_group=True)
SearchableMailbox(guid='1ec3058d-8cd5-44d2-9c49-7850662c9462', is_external=False, is_membership_group=True)
SearchableMailbox(guid='d72a7adf-cd67-451e-99a8-b3a327b6023d', is_external=False, is_membership_group=True)
SearchableMailbox(guid='505da7ad-af5d-41d1-b919-1c531e20eaf8', is_external=False, is_membership_group=True)
SearchableMailbox(guid='8ca9ffe2-ec48-436f-8fc3-6e3704479ec5', is_external=False, is_membership_group=True)
SearchableMailbox(guid='b82cf1ed-4116-4af2-b070-792138a7a399', is_external=False, is_membership_group=True)
SearchableMailbox(guid='d008e18b-63dd-4c4c-b7da-db939f491f24', is_external=False, is_membership_group=True)
SearchableMailbox(guid='e32137e7-9dea-451a-a1d2-503f46c0420f', is_external=False, is_membership_group=True)
SearchableMailbox(guid='4d07d919-e3da-40c1-9cdd-5d8fc06e24f7', is_external=False, is_membership_group=True)
SearchableMailbox(guid='96a15a05-6477-4c84-84a5-024c6d9d14fd', is_external=False, is_membership_group=True)
SearchableMailbox(guid='8b059653-8ab9-4659-8541-28264118c0c0', is_external=False, is_membership_group=True)
SearchableMailbox(guid='0f24e529-f423-4657-af8d-0e14b2ecd915', is_external=False, is_membership_group=True)
SearchableMailbox(guid='6fc1b339-fac1-45ca-848b-b5880387c516', is_external=False, is_membership_group=True)
SearchableMailbox(guid='90a4a654-a4ca-46ba-ba5d-d0716b88c9d9', is_external=False, is_membership_group=True)
SearchableMailbox(guid='a8f44e84-ae6f-4bf5-b9dc-7d2c49922159', is_external=False, is_membership_group=True)
SearchableMailbox(guid='201a6f2c-4376-4516-a8ab-7e259b4316f5', is_external=False, is_membership_group=True)
SearchableMailbox(guid='f7c53dac-c98b-478a-9d8d-1a666941a56f', is_external=False, is_membership_group=True)
SearchableMailbox(guid='4b4345aa-877f-4523-9e0e-694e3cb0e959', is_external=False, is_membership_group=True)
SearchableMailbox(guid='f80c396e-5951-4bc1-bc24-5a1356dc88d6', is_external=False, is_membership_group=True)
SearchableMailbox(guid='e3cadd9b-bee0-4f3d-8bc5-e510314492ea', is_external=False, is_membership_group=True)
SearchableMailbox(guid='ab872069-24a8-4bd3-883f-4a1e365b6edd', is_external=False, is_membership_group=True)
SearchableMailbox(guid='23235cf3-4adb-4afa-a51b-6b046089c2c4', is_external=False, is_membership_group=True)
SearchableMailbox(guid='d96717f9-d18e-404c-859e-ce803270e361', is_external=False, is_membership_group=True)
SearchableMailbox(guid='e606a879-ef5a-4ec5-acc9-742ffbb25b0a', is_external=False, is_membership_group=True)
SearchableMailbox(guid='bd14eed7-dc78-41e8-9933-3439b4fe7ccd', is_external=False, is_membership_group=True)
SearchableMailbox(guid='e482988c-f61b-43b3-8ea8-cdbe42e6b8c7', is_external=False, is_membership_group=True)
SearchableMailbox(guid='828414e3-3153-4d1b-9409-fb4e0e03e6c0', is_external=False, is_membership_group=True)
SearchableMailbox(guid='f1fbd802-32ed-430e-86d2-02fccdd3dc90', is_external=False, is_membership_group=True)
SearchableMailbox(guid='4541f0c2-58cd-4996-92ac-9487745f45a4', is_external=False, is_membership_group=True)
SearchableMailbox(guid='dc380e56-6879-4b29-a121-9ac9b2517fcc', is_external=False, is_membership_group=True)
SearchableMailbox(guid='49668d3a-addc-4943-8524-d531ff5d2d56', is_external=False, is_membership_group=True)
SearchableMailbox(guid='f832a144-fa37-4e2b-97a3-d1ca12975e3f', is_external=False, is_membership_group=True)
SearchableMailbox(guid='65e7368c-e5c7-470b-9adb-93e63affaeca', is_external=False, is_membership_group=True)
SearchableMailbox(guid='f76b1b82-8e67-47de-8418-ea2677b7e2c6', is_external=False, is_membership_group=True)
SearchableMailbox(guid='87dc9818-a1ed-468d-bc3d-1edc0240952e', is_external=False, is_membership_group=True)
SearchableMailbox(guid='beab0c72-ba9b-4fea-ba63-9f3bacde170c', is_external=False, is_membership_group=True)
SearchableMailbox(guid='a860f324-285b-4050-ad7a-761ae5e4ed93', is_external=False, is_membership_group=True)
SearchableMailbox(guid='93f059da-8e7d-4f53-b3b1-f6c4d4850bc4', is_external=False, is_membership_group=True)
SearchableMailbox(guid='58f3569c-2cd8-4fe4-b04c-02723aa93717', is_external=False, is_membership_group=True)
SearchableMailbox(guid='24744688-d3f6-40c8-9744-75a2098126ed', is_external=False, is_membership_group=True)
SearchableMailbox(guid='8fce723f-52f4-45bc-8861-b19ba587d67d', is_external=False, is_membership_group=True)
SearchableMailbox(guid='4f842f22-e39a-4673-885a-7c9ecf02292e', is_external=False, is_membership_group=True)
SearchableMailbox(guid='1a1cf464-89f5-49f7-a909-b497bdf75f7c', is_external=False, display_name='Exchange Install Domain Servers', is_membership_group=True)
SearchableMailbox(guid='318e2536-08d6-4eb9-816f-89f068f664ce', primary_smtp_address='Administrator@stargazer.org', is_external=False, display_name='Administrator', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=949a1eb02ff64828bcf65fc5c18e0fab-Administrator')
SearchableMailbox(guid='1794f74c-bc0d-497a-b718-1bd90e8786f8', primary_smtp_address='bertram.gilfoyle@stargazer.org', is_external=False, display_name='Bertram Gilfoyle', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=df19338bf96b4681b500de6e77dcf6b0-Bertram Gilfoy')
SearchableMailbox(guid='6f2b1ac2-fe93-400b-a1ff-dbe2efc3eb8b', primary_smtp_address='cert@stargazer.org', is_external=False, display_name='Stargazer CERT Team', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=de04161a3053405eb31610b07ee8e66f-Stargazer CERT')
SearchableMailbox(guid='7f068d0f-7ecc-4400-803a-fbfe34bd2874', primary_smtp_address='emma.emmerich@stargazer.org', is_external=False, display_name='Emma Emmerich', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5338f034c9dc440985114ccfdb171409-Emme Emmerich')
SearchableMailbox(guid='b63647b2-f5c2-478f-9774-8528e5120c6a', primary_smtp_address='eve.moneypenny@stargazer.org', is_external=False, display_name='Eve Moneypenny', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=586b855fa0564ce8a50d82c8bf9a87b4-Eve Moneypenny')
SearchableMailbox(guid='4038e02e-2597-4ba5-a9ba-5f33081b85d3', primary_smtp_address='itachi.uchiha@stargazer.org', is_external=False, display_name='Itachi Uchiha', is_membership_group=False, reference_id='/o=Stargazer/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=d89a563c45be4f80b56d9c7bd26a188f-Itachi Uchiha')
Traceback (most recent call last):
  File "initial.py", line 16, in <module>
    for item in account.protocol.get_searchable_mailboxes():
  File "/usr/local/lib/python3.5/dist-packages/exchangelib-1.11.4-py3.5.egg/exchangelib/services.py", line 1923, in call
    expand_group_membership=expand_group_membership,
  File "/usr/local/lib/python3.5/dist-packages/exchangelib-1.11.4-py3.5.egg/exchangelib/services.py", line 1948, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=container_name)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib-1.11.4-py3.5.egg/exchangelib/services.py", line 285, in _get_element_container
    raise TransportError('No %s elements in ResponseMessage (%s)' % (name, xml_to_str(message)))
exchangelib.errors.TransportError: No {http://schemas.microsoft.com/exchange/services/2006/messages}FailedMailboxes elements in ResponseMessage (<ns0:GetSearchableMailboxesResponse xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:ns1="http://schemas.microsoft.com/exchange/services/2006/types" ResponseClass="Success"><ns0:ResponseCode>NoError</ns0:ResponseCode><ns0:SearchableMailboxes><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /><ns1:SearchableMailbox /></ns0:SearchableMailboxes></ns0:GetSearchableMailboxesResponse>)
```

Let me know if you need anything else

**Comment by ecederstrand** [comment]
Thanks for the test! That was really helpful.

I just pushed a possible fix for the TransportError. Can you please run the test again?

**Comment by ecederstrand** [comment]
Hi @ninSmith Can you test the mentioned commit? If you can confirm it fixes the `TransportError`, then we can close this issue.

**Comment by ninSmith** [comment]
Hey man,

Sorry for the late reply, was off a few days.
I think it works, see below the output:

```
People I Know
ExchangeSyncData
RelevantContacts
XrmActivityClientInstrumentation
XrmActivityStream
XrmCompanySearch
XrmInsights
ParkedMessages
Shortcuts
Document Centric Conversations
FileCollectionCache
PdpProfileV2
Recoverable Items
Purges
Deletions
Calendar Logging
Versions
XrmSearch
O365 Suite Storage
Location
Finder
Voice Mail
PACE
DelveNotifications
XrmDeletedItems
AllItems
MailboxAssociations
Inference
Schedule
Orion Notes
System
Spooler Queue
SharePointNotifications
Pass-Through Search Results
Favorites
TemporarySaves
PdpProfile
Views
PeopleConnect
O365 Suite Notifications
Deferred Action
XrmProjects
To-Do Search
OneDriveRoot
Folder Memberships
CalendarItemSnapshots
PeopleInsights
TeamChatHistory
AllPersonMetadata
XrmActivityStreamSearch
Sharing
My Contacts
Reminders
MeetingSapces
UserSocialActivityNotifications
Top of Information Store
Tasks
Drafts
Inbox
TheHive
TheHive found
Files
Contacts
{06967759-274D-40B2-A3EB-D7F9E73727D7}
Companies
{A9E2BC46-B3A0-4243-B315-60D991004455}
Organizational Contacts
Recipient Cache
PeopleCentricConversation Buddies
GAL Contacts
Calendar
Junk Email
Notes
Deleted Items
ExternalContacts
Sent Items
Conversation Action Settings
Journal
Conversation History
Outbox
Yammer Root
Inbound
Feeds
Outbound
SmsAndChatsSync
XrmDealSearch
GraphStore
GraphNonSecureTransactions
GraphRelations
GraphEdges
GraphNodes
GraphNonSecureDrafts
Freebusy Data
BrokerSubscriptions
ShardRelevancyFolder
Common Views
AllContacts
XrmActivityServerInstrumentation
CalendarSharingCacheCollection
DefaultFoldersChangeHistory
```

feel free to ping me if you need more testing with this feature or any others. I have my own office2016 lab and could help you more :)

**Comment by ecederstrand** [comment]
Looks good. Thanks for all the testing!
