### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by r-chris** [ecederstrand/exchangelib#385]
Upon calling: `account = Account(primary_smtp_address='x@y.z', config=config)`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/env/lib/python3.6/site-packages/exchangelib/account.py", line 62, in __init__
    self.locale = locale or getlocale()[0] or None  # get_locale() might not be able to determine the locale
  File "/home/dev/env/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/home/dev/env/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by ecederstrand** [comment]
`Account` also has a `locale` argument that you can use to specify the locale of that account, instead of having `Account` call `getlocale()` to fetch the host locale.
