### ISSUE TITLE
Override WELLKNOWN_FOLDERS

### ISSUE THREAD

**Issue by frennkie** [ecederstrand/exchangelib#387]
Is it possible to manually override the WELLKNOWN_FOLDERS list? I have implemented a bot that only needs access to a few folders (inbox, calendar, sent) and therefore I only gave the account permissions on these three.

But now I get errors because Exchange tries to access all folders that are listed in well known...

I know that I can "fix" this by giving access to all the folders.. but it would be nicer to limit the account and have more flexibility with exchnagelib.

**Comment by ecederstrand** [comment]
I see your use case, but changing `WELLKNOWN_FOLDERS` is probably not the way to go.

To access wellknown (distinguished) folders, we need to do a `GetFolder` call. Instead of doing one call for every distinguished folder, we try to get them all in `GetFolder` call.

There are various ways to use more low-level methods than e.g. `Account.inbox` to get only the inbox folder, e.g. `FolderCollection.get_folders()`, but I think we should start by checking whether we can handle the error messages you get gracefully.

So please start by posting your stack trace and response XML containing the exceptions and let's see what we can do.

**Comment by frennkie** [comment]
Ah.. wasn't aware of the `FolderCollection.get_folders()`. On a first try this really seems to solve my issue.

Anyway here is the trace and the debug XML. As a demo I simply added a "Foo" folder to the WELLKNOWN_FOLDERS.

```
2018-04-09 19:47:58,546 exchangelib.services WARNING  EWS https://owa.example.com/EWS/Exchange.asmx, account bar@example.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\User\testing\venv\lib\site-packages\cached_property.py", line 64, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\testing\exchangelib\services.py", line 90, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\User\testing\exchangelib\services.py", line 174, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\Users\User\testing\exchangelib\services.py", line 230, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Users\User\testing\exchangelib\services.py", line 264, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorSchemaValidation: Fehler bei der Schemaüberprüfung der Anforderung.

Traceback (most recent call last):
  File "C:\Users\User\testing\venv\lib\site-packages\cached_property.py", line 64, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/testing/roster/cli.py", line 553, in <module>
    cli()
  File "C:\Users\User\testing\venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\testing\venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\testing\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\User\testing\venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\testing\venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:/Users/User/testing/roster/cli.py", line 239, in process_meeting_requests
    print(account.root.tree())
  File "C:\Users\User\testing\exchangelib\folders.py", line 432, in tree
    children = list(self.children)
  File "C:\Users\User\testing\exchangelib\folders.py", line 99, in __len__
    return len(self.folders)
  File "C:\Users\User\testing\venv\lib\site-packages\cached_property.py", line 67, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\User\testing\exchangelib\folders.py", line 96, in folders
    return list(self._folders)
  File "C:\Users\User\testing\exchangelib\folders.py", line 898, in get_children
    for f in self._folders_map.values():
  File "C:\Users\User\testing\exchangelib\folders.py", line 917, in _folders_map
    for f in FolderCollection(account=self.account, folders=distinguished_folders).get_folders():
  File "C:\Users\User\testing\exchangelib\services.py", line 1057, in call
    shape=shape,
  File "C:\Users\User\testing\exchangelib\services.py", line 90, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\User\testing\exchangelib\services.py", line 174, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\Users\User\testing\exchangelib\services.py", line 230, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Users\User\testing\exchangelib\services.py", line 264, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorSchemaValidation: Fehler bei der Schemaüberprüfung der Anforderung.
2018-04-09 19:47:58,702 exchangelib.protocol DEBUG    Server owa.example.com: Closing sessions
```

```
Request data:
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<s:Header>
		<t:RequestServerVersion Version="Exchange2010_SP2" />
		<t:TimeZoneContext>
			<t:TimeZoneDefinition Id="W. Europe Standard Time" />
		</t:TimeZoneContext>
	</s:Header>
	<s:Body>
		<m:GetFolder>
			<m:FolderShape>
				<t:BaseShape>IdOnly</t:BaseShape>
				<t:AdditionalProperties>
					<t:FieldURI FieldURI="folder:ChildFolderCount" />
					<t:FieldURI FieldURI="folder:EffectiveRights" />
					<t:FieldURI FieldURI="folder:FolderClass" />
					<t:FieldURI FieldURI="folder:DisplayName" />
					<t:FieldURI FieldURI="folder:ParentFolderId" />
					<t:FieldURI FieldURI="folder:TotalCount" />
					<t:FieldURI FieldURI="folder:UnreadCount" />
				</t:AdditionalProperties>
			</m:FolderShape>
			<m:FolderIds>
				<t:DistinguishedFolderId Id="archivedeleteditems">
					<t:Mailbox>
						<t:EmailAddress>bar@example.com</t:EmailAddress>
						<t:RoutingType>SMTP</t:RoutingType>
						<t:MailboxType>Mailbox</t:MailboxType>
					</t:Mailbox>
				</t:DistinguishedFolderId>
				[...]
				<t:DistinguishedFolderId Id="foo">
					<t:Mailbox>
						<t:EmailAddress>bar@example.com</t:EmailAddress>
						<t:RoutingType>SMTP</t:RoutingType>
						<t:MailboxType>Mailbox</t:MailboxType>
					</t:Mailbox>
				</t:DistinguishedFolderId>
			</m:FolderIds>
		</m:GetFolder>
	</s:Body>
</s:Envelope>

Response data:
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<s:Fault>
			<faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorSchemaValidation</faultcode>
			<faultstring xml:lang="de-DE">Fehler bei der Schema\xc3\xbcberpr\xc3\xbcfung der Anforderung: Das \'Id\'-Attribut ist ung\xc3\xbcltig - Der Wert \'foo\' ist gem\xc3\xa4\xc3\x9f seinem Datentyp \'http://schemas.microsoft.com/exchange/services/2006/types:DistinguishedFolderIdNameType\' ung\xc3\xbcltig - Enumeration-Einschr\xc3\xa4nkung ist fehlgeschlagen..</faultstring>
			<detail>
				<e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorSchemaValidation</e:ResponseCode>
				<e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">Fehler bei der Schema\xc3\xbcberpr\xc3\xbcfung der Anforderung.</e:Message>
				<t:MessageXml xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
					<t:LineNumber>1</t:LineNumber>
					<t:LinePosition>6361</t:LinePosition>
					<t:Violation>Das \'Id\'-Attribut ist ung\xc3\xbcltig - Der Wert \'foo\' ist gem\xc3\xa4\xc3\x9f seinem Datentyp \'http://schemas.microsoft.com/exchange/services/2006/types:DistinguishedFolderIdNameType\' ung\xc3\xbcltig - Enumeration-Einschr\xc3\xa4nkung ist fehlgeschlagen..</t:Violation>
				</t:MessageXml>
			</detail>
		</s:Fault>
	</s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment]
Thanks for the extra info! The problem here is that the XML is invalid because `archivedeleteditems` is not allowed as an `Id` value. This is the problem described in #370.

The surprising thing is that, according to https://github.com/OfficeDev/ews-managed-api/blob/master/Enumerations/WellKnownFolderName.cs#L197, `archivedeleteditems` is supported starting from Exchange 2010 SP1, and the server you are connecting to is 2010 SP2.

It would be highly surprising to me if Exchange changes the XML validation of the `Id` attribute based access restriction to these folders, but this is Microsoft so anything is possible...

**Comment by frennkie** [comment]
I'm not online at the moment. As far as I recall `archivedeleteditems` is not the issue.. but the additional Foo Folder. When I remove Foo it's working.

**Comment by ecederstrand** [comment]
Ah, you're entirely right. I misread the error message.

Folder `foo` should never have been requested as a `DistinguishedFolderId`. That will fail regrdless of the server version.

Can you please post the code triggering the error? We either have a bug or you're doing soething unsupported :-)

**Comment by ecederstrand** [comment]
Looking at the stack trace, I can't see this happening unless `WELLKNOWN_FOLDERS` has a member with a 'DISTINGUISHED_FOLDER_ID' value of `foo`. Do you have any local patches, or are you modifying `WELLKNOWN_FOLDERS` in any way?

**Comment by frennkie** [comment]
Hm.. sorry.. I have two separate environments (one at work and one at home). I used "Foo" yesterday at home to simulate the limited permission case. But I may have made a mistake. I just upgraded to 1.10 and ran my application and it's working. So sorry for taking up your time and I'll close the issue.
