### ISSUE TITLE
Error iterating over all emails in a folder

### ISSUE THREAD

**Issue by tbbstny** [ecederstrand/exchangelib#423]
This is in response to https://stackoverflow.com/q/50518343/5632784
Summary: When running script against the same folder I'll get errors at different item counts.  Sometimes I get a message that a connection was 'forcibly closed by remote host', and other just an 'Unknown SOAP response'.  

I talked to our Exchange Server admin folks.  They've 'associated my account with a different throttling policy', and while I can go a lot farther now, it eventually stills errors out.  As requested, I'm creating an issue with the captured output.  

The code to process emails has chaged a bit from original SO questions.  Our ultimate goal to extract to csv:

```python
credentials = Credentials(username = user_email, password = user_pass)
account = Account(user_email, credentials = credentials, autodiscover = True)

qs = account.sent.all().order_by('-datetime_received')
qs.page_size = 10
emails = qs.iterator()

with open('email.extract.' + timestamp + '.txt', 'w') as text_file:
    for i, email in enumerate(emails):
        logger.info("{0} ({1}) \"{2}\" from {3}".format(i, email.item_class, email.subject, email.sender.name))
        if email.body is not None:
            print(i, str(email.body).encode('utf-8'), file=text_file)
```

I've routed the logging to a file, but when I get an error, this is what is on the console:
```python
Traceback (most recent call last):
  File "email_test.py", line 54, in <module>
    for i, email in enumerate(emails):
  File "C:\projects\exchangelib\queryset.py", line 390, in _as_items
    for i in iterable:
  File "C:\projects\exchangelib\account.py", line 628, in fetch
    shape=IdOnly,
  File "C:\projects\exchangelib\services.py", line 581, in _pool_requests
    for chunk in chunkify(items, self.chunk_size):
  File "C:\projects\exchangelib\util.py", line 77, in chunkify
    for i in iterable:
  File "C:\projects\exchangelib\folders.py", line 239, in find_items
    for i in items:
  File "C:\projects\exchangelib\services.py", line 375, in _paged_call
    response = self._get_response_xml(payload=payload)
  File "C:\projects\exchangelib\services.py", line 171, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\projects\exchangelib\services.py", line 226, in _get_soap_payload
    raise SOAPError('Unknown SOAP response: %s' % xml_to_str(body))
exchangelib.errors.SOAPError: Unknown SOAP response: <ns0:Body xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" />
```

Here's the end of the log file:
```
06-05 14:35 exchangelib.util DEBUG    Session 14995 thread 14284: Useful response from https://oa.myhost.com/EWS/Exchange.asmx
06-05 14:35 exchangelib.protocol DEBUG    Server oa.myhost.com: Releasing session 14995
06-05 14:35 exchangelib.services DEBUG    Trying API version Exchange2010_SP2 for account myaccount@myhost.com
06-05 14:35 exchangelib.protocol DEBUG    Server oa.myhost.com: Got session 14995
06-05 14:35 exchangelib.util DEBUG    Session 14995 thread 1572: retry 0 timeout 120000 POST'ing to https://oa.myhost.com/EWS/Exchange.asmx after 1000s wait
06-05 14:36 urllib3.connectionpool DEBUG    https://oa.myhost.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
06-05 14:36 exchangelib.util DEBUG    Retry: 0
Waited: 1000
Timeout: 120000
Session: 14995
Thread: 1572
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x00000000049F4940>
URL: https://oa.myhost.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x00000000049F4C18>
Allow redirects: False
Response time: 60.02899999999863
Status code: 200
Request headers: {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Cookie': 'exchangecookie=e17cc11167e44a8d9d1834baa9178eb1', 'Content-Length': '1003'}
Response headers: {'Cache-Control': 'private', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/7.5', 'X-AspNet-Version': '2.0.50727', 'X-Powered-By': 'ASP.NET', 'Date': 'Tue, 05 Jun 2018 19:36:08 GMT', 'Transfer-Encoding': 'chunked'}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /><t:TimeZoneContext><t:TimeZoneDefinition Id="Central Standard Time" /></t:TimeZoneContext></s:Header><s:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>IdOnly</t:BaseShape></m:ItemShape><m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="10" Offset="2950" /><m:SortOrder><t:FieldOrder Order="Descending"><t:FieldURI FieldURI="item:DateTimeReceived" /></t:FieldOrder></m:SortOrder><m:ParentFolderIds><t:DistinguishedFolderId Id="sentitems"><t:Mailbox><t:EmailAddress>myaccount@myhost.com</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:ParentFolderIds></m:FindItem></s:Body></s:Envelope>'
Response data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="361" MinorBuildNumber="1" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Envelope>'

06-05 14:36 exchangelib.util DEBUG    Session 14995 thread 1572: Useful response from https://oa.myhost.com/EWS/Exchange.asmx
06-05 14:36 exchangelib.protocol DEBUG    Server oa.myhost.com: Releasing session 14995
06-05 14:36 exchangelib.services DEBUG    Trying API version Exchange2010_SP2 for account myaccount@myhost.com
```

**Comment by ecederstrand** [comment]
Th server is responding to a `FindItem` request with a seemingly wellformed SOAP response (HTTP status code 200, no suspicious HTTP headers), but the SOAP body is empty. I've reformatted the response data to highlight this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="361" MinorBuildNumber="1"
                             Version="Exchange2010_SP2"
                             xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
</s:Envelope>
```

From a purity point of view, I think we are correct in raising an exception that this is a bogus reply, because that's what it is. I can't imagine how this would ever be a sane reply, and I assume you are hitting a bug in your Exchange server.

If you are not already on the latest patch version of Exchange 2010 SP2, I would suggest upgrading. It's not easy to work around this in your own code because the exception occurs in the middle of a loop that sends paged requests. One option is to patch your installed exchangelib version here: https://github.com/ecederstrand/exchangelib/blob/ddd509f848ef87f9c06520e664d117944db39d63/exchangelib/services.py#L376

to add something like this before catching `ErrorServerBusy` (this will only work if you connected using a `ServiceAccount` instead of a `Credentials` instance):

```python
except SOAPError:
    if self.protocol.credentials.fail_fast:
        raise
    # Add a delay since we suspect this is due to excessive load on the server
    self.protocol.credentials.back_off_until = datetime.datetime.now() + datetime.timedelta(seconds=60)
    continue
```

I'm not keen to add this as an official patch, at least until we have a much better understanding of what is happening.

**Comment by tbbstny** [comment]
I noticed the empty body but wasn't sure what to make of that.  I've sent a question off asking about our patch state, but if we are not up-to-date I doubt what I'm working on will be able to provide enough leverage to make that happen.  

I did switch to using ```ServiceAccount``` and added the recommended patch.  When running with that, again in the 2900s it errored out but the console output changed slightly:
```
email.extract       : INFO     2959 (IPM.Note) "Re: Info. for SOS" from Doe, John J
Traceback (most recent call last):
  File "email_test.py", line 52, in <module>
    for i, email in enumerate(emails):
  File "C:\projects\exchangelib\queryset.py", line 390, in _as_items
    for i in iterable:
  File "C:\projects\exchangelib\account.py", line 628, in fetch
    shape=IdOnly,
  File "C:\projects\exchangelib\services.py", line 602, in _pool_requests
    for elem in r.get():
  File "C:\anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\projects\exchangelib\services.py", line 591, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "C:\projects\exchangelib\services.py", line 89, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\projects\exchangelib\services.py", line 171, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\projects\exchangelib\services.py", line 226, in _get_soap_payload
    raise SOAPError('Unknown SOAP response: %s' % xml_to_str(body))
exchangelib.errors.SOAPError: Unknown SOAP response: <ns0:Body xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" />
```
Just to make sure it's obvious, the error before reported line number ```375```, but was at line number ```89``` in this case.  So I applied the same patch there too, like so:
```
            except SOAPError:
                print("inside \"except SOAPError\"")
                if self.protocol.credentials.fail_fast:
                    raise
                # Add a delay since we suspect this is due to excessive load on the server
                print("setting back_off_until")
                self.protocol.credentials.back_off_until = datetime.datetime.now() + datetime.timedelta(seconds=60)
                continue                
```
I've ran a couple of times with this patch, and was able to loop through all emails.  FWIW, the processing stalls around the 2900 mark, prints out my poor man's debug statements, and then continues on:
```
email.extract       : INFO     2919 (IPM.Note) "RE: PTA setup" from Doe, John J
inside "except SOAPError"
setting back_off_until
inside "except SOAPError"
setting back_off_until
email.extract       : INFO     2920 (IPM.Note) "RE: trunk build failed, looking into it" from Doe, John J
````
So far it just stalls this one time, but my folder only has about 5800 emails in it, making the stall happen about 1/2 way through.  If the folder contained more items, perhaps it would happen multiple times.

I've not see the forced closed error again, but if we do we will be sure to respond back on that with debug infomation.

I also spun up a Java solution using the EWS java jar.  I havn't spent much time working in Python or with EWS, so may be some ignorance on my part, but the Java API and the Python one seem quite different.  For my current problem, a Python solution is prefereable for integration with some other Python scripts used to process emails once they are extracted.  I just spun un the Java solution to help see if that might help identify the source as either our Exchange server or a bug in the Python library.  In any case, the Java solution worked successfully right away.  I tweaked an example I found via Google, and here's the important bits:
```
    public void  readEmails() {
        boolean more = true;
        int i = 1;
        try {
            Folder folder = Folder.bind(service, WellKnownFolderName.SentItems);
            ItemView view = new ItemView(NUMBER_EMAILS_FETCH);

            while(more) {
                FindItemsResults<Item> results = service.findItems(folder.getId(), view);
                for (Item item : results) {
                    Map messageData = readEmailItem(item.getId());
                    System.out.println( String.format("%d \"%s\" from %s", i++, messageData.get("subject"), messageData.get("senderName") ) );
                }
                more = results.isMoreAvailable();
                if (more)
                {
                    view.setOffset(results.getNextPageOffset());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Comment by tbbstny** [comment]
The recommended patch has been working so we are considering this issue resolved.
