### ISSUE TITLE
EWSTest tests fail on Python 2.7

### ISSUE THREAD

**Issue by catern** [ecederstrand/exchangelib#427]
The setUpClass method catches only FileNotFoundError, not the IOError that is thrown on Python 2.7.

**Comment by ecederstrand** [comment]
The test suite passes with Python 2.7 on Travis: https://travis-ci.org/ecederstrand/exchangelib/jobs/389100540

Can you post the stack trace you are getting?

**Comment by catern** [comment]
```
ERROR
ERROR
skipped "Skip BaseItemTest, it's only for inheritance"
test_api_version (tests.BuildTest) ... ok
test_compare (tests.BuildTest) ... ok
test_magic (tests.BuildTest) ... ok
ERROR
ERROR
test_hardcode_all (tests.ConfigurationTest) ... ok
test_magic (tests.ConfigurationTest) ... ok
ERROR
test_equality (tests.CredentialsTest) ... ok
test_hash (tests.CredentialsTest) ... ok
test_type (tests.CredentialsTest) ... ok
test_ewsdate (tests.EWSDateTimeTest) ... ok
test_ewsdatetime (tests.EWSDateTimeTest) ... ok
test_ewstimezone (tests.EWSDateTimeTest) ... ok
test_generate (tests.EWSDateTimeTest) ... ok
test_localize (tests.EWSDateTimeTest) ... ok
test_garbage_input (tests.FieldTest) ... ok
test_naive_datetime (tests.FieldTest) ... ok
test_value_validation (tests.FieldTest) ... ok
test_versioned_choice (tests.FieldTest) ... ok
test_versioned_field (tests.FieldTest) ... ok
ERROR
test_task_validation (tests.ItemTest) ... ok
ERROR
test_add_field_with_no_field_cache (tests.PropertiesTest) ... ok
test_body (tests.PropertiesTest) ... ok
test_internet_message_headers (tests.PropertiesTest) ... ok
test_invalid_kwargs (tests.PropertiesTest) ... ok
test_itemid_equality (tests.PropertiesTest) ... ok
test_mailbox (tests.PropertiesTest) ... ok
test_physical_address (tests.PropertiesTest) ... ok
test_close (tests.ProtocolTest) ... skipped 'no network connection inside the Nix sandbox'
test_protocol_instance_caching (tests.ProtocolTest) ... ok
test_session (tests.ProtocolTest) ... ok
test_from_folder (tests.QuerySetTest) ... ok
test_magic (tests.QuerySetTest) ... ok
test_queryset_copy (tests.QuerySetTest) ... ok
test_magic (tests.RecurrenceTest) ... ok
test_validation (tests.RecurrenceTest) ... ok
test_magic (tests.RestrictionTest) ... ok
test_q (tests.RestrictionTest) ... ok
test_q_boolean_ops (tests.RestrictionTest) ... ok
test_q_expr (tests.RestrictionTest) ... ok
test_q_failures (tests.RestrictionTest) ... ok
test_q_inversion (tests.RestrictionTest) ... ok
test_invalid_server_version (tests.ServicesTest) ... ok
ERROR
test_get_auth_method_from_response (tests.TransportTest) ... ok
test_chunkify (tests.UtilTest) ... ok
test_get_domain (tests.UtilTest) ... ok
test_get_redirect_url (tests.UtilTest) ... ok
test_peek (tests.UtilTest) ... ok
test_pretty_xml_handler (tests.UtilTest) ... ok
test_to_xml (tests.UtilTest) ... ok
test_default_api_version (tests.VersionTest) ... ok
test_from_response (tests.VersionTest) ... ok

======================================================================
ERROR: setUpClass (tests.AccountTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.AutodiscoverTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.CalendarTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 2837, in setUpClass
    super(BaseItemTest, cls).setUpClass()
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.CommonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.ContactsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 2837, in setUpClass
    super(BaseItemTest, cls).setUpClass()
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.FolderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.MessagesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 2837, in setUpClass
    super(BaseItemTest, cls).setUpClass()
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

======================================================================
ERROR: setUpClass (tests.TasksTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/tests/__init__.py", line 2837, in setUpClass
    super(BaseItemTest, cls).setUpClass()
  File "/build/source/tests/__init__.py", line 1270, in setUpClass
    with open(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'settings.yml')) as f:
IOError: [Errno 2] No such file or directory: '/build/source/settings.yml'

----------------------------------------------------------------------
Ran 50 tests in 0.060s

FAILED (errors=8, skipped=2)
Test failed: <unittest.runner.TextTestResult run=50 errors=8 failures=0>

```

**Comment by catern** [comment]
To be clear: I'm intending to not provide a settings.yml. I want it to skip the tests, not fail them.

**Comment by ecederstrand** [comment]
Thanks!
