### ISSUE TITLE
Multi-folder search raises Exception

### ISSUE THREAD

**Issue by mrinehart-r7** [ecederstrand/exchangelib#432]
Any ideas on the following? I followed the samples in the documentation and came up with this exception. I did some exploratory work and services.py:355 was receiving a kwarg with an `account` key, not folders. Adjusting the code to take that into account led me to further exceptions in some other classes.

Error:
```
Traceback (most recent call last):
  File "/Users/mrinehart/Code/sandbox/exchange_testing/search_mailboxes.py", line 38, in <module>
    num_matches = len(matching_emails)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 320, in __len__
    return self.count()
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 637, in count
    return len(list(new_qs.__iter__()))
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 311, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 390, in _as_items
    for i in iterable:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/folders.py", line 228, in find_items
    items = FindItem(account=self.account, folders=self.folders, chunk_size=page_size).call(
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 355, in __init__
    raise ValueError('"folders" must not be empty')
ValueError: "folders" must not be empty
```

Code Sample:
```
class Connection(object):
    _EXCHANGE_VERSIONS = {
        "exchange 2007": exchangelib.version.EXCHANGE_2007,
        "exchange 2010": exchangelib.version.EXCHANGE_2010,
        "exchange 2010 sp2": exchangelib.version.EXCHANGE_2010_SP2,
        "exchange 2013": exchangelib.version.EXCHANGE_2013,
        "exchange 2016": exchangelib.version.EXCHANGE_2016
    }

    def __init__(self):
        self.user_config = None
        self.my_account = None

    def connect(self, params={}):
        # Because we aim to re-use much of the connection code, we're abstracting the connection configuration out
        # of the connect function and into a separate configuration function. This will allow us to re-use code.
        self.user_config = Configuration(params=params)
        logging.info("Connecting to Exchange...")
        self.connect_to_exchange(configuration=self.user_config)

    def connect_to_exchange(self, configuration: Configuration, impersonation: str = None):
        """
        Connects to the MS exchange server
        :param configuration: User configuration object used to configure an Exchange connection
        :param impersonation: Optional parameter. Allows an email address to be impersonated. Account must have privileges for impersonation
        """
        try:
            logging.info("Using username of %s" % configuration.username)
            credentials = exchangelib.Credentials(username=configuration.username,
                                                  password=configuration.password)

            # Decide whether or not to impersonate
            if not impersonation:
                address = configuration.primary_smtp_address
            else:
                logging.info("Impersonating email address of %s" % impersonation)
                address = impersonation

            if not configuration.verify_ssl:
                logging.info("SSL verification disabled")
                BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

            if not configuration.autodiscover:
                logging.info("Looking up Exchange server version settings...")
                server_version = self._EXCHANGE_VERSIONS.get(configuration.exchange_version)

                logging.info("Autodiscovery disabled. Using the following settings:\n"
                             "\tserver: {server}\n\texchange_version: {exchange_version}\n"
                             .format(server=configuration.server, exchange_version=server_version))

                logging.info("Creating server configuration...")
                version = exchangelib.Version(server_version)
                config = exchangelib.Configuration(server=configuration.server,
                                                   credentials=credentials,
                                                   has_ssl=configuration.use_ssl,
                                                   version=version)

                logging.info("Configuration created, connecting to server...")
                account = exchangelib.Account(primary_smtp_address=address,
                                              credentials=credentials,
                                              autodiscover=False,
                                              access_type=IMPERSONATION if impersonation else configuration.access_type,
                                              config=config)
            else:
                logging.info("Autodiscovering server settings...")
                account = exchangelib.Account(primary_smtp_address=address,
                                              credentials=credentials,
                                              autodiscover=True,
                                              access_type=IMPERSONATION if impersonation else configuration.access_type)

            if account:
                logging.info("Connected to Exchange server!")
                self.my_account = account
        except exchangelib.errors.ErrorImpersonateUserDenied:
            raise Exception("Unable to impersonate user.")
        except Exception as e:
            logging.error("Error connecting to Exchange server: %s" % e)
            raise


params = {
    "querystring": "From:jon@doe.com",
    "accounts": [
        "test1@doe.com",
        "test2@doe.com"
    ],
    "all_folders": True,
    "flatten": False
}


c = Connection()
c.connect(CONNECTION_PARAMS)

accounts = params.get("accounts")

all_matches = []
match_count = 0
for account in accounts:
    print("Reconnecting to Exchange server via Impersonation with: %s" % account)
    c.connect_to_exchange(configuration=c.user_config,
                          impersonation=account)

    if not params.get("all_folders"):
        matching_emails = c.my_account.inbox.filter(params.get("querystring"))
    else:
        matching_emails = c.my_account.inbox.children.filter(params.get("querystring"))

    # Check number of matches to see if it's worth going further on this account
    num_matches = matching_emails.count()
```

**Comment by ecederstrand** [comment]
This is probably caused by `inbox.children` being an empty list. `inbox.children.filter()` doesn't make sense in that case, and `services.py` is complaining that it received an empty list to do the filtering on.

**Comment by mrinehart-r7** [comment]
Thank you for the reply @ecederstrand - you are correct. There were no children of the `Inbox` folder - rather, they were at the same level in the folder hierarchy as Inbox. Moving custom folders to Inbox and then running my script again successfully found children and did not raise exceptions. Closing as this is not a bug and was an incorrect interpretation of the docs on my part :)

**Comment by ecederstrand** [comment]
No worries. Do you have any suggestions for a better error message that would have helped you diagnose the problem yourself?

**Comment by mrinehart-r7** [comment]
Yes, maybe something like "No subfolders found" or a message more oriented towards Exchange instead of the library.

I would also possibly consider switching that `raise` over to a logging message and just return None or something indicating that no folders were found rather than stopping execution. I think it can be a perfectly valid scenario to run into situations where no sub-folders are present.

As an example, I am using this combined with impersonation to iterate over a list of accounts, search all of them for emails (this is where the multi-folder search comes into play), and then print out information on matching emails. Not all accounts will have the same folder structure/hierarchy, with some having subfolders and some not.

**Comment by ecederstrand** [comment]
Thanks for your useful comments! Reopening to make sure it’s not lost.
