### ISSUE TITLE
Issues with periodic syncing

### ISSUE THREAD

**Issue by gtdavidv** [ecederstrand/exchangelib#443]
I'm trying to periodically sync up Exchange mail and calendar for my app's users. The sync cycle is called every 15 minutes. It'll run just fine for a while, but eventually I'm running into timeout issues when attempting to authenticate the user's account.

The connection code is:
```
try:
    credentials = Credentials(username=exchangeUsername, password=exchangePassword)
    try:
        config = Configuration(service_endpoint='https://outlook.office365.com/EWS/Exchange.asmx', credentials=credentials)
        account = Account(primary_smtp_address=exchangeEmail, config=config, autodiscover=False, access_type=accessType)
    except:
        account = Account(primary_smtp_address=exchangeEmail, credentials=credentials, autodiscover=True, access_type=accessType)
except:
    print(str(time.time()) + ' - Could not access Exchange (user ' + str(eachUser.id) + ')')
```

The timeout I'm getting after a few successful runs is:
```
EWS https://outlook.office365.com/EWS/Exchange.asmx, account ###emailaddress###: Exception in _get_elements: Traceback (most recent call last):
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 298, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/4degrees/.local/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/4degrees/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 88, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 164, in _get_response_xml
    allow_redirects=False)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 547, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 603, in _raise_response_errors
    raise r.headers['TimeoutException']
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 494, in post_ratelimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT)
  File "/home/4degrees/.local/lib/python3.5/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/4degrees/.local/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/4degrees/.local/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/4degrees/.local/lib/python3.5/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='outlook.office365.com', port=443): Read timed out. (read timeout=120)
```

After reading through some of the other issues, I tried the following as a solution after each sync cycle:
```
from exchangelib.protocol import close_connections
close_connections()
```
That code errored with the below. It also caused the authentication attempt on the next sync cycle to hang the process. I also tried `from exchangelib import close_connections` with the same results.
```
Service: Outlook importer
Error: Traceback (most recent call last):
  File "./app.py", line 57, in bg_process_outlook_mail_import
    outlook_import_mail()
  File "./background_processes/outlook_import_mail.py", line 322, in outlook_import_mail
    close_connections()
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 33, in close_connections
    CachingProtocol.clear_cache()
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 190, in clear_cache
    protocol.close()
AttributeError: 'RateLimitError' object has no attribute 'close'
```
I had also tried replacing `Credentials()` with `ServiceAccount()` but seemed to be experiencing hanging issues with that as well. I can attempt to get more specificity around that attempt if you think it's the right approach.

**Comment by ecederstrand** [comment]
You may simply be sending requests more frequently than Office365 is happy with, and this is their way of rate-limiting your account. `ServiceAccount` will gloss over much of this, but not magically make Office365 happier.

You could try one of these:
* Reduce your query complexity by requesting fewer fields, less items, shorter date ranges etc.
* Reduce your sync frequency
* Ask your Exchange admins to relax the throttling policies on your account
* Shrink the request pool:
```python
from exchangelib.protocol import BaseProtocol
BaseProtocol.SESSION_POOLSIZE = 1  # Default is 4
```

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's more we can do here :-)

**Comment by gtdavidv** [comment]
For posterity, the below didn't fix the problem, at least not on its own:

`BaseProtocol.SESSION_POOLSIZE = 1`

However, the original close_connections() fix (see original issue text) in combination with the "Only attempt to close Protocol instances" commit seems like it may have done the trick
