### ISSUE TITLE
Crash in Openshift / Kubernetes

### ISSUE THREAD

**Issue by tobiasge** [ecederstrand/exchangelib#448]
When using exchangelib in an Openshift / Kubernetes environment I get the following crash:
```
Traceback (most recent call last):
--
  | File "/usr/local/bin/exchangeToEInk", line 7, in <module>
  | from e_paper import main
  | File "/usr/local/lib/python3.6/site-packages/e_paper/__init__.py", line 10, in <module>
  | import exchangelib
  | File "/usr/local/lib/python3.6/site-packages/exchangelib/__init__.py", line 4, in <module>
  | from .account import Account
  | File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 14, in <module>
  | from .autodiscover import discover
  | File "/usr/local/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 55, in <module>
  | AUTODISCOVER_PERSISTENT_STORAGE = os.path.join(tempfile.gettempdir(), shelve_filename())
  | File "/usr/local/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 51, in shelve_filename
  | user = getpass.getuser()
  | File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
  | return pwd.getpwuid(os.getuid())[0]
  | KeyError: 'getpwuid(): uid not found: 1000540000'
```

The problem is with the Openshift security system that runs the containers as random userids.
This crash also happens when I disable the autodiscover option. I think there should be a fallback in the shelve_filename() function that works without a username.

**Comment by ecederstrand** [comment]
Be aware that different users will now share the same cache file. This means they will either be able to see which hostnames other users connect to, which may be unfortunate, or they may not have access to the file because it's owned by another user.
