### ISSUE TITLE
ErrorQuotaExceeded prevents sending?

### ISSUE THREAD

**Issue by mnsinger** [ecederstrand/exchangelib#457]
Not sure if this is an issue or something on the Exchange side that can't helped. I'm trying to send a message with a service account that has a full mailbox. I'm not saving the message only sending. I get the error 'exchangelib.errors.ErrorQuotaExceeded: Mailbox has exceeded maximum mailbox size.'

Is there anyway to ignore this error and have it send anyway?

```
def send_email(subject, body, recipients, attachments=None, html=False):
    credentials = ServiceAccount(username=properties_dict["email_uid"], password=decrypt(properties_dict["email_pwd"]).decode("latin-1"))
    config = Configuration(server='mail.---.org', credentials=credentials)
    account = Account(primary_smtp_address='{}@---.org'.format(properties_dict["email_uid"]), config=config, autodiscover=False, access_type=DELEGATE)

    to_recipients = []
    for recipient in recipients:
        to_recipients.append(Mailbox(email_address=recipient))

    if html:
        body = HTMLBody(body)
        
    # Create message
    m = Message(account=account,
                subject=subject,
                body=body,
                to_recipients=to_recipients)

    # attach files
    for attachment_name, attachment_content in attachments or []:
        file = FileAttachment(name=attachment_name, content=attachment_content)
        m.attach(file)
    m.send()
```

error:

```
Multiple results were found.
Traceback (most recent call last):
  File "C:\DataLine\r2d4_scheduler\r2d4_scheduler.py", line 595, in <module>
    mskcc.send_email(email_subject, email_body, recipients_formatted, attachments)
  File "C:\DataLine\python_modules\mskcc.py", line 65, in send_email
    m.send()
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\items.py", line 589, in send
    res = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=send_meeting_invitations)
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\items.py", line 247, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\account.py", line 382, in bulk_create
    send_meeting_invitations=send_meeting_invitations,
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\account.py", line 376, in <genexpr>
    i if isinstance(i, Exception)
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\services.py", line 456, in _pool_requests
    for elem in elems:
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\services.py", line 283, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\services.py", line 256, in _get_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Program Files\Python34\lib\site-packages\exchangelib\services.py", line 273, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorQuotaExceeded: Mailbox has exceeded maximum mailbox size.
```

**Comment by ecederstrand** [comment]
This is a server error that exchangelib cannot do anything about. If you are not able to raise your quota, you can recover from this by lowering your mailbox size. It's possible you can simply empty your trash and your recoverable items folder.

**Comment by dmsfabiano** [comment]
@ecederstrand somewhat related, but I cannot find this in the documentation.

Is there a method/attribute to get the maximum size of attachments supported by the library? I know I can catch the ErrorMessageSizeExceeded, but I would prefer to check for max size and send a difference response with out waiting for the exception to get triggered

**Comment by ecederstrand** [comment]
The attachment size limit is a server setting. I don't think it's possible to fetch this server setting using EWS.
