### ISSUE TITLE
Getting Calendar items by UID sometimes doesn't work

### ISSUE THREAD

**Issue by mcv21** [ecederstrand/exchangelib#492]
Hi,

I've looked at a few resolved issues in this area (#453 for example), and I still can't get this working. I may be doing something wrong.

What I want to do is retrieve a calendar event by its `uid` field (I want this, because AIUI this doesn't change on modification, whereas `item_id` does - and I want to be able to retrieve items later when they might have been changed in the mean time). The obvious search doesn't work:

```
>>> gautoac.calendar.get(uid=x.uid)
ERROR: items EWS does not support filtering on field 'uid'
```
(though the equivalent with `item_id` does)

I tried the approach documented in the help for `exchangelib.UID`, but even that doesn't always work; for example if I create the `GlobalObjectId` class, and then try and find events by it:
```python
>>> for event in gautoac.calendar.all():
...  ans=gautoac.calendar.get(global_object_id=GlobalObjectId(exchangelib.UID(event.uid)))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/upstreams/exchangelib/exchangelib/folders.py", line 581, in get
    return FolderCollection(account=self.root.account, folders=[self]).get(*args, **kwargs)
  File "/upstreams/exchangelib/exchangelib/folders.py", line 106, in get
    return QuerySet(self).get(*args, **kwargs)
  File "/upstreams/exchangelib/exchangelib/queryset.py", line 551, in get
    raise DoesNotExist()
exchangelib.queryset.DoesNotExist
```
I hasten to add, it works sometimes, just not all the time - but that's enough to mean it's not use for my purposes.

A failing event (i.e. where the above fails) example is:
```python
CalendarItem(mime_content=b'BEGIN:VCALENDAR\r\nMETHOD:PUBLISH\r\nPRODID:Microsoft Exchange Server 2010\r\nVERSION:2.0\r\nBEGIN:VTIMEZONE\r\nTZID:(UTC+00:00) Dublin\\, Edinburgh\\, Lisbon\\, London\r\nBEGIN:STANDARD\r\nDTSTART:16010101T020000\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0000\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T010000\r\nTZOFFSETFROM:+0000\r\nTZOFFSETTO:+0100\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nORGANIZER;CN=ISG Group:MAILTO:ISGGroup@sanger.ac.uk\r\nDESCRIPTION;LANGUAGE=en-US:\\n\r\nUID:040000008200E00074C5B7101A82E00800000000110067B4305BD401000000000000000\r\n 010000000AB844328F926A2439B0F75B32ED705D5\r\nSUMMARY;LANGUAGE=en-US:hc7 out\r\nDTSTART;VALUE=DATE:20181005\r\nDTEND;VALUE=DATE:20181006\r\nCLASS:PUBLIC\r\nPRIORITY:5\r\nDTSTAMP:20181003T154944Z\r\nTRANSP:TRANSPARENT\r\nSTATUS:CONFIRMED\r\nSEQUENCE:0\r\nLOCATION;LANGUAGE=en-US:\r\nX-MICROSOFT-CDO-APPT-SEQUENCE:0\r\nX-MICROSOFT-CDO-OWNERAPPTID:2116689169\r\nX-MICROSOFT-CDO-BUSYSTATUS:FREE\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nX-MICROSOFT-CDO-ALLDAYEVENT:TRUE\r\nX-MICROSOFT-CDO-IMPORTANCE:1\r\nX-MICROSOFT-CDO-INSTTYPE:0\r\nX-MICROSOFT-DISALLOW-COUNTER:FALSE\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n', id='AAMkADFjMGFhNWJlLWQxZGUtNDQ3Zi05YzUwLTY0MWJjODYyYzc0ZgBGAAAAAAAJz/egb2EmRZbzqYuY2W71BwAc1qYkGnzFS4z8QVJDeETkAAAAAAENAAAc1qYkGnzFS4z8QVJDeETkAAAAAA4YAAA=', changekey='DwAAABYAAAAc1qYkGnzFS4z8QVJDeETkAAAAABAY', parent_folder_id=ParentFolderId(id='AAMkADFjMGFhNWJlLWQxZGUtNDQ3Zi05YzUwLTY0MWJjODYyYzc0ZgAuAAAAAAAJz/egb2EmRZbzqYuY2W71AQAc1qYkGnzFS4z8QVJDeETkAAAAAAENAAA=', changekey='AQAAAA=='), item_class='IPM.Appointment', subject='hc7 out', sensitivity='Normal', text_body='\r\n', body='<html>\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n<style type="text/css" style="display:none;"><!-- P {margin-top:0;margin-bottom:0;} --></style>\r\n</head>\r\n<body dir="ltr">\r\n<div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Helvetica,sans-serif;" dir="ltr">\r\n<p><br>\r\n</p>\r\n</div>\r\n</body>\r\n</html>\r\n', attachments=[], datetime_received=EWSDateTime(2018, 10, 3, 15, 49, 44, tzinfo=<UTC>), size=4949, importance='Normal', is_submitted=False, is_draft=False, is_from_me=False, is_resend=False, is_unmodified=False, datetime_sent=EWSDateTime(2018, 10, 3, 15, 49, 44, tzinfo=<UTC>), datetime_created=EWSDateTime(2018, 10, 3, 15, 49, 44, tzinfo=<UTC>), reminder_due_by=EWSDateTime(2018, 10, 4, 23, 0, tzinfo=<UTC>), reminder_is_set=False, reminder_minutes_before_start=15, has_attachments=False, global_object_id=b'\x04\x00\x00\x00\x82\x00\xe0\x00t\xc5\xb7\x10\x1a\x82\xe0\x08\x00\x00\x00\x00\x11\x00g\xb40[\xd4\x01\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\xab\x84C(\xf9&\xa2C\x9b\x0fu\xb3.\xd7\x05\xd5', culture='en-US', effective_rights=EffectiveRights(create_associated=False, create_contents=False, create_hierarchy=False, delete=True, modify=True, read=True, view_private_items=False), last_modified_name='Helen Cousins', last_modified_time=EWSDateTime(2018, 10, 3, 15, 49, 44, tzinfo=<UTC>), is_associated=False, web_client_read_form_query_string='https://email.sanger.ac.uk/owa?itemid=AAMkADFjMGFhNWJlLWQxZGUtNDQ3Zi05YzUwLTY0MWJjODYyYzc0ZgBGAAAAAAAJz%2Fegb2EmRZbzqYuY2W71BwAc1qYkGnzFS4z8QVJDeETkAAAAAAENAAAc1qYkGnzFS4z8QVJDeETkAAAAAA4YAAA%3D&exvsurl=1&path=/calendar/item', conversation_id=ConversationId(id='AAQkADFjMGFhNWJlLWQxZGUtNDQ3Zi05YzUwLTY0MWJjODYyYzc0ZgAQAI9K1VH4tr9KgdutMeB20VE=', changekey=None), uid='040000008200E00074C5B7101A82E00800000000110067B4305BD401000000000000000010000000AB844328F926A2439B0F75B32ED705D5', start=EWSDateTime(2018, 10, 4, 23, 0, tzinfo=<UTC>), end=EWSDateTime(2018, 10, 5, 23, 0, tzinfo=<UTC>), is_all_day=True, legacy_free_busy_status='Free', is_meeting=False, is_cancelled=False, is_recurring=False, meeting_request_was_sent=False, is_response_requested=False, type='Single', my_response_type='Organizer', organizer=Mailbox(name='ISG Group', email_address='ISGGroup@sanger.ac.uk', routing_type='SMTP', mailbox_type='Mailbox', item_id=None), conflicting_meeting_count=3, adjacent_meeting_count=1, duration='P1D', appointment_sequence_number=0, _start_timezone=<StaticTzInfo 'GMT'>, _end_timezone=<StaticTzInfo 'GMT'>, allow_new_time_proposal=True, is_online_meeting=False)
```

**Comment by ecederstrand** [comment]
`item_id` shouldn't change when you update an item. Only the `changekey` value will change, at least if you use the `UpdateItem` service. It's possible that there are situations where the `UID` is stable even though the `item_id` changes, but I haven't heard about it.

**Comment by mcv21** [comment]
Ah, sorry, I think I mis-read "The ItemId element contains the unique identifier and change key of an item in the Exchange store." in the [MS docs](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/itemid), where I assume that in fact the thing that is exposed through exchangelib is the "id" element within ItemID?. Apologies for the noise .

**Comment by ecederstrand** [comment]
In EWS, an `ItemID` element consists of an ID and possibly a changekey. We flatten that in exchangelib to the `item_id` and `changekey` fields on Item objects (`id` and `changekey` in the latest release), to avoid the more clunky `some_item.item_id.id` accessor. So we keep both, but only the changekey is updated when an item is updated.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's anything we can improve.
