### ISSUE TITLE
can not import exchangelib

### ISSUE THREAD

**Issue by voostar** [ecederstrand/exchangelib#5]
>>> import exchangelib     
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/__init__.py", line 2, in <module>
    from .account import Account
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/account.py", line 3, in <module>
    from .autodiscover import discover
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/autodiscover.py", line 26, in <module>
    from .version import API_VERSIONS
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/version.py", line 8, in <module>
    from .transport import TNS, SOAPNS, dummy_xml, get_auth_instance
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/transport.py", line 10, in <module>
    from .util import create_element, add_xml_child, is_xml, get_redirect_url
  File "/usr/local/lib/python3.2/dist-packages/exchangelib/util.py", line 5, in <module>
    from threading import get_ident
ImportError: cannot import name get_ident

**Comment by ecederstrand** [comment]
`get_ident()` is new in Python 3.3: https://docs.python.org/3/library/threading.html#threading.get_ident

You'll need to upgrade to at least Python 3.3.
