### ISSUE TITLE
 exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.

### ISSUE THREAD

**Issue by AvitalL** [ecederstrand/exchangelib#501]
Hi :)

I am trying to connect to a mailbox with a piece of code that worked in multiple exchange environments, but is failing on an outlook 2010 SP2. It seems something with the schema the package is sending to the server. Could you please help me solve this issue?

Thanks!

The exception:
`exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.`

The code snippet (failing on the last line):
```python
creds = ServiceAccount(username=r'{0}\{1}'.format(domain, username), password=password)
config = Configuration(server=exchange_server_ip, credentials=credentials)
account = Account(primary_smtp_address=user_mail_address, config=config, autodiscover=False, access_type=DELEGATE)
```

Here are the debug logs I collected:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): localhost:8443
DEBUG:urllib3.connectionpool:https://localhost:8443 "GET /api/external/v1/sdk/GetProxySettings?format=snake HTTP/1.1" 200 136
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): localhost:8443
DEBUG:urllib3.connectionpool:https://localhost:8443 "GET /api/external/v1/sdk/configuration/Exchange?format=snake HTTP/1.1" 200 173
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '(u'https://10.7.3.228/EWS/Exchange.asmx', ServiceAccount('hmcorp.local\\saCISSMTP', u'********'))'
DEBUG:exchangelib.transport:Getting service auth type for https://10.7.3.228/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Requesting <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>hmcorp.local\saCISSMTP</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope> from https://10.7.3.228/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.7.3.228:443
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'Content-Length': '465', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.19.1', 'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8'}
DEBUG:exchangelib.transport:Response headers: {'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': 'exchangecookie=7d792b1badbd41109aff920f232c0644; expires=Fri, 18-Oct-2019 15:40:46 GMT; path=/; HttpOnly', 'Server': 'Microsoft-IIS/7.5', 'Date': 'Thu, 18 Oct 2018 15:40:45 GMT', 'WWW-Authenticate': 'Negotiate, NTLM'}
DEBUG:exchangelib.transport:Auth type is NTLM
DEBUG:exchangelib.protocol:Server 10.7.3.228: Created session 19495
DEBUG:exchangelib.protocol:Server 10.7.3.228: Created session 27837
DEBUG:exchangelib.protocol:Server 10.7.3.228: Created session 22416
DEBUG:exchangelib.protocol:Server 10.7.3.228: Created session 21824
DEBUG:exchangelib.transport:Getting docs auth type for https://10.7.3.228/EWS/types.xsd
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.7.3.228:443
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'Connection': 'keep-alive', 'Content-Type': u'text/xml; charset=utf-8', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.19.1'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Thu, 18 Oct 2018 15:40:45 GMT', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET', 'WWW-Authenticate': 'Negotiate, NTLM', 'Server': 'Microsoft-IIS/7.5'}
DEBUG:exchangelib.version:Asking server for version info
DEBUG:exchangelib.version:Getting https://10.7.3.228/EWS/types.xsd with auth type HttpNtlmAuth
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.7.3.228:443
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "GET /EWS/types.xsd HTTP/1.1" 200 24146
DEBUG:exchangelib.version:Request headers: {'Authorization': u'NTLM TlRMTVNTUAADAAAAGAAYAG0AAADyAPIAhQAAAAwADABYAAAACQAJAGQAAAAAAAAAbQAAABAAEAB3AQAANoKJ4gYBsR0AAAAP3TMSei8JmCjfc1WHfPGmqUhNQ09SUC5MT0NBTHNhQ0lTU01UUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANf6uDaSwBdOMahjhDFAI3YBAQAAAAAAABmmxu/4ZtQBYpajs3Ri6YgAAAAAAgAMAEgATQBDAE8AUgBQAAEAFgBTAFAASQBWAEUAWABDAEEAUwAwADEABAAYAGgAbQBjAG8AcgBwAC4AbABvAGMAYQBsAAMAMABTAFAASQBWAEUAWABDAEEAUwAwADEALgBoAG0AYwBvAHIAcAAuAGwAbwBjAGEAbAAFABgAaABtAGMAbwByAHAALgBsAG8AYwBhAGwABwAIABmmxu/4ZtQBBgAEAAIAAAAKABAAq9RJop8xJG0BD4CQXHoFygAAAAAAAAAAlHGx7IijYN7Hx76sczCooQ==', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.19.1'}
DEBUG:exchangelib.version:Response code: 200
DEBUG:exchangelib.version:Response headers: {'Content-Length': '24146', 'Content-Encoding': 'gzip', 'Accept-Ranges': 'bytes', 'X-Powered-By': 'ASP.NET', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/7.5', 'Last-Modified': 'Wed, 06 Feb 2013 04:00:32 GMT', 'ETag': '"0702f821e4ce1:0"', 'Date': 'Thu, 18 Oct 2018 15:40:45 GMT', 'Content-Type': 'text/xml', 'Persistent-Auth': 'true'}
DEBUG:exchangelib.version:Shortname according to https://10.7.3.228/EWS/types.xsd: Exchange2010_SP2
DEBUG:exchangelib.protocol:Server 10.7.3.228: Waiting for session
DEBUG:exchangelib.protocol:Server 10.7.3.228: Got session 21824
DEBUG:exchangelib.util:Session 21824 thread 5140: retry 0 timeout 120 POST'ing to https://10.7.3.228/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.7.3.228:443
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 21824
Thread: 5140
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000000003610EF0>
URL: https://10.7.3.228/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.NoVerifyHTTPAdapter object at 0x0000000003610DD8>
Allow redirects: False
Response time: 0.0820000171661
Status code: 200
Request headers: {'Content-Length': '469', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.19.1', 'Connection': 'Keep-Alive', 'Cookie': 'exchangecookie=4462d8a16d4841ffa3bc3374b4de85d0; expires=Fri, 18-Oct-2019 15:40:46 GMT; path=/; HttpOnly', 'Content-Type': u'text/xml; charset=utf-8', 'Authorization': u'NTLM TlRMTVNTUAADAAAAGAAYAG0AAADyAPIAhQAAAAwADABYAAAACQAJAGQAAAAAAAAAbQAAABAAEAB3AQAANoKJ4gYBsR0AAAAPKGvoMoNf8Jgu4qPW+SbuYUhNQ09SUC5MT0NBTHNhQ0lTU01UUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAONa3wkNe3ncVuA+WCyfY2IBAQAAAAAAAHYV3O/4ZtQBJMXQV6ZzNGsAAAAAAgAMAEgATQBDAE8AUgBQAAEAFgBTAFAASQBWAEUAWABDAEEAUwAwADEABAAYAGgAbQBjAG8AcgBwAC4AbABvAGMAYQBsAAMAMABTAFAASQBWAEUAWABDAEEAUwAwADEALgBoAG0AYwBvAHIAcAAuAGwAbwBjAGEAbAAFABgAaABtAGMAbwByAHAALgBsAG8AYwBhAGwABwAIAHYV3O/4ZtQBBgAEAAIAAAAKABAAq9RJop8xJG0BD4CQXHoFygAAAAAAAAAAFiXQl9vPzbU4koyVppsYew=='}
Response headers: {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'X-AspNet-Version': '2.0.50727', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5', 'Cache-Control': 'private', 'Date': 'Thu, 18 Oct 2018 15:40:45 GMT', 'Content-Type': 'text/xml; charset=utf-8', 'Persistent-Auth': 'true'}
Request data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>hmcorp.local\saCISSMTP</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="415" MinorBuildNumber="0" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:ResolveNamesResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:ResolveNamesResponseMessage ResponseClass="Error"><m:MessageText>No results were found.</m:MessageText><m:ResponseCode>ErrorNameResolutionNoResults</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey></m:ResolveNamesResponseMessage></m:ResponseMessages></m:ResolveNamesResponse></s:Body></s:Envelope>

DEBUG:exchangelib.util:Session 21824 thread 5140: Useful response from https://10.7.3.228/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server 10.7.3.228: Releasing session 21824
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account None
DEBUG:exchangelib.services:Adding missing build number Exchange2010_SP2
DEBUG:exchangelib.services:Getting folder Root (root)
DEBUG:exchangelib.protocol:Server 10.7.3.228: Waiting for session
DEBUG:exchangelib.protocol:Server 10.7.3.228: Got session 21824
DEBUG:exchangelib.util:Session 21824 thread 5140: retry 0 timeout 120 POST'ing to https://10.7.3.228/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://10.7.3.228:443 "POST /EWS/Exchange.asmx HTTP/1.1" 500 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 21824
Thread: 5140
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000000003610EF0>
URL: https://10.7.3.228/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.NoVerifyHTTPAdapter object at 0x0000000003610DD8>
Allow redirects: False
Response time: 0.00699996948242
Status code: 500
Request headers: {'Content-Length': '1115', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.19.1', 'Connection': 'Keep-Alive', 'Cookie': 'exchangecookie=4462d8a16d4841ffa3bc3374b4de85d0', 'Content-Type': u'text/xml; charset=utf-8'}
Response headers: {'X-AspNet-Version': '2.0.50727', 'Transfer-Encoding': 'chunked', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5', 'Cache-Control': 'private', 'Date': 'Thu, 18 Oct 2018 15:40:45 GMT', 'Content-Type': 'text/xml; charset=utf-8'}
Request data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /><t:TimeZoneContext><t:TimeZoneDefinition Id="UTC" /></t:TimeZoneContext></s:Header><s:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount" /><t:FieldURI FieldURI="folder:EffectiveRights" /><t:FieldURI FieldURI="folder:FolderClass" /><t:FieldURI FieldURI="folder:DisplayName" /><t:FieldURI FieldURI="folder:ParentFolderId" /><t:FieldURI FieldURI="folder:TotalCount" /><t:FieldURI FieldURI="folder:UnreadCount" /></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>saCISSMTP@hmcorp.local</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType><t:RoutingType>SMTP</t:RoutingType></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorSchemaValidation</faultcode><faultstring xml:lang="en-US">The request failed schema validation: The element 'Mailbox' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'RoutingType' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements expected: 'ItemId' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorSchemaValidation</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request failed schema validation.</e:Message><t:MessageXml xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><t:LineNumber>1</t:LineNumber><t:LinePosition>994</t:LinePosition><t:Violation>The element 'Mailbox' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'RoutingType' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements expected: 'ItemId' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.</t:Violation></t:MessageXml></detail></s:Fault></s:Body></s:Envelope>

DEBUG:exchangelib.util:Got status code 500 but trying to parse content anyway
DEBUG:exchangelib.util:Session 21824 thread 5140: Useful response from https://10.7.3.228/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server 10.7.3.228: Releasing session 21824
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account saCISSMTP@hmcorp.local
WARNING:exchangelib.services:EWS https://10.7.3.228/EWS/Exchange.asmx, account saCISSMTP@hmcorp.local: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 76, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 148, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 192, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 215, in _raise_soap_errors
    raise vars(errors)[code](msg)
ErrorSchemaValidation: The request failed schema validation.
```

**Comment by ecederstrand** [comment]
If you look at the last XML response:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <s:Fault>
            <faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorSchemaValidation
            </faultcode>
            <faultstring xml:lang="en-US">The request failed schema validation: The element 'Mailbox' in namespace
                'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'RoutingType' in
                namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements
                expected: 'ItemId' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.
            </faultstring>
            <detail>
                <e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">
                    ErrorSchemaValidation
                </e:ResponseCode>
                <e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request failed
                    schema validation.
                </e:Message>
                <t:MessageXml xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
                    <t:LineNumber>1</t:LineNumber>
                    <t:LinePosition>994</t:LinePosition>
                    <t:Violation>The element 'Mailbox' in namespace
                        'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element
                        'RoutingType' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of
                        possible elements expected: 'ItemId' in namespace
                        'http://schemas.microsoft.com/exchange/services/2006/types'.
                    </t:Violation>
                </t:MessageXml>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```

then the error becomes more apparent. This specific server sores not like the `RoutingType` child element of a `Mailbox` element.

In the documentation for Exchange 2010, it's mentioned as supported: https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa565036(v%3dexchg.140) so this is  bit surprising and possibly a bug that is only present on certain builds.

You could try to mark the `routing_type` field as not valid for the server you are connecting to. Something like this:

```python
from exchangelib.properties import Mailbox
from exchangelib.version import EXCHANGE_2013
Mailbox.get_field_by_fieldname('routing_type').supported_from = EXCHANGE_2013
```

**Comment by AvitalL** [comment]
Hi :)

Thanks for the quick response. I will try you suggestion and update if I will still have issues.

**Comment by AvitalL** [comment]
Verified the solution - it works as a charm. Thanks!
