### ISSUE TITLE
Synapse not able to connect with outlook.com OR outlook.office.com

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [ecederstrand/exchangelib#503]
I am having an issue and any help would be really appreciated. I have the TheHive, Synapse on Ubuntu 16.04 VM.
The mail is "shehreyar.ahmed@dig8labs.com" and is registered with outlook.office.com, no AD. 

My EwsConnecter.py file looks like: 

#!/usr/bin/env python3
# -*- coding: utf8 -*-

import logging
from exchangelib import DELEGATE, Account, Credentials, Configuration, NTLM

class EwsConnector:
    'Exchange web service connector'

    def __init__(self, cfg):
        self.logger = logging.getLogger('workflows.' + __name__)
        self.cfg = cfg
        self.account = self.getAccount()

    def getAccount(self):
        self.logger.info('%s. getAccount starts', __name__)

        try:
            username = self.cfg.get('EWS', 'username')
            password = self.cfg.get('EWS', 'password')
            credentials = Credentials(username='shehreyar.ahmed@dig8labs.com', password='********')
            
            ews_server = self.cfg.get('EWS', 'server')
            smtp_address = self.cfg.get('EWS', 'smtp_address')
            
            config = Configuration(server='outlook.office.com',
                credentials=credentials,
                auth_type=NTLM)
                #auth_type=NTLM,
                #verify_ssl='/home/dc/exchange.crt')

            account = Account(primary_smtp_address='shehreyar.ahmed@dig8labs.com',
                config=config, autodiscover=False, access_type=DELEGATE)

            return account
        except Exception as e:
            self.logger.error('Failed to get account', exc_info=True)
            raise

    def scan(self, folderName):
        #returns a query set of unread emails
        #<class 'exchangelib.queryset.QuerySet'>

        self.logger.info('%s.scan starts', __name__)

        folder = None
        try:
            #get the folder first
            if folderName == 'inbox':
                folder = self.account.inbox
            else:
                for f in self.account.root.walk():
                    if f.name == folderName:
                        folder = f

            if folder is None:
                raise ValueError('folder %s not found', folderName)

            unread = folder.filter(is_read = False)

            return unread

        except Exception as e:
            self.logger.error('Failed to get unread emails', __name__, exc_info = True)
            raise

    def markAsRead(self, msg):
        self.logger.info('%s.markAsRead starts', __name__)
        msg.is_read = True
        msg.save()
        return msg

My synapse.conf file: 

[api]
debug:False
host: 0.0.0.0
port:5000
threaded:True

[TheHive]
url:http://192.168.132.129:9000
user:synapse
api_key:Zu14re2pt7t****AVIq76wIrhuu3eGx8P

[EWS]
#ip or domain to EWS server
server: outlook.office.com
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
username :shehreyar.ahmed@dig8labs.com
password:*******
smtp_address:shehreyar.ahmed@dig8labs.com
folder_name:TheHive

My log file after curl request to Synapse: 

2018-10-18 21:49:58,730 :: INFO :: workflows.Ews2Case.connectEws starts
2018-10-18 21:49:58,731 :: INFO :: common.common.getConf starts
2018-10-18 21:49:58,734 :: INFO :: objects.EwsConnector. getAccount starts
2018-10-18 21:49:58,735 :: ERROR :: Failed to get account
Traceback (most recent call last):
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 181, in __call__
    raise e
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 209, in __init__
    name=self.credentials.username)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 156, in get_service_authtype
    raise TransportError('Failed to get auth type from service')
exchangelib.errors.TransportError: Failed to get auth type from service
2018-10-18 21:49:58,737 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 159, in __call__
    raise protocol
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 181, in __call__
    raise e
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 209, in __init__
    name=self.credentials.username)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 156, in get_service_authtype
    raise TransportError('Failed to get auth type from service')
exchangelib.errors.TransportError: Failed to get auth type from service 

 "Success=False" did not go away in any of my tries

I also have used the simple free hotmail account as mentioned in the Thehive user guide. With and without configuration of web exchange certificates.

**Comment by shehreyarahmedkohati** [comment]
With default settings, not changing the config files. I got errors regarding wrong username and password.

**Comment by shehreyarahmedkohati** [comment]
@ecederstrand would you please look into this!

**Comment by ecederstrand** [comment]
Please have a look at the suggestion in #502

**Comment by shehreyarahmedkohati** [comment]
@ecederstrand thanks its resolved!
