### ISSUE TITLE
Issue with Timezones?

### ISSUE THREAD

**Issue by jslay88** [ecederstrand/exchangelib#51]
Fresh install on an Ubuntu and Windows box. Keep getting the same issue. 2.7 and 3.5

Tried UTC, US/Pacific, Mountain Standard Time

```
Traceback (most recent call last):
  File "exch.py", line 1, in <module>
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, Mailbox, Q
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/__init__.py", line 1, in <module>
    from .account import Account
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/account.py", line 15, in <module>
    from .folders import Root, Calendar, DeletedItems, Drafts, Inbox, Outbox, SentItems, JunkEmail, Tasks, Contacts, \
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/folders.py", line 20, in <module>
    from .ewsdatetime import EWSDateTime, UTC, UTC_NOW
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/ewsdatetime.py", line 103
    raise ValueError('PYTZ_TO_MS_MAP value %s must be a key in MS_TIMEZONE_DEFINITIONS' % self_cls.ms_id) from e
                                                                                                             ^
SyntaxError: invalid syntax
```

**Comment by ecederstrand** [comment]
Python 2.7 is broken ATM. I'm fixing fallout from the Python 2.7 backport earlier today and will release a new version when it's fixed.

**Comment by jslay88** [comment]
Appreciate it. I wish I knew more, I'd offer to help.

**Comment by ecederstrand** [comment]
Version 1.7.4 on PyPI should fix the issue for you.

**Comment by jslay88** [comment]
Now receiving

```
Traceback (most recent call last):
  File "exch.py", line 21, in <module>
    autodiscover=True, access_type=DELEGATE)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/account.py", line 44, in __init__
    assert isinstance(self.locale, string_types)
AssertionError
```

**Comment by ecederstrand** [comment]
Looks like a bug in the new Python2 support. Try setting account locale explicitly untis I can commit a fix, e.g.:

```python
a = Account(..., locale='en_US')
```

**Comment by jslay88** [comment]
Code

```
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, Mailbox, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, HTMLBody

year, month, day = 2016, 12, 16
tz = EWSTimeZone.timezone('UTC')

calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
    ))

credentials = Credentials(username='domain\\user', password='password')

account = Account(primary_smtp_address='me@company.com', credentials=credentials,
                  autodiscover=True, access_type=DELEGATE, locale='en_US')

res = account.calendar.bulk_create(calendar_items)
print(res)
```

Error
```
Traceback (most recent call last):
  File "exch.py", line 23, in <module>
    res = account.calendar.bulk_create(calendar_items)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib-1.7.4-py2.7.egg/exchangelib/folders.py", line 2109, in bulk_create
    return self.account.bulk_create(folder=self, *args, **kwargs)
TypeError: bulk_create() got multiple values for keyword argument 'folder'
```

**Comment by ecederstrand** [comment]
Python2 is apparently more picky about args and kwargs than Python3. Try this:

```
res = account.calendar.bulk_create(items=calendar_items)
```

**Comment by jslay88** [comment]
Nice.

Check your email if you don't mind.
