### ISSUE TITLE
Improve error handling on failing GetAttachment call

### ISSUE THREAD

**Issue by Algo-Data** [ecederstrand/exchangelib#539]
I noticed, that it is not possible to read out the content of a **FileAttachment** for me.

Informations:
**Echangelib Version: 1.12.1**
**Exchang Server: 2013_SP1**

Error Message received: `The element to be streamed from was not found`

Code:
```python
    def saveMailAttachments(self, mail, tag):
       try:
           for attachment in mail.attachments:
               try:
                   print("########CONTENT##########")
                   if isinstance(attachment, FileAttachment):
                       print("1")
                       local_path = os.path.join("tmp", attachment.name)
                       print("2")
                       with open(local_path, 'wb') as f, attachment.fp as fp:
                           print("3")
                           buffer = fp.read()
                           print("4")
                           while buffer:
                               print("5")
                               f.write(buffer)
                               print("6")
                               buffer = fp.read()
                               print("7")
 
                       print('Successfully saved File')
 
               except Exception as e:
                   print(e)
```

Output:
```
########CONTENT##########
1
2
3
The element to be streamed from was not found
```

`Also the same problem appears with attachment.content`

XML-Response:
```xml
Response data: b'<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="1044" MinorBuildNumber="21"
                             Version="V2_22" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <m:GetItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                           xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:GetItemResponseMessage ResponseClass="Success">
                    <m:ResponseCode>NoError</m:ResponseCode>
                    <m:Items>
                        <t:Message>
                            <t:MimeContent CharacterSet="UTF-8">shortened the content</t:MimeContent>
                            <t:ItemId
                                    Id="AAMkADg1NTkwMDc0LWJkMmUtNDkwNS1hOGM4LThhMGVmOTMzNjljOQBGAAAAAABEpW5IUC1oSKNdhm8J3vFTBwDuQ+EthXlrQaucasE1PLtSAAAAAAEMAADuQ+EthXlrQaucasE1PLtSAAAAAAJyAAA="
                                    ChangeKey="censored"/>
                            <t:ParentFolderId
                                    Id="AAMkADg1NTkwMDc0LWJkMmUtNDkwNS1hOGM4LThhMGVmOTMzNjljOQAuAAAAAABEpW5IUC1oSKNdhm8J3vFTAQDuQ+EthXlrQaucasE1PLtSAAAAAAEMAAA="
                                    ChangeKey="AQAAAA=="/>
                            <t:ItemClass>IPM.Note</t:ItemClass>
```

Feel free to contact me if u need anything else

Kind regards

**Comment by ecederstrand** [comment]
First, `fp.read()` with no arguments will get the entire content of the attachment. Use `fp.read(some_bufsize)` if you actually want buffered reads.

Second, we need the XML response from `GetAttachments` call, not the `GetItem` call.

Finally, please post the entire stack trace. Just remove the `try/except` and run your code again.

**Comment by Algo-Data** [comment]
### Without buffer size:
```
Request data: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/type>
<s:Header>
	<t:RequestServerVersion Version="Exchange2013_SP1"/>
	<t:TimeZoneContext><t:TimeZoneDefinition Id="W. Europe Standard Time"/></t:TimeZoneContext>
</s:Header>
<s:Body>
<m:GetAttachment>
<m:AttachmentIds>
	<t:AttachmentId Id="AAMkADg1NTkwMDc0LWJkMmUtNDkwNS1hOGM4LThhMGVmOTMzNjljOQBGAAAAAABEpW5IUC1oSKNdhm8J3vFTBwDuQ+EthXlrQaucasE1PLtSAAAAAAEMAADuQ+EthXlrQaucasE1PLtSAAAAAAJ5AAABEgAQAKcFP6713w1EhE4jjpDo5ho="/>
</m:AttachmentIds>
</m:GetAttachment>
</s:Body>
</s:Envelope>'
Response data: [STREAMING]
```


```
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 46, in main
    Exchange.saveMailAttachments(mail, tag)
  File "c:\workspace\xxx\www\xxx\xxx\ewsapi\__init__.py", line 78, in saveMailAttachments
    buffer = fp.read()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\attachments.py", line 272, in read
    return b''.join(self._stream)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\util.py", line 300, in parse
    raise ElementNotFound('The element to be streamed from was not found', data=collected_data)
exchangelib.util.ElementNotFound: The element to be streamed from was not found
```

### Buffer size: 1024
```
Request data: b
<?xml version=\'1.0\' encoding=\'utf-8\'?>\n
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header>
<t:RequestServerVersion Version="Exchange2013_SP1"/>
<t:TimeZoneContext>
<t:TimeZoneDefinition Id="W. Europe Standard Time"/>
</t:TimeZoneContext>
</s:Header>
<s:Body>
<m:GetAttachment>
<m:AttachmentIds>
<t:AttachmentId Id="AAMkADg1NTkwMDc0LWJkMmUtNDkwNS1hOGM4LThhMGVmOTMzNjljOQBGAAAAAABEpW5IUC1oSKNdhm8J3vFTBwDuQ+EthXlrQaucasE1PLtSAAAAAAEMAADuQ+EthXlrQaucasE1PLtSAAAAAAJ8AAABEgAQAKcFP6713w1EhE4jjpDo5ho="/></m:AttachmentIds>
</m:GetAttachment>
</s:Body>
</s:Envelope>'
Response data: [STREAMING]
```

```
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 46, in main
    Exchange.saveMailAttachments(mail, tag)
  File "C:\workspace\xxx\www\xxx\xxx\ewsapi\__init__.py", line 78, in saveMailAttachments
    buffer = fp.read(1024)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\attachments.py", line 280, in read
    next_chunk = next(self._stream)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\util.py", line 300, in parse
    raise ElementNotFound('The element to be streamed from was not found', data=collected_data)
exchangelib.util.ElementNotFound: The element to be streamed from was not found
```

Thanks in advance

**Comment by ecederstrand** [comment]
Ok. I forgot this is a streaming response, so the `Response data:` part of the log message doesn't contain the response data.

You need to print the `data` attribute of the exception instance to get the data that was streamed thus far:

```python
import exchangelib.util
try:
    # Your code here
except exchangelib.util.ElementNotFound:
    print(e)
    print(e.data)
```

**Comment by Algo-Data** [comment]
Here we go
```
########CONTENT##########
1
2
3
The element to be streamed from was not found
[60, 63, 120, 109, 108, 32, 118, 101, 114, 115, 105, 111, 110, 61, 34, 49, 46, 48, 34, 32, 101, 110, 99, 111, 100, 105, 110, 103, 61, 34, 117, 116, 102, 45, 56, 34, 63, 62, 60, 115, 58, 69, 110, 118, 101, 108, 111, 112, 101, 32, 120, 109, 108, 110, 115, 58, 115, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 99, 104, 101, 109, 97, 115, 46, 120, 109, 108, 115, 111, 97, 112, 46, 111, 114, 103, 47, 115, 111, 97, 112, 47, 101, 110, 118, 101, 108, 111, 112, 101, 47, 34, 62, 60, 115, 58, 72, 101, 97, 100, 101, 114, 62, 60, 104, 58, 83, 101, 114, 118, 101, 114, 86, 101, 114, 115, 105, 111, 110, 73, 110, 102, 111, 32, 77, 97, 106, 111, 114, 86, 101, 114, 115, 105, 111, 110, 61, 34, 49, 53, 34, 32, 77, 105, 110, 111, 114, 86, 101, 114, 115, 105, 111, 110, 61, 34, 48, 34, 32, 77, 97, 106, 111, 114, 66, 117, 105, 108, 100, 78, 117, 109, 98, 101, 114, 61, 34, 49, 48, 52, 52, 34, 32, 77, 105, 110, 111, 114, 66, 117, 105, 108, 100, 78, 117, 109, 98, 101, 114, 61, 34, 50, 49, 34, 32, 86, 101, 114, 115, 105, 111, 110, 61, 34, 86, 50, 95, 50, 50, 34, 32, 120, 109, 108, 110, 115, 58, 104, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 99, 104, 101, 109, 97, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 120, 99, 104, 97, 110, 103, 101, 47, 115, 101, 114, 118, 105, 99, 101, 115, 47, 50, 48, 48, 54, 47, 116, 121, 112, 101, 115, 34, 32, 120, 109, 108, 110, 115, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 99, 104, 101, 109, 97, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 120, 99, 104, 97, 110, 103, 101, 47, 115, 101, 114, 118, 105, 99, 101, 115, 47, 50, 48, 48, 54, 47, 116, 121, 112, 101, 115, 34, 32, 120, 109, 108, 110, 115, 58, 120, 115, 100, 61, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 49, 47, 88, 77, 76, 83, 99, 104, 101, 109, 97, 34, 32, 120, 109, 108, 110, 115, 58, 120, 115, 105, 61, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 49, 47, 88, 77, 76, 83, 99, 104, 101, 109, 97, 45, 105, 110, 115, 116, 97, 110, 99, 101, 34, 47, 62, 60, 47, 115, 58, 72, 101, 97, 100, 101, 114, 62, 60, 115, 58, 66, 111, 100, 121, 32, 120, 109, 108, 110, 115, 58, 120, 115, 105, 61, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 49, 47, 88, 77, 76, 83, 99, 104, 101, 109, 97, 45, 105, 110, 115, 116, 97, 110, 99, 101, 34, 32, 120, 109, 108, 110, 115, 58, 120, 115, 100, 61, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 49, 47, 88, 77, 76, 83, 99, 104, 101, 109, 97, 34, 62, 60, 109, 58, 71, 101, 116, 65, 116, 116, 97, 99, 104, 109, 101, 110, 116, 82, 101, 115, 112, 111, 110, 115, 101, 32, 120, 109, 108, 110, 115, 58, 109, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 99, 104, 101, 109, 97, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 120, 99, 104, 97, 110, 103, 101, 47, 115, 101, 114, 118, 105, 99, 101, 115, 47, 50, 48, 48, 54, 47, 109, 101, 115, 115, 97, 103, 101, 115, 34, 32, 120, 109, 108, 110, 115, 58, 116, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 99, 104, 101, 109, 97, 115, 46, 109, 105, 99, 114, 111, 115, 111, 102, 116, 46, 99, 111, 109, 47, 101, 120, 99, 104, 97, 110, 103, 101, 47, 115, 101, 114, 118, 105, 99, 101, 115, 47, 50, 48, 48, 54, 47, 116, 121, 112, 101, 115, 34, 62, 60, 109, 58, 82, 101, 115, 112, 111, 110, 115, 101, 77, 101, 115, 115, 97, 103, 101, 115, 62, 60, 109, 58, 71, 101, 116, 65, 116, 116, 97, 99, 104, 109, 101, 110, 116, 82, 101, 115, 112, 111, 110, 115, 101, 77, 101, 115, 115, 97, 103, 101, 32, 82, 101, 115, 112, 111, 110, 115, 101, 67, 108, 97, 115, 115, 61, 34, 69, 114, 114, 111, 114, 34, 62, 60, 109, 58, 77, 101, 115, 115, 97, 103, 101, 84, 101, 120, 116, 62, 84, 104, 101, 32, 115, 112, 101, 99, 105, 102, 105, 101, 100, 32, 111, 98, 106, 101, 99, 116, 32, 119, 97, 115, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100, 32, 105, 110, 32, 116, 104, 101, 32, 115, 116, 111, 114, 101, 46, 60, 47, 109, 58, 77, 101, 115, 115, 97, 103, 101, 84, 101, 120, 116, 62, 60, 109, 58, 82, 101, 115, 112, 111, 110, 115, 101, 67, 111, 100, 101, 62, 69, 114, 114, 111, 114, 73, 116, 101, 109, 78, 111, 116, 70, 111, 117, 110, 100, 60, 47, 109, 58, 82, 101, 115, 112, 111, 110, 115, 101, 67, 111, 100, 101, 62, 60, 109, 58, 68, 101, 115, 99, 114, 105, 112, 116, 105, 118, 101, 76, 105, 110, 107, 75, 101, 121, 62, 48, 60, 47, 109, 58, 68, 101, 115, 99, 114, 105, 112, 116, 105, 118, 101, 76, 105, 110, 107, 75, 101, 121, 62, 60, 109, 58, 65, 116, 116, 97, 99, 104, 109, 101, 110, 116, 115, 47, 62, 60, 47, 109, 58, 71, 101, 116, 65, 116, 116, 97, 99, 104, 109, 101, 110, 116, 82, 101, 115, 112, 111, 110, 115, 101, 77, 101, 115, 115, 97, 103, 101, 62, 60, 47, 109, 58, 82, 101, 115, 112, 111, 110, 115, 101, 77, 101, 115, 115, 97, 103, 101, 115, 62, 60, 47, 109, 58, 71, 101, 116, 65, 116, 116, 97, 99, 104, 109, 101, 110, 116, 82, 101, 115, 112, 111, 110, 115, 101, 62, 60, 47, 115, 58, 66, 111, 100, 121, 62, 60, 47, 115, 58, 69, 110, 118, 101, 108, 111, 112, 101, 62]
```

**Comment by ecederstrand** [comment]
`e.data` contains raw bytes. If you do `print(bytes(e.data))` you will get this output instead:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0"
                             MajorBuildNumber="1044" MinorBuildNumber="21" Version="V2_22"
                             xmlns="http://schemas.microsoft.com/exchange/services/2006/types"/>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <m:GetAttachmentResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                                 xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:GetAttachmentResponseMessage ResponseClass="Error">
                    <m:MessageText>The specified object was not found in the store.</m:MessageText>
                    <m:ResponseCode>ErrorItemNotFound</m:ResponseCode>
                    <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
                    <m:Attachments/>
                </m:GetAttachmentResponseMessage>
            </m:ResponseMessages>
        </m:GetAttachmentResponse>
    </s:Body>
</s:Envelope>
```

So you are requesting an attachment ID that somehow doesn't exist anymore.

**Comment by ecederstrand** [comment]
Thanks!

I'm reopening because it's a good test case for improving the error handling here. We should raise `ErrorItemNotFound('The specified object was not found in the store')` instead of the non-obvious `ElementNotFound`.
