### ISSUE TITLE
TypeError: bulk_create() got multiple values for argument 'folder'

### ISSUE THREAD

**Issue by ramwin** [ecederstrand/exchangelib#54]
Dear author. Thank you for providing such a convenient lib for exchange. 
Recently I'm using the lib to create and delete my outlook calendar. 
Using this lib, I delete my event in calendar successfully, but when I create the event, it raise a TypeError. 
```
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody
USERNAME = "username@example.com"
PASSWORD = "mypassword"
EWSTimeZone.PYTZ_TO_MS_MAP["Asia/Shanghai"] = 'China Standard Time'
year, month, day = 2016, 12, 26
tz = EWSTimeZone.timezone("Asia/Shanghai")

# Build a list of calendar items
calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
    ))


credentials = Credentials(username='USERNAME', password='PASSWORD' , is_service_account=False)

config = Configuration(
    server='mail.example.com',
    credentials=Credentials(username='USERNAME', password='PASSWORD'),
    auth_type=NTLM,
    verify_ssl=False,
)
account = Account(primary_smtp_address='USERNAME', config=config,
                  access_type=DELEGATE)

for event in account.calendar.all():
    print(event.subject)  # it print the subject of my event
    event.delete()  # my event has been deleted from my calendar successfully

res = account.calendar.bulk_create(calendar_items) # raise Error
print(res)
```
The result shows like this:
```
Test Subject
My Event
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/folders.py", line 2042, in add_items
    return self.bulk_create(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/folders.py", line 2045, in bulk_create
    return self.account.bulk_create(folder=self, *args, **kwargs)
TypeError: bulk_create() got multiple values for argument 'folder'

```
How can I fix this. Thank you for your consideration and I will be looking forward to your reply.

**Comment by ramwin** [comment]
But it worked if I use this code:
···
item = CalendarItem(
  folder=account.calendar,
  subject='foo',
  account=account,
  start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
  end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),)
···

**Comment by ecederstrand** [comment]
Thanks for the kind words, @ramwin

Yes, this is a bug. I have a fix almost ready. Adding the 'items' kwarg is an acceptable workaround.

**Comment by ramwin** [comment]
Thank you for your fast reply. I'm wondering how to create a event with other people. I use  
```
item = CalendarItem(
  folder=account.calendar,
  subject='foo',
  account=account,
  start=tz.localize(EWSDateTime(year, month, day, 17, 30)),
  end=tz.localize(EWSDateTime(year, month, day, 17 + 1, 15)),
  required_attendees=["user1@example.com"],
  optional_attendees=["user1@example.com"],
  )
item.save()
```
But the event is only shared by myself. How to create a multiplayer events?

**Comment by ramwin** [comment]
The code `res = account.calendar.bulk_create(items=calendar_items)` worked, thank you very much.

**Comment by ecederstrand** [comment]
You need to wrap attendees in an `Attendee` object:

```python
from exchangelib.folders import Attendee, Mailbox
required_attendees = [Attendee(
    mailbox=Mailbox(email_address='user1@example.com'),
    response_type='Accept')
]
```

**Comment by ramwin** [comment]
I tried but it didn't work. I think I should read the document carefully first. And since the origin problem has been solved, I will close the issue. Thank you for your reply.

**Comment by ecederstrand** [comment]
Ok. There may be bugs in there. Meeting invitations and required/optional attendees is difficult for me to test because my test server only has one account.
