### ISSUE TITLE
ImportError: cannot import name 'Credentials'

### ISSUE THREAD

**Issue by deepakguna** [ecederstrand/exchangelib#543]
python 3.6.7
exchange lib __version__ = '1.12.1'
On Ubuntu 18.04.1 LTS

I tried running the code specified in the teaser , after replacing my details: 

```python
from exchangelib import Credentials, Account

credentials = Credentials('john@example.com', 'topsecret')
account = Account('john@example.com', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)

```
it failed as it couldn't import Credentials and accounts. 

`ImportError: cannot import name 'Credentials'`

following is the trace back: 
```python
Traceback (most recent call last):
  File "email.py", line 1, in <module>
    from exchangelib import Credentials, Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/__init__.py", line 4, in <module>
    from .account import Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/account.py", line 11, in <module>
    from .autodiscover import discover
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 29, in <module>
    from . import transport
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/transport.py", line 6, in <module>
    import requests.auth
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python3/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/home/ubuntu/pytest/email.py", line 1, in <module>
    from exchangelib import Credentials, Account
ImportError: cannot import name 'Credentials'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 21, in <module>
    from urllib.request import urlopen
  File "/usr/lib/python3.6/urllib/request.py", line 86, in <module>
    import email
  File "/home/ubuntu/pytest/email.py", line 1, in <module>
    from exchangelib import Credentials, Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/__init__.py", line 4, in <module>
    from .account import Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/account.py", line 11, in <module>
    from .autodiscover import discover
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 29, in <module>
    from . import transport
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/transport.py", line 6, in <module>
    import requests.auth
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python3/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
ModuleNotFoundError: No module named 'email.parser'; 'email' is not a package

Original exception was:
Traceback (most recent call last):
  File "email.py", line 1, in <module>
    from exchangelib import Credentials, Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/__init__.py", line 4, in <module>
    from .account import Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/account.py", line 11, in <module>
    from .autodiscover import discover
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/autodiscover.py", line 29, in <module>
    from . import transport
  File "/home/ubuntu/.local/lib/python3.6/site-packages/exchangelib/transport.py", line 6, in <module>
    import requests.auth
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python3/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/home/ubuntu/pytest/email.py", line 1, in <module>
    from exchangelib import Credentials, Account
ImportError: cannot import name 'Credentials'
```

**Comment by ecederstrand** [comment]
The problem is that you have a script called `email.py` which overrides the built-in `email` module. See a more detailed explanation at https://stackoverflow.com/questions/49692183/package-import-failure-in-python-3-5/49692407#49692407
