### ISSUE TITLE
SOAPError: Unknown SOAP response

### ISSUE THREAD

**Issue by joshswimlane** [ecederstrand/exchangelib#553]
Hello, i am having an issue with continually getting a `SOAPError: Unknown SOAP Response` but the response looks fine to me.  

I receive this error:
```bash
2019-01-31 23:24:10,670 exchangelib.services WARNING  EWS https://outlook.office365.com/EWS/Exchange.asmx, account hackathon@somecompany.onmicrosoft.com: Exception in _get_elements: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 92, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 174, in _get_response_xml
    res = self._get_soap_payload(response=r, **parse_opts)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 274, in _get_soap_payload
    raise SOAPError('Unknown SOAP response: %s' % xml_to_str(body))
```

I am creating my own inherited class that is utilizing the `SearchMailboxes` service name.  I took the liberty of `import from lxml import etree` and calling `print(etree.tostring(root, pretty_print=True))` on line 264 of services.py.

Line 263 calls `root = to_xml(response.iter_content())` so when it prints before hitting the body and response checks it prints out fine I think:

```
Root: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="20"
MajorBuildNumber="1558" MinorBuildNumber="24" Version="V2018_01_08"/>
  </s:Header>
  <s:Body>
    <GetSearchableMailboxesResponse xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ResponseClass="Success">
      <ResponseCode>NoError</ResponseCode>
      <SearchableMailboxes>
        <SearchableMailbox xmlns="http://schemas.microsoft.com/exchange/services/2006/types">
          <Guid>d41235a8-04d4-489f-8a88-1de876260bc6</Guid>
          <PrimarySmtpAddress>hackathon@somecompany.onmicrosoft.com</PrimarySmtpAddress>
          <IsExternalMailbox>false</IsExternalMailbox>
          <ExternalEmailAddress/>
          <DisplayName>Research</DisplayName>
          <IsMembershipGroup>false</IsMembershipGroup>
          <ReferenceId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</ReferenceId>
        </SearchableMailbox>
        <SearchableMailbox xmlns="http://schemas.microsoft.com/exchange/services/2006/types">
          <Guid>6d6be016-3865-459f-b494-ded83a9add49</Guid>
          <PrimarySmtpAddress>josh@somecompany.onmicrosoft.com</PrimarySmtpAddress>
          <IsExternalMailbox>false</IsExternalMailbox>
          <ExternalEmailAddress/>
          <DisplayName>Josh</DisplayName>
          <IsMembershipGroup>false</IsMembershipGroup>
          <ReferenceId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</ReferenceId>
        </SearchableMailbox>
      </SearchableMailboxes>
    </GetSearchableMailboxesResponse>
  </s:Body>
</s:Envelope>

<Element {http://schemas.microsoft.com/exchange/services/2006/messages}GetSearchableMailboxesResponse at 0x110fa6200>
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/><t:TimeZoneContext><t:TimeZoneDefinition Id="Central Standard Time"/></t:TimeZoneContext></s:Header><s:Body><t:MailboxQuery><t:Query>Subject:Account</t:Query><t:MailboxSearchScopes><t:MailboxSearchScope><t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:Mailbox><t:SearchScope>All</t:SearchScope></t:MailboxSearchScope><t:MailboxSearchScope><t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:Mailbox><t:SearchScope>All</t:SearchScope></t:MailboxSearchScope></t:MailboxSearchScopes></t:MailboxQuery></s:Body></s:Envelope>
Root: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="20"MajorBuildNumber="1558" MinorBuildNumber="24" Version="V2018_01_08"/>
  </s:Header>
  <s:Body>
    <m:SearchMailboxesResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:SearchMailboxesResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:SearchMailboxesResult>
            <t:SearchQueries>
              <t:MailboxQuery>
                <t:Query>Subject:Account</t:Query>
                <t:MailboxSearchScopes>
                  <t:MailboxSearchScope>
                    <t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:Mailbox>
                    <t:SearchScope>All</t:SearchScope>
                  </t:MailboxSearchScope>
                  <t:MailboxSearchScope>
                    <t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:Mailbox>
                    <t:SearchScope>All</t:SearchScope>
                  </t:MailboxSearchScope>
                </t:MailboxSearchScopes>
              </t:MailboxQuery>
            </t:SearchQueries>
            <t:ResultType>PreviewOnly</t:ResultType>
            <t:ItemCount>2</t:ItemCount>
            <t:Size>162604</t:Size>
            <t:PageItemCount>2</t:PageItemCount>
            <t:PageItemSize>162604</t:PageItemSize>
            <t:Items>
              <t:SearchPreviewItem>
                <t:Id Id="AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgBGAAAAAAAS8t9axn4gRL5iFdthqZ/ZBwCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAACzvtDiUSWoTY36a7wbzDSQAAAAAAV1AAA=" ChangeKey="CQAAABYAAACzvtDiUSWoTY36a7wbzDSQAAAAAAPd"/>
                <t:Mailbox>
                  <t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:MailboxId>
                  <t:PrimarySmtpAddress>josh@somecompany.onmicrosoft.com</t:PrimarySmtpAddress>
                </t:Mailbox>
                <t:ParentId Id="AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgAuAAAAAAAS8t9axn4gRL5iFdthqZ/ZAQCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAAA=" ChangeKey="AQAAAA=="/>
                <t:ItemClass/>
                <t:UniqueHash>00044&lt;CAKLtyy6eM1vQcf3mR72rKE6Z1Uoqnhe11B3JpXSoK_m1_F7HHQ@mail.gmail.com&gt;0015Upgrade Your Account!000C?6Y???n?</t:UniqueHash>
                <t:SortValue>001B2019-01-24T18:41:11.000000000001A8E000F66A5</t:SortValue>
                <t:OwaLink>https://outlook.office365.com/owa/?realm=somecompany.onmicrosoft.comviewmodel=ItemReadingPaneViewModelPopOutFactoryIsDiscoveryView=1exsvurl=1ItemID=AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgBGAAAAAAAS8t9axn4gRL5iFdthqZ%2FZBwCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAACzvtDiUSWoTY36a7wbzDSQAAAAAAV1AAA%3D</t:OwaLink>
                <t:Sender>Josh</t:Sender>
                <t:ToRecipients>
                  <t:SmtpAddress>Josh</t:SmtpAddress>
                </t:ToRecipients>
                <t:CreatedTime>2019-01-24T18:41:11-06:00</t:CreatedTime>
                <t:ReceivedTime>2019-01-24T18:41:11-06:00</t:ReceivedTime>
                <t:SentTime>2019-01-24T18:41:05-06:00</t:SentTime>
                <t:Subject>Upgrade Your Account!</t:Subject>
                <t:Size>62418</t:Size>
                <t:Preview/>
                <t:Importance>Low</t:Importance>
                <t:Read>false</t:Read>
                <t:HasAttachment>false</t:HasAttachment>
              </t:SearchPreviewItem>
              <t:SearchPreviewItem>
                <t:Id Id="AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMABGAAAAAABdQG8UG7qjTKf0wCVbqLyMBwC6DuFzUH4qRojG/OZVoLCfAAAAAAEKAAC6DuFzUH4qRojG/OZVoLCfAAAIf9wdAAA=" ChangeKey="CQAAABYAAAC6DuFzUH4qRojG/OZVoLCfAAAIfgjQ"/>
                <t:Mailbox>
                  <t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:MailboxId>
                  <t:PrimarySmtpAddress>hackathon@somecompany.onmicrosoft.com</t:PrimarySmtpAddress>
                </t:Mailbox>
                <t:ParentId Id="AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMAAuAAAAAABdQG8UG7qjTKf0wCVbqLyMAQC6DuFzUH4qRojG/OZVoLCfAAAAAAEKAAA=" ChangeKey="AQAAAA=="/>
                <t:ItemClass>IPM.Note</t:ItemClass>
                <t:UniqueHash>0003E6a5c1acf-d933-4ce3-93e0-4f1ddd4bef9c@las1s04mta1008.xt.local0028New or modified user account information000C???9B</t:UniqueHash>
                <t:SortValue>001B2019-01-24T18:38:06.000000000003BD7000FCCA0</t:SortValue>
                <t:OwaLink>https://outlook.office365.com/owa/?realm=somecompany.onmicrosoft.comviewmodel=ItemReadingPaneViewModelPopOutFactoryIsDiscoveryView=1exsvurl=1ItemID=AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMABGAAAAAABdQG8UG7qjTKf0wCVbqLyMBwC6DuFzUH4qRojG%2FOZVoLCfAAAAAAEKAAC6DuFzUH4qRojG%2FOZVoLCfAAAIf9wdAAA%3D</t:OwaLink>
                <t:Sender>Microsoft Online Services Team</t:Sender>
                <t:ToRecipients>
                  <t:SmtpAddress>Research</t:SmtpAddress>
                </t:ToRecipients>
                <t:CreatedTime>2019-01-24T12:38:06-06:00</t:CreatedTime>
                <t:ReceivedTime>2019-01-24T12:38:06-06:00</t:ReceivedTime>
                <t:SentTime>2019-01-24T12:38:04-06:00</t:SentTime>
                <t:Subject>New or modified user account information</t:Subject>
                <t:Size>100186</t:Size>
                <t:Preview/>
                <t:Read>true</t:Read>
                <t:HasAttachment>false</t:HasAttachment>
              </t:SearchPreviewItem>
            </t:Items>
            <t:MailboxStats>
              <t:MailboxStat>
                <t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:MailboxId>
                <t:DisplayName>Research</t:DisplayName>
                <t:ItemCount>1</t:ItemCount>
                <t:Size>100186</t:Size>
              </t:MailboxStat>
              <t:MailboxStat>
                <t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:MailboxId>
                <t:DisplayName>Josh</t:DisplayName>
                <t:ItemCount>1</t:ItemCount>
                <t:Size>62418</t:Size>
              </t:MailboxStat>
            </t:MailboxStats>
          </m:SearchMailboxesResult>
        </m:SearchMailboxesResponseMessage>
      </m:ResponseMessages>
    </m:SearchMailboxesResponse>
  </s:Body>
</s:Envelope>
```

Then I receive the error:

```
2019-01-31 23:30:28,531 exchangelib.services WARNING  EWS https://outlook.office365.com/EWS/Exchange.asmx, account hackathon@somecompany.onmicrosoft.com: Exception in _get_elements: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 92, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 174, in _get_response_xml
    res = self._get_soap_payload(response=r, **parse_opts)
  File "/usr/local/lib/python2.7/site-packages/exchangelib/services.py", line 274, in _get_soap_payload
    raise SOAPError('Unknown SOAP response: %s' % xml_to_str(body))
SOAPError: Unknown SOAP response: <s:Body xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><m:SearchMailboxesResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:SearchMailboxesResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:SearchMailboxesResult><t:SearchQueries><t:MailboxQuery><t:Query>Subject:Account</t:Query><t:MailboxSearchScopes><t:MailboxSearchScope><t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:Mailbox><t:SearchScope>All</t:SearchScope></t:MailboxSearchScope><t:MailboxSearchScope><t:Mailbox>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:Mailbox><t:SearchScope>All</t:SearchScope></t:MailboxSearchScope></t:MailboxSearchScopes></t:MailboxQuery></t:SearchQueries><t:ResultType>PreviewOnly</t:ResultType><t:ItemCount>2</t:ItemCount><t:Size>162604</t:Size><t:PageItemCount>2</t:PageItemCount><t:PageItemSize>162604</t:PageItemSize><t:Items><t:SearchPreviewItem><t:Id Id="AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgBGAAAAAAAS8t9axn4gRL5iFdthqZ/ZBwCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAACzvtDiUSWoTY36a7wbzDSQAAAAAAV1AAA=" ChangeKey="CQAAABYAAACzvtDiUSWoTY36a7wbzDSQAAAAAAPd"/><t:Mailbox><t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:MailboxId><t:PrimarySmtpAddress>joshd@somecompany.onmicrosoft.com</t:PrimarySmtpAddress></t:Mailbox><t:ParentId Id="AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgAuAAAAAAAS8t9axn4gRL5iFdthqZ/ZAQCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAAA=" ChangeKey="AQAAAA=="/><t:ItemClass/><t:UniqueHash>00044&lt;CAKLtyy6eM1vQcf3mR72rKE6Z1Uoqnhe11B3JpXSoK_m1_F7HHQ@mail.gmail.com&gt;0015Upgrade Your Account!000C?6Y???n?</t:UniqueHash><t:SortValue>001B2019-01-24T18:41:11.000000000001A8E000F66A5</t:SortValue><t:OwaLink>https://outlook.office365.com/owa/?realm=somecompany.onmicrosoft.comviewmodel=ItemReadingPaneViewModelPopOutFactoryIsDiscoveryView=1exsvurl=1ItemID=AAMkADAyNTZhNmMyLWNmZTctNDIyZC05NWU4LTgyY2IyMjUyNWZiNgBGAAAAAAAS8t9axn4gRL5iFdthqZ%2FZBwCzvtDiUSWoTY36a7wbzDSQAAAAAAEMAACzvtDiUSWoTY36a7wbzDSQAAAAAAV1AAA%3D</t:OwaLink><t:Sender>Josh</t:Sender><t:ToRecipients><t:SmtpAddress>Josh</t:SmtpAddress></t:ToRecipients><t:CreatedTime>2019-01-24T18:41:11-06:00</t:CreatedTime><t:ReceivedTime>2019-01-24T18:41:11-06:00</t:ReceivedTime><t:SentTime>2019-01-24T18:41:05-06:00</t:SentTime><t:Subject>Upgrade Your Account!</t:Subject><t:Size>62418</t:Size><t:Preview/><t:Importance>Low</t:Importance><t:Read>false</t:Read><t:HasAttachment>false</t:HasAttachment></t:SearchPreviewItem><t:SearchPreviewItem><t:Id Id="AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMABGAAAAAABdQG8UG7qjTKf0wCVbqLyMBwC6DuFzUH4qRojG/OZVoLCfAAAAAAEKAAC6DuFzUH4qRojG/OZVoLCfAAAIf9wdAAA=" ChangeKey="CQAAABYAAAC6DuFzUH4qRojG/OZVoLCfAAAIfgjQ"/><t:Mailbox><t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:MailboxId><t:PrimarySmtpAddress>hackathon@somecompany.onmicrosoft.com</t:PrimarySmtpAddress></t:Mailbox><t:ParentId Id="AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMAAuAAAAAABdQG8UG7qjTKf0wCVbqLyMAQC6DuFzUH4qRojG/OZVoLCfAAAAAAEKAAA=" ChangeKey="AQAAAA=="/><t:ItemClass>IPM.Note</t:ItemClass><t:UniqueHash>0003E6a5c1acf-d933-4ce3-93e0-4f1ddd4bef9c@las1s04mta1008.xt.local0028New or modified user account information000C???9B</t:UniqueHash><t:SortValue>001B2019-01-24T18:38:06.000000000003BD7000FCCA0</t:SortValue><t:OwaLink>https://outlook.office365.com/owa/?realm=somecompany.onmicrosoft.comviewmodel=ItemReadingPaneViewModelPopOutFactoryIsDiscoveryView=1exsvurl=1ItemID=AAMkAGZjOTlkOWExLTM2MDEtNGI3MS04ZDJiLTllNzgwNDQxMThmMABGAAAAAABdQG8UG7qjTKf0wCVbqLyMBwC6DuFzUH4qRojG%2FOZVoLCfAAAAAAEKAAC6DuFzUH4qRojG%2FOZVoLCfAAAIf9wdAAA%3D</t:OwaLink><t:Sender>Microsoft Online Services Team</t:Sender><t:ToRecipients><t:SmtpAddress>Researc</t:SmtpAddress></t:ToRecipients><t:CreatedTime>2019-01-24T12:38:06-06:00</t:CreatedTime><t:ReceivedTime>2019-01-24T12:38:06-06:00</t:ReceivedTime><t:SentTime>2019-01-24T12:38:04-06:00</t:SentTime><t:Subject>New or modified user account information</t:Subject><t:Size>100186</t:Size><t:Preview/><t:Read>true</t:Read><t:HasAttachment>false</t:HasAttachment></t:SearchPreviewItem></t:Items><t:MailboxStats><t:MailboxStat><t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=2ae3541cef834557aadf2fa434590af2-mailbox1</t:MailboxId><t:DisplayName>Researc</t:DisplayName><t:ItemCount>1</t:ItemCount><t:Size>100186</t:Size></t:MailboxStat><t:MailboxStat><t:MailboxId>/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=5341a4228e8c433ba81b4b4b6d75e100-josh</t:MailboxId><t:DisplayName>Josh</t:DisplayName><t:ItemCount>1</t:ItemCount><t:Size>62418</t:Size></t:MailboxStat></t:MailboxStats></m:SearchMailboxesResult></m:SearchMailboxesResponseMessage></m:ResponseMessages></m:SearchMailboxesResponse></s:Body>
```

Any ideas?

**Comment by ecederstrand** [comment]
Hi @joshswimlane 

Did you find a solution to this problem?

**Comment by ecederstrand** [comment]
Assuming this is an error with your subclass. Feel free to reopen if you think otherwise :-)
