### ISSUE TITLE
"ValueError: Item type unexpected in a Folder folder"  

### ISSUE THREAD

**Issue by gtdavidv** [ecederstrand/exchangelib#559]
We're using ExchangeLib to sync up with customer accounts every 30 minutes or so. In the past ~24 hours, I've started getting an error when attempting to retrieve Outlook365 users' emails.

The offending code:
```
messageList = []
mailItems = (account.root / 'Top of Information Store').children.filter(datetime_sent__gt=tz.localize(EWSDateTime(searchYear, searchMonth, searchDay, searchHour, searchMinute))).only('subject', 'body', 'to_recipients', 'sender')[:querySize]
for message in mailItems:
	messageList.append(message)
```

I believe the error is triggered by `for message in mailItems`, as I tried wrapping `messageList.append()` with try/except without any luck.

The error I'm getting is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/folders.py", line 531, in item_model_from_tag
    return cls.ITEM_MODEL_MAP[tag]
KeyError: '{http://schemas.microsoft.com/exchange/services/2006/types}Item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/queryset.py", line 298, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/queryset.py", line 375, in _item_yielder
    for i in iterable:
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/account.py", line 585, in fetch
    item = validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/folders.py", line 533, in item_model_from_tag
    raise ValueError('Item type %s was unexpected in a %s folder' % (tag, cls.__name__))
ValueError: Item type {http://schemas.microsoft.com/exchange/services/2006/types}Item was unexpected in a Folder folder
```

This is now happening for at least 8 of my users; all started in the last 24 hours or so, though the exact start time seems to vary.

**Comment by ecederstrand** [comment]
I think this was fixed in https://github.com/ecederstrand/exchangelib/commit/e64a28d5f836d3fe9cc866b674518c7a74f277d5

There hasn't been a release since that commit, so you'll have to install from GitHub.

**Comment by gtdavidv** [comment]
Looks like that's working. Thanks!
