### ISSUE TITLE
Fail to read mailbox properties

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#569]
Getting mailbox properties for exchange online mailbox is failing with below error.

```python
 File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Commvault/Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 213, in get_mailbox_proeprties
    access_type=IMPERSONATION)
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\account.py", line 91, in __init__
    self.root = Root.get_distinguished(account=self)
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\folders.py", line 621, in get_distinguished
    folders = list(cls.get_folders(account=account, ids=[cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID)]))
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\folders.py", line 612, in get_folders
    shape=IdOnly
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 887, in call
    shape=shape,
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 76, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 140, in _get_response_xml
    allow_redirects=False)
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\util.py", line 495, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\util.py", line 553, in _raise_response_errors
    raise r.headers['TimeoutException']
  File "C:\Program Files\Python36\lib\site-packages\exchangelib\util.py", line 453, in post_ratelimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by ecederstrand** [comment]
Can you please post the code that triggered this stack trace?

**Comment by ecederstrand** [comment]
Hi @shireen91 Did you find a solution to your problem?

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you have additional information,.
