### ISSUE TITLE
ImportError: cannot import name 'x509' from 'cryptography' 

### ISSUE THREAD

**Issue by elliotmartin** [ecederstrand/exchangelib#589]
Python version 3.7.0 
Exchangelib version 1.12.4

Failed on attempting to run the code in teaser with my credentials replaced.

```
from exchangelib import Credentials, Account

credentials = Credentials("john@example.com", "topsecret")
account = Account("john@example.com", credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by("-datetime_received")[:100]:
    print(item.subject, item.sender, item.datetime_received)

```
The failure is on the first line. This failed in both my PyCharm venv as well as when attempting to start fresh on the command line with the same error message: 
```
Traceback (most recent call last):
  File "C:/Users/martine/PycharmProjects/scripts/account_creation/send_mail.py", line 1, in <module>
    from exchangelib import Credentials, Account
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\exchangelib\__init__.py", line 4, in <module>
    from .account import Account
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\exchangelib\account.py", line 11, in <module>
    from .autodiscover import discover
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\exchangelib\autodiscover.py", line 29, in <module>
    from . import transport
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\exchangelib\transport.py", line 7, in <module>
    import requests_ntlm
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\requests_ntlm\__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "C:\Users\martine\PycharmProjects\scripts\venv\lib\site-packages\requests_ntlm\requests_ntlm.py", line 5, in <module>
    from cryptography import x509
ImportError: cannot import name 'x509' from 'cryptography' (C:\Users\martine\AppData\Local\Programs\Python\Python37-32\cryptography.py)
```

I attempted to reinstall exchangelib and cryptography with PyCharm's IDE and with pip via command line. Neither solved the problem.

**Comment by ecederstrand** [comment]
This is not an exchangelib issue. You have a file called `cryptography.py` at `C:\Users\martine\AppData\Local\Programs\Python\Python37-32\cryptography.py` that has a namespace clash with the `cryptography` package that exchangelib has a subdependency on. You need to rename the file to something else, or move it out of Python's search path.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this did not fix your issue :-)
