### ISSUE TITLE
get room free/busy info, 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by MariaUdal** [ecederstrand/exchangelib#594]
Hello!
I'm trying to get room free/busy info for calculating time when it's available
```
credentials = Credentials(username=r'myusername', password='mypass')
config = Configuration(server='mail.company.ru/ews/exchange.asmx', credentials=credentials)
account = Account(primary_smtp_address='room@company.ru',
                  credentials=credentials,
                  config=config,
                  autodiscover=False,
                  access_type=DELEGATE)

start = account.default_timezone.localize(EWSDateTime.now()) + timedelta(hours=0)
end = start + timedelta(hours=10)
accounts = [(account, "Organizer", False)]


for busy_info in account.protocol.get_free_busy_info(accounts=accounts, start=start, end=end):
    for event in busy_info.calendar_events:
        print(event)
```

In the ouput I'm getting error

```
Request headers: {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Cookie': 'X-BackEndCookie=S-1-5-21-3141827748-1111936510-3508575369-26162=u56Lnp2ejJqByZ3KnZqayZ7SnpqendLLmsbG0p6bnMnSy8nInMnKzpnNm8rLgYHNz87G0s/J0szPq8/KxcvJxc3LgZGMm9GNioHP; exchangecookie=de636dc23b6d43fab83f7a87f49ff722', 'Content-Length': '1305'}
Response headers: {'Cache-Control': 'private', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/8.5', 'request-id': 'b33964a4-869b-479b-b14a-bcb0d7481386', 'X-CalculatedBETarget': 'ex02-dsp.nsd.ru', 'X-DiagInfo': 'EX02-DSP', 'X-BEServer': 'EX02-DSP', 'X-AspNet-Version': '4.0.30319', 'Set-Cookie': 'exchangecookie=de636dc23b6d43fab83f7a87f49ff722; path=/, X-BackEndCookie=S-1-5-21-3141827748-1111936510-3508575369-26162=u56Lnp2ejJqByZ3KnZqayZ7SnpqendLLmsbG0p6bnMnSy8nInMnKzpnNm8rLgYHNz87G0s/J0szPq8/KxcvJxc3LgZGMm9GNioHP; expires=Sun, 30-Jun-2019 05:46:24 GMT; path=/ews; secure; HttpOnly', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'EX01-M1', 'Date': 'Fri, 31 May 2019 05:46:24 GMT'}
Request data: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/></s:Header><s:Body><m:GetUserAvailabilityRequest><t:TimeZone><t:Bias>-180</t:Bias><t:StandardTime><t:Bias>0</t:Bias><t:Time>00:00:00</t:Time><t:DayOrder>1</t:DayOrder><t:Month>1</t:Month><t:DayOfWeek>Monday</t:DayOfWeek></t:StandardTime><t:DaylightTime><t:Bias>0</t:Bias><t:Time>00:00:00</t:Time><t:DayOrder>5</t:DayOrder><t:Month>12</t:Month><t:DayOfWeek>Sunday</t:DayOfWeek></t:DaylightTime></t:TimeZone><m:MailboxDataArray><t:MailboxData><t:Email><t:Address>room-1-8@nsd.ru</t:Address><t:RoutingType>SMTP</t:RoutingType></t:Email><t:AttendeeType>Organizer</t:AttendeeType><t:ExcludeConflicts>0</t:ExcludeConflicts></t:MailboxData></m:MailboxDataArray><t:FreeBusyViewOptions><t:TimeWindow><t:StartTime>2019-05-31T08:46:24+03:00</t:StartTime><t:EndTime>2019-05-31T18:46:24+03:00</t:EndTime></t:TimeWindow><t:MergedFreeBusyIntervalInMinutes>30</t:MergedFreeBusyIntervalInMinutes><t:RequestedView>DetailedMerged</t:RequestedView></t:FreeBusyViewOptions></m:GetUserAvailabilityRequest></s:Body></s:Envelope>'
Response data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="1" MajorBuildNumber="1713" MinorBuildNumber="5" Version="V2017_07_11" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetUserAvailabilityResponse xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"><FreeBusyResponseArray><FreeBusyResponse><ResponseMessage ResponseClass="Success"><ResponseCode>NoError</ResponseCode></ResponseMessage><FreeBusyView><FreeBusyViewType xmlns="http://schemas.microsoft.com/exchange/services/2006/types">DetailedMerged</FreeBusyViewType><MergedFreeBusy xmlns="http://schemas.microsoft.com/exchange/services/2006/types">00022222222222222000</MergedFreeBusy><CalendarEventArray xmlns="http://schemas.microsoft.com/exchange/services/2006/types"><CalendarEvent><StartTime>2019-05-31T10:30:00</StartTime><EndTime>2019-05-31T11:30:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83500000</ID><Subject>\xd0\xa7\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2 \xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x80 \xd0\xa1\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb5\xd0\xb5\xd0\xb2\xd0\xb8\xd1\x87 \xd0\x9b\xd0\xb8\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xb2\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd1\x87\xd0\xb0</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent><CalendarEvent><StartTime>2019-05-31T12:00:00</StartTime><EndTime>2019-05-31T13:00:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83360000</ID><Subject>\xd0\xa7\xd0\xb5\xd0\xba\xd1\x83\xd0\xbb\xd0\xb0\xd0\xb5\xd0\xb2\xd0\xb0 \xd0\x95\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\x92\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbd\xd0\xb0 \xd0\xb2\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd1\x87\xd0\xb0</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent><CalendarEvent><StartTime>2019-05-31T13:30:00</StartTime><EndTime>2019-05-31T14:00:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83460000</ID><Subject>\xd0\x9c\xd0\xbe\xd1\x88\xd0\xba\xd0\xb8\xd0\xbd\xd0\xb0 \xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x80\xd0\xb0 \xd0\x9c\xd0\xb8\xd1\x85\xd0\xb0\xd0\xb9\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbd\xd0\xb0 \xd0\x92\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd1\x87\xd0\xb0 \xd1\x81 \xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x80\xd0\xbe\xd0\xbc \xd0\xa2\xd0\xb0\xd1\x80\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xbc (\xd0\x9d\xd0\xa0\xd0\x94-\xd0\x9f\xd0\xb5\xd1\x80\xd1\x81\xd0\xbf\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xb0)</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent><CalendarEvent><StartTime>2019-05-31T14:00:00</StartTime><EndTime>2019-05-31T15:00:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83380000</ID><Subject>\xd0\x9a\xd1\x83\xd0\xb7\xd0\xbd\xd0\xb5\xd1\x86\xd0\xbe\xd0\xb2 \xd0\x9f\xd0\xb5\xd1\x82\xd1\x80 \xd0\x9d\xd0\xb8\xd0\xba\xd0\xbe\xd0\xbb\xd0\xb0\xd0\xb5\xd0\xb2\xd0\xb8\xd1\x87 \xd0\x9a\xd0\xbe\xd0\xbd\xd1\x84-\xd0\xba\xd0\xbe\xd0\xbb\xd0\xbb</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent><CalendarEvent><StartTime>2019-05-31T15:30:00</StartTime><EndTime>2019-05-31T16:00:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83450000</ID><Subject>\xd0\x9c\xd0\xbe\xd1\x88\xd0\xba\xd0\xb8\xd0\xbd\xd0\xb0 \xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x80\xd0\xb0 \xd0\x9c\xd0\xb8\xd1\x85\xd0\xb0\xd0\xb9\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbd\xd0\xb0 \xd0\x92\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd1\x87\xd0\xb0 \xd1\x81 \xd0\x9a\xd0\xbb\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8\xd0\xb5\xd0\xbc \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb3\xd1\x83\xd0\xb4\xd0\xb0 (\xd0\xa1\xd1\x82\xd0\xb0\xd0\xb6\xd0\xb5\xd1\x80 \xd0\x9d\xd0\xa0\xd0\x94-\xd0\x9f\xd0\xb5\xd1\x80\xd1\x81\xd0\xbf\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xb0)</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent><CalendarEvent><StartTime>2019-05-31T16:00:00</StartTime><EndTime>2019-05-31T17:00:00</EndTime><BusyType>Busy</BusyType><CalendarEventDetails><ID>0000000043315AED1B24CC4AB8FBB9E86359EEC6070088428D536E9A174B9B913F6EFBCBB29B0000001A64F40000BB648F5569620B46AB6CCB4EF39F127B0001158F83490000</ID><Subject>\xd0\x9a\xd0\xbe\xd0\xb7\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb0 \xd0\x9c\xd0\xb0\xd1\x80\xd0\xb8\xd1\x8f \xd0\x90\xd0\xbd\xd0\xb0\xd1\x82\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb5\xd0\xb2\xd0\xbd\xd0\xb0 \xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8c\xd1\x8e: \xd0\xa0\xd0\xbe\xd0\xb3\xd0\xbe\xd0\xb7\xd0\xb8\xd0\xbd \xd0\x92\xd0\xb8\xd0\xba\xd1\x82\xd0\xbe\xd1\x80_ \xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xbd\xd0\xb0\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f \xd1\x80\xd0\xb0\xd0\xb7\xd1\x80\xd0\xb0\xd0\xb1\xd0\xbe\xd1\x82\xd0\xba\xd0\xb8 \xd0\xba\xd0\xbb\xd0\xb8\xd0\xb5\xd0\xbd\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd1\x85 \xd0\xbf\xd1\x80\xd0\xb8\xd0\xbb\xd0\xbe\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb9 Java</Subject><Location>1.8 "\xd0\x93\xd0\xb0\xd0\xbb\xd0\xb5\xd1\x80\xd0\xb5\xd1\x8f \xd0\xa3\xd1\x84\xd0\xb8\xd1\x86\xd1\x86\xd0\xb8" (6) \xd1\x82\xd0\xb5\xd0\xbb. 4362</Location><IsMeeting>true</IsMeeting><IsRecurring>false</IsRecurring><IsException>false</IsException><IsReminderSet>false</IsReminderSet><IsPrivate>false</IsPrivate></CalendarEventDetails></CalendarEvent></CalendarEventArray></FreeBusyView></FreeBusyResponse></FreeBusyResponseArray></GetUserAvailabilityResponse></s:Body></s:Envelope>'

DEBUG:exchangelib.util:Session 25317 thread 17200: Useful response from https://mail.nsd.ru/ews/exchange.asmx/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server mail.nsd.ru: Releasing session 25317
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 10:30:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 11:30:00 on field end
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 12:00:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 13:00:00 on field end
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 13:30:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 14:00:00 on field end
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 14:00:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 15:00:00 on field end
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 15:30:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 16:00:00 on field end
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 16:00:00 on field start
WARNING:exchangelib.fields:Returning naive datetime 2019-05-31 17:00:00 on field end
Traceback (most recent call last):
  File "C:/Users/Udalova.MV/projects/devops/rc_bots/meeting_bot/meeting_bot.py", line 40, in <module>
    for busy_info in account.protocol.get_free_busy_info(accounts=accounts, start=start, end=end):
  File "C:\Users\Udalova.MV\projects\devops\rc_bots\venv\lib\site-packages\exchangelib\services.py", line 2010, in call
    yield FreeBusyView.from_xml(elem=elem, account=None)
  File "C:\Users\Udalova.MV\projects\devops\rc_bots\venv\lib\site-packages\exchangelib\properties.py", line 743, in from_xml
    kwargs[f.name] = f.from_xml(elem=elem.find('{%s}WorkingHours' % TNS), account=account)
  File "C:\Users\Udalova.MV\projects\devops\rc_bots\venv\lib\site-packages\exchangelib\fields.py", line 827, in from_xml
    iter_elem = elem.find(self.response_tag())
AttributeError: 'NoneType' object has no attribute 'find'
DEBUG:exchangelib.protocol:Server mail.nsd.ru: Closing sessions
```

Could you please explain to me what am I doing wrong?

**Comment by ecederstrand** [comment]
Thanks for the thorough report!

This is a bug in exchangelib. I just pushed a change that should fix this. Feel free to reopen if you still have issues.

**Comment by gismcieri** [comment]
> Thanks for the thorough report!
> 
> This is a bug in exchangelib. I just pushed a change that should fix this. Feel free to reopen if you still have issues.

Hi @ecederstrand ,

Are these types of bug fixes only in the most current software? ie (pip install git+https://github.com/ecederstrand/exchangelib.git).

If so when do you usually push them to the main release.

Thanks,
Matt

**Comment by ecederstrand** [comment]
Yes, this is still only available on the master branch. I usually release new versions once a month.

In each commit on GitHub ( e.g. https://github.com/ecederstrand/exchangelib/commit/efdafe2caa87dafd1260a5552be4772d8fedb7f8) you can see in the blue bar at the top of the page which version the commit is available in.

**Comment by MariaUdal** [comment]
Thank you, ecederstrand! Your fix helped me.
When are you able to include this fix into new release version?
