### ISSUE TITLE
Send Email fails: ErrorInvalidPropertySet (message:InternetMessageId)

### ISSUE THREAD

**Issue by AvitalL** [ecederstrand/exchangelib#619]
Hi,

I am trying to send an email with a piece of code that worked for me before on many Exchange servers (2013, 2016, O365), and I get the following exception: 

`
Traceback (most recent call last):File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\jmxvfjx4.huk.py", line 45, in [module]main()File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\jmxvfjx4.huk.py", line 37, in mainem.send_mail_html_embedded_photos(siemplify.parameters['Send to'], subject, content, attachment_paths, cc=siemplify.parameters.get('CC', ""), bcc=siemplify.parameters.get('BCC', ""))File "C:\Siemplify_Server\bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\ExchangeManager.py", line 339, in send_mail_html_embedded_photosmsg.send()File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\items.py", line 705, in sendres = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=send_meeting_invitations)File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\items.py", line 285, in _createsend_meeting_invitations=send_meeting_invitations)File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\account.py", line 406, in bulk_createsend_meeting_invitations=send_meeting_invitations,File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\account.py", line 401, in [genexpr]i if isinstance(i, Exception)File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\account.py", line 319, in _consume_item_servicefor i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\services.py", line 616, in _pool_requestsfor elem in elems:File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\services.py", line 312, in _get_elements_in_responsecontainer_or_exc = self._get_element_container(message=msg, name=self.element_container_name)File "C:\Siemplify_Server\Bin\Scripting\PythonSDK\IntegrationsVirtualEnvironment\Exchange\lib\site-packages\exchangelib\services.py", line 287, in _get_element_containerraise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: [t:FieldURI xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" FieldURI="message:InternetMessageId"/])
`

Here is the code snippet I was using.

```python
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    Configuration, ServiceAccount, \
    Message, EWSDateTime, EWSTimeZone, Mailbox, HTMLBody, FileAttachment, \
    ItemAttachment
from bs4 import BeautifulSoup
import email
import os


def send_email(self, to_addresses, subject, html_body, attachments_paths=[], cc=None, bcc=None):
    soup = BeautifulSoup(html_body, "lxml")
    for cst_tag in soup.findAll("cstimage"):
        cst_tag.extract()
    body = HTMLBody(soup.prettify())

    msg_id = email.utils.make_msgid()

    # Create message object
    msg = Message(
        account=self.account,
        message_id=msg_id,
        subject=subject,
        body=body,
        to_recipients=[Mailbox(email_address=mail_address.strip(' ')) for mail_address in to_addresses.split(',')],
        cc_recipients=[Mailbox(email_address=mail_address.strip(' ')) for mail_address in
                       cc.split(',')] if cc else None,
        bcc_recipients=[Mailbox(email_address=mail_address.strip(' ')) for mail_address in
                        bcc.split(',')] if bcc else None
    )

    for attachment_path in attachments_paths:
        if not os.path.exists(attachment_path):
            raise Exception("Attachment {} doesn't exist.".format(attachment_path))

        with open(attachment_path, 'rb') as attachment:
            file_content = attachment.read()
            file_name = os.path.basename(attachment_path)
            msg.attach(FileAttachment(name=file_name, content=file_content))

    # Send mail
    msg.send()
    return msg_id
```
As seen in the logs attached, there were no attachments when the error occurred and the email was pretty simple (I changed the addresses): 

`Message(subject=u'test', body=u'<html>\n <body>\n  <p>\n   test\n  </p>\n </body>\n</html>', attachments=[], to_recipients=[Mailbox(name=None, email_address=u'someone@example.com', routing_type=None, mailbox_type=None, item_id=None)], message_id='<156519098600.3564.7360863222641447294@1234.example.com>')
`
I collected the exchangelib logs, it seems the issue is related to **message ID** (I have to generate one and return it as later I query about it, and use it to identify the specific email). 

The server version according to the IT guys is **Exchange Server 2010 SP3** build number **14.3.123.4.**

The debug logs are attached (again, changed the addresses because of internal policy)
[exchange_615e2547-e275-4fd5-987f-51abf5ca20ec (1).log](https://github.com/ecederstrand/exchangelib/files/3489617/exchange_615e2547-e275-4fd5-987f-51abf5ca20ec.1.log)

Appreciate your help!

**Comment by ecederstrand** [comment]
Judging by the error message, it looks like the `InternetMessageId` field is read-only on that version of Exchange. I don't think there's anything you can do about that.

There's issue #496 which seems related to this.

**Comment by AvitalL** [comment]
First, thanks for your quick response :)

Second, if this is the situation, can you think of other way for me to overcome this, and get the generated InternetMessageID from Exchange after the email was sent? We are using the messageId for further queries, like identifying reply emails with the In-Reply-To headers, etc.

**Comment by ecederstrand** [comment]
`.send()` copies the message to the sent folder by default, I think. Otherwise, you can specify it explicitly: `.send(copy_to_folder=account.sent)`. If you fetch the message from the sent folder, you may be able to find the `InternetMessageId` value there. Otherwise, you could Bcc yourself a copy of the email.

**Comment by AvitalL** [comment]
Thanks, I will try.
