### ISSUE TITLE
Send email failed

### ISSUE THREAD

**Issue by mkitby** [ecederstrand/exchangelib#63]
Hello,

I'm trying to use the exchangelib to send an email with my exchange account, but ran into some issues. I use the following code. 

```
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody
    
config = Configuration(
    server='email.example.com',
    credentials=Credentials(username='MYWINDOMAIN\\myusername', password='topsecret'),
    auth_type=NTLM
)

account = Account(primary_smtp_address='mkitby@example.com', config=config,
                  access_type=DELEGATE)    

m = Message(
    account=a,   # What should I fill in this field?
    subject='Daily motivation',
    body='All bodies are beautiful',
    to_recipients=[Mailbox(email_address='anne@example.com')]
)
m.send()
```

What does Message.account mean? What value should be assigned?

The traceback is,
```
Traceback (most recent call last):

  File "<ipython-input-17-9d9b628354cd>", line 1, in <module>
    runfile('C:/Users/xp3409/Desktop/1.py', wdir='C:/Users/xp3409/Desktop')

  File "e:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "e:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/xp3409/Desktop/1.py", line 27, in <module>
    autodiscover=True, access_type=DELEGATE)

  File "e:\Anaconda3\lib\site-packages\exchangelib\account.py", line 44, in __init__
    assert isinstance(self.locale, string_types)
```

**Comment by ecederstrand** [comment]
This is a bug that was fixed in https://github.com/ecederstrand/exchangelib/commit/ba04b3a52012e145ef647af8067d5b3df4891672 but there hasn't been a release since. To work around, either install from GitHub or set your `locale` explicitly on the `Account`:

```python
account = Account(primary_smtp_address='mkitby@example.com', ..., locale='en_US')
```
