### ISSUE TITLE
How to change credentials after UnauthorizedError

### ISSUE THREAD

**Issue by lululukas** [ecederstrand/exchangelib#662]
I'm trying to implement re-prompting the password when the credentials are incorrect. I try `account.root.refresh()` or `account.inbox.all().exists()` after establishing the connection to catch the ` UnauthorizedError` raised with incorrect credentials and then re-prompt. However, at times the exception is not raised and it just hangs forever. When I look at the stack trace, I see that it doesn't find `root` in the object dict, however the resulting `KeyError` is not raised (if I could catch that would be fine). It then goes on to keep trying and increasing the rate limit, if I understand the log correctly. I think I either have to invalidate ` cached_property` at the beginning or the `KeyError` when not finding `root` should be raised.

Here's the full log:

```
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\Scripts\ewsharvest-script.py", line 11, in <module>
    load_entry_point('ews-harvester', 'console_scripts', 'ewsharvest')()
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\myuser\src\ews_harvester\ews_harvester\main.py", line 6, in <module>
    from ews_harvester.harvester import MailHarvester
  File "c:\users\myuser\src\ews_harvester\ews_harvester\harvester.py", line 118, in <module>
    class MailHarvester:
  File "c:\users\myuser\src\ews_harvester\ews_harvester\harvester.py", line 123, in MailHarvester
    account.root.refresh()
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\account.py", line 241, in root
    return Root.get_distinguished_root(account=self)
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\folders\roots.py", line 85, in get_distinguished_root
    folder=cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID, is_distinguished=True)
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\folders\base.py", line 570, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\folders\collections.py", line 225, in resolve
    additional_fields=additional_fields
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\folders\collections.py", line 287, in get_folders
    shape=ID_ONLY,
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\services\get_folder.py", line 31, in call
    shape=shape,
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\services\common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\services\common.py", line 135, in _get_response_xml
    stream=self.streaming,
  File "C:\Users\myuser\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\exchangelib\util.py", line 676, in post_ratelimited
    time.sleep(wait)  # Increase delay for every retry
```

**Comment by ecederstrand** [comment]
Can you post a complete example? Which version of exchangelib is this?

I think the issue here is that you have retry policy enabled (see https://github.com/ecederstrand/exchangelib#setup-and-connecting), and that cannot distinguish an unauthorised login from a backoff request from the server. So we go into a retry loop. If the retry policy mode is disabled, you should always get an `UnauthorizedError`.

You may have to delete the `Account` object entirely after prompting for the password because the username and password could be cached in the TCP session pool of the `Account.protocol` object. We should probably invalidate the session pool if we encounter an `UnauthorizedError` and the retry policy is not enabled.

**Comment by lululukas** [comment]
exchangelib is version 2.0.1. You are right, I did have retry policy enabled and without it the `UnauthorizedError` is raised. Is there no way to have retry policy enabled and still get authorization errors raised?

At the moment, the retry loop looks like this:

```python
attempts = 0
while True:
    try:
        account = get_account()
        account.root.refresh()
        break
    except errors.UnauthorizedError:
        if attempts < 3:
            logging.warning(
                f"You have provided a wrong password. Remaining attempts: {2 - attempts}"
            )
            attempts += 1
        else:
            raise PermissionError(
                "You've entered the password wrong too many times. Aborting.."
            )
```

But after your feedback I will probably change it a bit to delete the account object after `UnauthorizedError` and get it again.

**Comment by ecederstrand** [comment]
There is no way to propagate the `UnauthorizedError` with retry policy, unfortunately. The problem is that Exchange servers sometimes return HTTP 401 without any additional context when they are under heavy load. Then, when load decreases, the server continues to accept requests. I haven't found any way to distinguish this situation from a genuine authorization error.

**Comment by lululukas** [comment]
Thanks for the additional info. I'll use it without retry policy for now then and see if there are any issues. Otherwise, I guess I'll just have to skip the re-prompt.

**Comment by ecederstrand** [comment]
You could prompt for user and password without retry policy in a loop until the auth goes well. Then switch to retry policy when you have working auth.

**Comment by lululukas** [comment]
Nice idea. That would mean I need to create a new `Configuration` object though, right? It's not possible to set `retry_policy` on an already created account, is it?

**Comment by ecederstrand** [comment]
Yes, you'd probably need to create a new object. The classes haven't been designed for this situation, and the tests don't cover this use case. It would be nice to make sure that changing the username or password in a `Credentials` object propagates down to the `Session` objects in the protocol session pool.

**Comment by lululukas** [comment]
Sure, happy to test this. My current connection set up looks like this:

```python
def make_config(email_addr, pw):
    ews_config = Configuration(
        # retry_policy=FaultTolerance(max_wait=3600),
        server="outlook.office365.com",
        credentials=Credentials(email_addr, pw),
        version=Version(build=Build(14, 3, 442, 0)),
    )
    return ews_config


def get_account(mailbox_addr=settings['central_mailbox']):
    addr = input(
        f"Login address (default: {settings['user_address']}): "
    )
    if addr in ["", " "]:
        addr = settings['user_address']
    pw = getpass.getpass("Please enter you password: ")
    ews_config = make_config(addr, pw)
    account = Account(
        primary_smtp_address=mailbox_addr,
        config=ews_config,
        autodiscover=False,
        access_type=DELEGATE
    )
    return account
```

I'm thinking to make a new function `get_creds` that would just get credentials and create an `Account` without `retry_policy` set, just for validation. As soon as creds could be validated, they are passed to `get_account` that then creates the account to be used throughout the application, with `retry_policy` set.

**Comment by lululukas** [comment]
Seems to be all working fine, I'm creating a config and account for validation only, both objects are deleted after each unsuccessful validation attempt. Validated creds are then used to create final config and account.
