### ISSUE TITLE
exchangelib.errors.AutoDiscoverFailed: Error guessing auth type: HTTPSConnectionPool

### ISSUE THREAD

**Issue by gotonnc** [ecederstrand/exchangelib#677]
Hi, my code is very simple:

from exchangelib import Credentials, Configuration, Account, Version, Build, NTLM, GSSAPI, SSPI, BASIC, DELEGATE

credentials = Credentials('myusername@mydomain.com', 'mysecret')
account = Account(primary_smtp_address='myusername@mydomain.com', credentials=credentials, autodiscover=True)

But I got this the following error. I suppose that the certificate that was issued for www.mydomain.com is not valid with mydomain.com. Do you have idea to fix it ?

Thanks

Traceback (most recent call last):
  File "/run/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/run/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/run/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/run/python3.6/site-packages/urllib3/connection.py", line 364, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/run/python3.6/site-packages/urllib3/connection.py", line 374, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'mydomain.com' doesn't match either of 'www.mydomain.com', 'intranet.mydomain.com', 'www.ent.mydomain.com', 'www.laboratory.mydomain.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/run/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/run/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mydomain.com', port=443): Max retries exceeded with url: /Autodiscover/Autodiscover.xml (Caused by SSLError(CertificateError("hostname 'mydomain.com' doesn't match either of 'www.mydomain.com', 'intranet.mydomain.com', 'www.ent.mydomain.com', 'www.laboratory.mydomain.com'",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/run/python3.6/site-packages/exchangelib/account.py", line 92, in __init__
    email=self.primary_smtp_address, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "/run/python3.6/site-packages/exchangelib/autodiscover.py", line 232, in discover
    auth_type=auth_type, retry_policy=retry_policy)
  File "/run/python3.6/site-packages/exchangelib/autodiscover.py", line 250, in _try_autodiscover
    auth_type=auth_type, retry_policy=retry_policy)
  File "/run/python3.6/site-packages/exchangelib/autodiscover.py", line 341, in _autodiscover_hostname
    r = _get_response(protocol=autodiscover_protocol, email=email)
  File "/run/python3.6/site-packages/exchangelib/autodiscover.py", line 407, in _get_response
    headers=DEFAULT_HEADERS.copy(), data=data, allow_redirects=True)
  File "/run/python3.6/site-packages/exchangelib/util.py", line 724, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/run/python3.6/site-packages/exchangelib/util.py", line 796, in _raise_response_errors
    raise response.headers['TimeoutException']
  File "/run/python3.6/site-packages/exchangelib/util.py", line 678, in post_ratelimited
    stream=stream)
  File "/run/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/run/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/run/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/run/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mydomain.com', port=443): Max retries exceeded with url: /Autodiscover/Autodiscover.xml (Caused by SSLError(CertificateError("hostname 'mydomain.com' doesn't match either of 'www.mydomain.com', 'intranet.mydomain.com', 'www.ent.mydomain.com', 'www.laboratory.mydomain.com'",),))

**Comment by ecederstrand** [comment]
This is an SSL certificate issue. It's not a problem with exchangelib. You should raise this with your system administrators, but you can disable SSL verification if you think it's OK to do so. See the README for details.
