### ISSUE TITLE
Unable to import into archive

### ISSUE THREAD

**Issue by CrowCakes** [ecederstrand/exchangelib#690]
After following the import/export example in the readme, I was able to successfully export from a sample inbox and upload its messages into an inbox from a different account. I then tried to follow the same exact steps for the archive folders, but ran into this error:

```
Traceback (most recent call last):
  File "exchange-migrate.py", line 44, in <module>
    target_account.upload((target_archive, d) for d in data)
  File "C:\Python37\lib\site-packages\exchangelib\account.py", line 345, in upload
    return list(UploadItems(account=self, chunk_size=chunk_size).call(data=data))
  File "C:\Python37\lib\site-packages\exchangelib\services\common.py", line 535, in _pool_requests
    elems = r.get()
  File "C:\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\lib\site-packages\exchangelib\services\common.py", line 516, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "C:\Python37\lib\site-packages\exchangelib\services\upload_items.py", line 34, in get_payload
    parentfolderid = ParentFolderId(parent_folder.id, parent_folder.changekey)
AttributeError: 'FolderCollection' object has no attribute 'id'
```

This is the code I am using:
```
archive = my_account.root.glob('*/Archive')
target_archive = target_account.root.glob('*/Archive')

for folder in target_archive:
    print(folder)

items = archive.all().only('id', 'changekey')
print("Exporting archive")
data = my_account.export(items)
for item in data:
    print(item[0:300], "\n-------------\n")
	
print("Migrating archive")
target_account.upload((target_archive, d) for d in data)
```

This brings me to a related problem: I can't access the account's `archive_inbox` or its root using the account method.

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'archive_msg_folder_root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'archive_root'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\exchangelib\folders\roots.py", line 102, in get_distinguished
    folder=cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID, is_distinguished=True)
  File "C:\Python37\lib\site-packages\exchangelib\folders\base.py", line 508, in resolve
    raise f
  File "C:\Python37\lib\site-packages\exchangelib\services\common.py", line 341, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorFolderNotFound: The specified folder could not be found in the store.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exchange-migrate.py", line 28, in <module>
    archive = my_account.archive_inbox
  File "C:\Python37\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Python37\lib\site-packages\exchangelib\account.py", line 113, in archive_inbox
    return self.archive_root.get_default_folder(ArchiveInbox)
  File "C:\Python37\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Python37\lib\site-packages\exchangelib\account.py", line 137, in archive_root
    return ArchiveRoot.get_distinguished(account=self)
  File "C:\Python37\lib\site-packages\exchangelib\folders\roots.py", line 105, in get_distinguished
    raise ErrorFolderNotFound('Could not find distinguished folder %s' % cls.DISTINGUISHED_FOLDER_ID)
exchangelib.errors.ErrorFolderNotFound: Could not find distinguished folder archiveroot
```

I'd thought that the import function only needed a folder, but it seems something's wrong with the steps leading up to it. Is this because something unexpected was found in the mailbox hierarchy?

**Comment by ecederstrand** [comment]
The first problem is because you are trying to upload to `target_archive`, but `target_archive` is not a single folder. It's a glob pattern that may return multiple folders. Uploading data must be done to a single folder.

Re. your second problem, the `archiveroot` root folder is only available on some Exchange mailboxes. Probably your target mailbox does not have an archive set up.

**Comment by CrowCakes** [comment]
I'd thought as much after looking into FolderCollection. I didn't know about archiveroot having limited availability though.

After realizing that I could just iterate over the presumably only element in the FolderCollection, I came up with this change:
```
for folder in target_archive:
	print(folder)
	target_archive = folder
	break
```
Not particularly nice, but it's allowing me to at least run the whole script, and it does upload the source archive into the target archive.

**Comment by ecederstrand** [comment]
You can also do:

```python
target_archive = list(target_account.root.glob('*/Archive'))[0]
```

But since you already know the glob will match exactly one folder, so you can just reference it directly:

```python
target_archive = target_account.root / 'Archive'
```
