### ISSUE TITLE
doesn't detect/delete wrong /tmp/exchangelib.winzone.cache.db

### ISSUE THREAD

**Issue by jspricke** [ecederstrand/exchangelib#70]
Hi,
thanks a lot for exchangelib! This morning I found this small error:
```
Traceback (most recent call last):
  File "./exchange.py", line 25, in <module>
    from exchangelib import Account, Credentials, Configuration, DELEGATE, NTLM
  File "...exchangelib/exchangelib/__init__.py", line 2, in <module>
    from .account import Account  # noqa
  File "...exchangelib/exchangelib/account.py", line 12, in <module>
    from .autodiscover import discover
  File "...exchangelib/exchangelib/autodiscover.py", line 29, in <module>
    from .protocol import BaseProtocol, Protocol
  File "...exchangelib/exchangelib/protocol.py", line 23, in <module>
    from .services import GetServerTimeZones, GetRoomLists, GetRooms, ResolveNames
  File "...exchangelib/exchangelib/services.py", line 31, in <module>
    from .ewsdatetime import EWSDateTime
  File "...exchangelib/exchangelib/ewsdatetime.py", line 136, in <module>
    class EWSTimeZone(object):
  File "...exchangelib/exchangelib/ewsdatetime.py", line 141, in EWSTimeZone
    PYTZ_TO_MS_MAP = _get_pytz_to_ms_map()
  File "...exchangelib/exchangelib/ewsdatetime.py", line 121, in _get_pytz_to_ms_map
    with shelve_open(PYTZ_TO_MS_MAP_PERSISTENT_STORAGE) as db:
  File "/usr/lib/python3.5/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.5/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.5/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

I can have a look into this, but I'm not sure if the cache file is meant to stay after using exchangelib.
Edit: Deleting the file made it work again.

**Comment by ecederstrand** [comment]
Hmm, did you use `exchangelib` with multiple versions of Python?

The `/tmp/exchangelib.winzone.cache.db` file is meant to stay. It holds a local cache of a CIDR database so you don't have to download it every time you import `exchangelib`.

Somehow, the file got corrupt. To solve this, just delete the file or run `EWSTimeZone.reset_cache()`.

**Comment by jspricke** [comment]
Could be that the old version was still with python2. Removing made it work.
Wouldn't it make sense to catch the exception and execute `EWSTimeZone.reset_cache()`?
