### ISSUE TITLE
Query folder structure on mailbox with large number of folders times out

### ISSUE THREAD

**Issue by jcalero** [ecederstrand/exchangelib#700]
I've been spending the last few days trying to get this use case to work:

**I need to retrieve a full list of folder names (+ids) in a mailbox.** 

In a mailbox with a small number of folders this is easily achieved with `root.walk()`, however this will time out if the mailbox contains a large number of folders, which I can understand, so I've been trying alternative, paginated approaches, but none seem to work. I would really appreciate some advice in how to approach this!

It seems that, no matter the query I do (I've tried simple `list(folder.children)` queries with a known folder I know has only 3 subfolders) the underlying logic tries to cache the _entire_ folder structure, starting from root, causing eventual timeout.

I may be tackling this issue from the wrong angle, so apologies if there's an obvious solution to this, but I haven't been able to find one yet.

**Comment by ecederstrand** [comment]
It’s correct that every normal access to the folder hierarchy will cache the entire folder hierarchy. There is no concept of stubs that are expanded as needed. If you want to avoid the caching, you can specify the path to the folder using double-slash notation (`//`).

That said, it would be interesting to find out why it’s hanging. How many folders does the mailbox have? If you enable debug logging, you should be able to get an idea of where time is spent.

**Comment by jcalero** [comment]
Thanks for the clarification, I'm slowly getting to grips with the best practices surrounding EWS.

As for my specific use-case, I'm still struggling to perform this query to it's full conclusion, but I've been logging a lot more and looking at the steps independently to get some answers. The mailbox I have has roughly 150 folders.

I can't provide a full log as there's client sensitive information, but I'm attaching some snippets.

The code I run on my end is simply:
```python
for folder in account.root.walk(): # <-- exception is raised here
    some_operation_on(folder)
```

**Abridged log from service:**
(I think the interesting bits here are from the XML which I've snipped, but I'll post a summary next. I also note that it does fetch the full list of folders but times out on the `GetFolder` request later on when it populates the folder objects with more information.)
```
2020-01-07 21:38:35,700 (exchangelib.util) [DEBUG]: Retry: 0
Waited: 10
Timeout: 120
Session: 25723
Thread: 139889888511552
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f3a9dc971d0>
URL: https://example.net:443/EWS/Exchange.asmx
HTTP adapter: <ews.service.main.<locals>.EWSAdapter object at 0x7f3a9dc97278>
Allow redirects: False
Streaming: False
Response time: 60.107063710005605
Status code: 200
Request headers: {'User-Agent': 'exchangelib/2.1.1 (python-requests/2.22.0)',
'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive',
'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox':
'MAILBOX@CLIENT.com', 'Cookie': 'exchangecookie=xxx', 'Content-Length': '48840'}
Response headers: {'Cache-Control': 'private', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/7.5', 'X-AspNet-Version': '2.0.50727', 'X-Powered-By': 'ASP.NET', 'Date': 'Tue, 07 Jan 2020 21:38:37 GMT', 'Transfer-Encoding': 'chunked'}
Request data: b'<?xml [SNIPPED DUE TO LARGE SIZE]>
Response data: b'<?xml [SNIPPED DUE TO SENSITIVE INFO] >'

2020-01-07 21:38:35,711 (exchangelib.util) [DEBUG]: Session 25723 thread 139889888511552: Useful response from https://example.net:443/EWS/Exchange.asmx
2020-01-07 21:38:35,711 (exchangelib.protocol) [DEBUG]: Server example.net:443: Releasing session 25723
2020-01-07 21:38:36,898 (exchangelib.folders.base) [DEBUG]: Fallback to class Folder (folder_class None, name Finder)
.... (Lots of other folders here) ....
2020-01-07 21:38:36,926 (exchangelib.folders.base) [DEBUG]: Fallback to class Folder (folder_class None, name Subscriptions)
2020-01-07 21:38:36,927 (exchangelib.folders.base) [DEBUG]: Fallback to class Folder (folder_class None, name Top of Information Store)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/ews/run.py", line 5, in <module>
    main()
  File "/src/ews/ews/service.py", line 557, in main
    ews_service.poll(config.mailbox_iter_limit)
  File "/src/ews/ews/service.py", line 381, in poll
    query = self._build_query(cursor)
  File "/src/ews/ews/service.py", line 155, in _build_query
    folder_collection = self._detect_folders(cursor.mailbox)
  File "/src/ews/ews/service.py", line 129, in _detect_folders
    for folder in mailbox.account.root.walk():
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/collections.py", line 42, in __iter__
    for f in self.folders:
  File "/opt/app-root/lib/python3.6/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/collections.py", line 36, in folders
    return list(self._folders)
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/base.py", line 110, in _walk
    for c in self.children:
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/collections.py", line 42, in __iter__
    for f in self.folders:
  File "/opt/app-root/lib/python3.6/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/collections.py", line 36, in folders
    return list(self._folders)
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/roots.py", line 88, in get_children
    for f in self._folders_map.values():
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/roots.py", line 165, in _folders_map
    for f in SingleFolderQuerySet(account=self.account, folder=self).depth(self.TRAVERSAL_DEPTH).all():
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/queryset.py", line 137, in _query
    for f, complex_f in zip(resolveable_folders, complex_folders):
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/folders/collections.py", line 297, in get_folders
    shape=ID_ONLY,
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/services/get_folder.py", line 31, in call
    shape=shape,
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/services/common.py", line 381, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/opt/app-root/lib/python3.6/site-packages/exchangelib/services/common.py", line 341, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorTimeoutExpired: The request timed out.
2020-01-07 21:38:37,128 (exchangelib.protocol) [DEBUG]: Server example.net:443: Closing thread pool
2020-01-07 21:38:37,128 (exchangelib.protocol) [DEBUG]: Server example.net:443: Closing sessions
```

The request it's making at the time of the timeout looks like a standard `GetFolder` request:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
    <t:ExchangeImpersonation>
      <t:ConnectingSID>
        <t:PrimarySmtpAddress>mailbox@client.com</t:PrimarySmtpAddress>
      </t:ConnectingSID>
    </t:ExchangeImpersonation>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="UTC"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:GetFolder>
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:PermissionSet"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:FolderIds>
        <t:FolderId Id="AAMkADlmMjU2OTYwLTc5ZmItNGE3Ny1iMjc4LWQzYjdmMzk4MWI3OQAuAAAAAADq+P2owTnWQKepktckv6HXAQAcQ9QRiURMQag3EvlgDnM8AAAAAbSNAAA=" ChangeKey="BwAAABYAAAAcQ9QRiURMQag3EvlgDnM8AAAAAbSQ"/>
        <t:FolderId Id="AAMkADlmMjU2OTYwLTc5ZmItNGE3Ny1iMjc4LWQzYjdmMzk4MWI3OQAuAAAAAADq+P2owTnWQKepktckv6HXAQCGi53UH8NGRZiKBNMVlY8AAAADX3QpAAA=" ChangeKey="AQAAABYAAACGi53UH8NGRZiKBNMVlY8AAAADX3Y3"/>
... dozens of FolderId's here ...
      </m:FolderIds>
    </m:GetFolder>
  </s:Body>
</s:Envelope>
```
And finally, the response, which has probably about 100 folders correctly fetched, but then fails on the subsequent 50, after a timeout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" MajorVersion="14" MinorVersion="3" MajorBuildNumber="442" MinorBuildNumber="0" Version="Exchange2010_SP2"/>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:GetFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:GetFolderResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Folders>
            <t:SearchFolder>
              <t:FolderId Id="AAMkADlmMjU2OTYwLTc5ZmItNGE3Ny1iMjc4LWQzYjdmMzk4MWI3OQAuAAAAAADq+P2owTnWQKepktckv6HXAQAcQ9QRiURMQag3EvlgDnM8AAAAAbSNAAA=" ChangeKey="BwAAABYAAAAcQ9QRiURMQag3EvlgDnM8AAAAAbSQ"/>
              <t:FolderClass>IPF</t:FolderClass>
              <t:DisplayName>AllItems</t:DisplayName>
              ... other properties ...
            </t:SearchFolder>
          </m:Folders>
        </m:GetFolderResponseMessage>
        <m:GetFolderResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Folders>
            <t:Folder>
              <t:FolderId Id="AAMkADlmMjU2OTYwLTc5ZmItNGE3Ny1iMjc4LWQzYjdmMzk4MWI3OQAuAAAAAADq+P2owTnWQKepktckv6HXAQCGi53UH8NGRZiKBNMVlY8AAAADX3QpAAA=" ChangeKey="AQAAABYAAACGi53UH8NGRZiKBNMVlY8AAAADX3Y3"/>
              <t:DisplayName>Common Views</t:DisplayName>
              ... other properties ...
            </t:Folder>
          </m:Folders>
        </m:GetFolderResponseMessage>
        ... Many more successful folders ...
        <m:GetFolderResponseMessage ResponseClass="Error">
          <m:MessageText>The request timed out.</m:MessageText>
          <m:ResponseCode>ErrorTimeoutExpired</m:ResponseCode>
          <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          <m:Folders/>
        </m:GetFolderResponseMessage>
        <m:GetFolderResponseMessage ResponseClass="Warning">
          <m:MessageText>Item was not processed as a result of a previous error.</m:MessageText>
          <m:ResponseCode>ErrorBatchProcessingStopped</m:ResponseCode>
          <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          <m:Folders/>
        </m:GetFolderResponseMessage>
        ... The remaining folder repsonses are the same as above ...
      </m:ResponseMessages>
    </m:GetFolderResponse>
  </s:Body>
</s:Envelope>
```

It doesn't give me a lot to go on, but what I suspect is, either the server is being too busy to handle the request halfway, or I'm being throttled by the server.

Is there something you would suggest I could do to mitigate these timeouts?

**Comment by jcalero** [comment]
Just a quick update on this.

Seeing as how the operation that fails is `GetFolder`, while `FindFolder` seems to finish fairly quickly without issue I also noticed that `GetFolder` is not batched, while `FindFolder` is. So I thought I'd try to bypass the `GetFolder` operation in the meantime to see if I can perform my query without it.

What I did was essentially this:

```python
account = Account(...)
# At this point GetFolder is called twice but with only 1 folder
# each time, so is quick and doesn't build the folder cache.
top_folder = account.root // "Top of Information Store"

collection = FolderCollection(account=account, folders=[top])
# At this point I can actually paginate the request to EWS if needed
folders = list(collection.find_folders(q=Q(folder_class="IPF.NOTE")))

collection = FolderCollection(account=account, folders=folders)
# Now I can perform the queries on "all folders" without having run
# 'GetFolders' on every single folder.
query = collection.all().only('subject')  # example 
```

I have not been able to run this on the failing mailbox yet as that's unacceptable to me at the moment, but will report back if it has solved my issue.

Regardless, I thought it worth mentioning my progress, and maybe something worth noting in the README in regards to operations in very large mailboxes? The `GetFolder` operation you do on _every single folder_ seems needlessly expensive when it doesn't seem to be strictly necessary in all cases. I could perfectly well be misunderstanding the use of the library though.

**Comment by ecederstrand** [comment]
Oh, are you seeing one `GetFolder` request Per folder? That’s definitely not intended.

**Comment by jcalero** [comment]
@ecederstrand, no no, I'm not, sorry for the confusion, I'm seeing one GetFolder request for an entire batch, but those batches get very large and aren't paginated so can time out as you can see in the XML response I posted above, which is why I'm trying to work around that.

**Comment by ecederstrand** [comment]
I just make GetFolder split into multiple requests. Can you please test if that improves the situation?

Anyway, I agree that this part of exchangelib can be improved. It's sort of all-or-nothing right now.

**Comment by jcalero** [comment]
https://github.com/ecederstrand/exchangelib/commit/57df618ba27427cf08a66c292ac4a60615b823e5 This is great! I gave it a go and it works, as expected, 100 folders is a reasonable page size and I think it will be the right amount.

I'd be keeping an eye out for when it's merged into a release so I can ship it with my service, thanks a lot for the quick turnaround!

**Comment by ecederstrand** [comment]
Good to hear. I assume we can close this issue?

**Comment by jcalero** [comment]
Yep, fine by me!
