### ISSUE TITLE
1.7.6 - problem with UTC timezone

### ISSUE THREAD

**Issue by AltruisConsulting** [ecederstrand/exchangelib#71]
Firstly, I love this package. Thank you very much!

I have been using 1.7.5 on my local for development purposes, which was working perfectly fine. I'm running Python 2.7.12.

I did a simply pip install exchangelib on my heroku instance in order to test sending/receiving emails from the console and it failed on a simple 'import exchangelib'. Here is the full traceback:

```
>>> import exchangelib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/__init__.py", line 2, in <module>
    from .account import Account  # noqa
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/account.py", line 15, in <module>
    from .folders import Root, Calendar, DeletedItems, Drafts, Inbox, Outbox, SentItems, JunkEmail, Tasks, Contacts, \
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/folders.py", line 20, in <module>
    from .ewsdatetime import EWSDateTime, UTC, UTC_NOW
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 191, in <module>
    UTC = EWSTimeZone.timezone('UTC')
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 178, in timezone
    return cls.from_pytz(tz)
  File "/app/.heroku/python/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 159, in from_pytz
    raise_from(ValueError('No Windows timezone name found for timezone "%s"' % tz.zone), e)
  File "/app/.heroku/python/lib/python2.7/site-packages/future/utils/__init__.py", line 454, in raise_from
    raise e
ValueError: No Windows timezone name found for timezone "UTC"

```

The issue was solved by uninstalling 1.7.6 and reinstalling 1.7.5, so not a huge issue for me, but I thought you might like to know.

**Comment by ecederstrand** [comment]
Thanks for the kind words!

This is due to a fragile implementation of the caching of some Windows timezone names from CIDR.

You should be able to get around the issue by running this in a shell before importing exchangelib:

```python
import os
os.remove(os.path.join(tempfile.gettempdir(), 'exchangelib.winzone.cache.db'))
```

The cache file should re-generate upon next import. I'll try to find a better solution in for the next release.

**Comment by ecederstrand** [comment]
This should be fixed by https://github.com/ecederstrand/exchangelib/commit/d766796715f11d9e5f2650d0a8e99c4752a6bd70. I just released version 1.8.0 containing the fix.

**Comment by AltruisConsulting** [comment]
Thank you!

**Comment by ecederstrand** [comment]
I managed to totally botch the 1.8.0 release. Try 1.8.1 instead :-)

**Comment by ticapix** [comment]
Hi,

I hitting the same issue with exchangelib==1.9.4

```shell
/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/__init__.py
Traceback (most recent call last):
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/ewsdatetime.py", line 156, in from_pytz
    self_cls.ms_id = cls.PYTZ_TO_MS_MAP[tz.zone]
KeyError: 'local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 28, in <module>
    account = Account(primary_smtp_address=primary_smtp_address, credentials=credentials, autodiscover=True, access_type=DELEGATE)
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/account.py", line 72, in __init__
    self.default_timezone = default_timezone or EWSTimeZone.localzone()
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/ewsdatetime.py", line 173, in localzone
    return cls.from_pytz(tz)
  File "/mnt/c/Users/pgronlie/workspace/outlook-givememail/venv3/lib/python3.4/site-packages/exchangelib/ewsdatetime.py", line 158, in from_pytz
    raise ValueError('No Windows timezone name found for timezone "%s"' % tz.zone)
ValueError: No Windows timezone name found for timezone "local"
```

**Comment by ticapix** [comment]
In my case, it seems to be an issue with not getting current timezone on WSL (Windows Subsystem for Linux): https://github.com/HowardHinnant/date/issues/102
I got it fixed by running `sudo dpkg-reconfigure tzdata`
