### ISSUE TITLE
Autodiscover failing in versions >=3.0.0

### ISSUE THREAD

**Issue by Austin-Schmidli** [ecederstrand/exchangelib#718]
Autodiscover is working as expected in 2.1.0 and 2.2.0. However on 3.0.0, 3.1.0, 3.1.1, the same code fails.

Code sample:
```
credentials = exchangelib.Credentials(username, password)
account = exchangelib.Account(primary_smtp_address=email_address, credentials=credentials, access_type=exchangelib.DELEGATE, autodiscover=True)
```

Resultant Error:
```
DEBUG:exchangelib.util:No retry: wrong status code 200
DEBUG:exchangelib.util:Session 25743 thread 140734995797440: Useful response from https://autodiscover.***.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.protocol:Server autodiscover.***.com: Releasing session 25743
INFO:exchangelib.autodiscover.discovery:Step 5: Checking response
DEBUG:exchangelib.autodiscover.discovery:Released autodiscover_cache_lock
Traceback (most recent call last):
  File "local/exch.py", line 13, in <module>
    account = exchangelib.Account(primary_smtp_address=email_address, credentials=credentials, access_type=exchangelib.DELEGATE, autodiscover=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exchangelib/account.py", line 86, in __init__
    email=primary_smtp_address, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exchangelib/autodiscover/discovery.py", line 24, in discover
    email=email, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exchangelib/autodiscover/discovery.py", line 113, in discover
    return self._build_response(ad_response=ad_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/exchangelib/autodiscover/discovery.py", line 139, in _build_response
    if protocol.ews_url.lower() == ews_url.lower() and protocol.server_version:
AttributeError: 'NoneType' object has no attribute 'lower'
DEBUG:exchangelib.autodiscover.cache:Domain ***.com: Closing sessions
DEBUG:exchangelib.protocol:Server autodiscover.***.com: Closing sessions
DEBUG:exchangelib.protocol:Server autodiscover.***.com: Closing sessions
```
(Company name redacted)

Let me know if there's any further information I can provide to help debug this issue.

**Comment by ecederstrand** [comment]
Just committed a  fix to the immediate problem. Let me know if you still can't autodiscover the address.

**Comment by Austin-Schmidli** [comment]
It looks like that has fixed the issue!
