### ISSUE TITLE
Get Delegates Not working

### ISSUE THREAD

**Issue by valouvaliavlo** [ecederstrand/exchangelib#726]
Hello, 
I've test delegate but it's not working.
The credentials are fine, tested with python3 and python2.7.

The Code :
```python
from exchangelib import Credentials, Account

credentials = Credentials('mail', 'password')
account = Account('mail', credentials=credentials, autodiscover=True)

print(account.delegates)
```

The result : 
```
Traceback (most recent call last):
  File "./get_delegate.py", line 8, in <module>
    print(account.delegates)
  File "/home/valentin/.local/lib/python2.7/site-packages/exchangelib/account.py", line 630, in delegates
    return list(GetDelegate(account=self).call(user_ids=None, include_permissions=True))
  File "/home/valentin/.local/lib/python2.7/site-packages/exchangelib/services/get_delegate.py", line 23, in call
    include_permissions=include_permissions,
  File "/home/valentin/.local/lib/python2.7/site-packages/exchangelib/services/common.py", line 512, in _pool_requests
    for chunk in chunkify(items, self.chunk_size):
  File "/home/valentin/.local/lib/python2.7/site-packages/exchangelib/util.py", line 109, in chunkify
    for i in iterable:
TypeError: 'NoneType' object is not iterable
```

**Comment by ecederstrand** [comment]
Thanks. This is a bug. I'll have a fix ready later today.

**Comment by valouvaliavlo** [comment]
Hello, 
I come to test and this seem to not work.
I've exchange account in OVH, when i run this script i've no delegate.
But with an account where the calendar is in delegate mode i've a result but not for a delegate of entire mailbox.

**Comment by ecederstrand** [comment]
Can you add debug logging so you can see the XML being sent and received? It's possible that we are not asking for the right information, or not parsing the entire response.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you can provide the debugging info needed.
