### ISSUE TITLE
TypeError: String or Integer object expected for key, unicode found

### ISSUE THREAD

**Issue by ocgariando** [ecederstrand/exchangelib#73]
Hi

Thanks you in advance and thank you for this exchangelib

Before this error i got ValueError: No Windows timezone name found for timezone "UTC"
it was fixed when i remove the exchangelib.winzone.cache

then i got this error blow.  This was running on my mac development PC. but did not work on Censtosh 

Traceback (most recent call last):
  File "/home/xx/run_email_services.py", line 3, in <module>
    from exchangelib import DELEGATE, Account, Credentials
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/__init__.py", line 2, in <module>
    from .account import Account  # noqa
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/account.py", line 15, in <module>
    from .folders import Root, Calendar, DeletedItems, Drafts, Inbox, Outbox, SentItems, JunkEmail, Tasks, Contacts, \
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/folders.py", line 20, in <module>
    from .ewsdatetime import EWSDateTime, UTC, UTC_NOW
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 136, in <module>
    class EWSTimeZone(object):
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 141, in EWSTimeZone
    PYTZ_TO_MS_MAP = _get_pytz_to_ms_map()
  File "/home/xx/venv/local/lib/python2.7/site-packages/exchangelib/ewsdatetime.py", line 129, in _get_pytz_to_ms_map
    db['UTC'] = str('UTC')
  File "/usr/lib64/python2.7/shelve.py", line 133, in __setitem__
    self.dict[key] = f.getvalue()
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 279, in __setitem__
    _DeadlockWrap(wrapF)  # self.db[key] = value
  File "/usr/lib64/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib64/python2.7/bsddb/__init__.py", line 278, in wrapF
    self.db[key] = value
TypeError: String or Integer object expected for key, unicode found

**Comment by ecederstrand** [comment]
Thanks for the report. Your best bet is to downgrade to 1.7.5. I'll commit a more robust Windows timezone cache in 1.7.7.

**Comment by ocgariando** [comment]
Hi 
Hi ecederstrand

Its work on 1.7.5 version 

Made some small changes 
account.py      
-init-
add this
if self.locale is not None:
            assert isinstance(self.locale, string_types)

-- due to schema error
services.py - I used the 1.7.6 version

Thanks
Os

**Comment by ecederstrand** [comment]
This should be fixed by https://github.com/ecederstrand/exchangelib/commit/d766796715f11d9e5f2650d0a8e99c4752a6bd70. I just released version 1.8.0 containing the fix.
