### ISSUE TITLE
python Is it possible to convert item.datetime_received to localtimezone

### ISSUE THREAD

**Issue by pythonRookie94** [ecederstrand/exchangelib#730]
```
    # date
    date_initial = datetime.now()
    date_year = int((date_initial.strftime("%Y")))
    date_month = int((date_initial.strftime("%-m")))
    date_day = int((date_initial.strftime("%-d")))
    print(date_year)
    print(date_month)
    print(date_day)
    
    # file name
    file_date_val = datetime.now() - timedelta(days=1)
    file_path = "/home/shivam/PycharmProjects/Exchange2/Logs/"
    file_date = (file_date_val.strftime("%m-%d-%Y"))
    text = " - sent report full.txt"
    fileName = file_path+file_date + text
    
    start_localTz=account.default_timezone.localize(EWSDateTime(year=date_year, month=date_month, day=date_day)) - timedelta(days=1)
    end_localTz=account.default_timezone.localize(EWSDateTime(year=date_year, month=date_month, day=date_day))
    print(start_localTz)
    print(end_localTz)
    
    #gather information on top email in the sent mailbox ordered by datetime received
    for item in account.sent.all().order_by('-datetime_received')[:1]:
    
            date = item.datetime_received
            print(date)
    
            #convert item.datetime_received to local timezone
            date_rcvd = account.default_timezone(EWSDateTime(item.datetime_received))
            print(date_rcvd)
```

the output of this give me 

```
    2020
    3
    10
    2020-03-09 00:00:00-04:00
    2020-03-10 00:00:00-04:00
    2020-03-10 19:42:24+00:00
    Traceback (most recent call last):
      File "test.py", line 63, in <module>
        date_rcvd = account.default_timezone(EWSDateTime(item.datetime_received))
      File "/home/shivam/PycharmProjects/Exchange2/venv/lib64/python3.6/site-packages/exchangelib/ewsdatetime.py", line 97, in __new__
        return super().__new__(cls, *args, **kwargs)
    TypeError: an integer is required (got type EWSDateTime)

```
when i ran this script before daylight saving went into affect (this does not include the error I get above as of right now as its the same)

```
    2020-03-05 00:00:00-05:00
    2020-03-06 00:00:00-05:00
```

So what I am having difficulties is with converting the time to UTC since the exchangelib library outputs datetime_received as UTC. When the script runs I need the datetime_received (exchangelib) converted to UTC. I need the script to be able to convert from Eastern Standard Time or Eastern Daylight Time to the correct UTC time. Also I am very new to python and I am creating a script to check all emails in the sent box of a shared calendar and this is the last hurdle I need to cross.

**Comment by ecederstrand** [comment]
You ar not converting datetimes correctly. The timezone implementation in exchangelib is based on `pytz`.  When you want to translate a timezone-aware datetime to a different timezone, use the `.astimezone()` method:

```python
localized_date = item.datetime_received.astimezone(account.default_timezone)
```

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have issues with the suggested approach.

**Comment by adisidis** [comment]
@ecederstrand Does this mean that item.datetime_received is UTC?

**Comment by ecederstrand** [comment]
@adisidis Just print it out and see for yourself. It should state its timezone.
