### ISSUE TITLE
Exception in _get_elements: Traceback (most recent call last):  ... site-packages\cached_property.py", line 69, in __get__     return obj_dict[name] KeyError: 'sent'

### ISSUE THREAD

**Issue by h888866j** [ecederstrand/exchangelib#744]
### KeyError: 'sent'
I searched around, but did not find similar issue on the web.
Issue is not persistent, my colleague have met this error several times, and today I met an error quite similar this one. `KeyError: 'sent'`. Error was triggered when i tried to use send_and_save method of Items. Before I sent email, I used this lib to retrieve some emails from inbox folder, all succeed.  

Actually the error i met today is a little bit different from the one posted here. The one here is from my colleague.  I forgot to pasted errors to notepad++ but forget to save and no autosaved version found as well. But the error itself is quite the same....the `KeyError: 'sent'` of cached_property, the `m.send_and_save()` throw error.

I tried to run script again, all working then....

When I met this error next time or get another error report from my colleague, I will post it here. 

```
EWS https://mail.yyy.com/ews/exchange.asmx, account xxx@yyy.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'sent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\services\common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\services\common.py", line 128, in _get_response_xml
    r, session = post_ratelimited(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 724, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 796, in _raise_response_errors
    raise response.headers['TimeoutException']
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 677, in post_ratelimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT,
 File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Traceback (most recent call last):
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'sent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user01\Documents\ETautomation\bin\bin.py", line 386, in <module>
    b.send_mail(
  File "C:\Users\user01\Documents\ETautomation\module\email_check.py", line 133, in send_mail
    m.send_and_save()
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\items.py", line 759, in send_and_save
    res = self._create(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\items.py", line 288, in _create
    res = self.account.bulk_create(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\account.py", line 378, in bulk_create
    folder = self.sent  # 'Sent' is default EWS behaviour
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\account.py", line 249, in sent
    return self.root.get_default_folder(SentItems)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\roots.py", line 216, in get_default_folder
    return super(Root, self).get_default_folder(folder_cls)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\roots.py", line 122, in get_default_folder
    return folder_cls.get_distinguished(root=self)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\base.py", line 612, in get_distinguished
    return cls.resolve(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\base.py", line 501, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\collections.py", line 234, in resolve
    for f in self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\folders\collections.py", line 294, in get_folders
    for f in GetFolder(account=self.account).call(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\services\get_folder.py", line 28, in call
    for folder, elem in zip(folders_list, self._get_elements(payload=self.get_payload(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\services\common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\services\common.py", line 128, in _get_response_xml
    r, session = post_ratelimited(
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 724, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 796, in _raise_response_errors
    raise response.headers['TimeoutException']
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\exchangelib\util.py", line 677, in post_ratelimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT,
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user01\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

```

**Comment by ecederstrand** [comment]
The `KeyError` is misleading and is just an artifact of `account.sent` being a property that is in the process of being cached. What is interesting is the `ConnectionResetError` which means that your server kicked you out.

Your server may be throttling your account if you are sending too many requests or have too many connections open to the server. In that case, try scaling down or asking your Exchange admin to change the throttling policy for your account.

You can also handle infrequent failures gracefully by configuring a retry policy. See https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by h888866j** [comment]
@ecederstrand , thanks for the advice. 

I pragmatically searching emails(23 in total) in a folder and try to parse the only email that matched with certain search condition.  Is there a way to close the connections I opened? I will try your advice to add retry policy and get back to you later.

BTW,  another team member received this error. She(and we) then retried to run the script, this error is not seen, script running smoothly.

```
EWS https://mail.yyy.com/ews/exchange.asmx, account xxx@yyy.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'sent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\services\common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\services\common.py", line 135, in _get_response_xml
    stream=self.streaming,
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\util.py", line 724, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\util.py", line 796, in _raise_response_errors
    raise response.headers['TimeoutException']
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\util.py", line 678, in post_ratelimited
    stream=stream)
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user3\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.Connectio
``

**Comment by ecederstrand** [comment]
I looks like the stack trace got cut off, but looks like a timeout error. This and other connection errors can happen *very* frequently on busy servers. exchangelib can handle them via a retry policy, but you can also handle them yourself, if you prefer.

Connections are closed automatically on standard Python garbage collection. Connections are attached to the `account.protocol` object. You can also call `account.protocol.close()` to close connections to a specific email server, or `exchangelib.close_connections()` to have *all* connections to any server closed.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this did not solve your issue.

**Comment by h888866j** [comment]
Just as a feedback, adding retry policy fixed the error.
@ecederstrand Thank you very much.
