### ISSUE TITLE
Timezone error upgrading from 1.7.4 to 3.2.0

### ISSUE THREAD

**Issue by pekh** [ecederstrand/exchangelib#760]
Hi!

I had to upgrade exchangelib after a LONG time in a project today, and now I get the following error:

```
Traceback (most recent call last):
  File "iaa_tools.py", line 103, in <module>
    update(**arguments)
  File "iaa_tools.py", line 76, in update
    update_status=update_status)
  File "/usr/src/app/iaa/main.py", line 82, in update
    data = conn.get_data(BEGIN, END, employees, stale_status)
  File "/usr/src/app/iaa/connectors/exchange.py", line 65, in get_data
    for item in items:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 286, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 371, in _item_yielder
    for i in iterable:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 574, in fetch
    item = validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items/calendar_item.py", line 220, in from_xml
    setattr(item, field_name, val.astimezone(tz).date())
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 127, in astimezone
    return self.from_datetime(t)  # We want to return EWSDateTime objects
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 120, in from_datetime
    tz = EWSTimeZone.from_pytz(d.tzinfo)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/ewsdatetime.py", line 242, in from_pytz
    self_cls = type(cls.__name__, base_classes, dict(tz.__class__.__dict__))
TypeError: type 'datetime.timezone' is not an acceptable base type
```
BEGIN and END are initialized as follows:

```
NOW = LOCT.localize(datetime.now()).astimezone(UTC)
BEGIN = LOCT.localize(datetime.combine(NOW, time(0))).astimezone(UTC)
END = LOCT.localize(datetime.combine(
                                   NOW + timedelta(days=7), time(23, 59))).astimezone(UTC)
```
where LOCT is a pytz.timezone ('Europe/Copenhagen')

While this always seemed awkward to me, it seemed to be the only way to get the correctly localized date.

What do I have to change to get my code working again?

Greetings,

Jan-Peer

**Comment by pekh** [comment]
I downgraded to 3.1.0, and my code runs again flawlessly. So there seems to be a bug or incompatible change somewhere in between.

**Comment by ecederstrand** [comment]
What is UTC here?

Can you please post a full, minimal example that triggers the error? It's difficult to reproduce with just the above code.

**Comment by pekh** [comment]
UTC is pytz.UTC;
I'll try to strip the code, but as I'm running out of time, it will probably take some days.

**Comment by ecederstrand** [comment]
Ok. I haven't checked, but I think `EWSTimeZone.astimezone()` requires an `EWSTimeZone` instance. You can use `exchangelib.UTC` instead of `pytz.UTC`.

**Comment by ecederstrand** [comment]
Looking again at the stacktrace, it seems you may be setting a value for `Account.default_timezone` that is not a pytz timezone, but rather a `default_timezone` instance.

**Comment by ecederstrand** [comment]
Closing, as I think you have provided a `datetime.timezone` somewhere in your code, but exchangelib only accepts `ptyz` timezones. If you disagree, feel free to reopen and provide a full, minimal example showing the error.
