### ISSUE TITLE
401 error when running from Linux and Mac but working fine from Windows 

### ISSUE THREAD

**Issue by leoseccia** [ecederstrand/exchangelib#761]
When we run the code below in Linux (Ubuntu via WSL) or Mac, we get a 401 error. In Windows, it works fine. Both environments use Python v3.7.4

```python
from exchangelib import Credentials, Account, Configuration, DELEGATE

import logging
from exchangelib.util import PrettyXmlHandler

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

credentials = Credentials('account@somedomain.net', 'password')
config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account(primary_smtp_address='mailbox@somedomain.net',
            config=config,
            autodiscover=False,
            access_type=DELEGATE
            )

for item in account.inbox.all().order_by('-datetime_received')[:2]:
    print(item.subject, item.sender, item.datetime_received)
```

Debug trace from Linux:

```
WARNING:exchangelib.account:No Windows timezone name found for timezone "local". Fallback to UTC
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://outlook.office365.com/EWS/Exchange.asmx', Credentials('account@somedomain.net', '********'))'
DEBUG:exchangelib.transport:Requesting b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>account@somedomain.net</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>' from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Trying to get service auth type for https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.office365.com:443
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'exchangelib/3.2.0 (python-requests/2.23.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '473'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/10.0', 'request-id': 'f23966f9-68f1-4a82-8b56-c25b52b77136', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'LO2P265CA0154', 'WWW-Authenticate': 'Basic Realm=""', 'Date': 'Thu, 28 May 2020 16:22:29 GMT', 'Content-Length': '0'}
DEBUG:exchangelib.transport:realm: 
DEBUG:exchangelib.transport:Auth type is basic
DEBUG:exchangelib.protocol:Server outlook.office365.com: Created session 22005
DEBUG:exchangelib.version:Asking server for version info using API version Exchange2019
DEBUG:exchangelib.services.common:Trying API version Exchange2019
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session 22005
DEBUG:exchangelib.util:Session 22005 thread 140194703675520: retry 0 timeout 120 POST'ing to https://outlook.office365.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.office365.com:443
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 22005
Thread: 140194703675520
Auth type: <requests.auth.HTTPBasicAuth object at 0x7f8196ae0890>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f8196ae0ad0>
Allow redirects: False
Streaming: False
Response time: 0.6830174000024272
Status code: 401
Request headers: {'User-Agent': 'exchangelib/3.2.0 (python-requests/2.23.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '473', 'Authorization': 'Basic c3ZjLWxlZ2xuZ3lvdXJjQGxlZ2FsLnJlZ24ubmV0OldlbGNvbWVANjIwMQ=='}
Response headers: {'Server': 'Microsoft-IIS/10.0', 'request-id': 'e9b6b437-a13a-49c8-a4a9-5eb273452b47', 'X-CalculatedFETarget': 'SN6PR2101CU001.internal.outlook.com', 'X-BackEndHttpStatus': '401, 401', 'Set-Cookie': 'exchangecookie=926f119ddd464136bef6257a39cfe747; expires=Fri, 28-May-2021 16:22:29 GMT; path=/; secure; HttpOnly', 'X-FEProxyInfo': 'SN6PR2101CA0022.NAMPRD21.PROD.OUTLOOK.COM', 'X-CalculatedBETarget': 'SN6PR08MB4671.namprd08.prod.outlook.com', 'X-RUM-Validated': '1', 'X-BeSku': 'WCS5', 'X-DiagInfo': 'SN6PR08MB4671', 'X-BEServer': 'SN6PR08MB4671', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '401', 'X-FEServer': 'SN6PR2101CA0022, LO2P265CA0478', 'X-Powered-By': 'ASP.NET', 'WWW-Authenticate': 'Basic Realm=""', 'Date': 'Thu, 28 May 2020 16:22:29 GMT', 'Content-Length': '0'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2019"/>
  </s:Header>
  <s:Body>
    <m:ResolveNames ReturnFullContactData="false">
      <m:UnresolvedEntry>account@somedomain.net</m:UnresolvedEntry>
    </m:ResolveNames>
  </s:Body>
</s:Envelope>

Response data: b''

DEBUG:exchangelib.util:No retry: no fail-fast policy
DEBUG:exchangelib.protocol:Server outlook.office365.com: Retiring session 22005
DEBUG:exchangelib.protocol:Server outlook.office365.com: Created session 25674
DEBUG:exchangelib.protocol:Server outlook.office365.com: Releasing session 25674
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    access_type=DELEGATE
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/account.py", line 125, in __init__
    self.version = self.protocol.version
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/protocol.py", line 420, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/version.py", line 226, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/services/resolve_names.py", line 32, in call
    contact_data_shape=contact_data_shape,
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/services/common.py", line 84, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/services/common.py", line 162, in _get_response_xml
    stream=self.streaming,
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/util.py", line 770, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/home/my_user/tmp_exchange_test/venv/lib/python3.7/site-packages/exchangelib/util.py", line 847, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server outlook.office365.com: Closing sessions
```

Debug trace from Windows:
```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://outlook.office365.com/EWS/Exchange.asmx', Credentials('account@somedomain.net', '********'))'
DEBUG:exchangelib.transport:Requesting b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>account@somedomain.net</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>' from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Trying to get service auth type for https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.office365.com:443
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'exchangelib/3.2.0 (python-requests/2.23.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '473'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/10.0', 'request-id': 'b2587a45-8895-42bd-948d-d10285d707ea', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'LO2P265CA0221', 'WWW-Authenticate': 'Basic Realm=""', 'Date': 'Thu, 28 May 2020 15:13:25 GMT', 'Content-Length': '0'}
DEBUG:exchangelib.transport:realm:
DEBUG:exchangelib.transport:Auth type is basic
DEBUG:exchangelib.protocol:Server outlook.office365.com: Created session 24897
DEBUG:exchangelib.version:Asking server for version info using API version Exchange2019
DEBUG:exchangelib.services.common:Trying API version Exchange2019
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session 24897
DEBUG:exchangelib.util:Session 24897 thread 25680: retry 0 timeout 120 POST'ing to https://outlook.office365.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.office365.com:443
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 500 753
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 24897
Thread: 25680
Auth type: <requests.auth.HTTPBasicAuth object at 0x0000026562E8E508>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000026562E80FC8>
Allow redirects: False
Streaming: False
Response time: 0.26599999999962165
Status code: 500
Request headers: {'User-Agent': 'exchangelib/3.2.0 (python-requests/2.23.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '473', 'Authorization': 'Basic c3ZjLWxlZ2xuZ3lvdXJjQGxlZ2FsLnJlZ24ubmV0OldlbGNvbWVANjIwMQ=='}
Response headers: {'Cache-Control': 'private', 'Content-Length': '753', 'Content-Type': 'text/xml; charset=utf-8', 'Server': 'Microsoft-IIS/10.0', 'request-id': 'de4b882c-74e8-4ca3-aa92-8415cde10df6', 'X-CalculatedFETarget': 'SA9PR11CU001.internal.outlook.com', 'X-BackEndHttpStatus': '500, 500', 'Set-Cookie': 'exchangecookie=a4fb80a1756d4b4a99c58cc4c208df9a; expires=Fri, 28-May-2021 15:13:25 GMT; path=/; secure; HttpOnly', 'X-FEProxyInfo': 'SA9PR11CA0013.NAMPRD11.PROD.OUTLOOK.COM', 'X-CalculatedBETarget': 'SN6PR08MB4671.namprd08.prod.outlook.com', 'X-RUM-Validated': '1', 'X-AspNet-Version': '4.0.30319', 'X-BeSku': 'WCS5', 'X-DiagInfo': 'SN6PR08MB4671', 'X-BEServer': 'SN6PR08MB4671', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '500', 'X-FEServer': 'SA9PR11CA0013, LO2P265CA0219', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 28 May 2020 15:13:25 GMT'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2019"/>
  </s:Header>
  <s:Body>
    <m:ResolveNames ReturnFullContactData="false">
      <m:UnresolvedEntry>account@somedomain.net</m:UnresolvedEntry>
    </m:ResolveNames>
  </s:Body>
</s:Envelope>

Response data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <Action xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none" s:mustUnderstand="1">*</Action>
  </s:Header>
  <s:Body>
    <s:Fault>
      <faultcode
    xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidServerVersion</faultcode>
      <faultstring xml:lang="en-US">The specified server version is invalid.</faultstring>
      <detail>
        <e:ResponseCode
    xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidServerVersion</e:ResponseCode>
        <e:Message
    xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The specified server version is invalid.</e:Message>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>


DEBUG:exchangelib.util:No retry: wrong status code 500
DEBUG:exchangelib.util:Got status code 500 but trying to parse content anyway
DEBUG:exchangelib.util:Session 24897 thread 25680: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server outlook.office365.com: Releasing session 24897
DEBUG:exchangelib.services.common:Failed to update version info (No ServerVersionInfo in header: '<s:Header xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><Action xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none" s:mustUnderstand="1">*</Action></s:Header>')
DEBUG:exchangelib.services.common:API version Exchange2019 was invalid
DEBUG:exchangelib.services.common:Trying API version Exchange2016
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session 24897
DEBUG:exchangelib.util:Session 24897 thread 25680: retry 0 timeout 120 POST'ing to https://outlook.office365.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 24897
Thread: 25680
Auth type: <requests.auth.HTTPBasicAuth object at 0x0000026562E8E508>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000026562E80FC8>
Allow redirects: False
Streaming: False
Response time: 0.18799999999828287
Status code: 200

and then continues on...
```

How do we fix it?

**Comment by ecederstrand** [comment]
That's really wierd. The exchangelib and requests package versions are the same in both requests, the endpoint is the same, the HTTP body and headers are the same, and judging by the HTTP auth headers the username and password is also the same, and there is nothing special in exchangelib that depends on the OS vendor.

The only thing I can think of is that your Exchange server somehow restricts clients based on IP address or OS vendor. Are you able to connect to the Exchange server from the same Linux or OS X machines using other clients, e.g. Evolution, Office etc.?

**Comment by leoseccia** [comment]
@ecederstrand - I have been thinking along the same lines so I did some more testing and found that the following code manifests the same issue (as in it will work in Windows but not in Linux):

```
import requests
# WARNING: You should point this to your cert file for the server to actually
# verify the host. Skips verification if set to false
CERT_FILE = False
authed_session = requests.Session()
# Add your credentials
authed_session.auth = ('account@somedomain.net', 'password')
# Cert verification, will not verify on false
authed_session.verify = CERT_FILE
authed_session.headers.update({'User-Agent': 'exchangelib/3.2.0 (python-requests/2.23.0)'})
# Fetch the actual data
fetched_data = authed_session.get('https://outlook.office365.com/EWS/Exchange.asmx')
print(fetched_data)
```

**Comment by ecederstrand** [comment]
Does disabling TLS validation make a difference here?

**Comment by leoseccia** [comment]
@ecederstrand - `verify=False` does not help however something else does... If I do a `nslookup outlook.office365.com` get the first IP and replace the domain with the IP in the code, then it works...

`nslookup` from the same machine (WSL)

Any ideas?

**Comment by ecederstrand** [comment]
Does outlook.office365.com resolve to the same IP in all environments?

**Comment by leoseccia** [comment]
nslookup addresses change every time the command is ran

**Comment by leoseccia** [comment]
In `exchangelib` using the ip address and ignoring TLS errors works.

```
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
# Tell exchangelib to use this adapter class instead of the default
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
```

**Comment by leoseccia** [comment]
@ecederstrand - Thank you Erik, it is super nice of you to help us out with this issue. I will try all four IP addresses we get. We are behind a corporate VPN, so it could be that... It is a pretty weird issue, though. 🤔

**Comment by leoseccia** [comment]
Quick update - I tried all four IPs I got from a nslookup and they all worked... I wonder whether it could be an issue with IPv6.,. I'll let you know if I figure out anything else.

**Comment by ecederstrand** [comment]
@leoseccia Did you get anywhere with this?

Looking at our previous exchange, I think the issue lies outside exchangelib.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think we can do something in exchangelib to solve this problem.

**Comment by leoseccia** [comment]
@ecederstrand - sorry, we still didn't get to the bottom of this... You are right though, this is not an `exchangelib` problem. Thank you for all your help.
