### ISSUE TITLE
Code gets stuck at Account object creation

### ISSUE THREAD

**Issue by Abhi-1504** [ecederstrand/exchangelib#766]
I am trying to access mails from mailbox hosted on EWS server using the module. It's managed by my organisation.

It was woking fine 1-2 weeks back but now it gets stuck at **Account object creation while trying to make a connection and retrieve the information**. I believe this to be the issue of something blocking the connection and not with the code, need better insights. 

Below is the stack I get when I send a keyboard interrupt. Let me know if any further information is needed.

`Traceback (most recent call last):
  File "Test_Mail.py", line 43, in <module>
    account = Account(primary_smtp_address='xxx@xxx.com', config=config, credentials=credentials, autodiscover=True, access_type=DELEGATE)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 86, in __init__
    email=primary_smtp_address, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/autodiscover/discovery.py", line 24, in discover
    email=email, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/autodiscover/discovery.py", line 99, in discover
    ad_response = self._step_1(hostname=domain)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/autodiscover/discovery.py", line 329, in _step_1
    is_valid_response, ad = self._attempt_response(url=url)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/autodiscover/discovery.py", line 288, in _attempt_response
    auth_type, r = self._get_unauthenticated_response(url=url)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/autodiscover/discovery.py", line 230, in _get_unauthenticated_response
    r = getattr(s, method)(**kwargs)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt`

**Comment by ecederstrand** [comment]
Autodiscovery may take quite a while, especially if there are unresponsive servers in the list of servers that are attempted. There's a default timeout of 10 seconds for each autodiscover step (see https://github.com/ecederstrand/exchangelib/blob/aa2b161305731eebb787d1269115df0ca9eb24a2/exchangelib/autodiscover/protocol.py#L6), and there could be 10 or more steps, depending on how many times you are redirected. It should complete eventually, but it could take up to 5 minutes.

If you enable debug logging, you can see which steps in the autodiscover protocol are taken.

**Comment by ecederstrand** [comment]
If your code works with a hardcoded username and password, then I don't think this is an issue with exchangelib. I'd suggest starting a debugger to find out why your values are different in the failing example.

**Comment by Abhi-1504** [comment]
Thanks for the response, I am quite new to this library. Are you referring to enable logging in the exchangelib functions, if so is there parameter to set so?

**Comment by ecederstrand** [comment]
No, I'm talking about setting a [breakpoint()](https://docs.python.org/3/library/functions.html#breakpoint) where you first pick up the username and password values, and using https://docs.python.org/3/library/pdb.html to inspect the values.

**Comment by Abhi-1504** [comment]
> No, I'm talking about setting a [breakpoint()](https://docs.python.org/3/library/functions.html#breakpoint) where you first pick up the username and password values, and using https://docs.python.org/3/library/pdb.html to inspect the values.

Thanks for the help. The issue was rather an embarrassing one, there was a typo in the username given in the config file and hence authorisation error occurred. It's working fine now.

Thanks again for all the help. I am closing this issue.
