### ISSUE TITLE
How to propose meeting time correctly?

### ISSUE THREAD

**Issue by denisovkv** [ecederstrand/exchangelib#769]
Hello! I want to be able to propose meeting time. So I perform something like:

```python
event = account.calendar.get(id=event_id)
event.decline(
    proposed_start=start,
    proposed_end=end
)
```

from attendee account.

Then I find this message with time proposition in organizer mailbox. It is an instance of MeetingResponse. This object has `associated_calendar_item_id` field with `AssociatedCalendarItemId` instance in it.

I tried to find this message by this field to get `changekey` of event in hope this event has proposed time so i could update old event
```python
items = account.inbox.all().filter(associated_calendar_item_id=AssociatedCalendarItemId(id=event.id))
```

But got an error:
```
Traceback (most recent call last):
  File "/opt/project/backend/api/content/views.py", line 180, in propose_time
    for item in items:
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/queryset.py", line 286, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/queryset.py", line 363, in _item_yielder
    for i in iterable:
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/account.py", line 597, in fetch
    shape=ID_ONLY,
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/account.py", line 301, in _consume_item_service
    is_empty, items = peek(items)
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/util.py", line 115, in peek
    first = next(iterable)
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/folders/collections.py", line 190, in find_items
    for i in items:
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/services/common.py", line 424, in _paged_call
    payload = payload_func(**kwargs)
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/services/find_item.py", line 62, in get_payload
    finditem.append(restriction.to_xml(version=self.account.version))
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/restriction.py", line 516, in to_xml
    return self.q.to_xml(folders=self.folders, version=version, applies_to=self.applies_to)
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/restriction.py", line 307, in to_xml
    elem = self.xml_elem(folders=folders, version=version, applies_to=applies_to)
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/restriction.py", line 407, in xml_elem
    constant.set('Value', value_to_xml_text(clean_value))
  File "/home/python/.local/lib/python3.7/site-packages/exchangelib/util.py", line 171, in value_to_xml_text
    raise NotImplementedError('Unsupported type: %s (%s)' % (type(value), value))
NotImplementedError: Unsupported type: <class 'exchangelib.properties.AssociatedCalendarItemId'> (AssociatedCalendarItemId(id='AAMkADg2YmM3ODM2LTM3MTMtNGVjMC05MDA0LTQ3NDU4NTFjZGNlMgBGAAAAAAAosqJKvdcXSpP/q+vqbwR7BwAzIQyfAI5ESbdg/ESrxKSSAAAAAAENAAAzIQyfAI5ESbdg/ESrxKSSAAA74NHwAAA='))
```

I guess i can't filter inbox items by `associated_calendar_item_id` field. But may be it isn't necessary.

Please, could you explain, if it possible to send new invitation with proposed time? And what is the right way to do this if so?

**Comment by denisovkv** [comment]
UPD:

According with algorithm from [this](https://docs.microsoft.com/ru-ru/exchange/client-developer/exchange-web-services/how-to-propose-a-new-meeting-time-by-using-ews-in-exchange) article I expected to get `propose_start` and `proposed_end` fields from MeetingResponse object, but have not found them in MeetingResponse class:

https://github.com/ecederstrand/exchangelib/blob/d19534b39ba6d3a234da5ec595c1d173d5d10726/exchangelib/items/calendar_item.py#L335-L341

So i tried to add desired fields in it:
```python
class MeetingResponse(BaseMeetingItem):
    """MSDN: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/meetingresponse"""
    ELEMENT_NAME = 'MeetingResponse'
    LOCAL_FIELDS = [
        MailboxField('received_by', field_uri='message:ReceivedBy', is_read_only=True),
        MailboxField('received_representing', field_uri='message:ReceivedRepresenting', is_read_only=True),
        DateTimeField('proposed_start', field_uri='meeting:ProposedStart', is_read_only=True),
        DateTimeField('proposed_end', field_uri='meeting:ProposedEnd', is_read_only=True),
    ]
```

And seems like it works!

```python
for item in account.inbox.all().order_by('-datetime_received').iterator():
    if isinstance(item, MeetingResponse):
        for atr in dir(item):
            try:
                if not callable(item.__getattribute__(atr)):
                    print(atr, item.__getattribute__(atr))
            except Exception:
                pass

        break
```
`proposed_start` and `proposed_end` fields have appeared in output:
```
ews_1  | proposed_end 2020-06-23 12:30:00+00:00
ews_1  | proposed_start 2020-06-23 12:00:00+00:00
```

@ecederstrand Please could you add some comments if this way right and have you any plans to add this feature? Thanks for the great library!

**Comment by ecederstrand** [comment]
It looks like MSDN docs are inconsistent here: https://github.com/MicrosoftDocs/office-developer-exchange-docs/issues/94 I'll have the extra fields added until Microsoft returns with an answer.
