### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by tomazmota** [ecederstrand/exchangelib#807]
Hi,

I`m pretty to no exchange lib, I` ve been trying to connect for a project but am getting Invalid Credentials. Tried to go around but to no avail.  

Is there a way to authenticate via the current session or maybe with win32.client?

Code:
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, Configuration,NTLM,Version,Build,Folder,Q
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter

BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

usador= ''
senha=''
servidor= ''
cred=Credentials(username=usador, password=senha)
conf = Configuration(server=servidor, credentials=cred)

conta=Account(primary_smtp_address=usador, config=conf, autodiscover=False, access_type=DELEGATE)

print(conta.root.tree())

But, I`m getting the below:

Traceback (most recent call last):
  File "C:/Users/t/PycharmProjects/a/venv/E.py", line 15, in <module>
    conta=Account(primary_smtp_address=usador,config=conf,autodiscover=False,access_type=DELEGATE)
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\account.py", line 132, in __init__
    self.version = self.protocol.version
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\services\resolve_names.py", line 32, in call
    for elem in elements:
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\services\common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\services\common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\services\common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\util.py", line 814, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Users\t\PycharmProjects\a\venv\lib\site-packages\exchangelib\util.py", line 891, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for ''

Thanks!

**Comment by ecederstrand** [comment]
Debugging failed login is almost impossible on a public list.

There are a couple of possible reasons for this error:
1. The credentials you supplied are in fact correct. Are you sure these credentials are valid for your Exchange server?
1. The server address is wrong. Please ask your Exchange admins for the correct URL to the EWS service, or enable autodiscover to have the URL detected automatically (assuming autodiscover is set up correctly on your server)

**Comment by ecederstrand** [comment]
Hi @tomazmota Did you get anywhere with this?

**Comment by ecederstrand** [comment]
Closing due to timeout. Feel free to reopen if you have additional information on this issue.
