### ISSUE TITLE
Unable to make exchangelib work with existing access_token

### ISSUE THREAD

**Issue by matifayaz** [ecederstrand/exchangelib#852]
A web-application's back-end scheduler currently uses username and password credentials to connect to Outlook mail server and sends/receives emails. I need to replace the authentication with OAuth. The OAuth flow has already been implemented to receive the access tokens and I am storing them to a sqlite database. The SendMail and Read mail function are working fine when were tested with MS Graph API.

Now to replace the username/password credentials with OAuth credentials, I am trying following code:

```python
token=<oauth_access_token_got_from_oauth_flow>
user=<my_outlook_email_address>
client_id=configuration.get('ms_oauth.app_id')
client_secret=configuration.get('ms_oauth.app_secret')

from exchangelib import DELEGATE, IMPERSONATION, Account, Configuration, OAuth2Credentials, OAuth2AuthorizationCodeCredentials, Identity, OAUTH2
from oauthlib.oauth2 import OAuth2Token
credentials = OAuth2AuthorizationCodeCredentials(
    client_id=client_id, client_secret=client_secret, access_token=OAuth2Token(token)
)
config = Configuration(credentials=credentials, auth_type=OAUTH2, service_endpoint='https://graph.microsoft.com')
account = Account(
    user,
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)
```

I get error:

```
Response data: b'{\r\n  "error": {\r\n    "code": "UnknownError",\r\n    "message": "Method not allowed",\r\n    "innerError": {\r\n      "date": "2021-01-23T07:14:48",\r\n      "request-id": "a7494e9e-6ebd-4a15-a9e2-62d7ad171dd5",\r\n      "client-request-id": "a7494e9e-6ebd-4a15-a9e2-62d7ad171dd5"\r\n    }\r\n  }\r\n}'

Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/account.py", line 132, in __init__
    self.version = self.protocol.version
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/resolve_names.py", line 32, in call
    for elem in elements:
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 811, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 892, in _raise_response_errors
    raise TransportError(str('Unknown failure\n') + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
```

Can you help please.

Thanks

**Comment by ecederstrand** [comment]
At a quick glance, the `service_endpoint` is wrong. This package uses the EWS API, not the Graph API. You should use `server = 'outlook.office.com'` instead.

Apart from that, I haven't used the OAuth flow myself so I don't have much experience with it.

**Comment by matifayaz** [comment]
Thank you for the correction of service_endpoint. I've now set it to: `https://outlook.office365.com/EWS/Exchange.amx`

Now, I am getting different errors: 
- `ERROR:exchangelib.util:TypeError: refresh() missing 1 required positional argument: 'session'`
- `TypeError: refresh() missing 1 required positional argument: 'session'`

The token was got a few minutes before the function call and had expiry of default _3600_ seconds. Still if it was expired due to any reason how can we handle the missing session argument error?

Here is the compete trace:

`ERROR:exchangelib.util:TypeError: refresh() missing 1 required positional argument: 'session'
Retry: 0
Waited: 10
Timeout: 120
Session: 24566
Thread: 140299886962496
Auth type: <requests_oauthlib.oauth2_auth.OAuth2 object at 0x7f9a12bb7198>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f9a12bb7240>
Allow redirects: False
Streaming: False
Response time: 0.0018682120135053992
Status code: 401
Request headers: None
Response headers: {'TokenExpiredError': TokenExpiredError('(token_expired) ',)}
Request data: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>e519e5a2-d43a-425e-a499-1f301cf23ede [access_token]</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
Response data: b''

WARNING:exchangelib.services.common:EWS https://outlook.office365.com/EWS/Exchange.asmx, account None: Exception in _get_elements: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 781, in post_ratelimited
    session = protocol.refresh_credentials(session)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/protocol.py", line 244, in refresh_credentials
    self.credentials.refresh()
TypeError: refresh() missing 1 required positional argument: 'session'

Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/account.py", line 132, in __init__
    self.version = self.protocol.version
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/resolve_names.py", line 32, in call
    for elem in elements:
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 781, in post_ratelimited
    session = protocol.refresh_credentials(session)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/protocol.py", line 244, in refresh_credentials
    self.credentials.refresh()
TypeError: refresh() missing 1 required positional argument: 'session'`


Thanks

**Comment by ecederstrand** [comment]
That’s a bug that was fixed in https://github.com/ecederstrand/exchangelib/commit/c32a9c487e94371e036ed5b1a4303314287747e3 but not yet released to pypi.

**Comment by matifayaz** [comment]
Thank you

**Comment by ecederstrand** [comment]
Did that fix your issue? Are you able to successfully authenticate now?

**Comment by matifayaz** [comment]
The 'session' error has gone but got another error. I think the reason is the access token was taken from `Microsoft Graph API` not from `Microsoft EWS Managed API`?

Here is the trace:
`Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/account.py", line 132, in __init__
    self.version = self.protocol.version
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/resolve_names.py", line 32, in call
    for elem in elements:
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/services/common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 811, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/util.py", line 888, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx`

Planning to completely move to MS Graph API.

**Comment by ecederstrand** [comment]
Alright. I'm closing this issue then. Feel free to reopen if you need additional help with this.

**Comment by matifayaz** [comment]
Thank you @ecederstrand 
I think the library should have ability to get Oauth tokens and authorizations also. It would make the lives of the developers easier who are still using `exchangelib` and need Oauth implementation instead of basic username/password auth.

**Comment by ecederstrand** [comment]
I'd like to do that, but I'm not very familiar with the OAuth protocol. Can you explain a bit more, possibly with some example or pseudo-code? The current capabilities are described at https://ecederstrand.github.io/exchangelib/#oauth-authentication

**Comment by matifayaz** [comment]
> I'd like to do that, but I'm not very familiar with the OAuth protocol. Can you explain a bit more, possibly with some example or pseudo-code? The current capabilities are described at https://ecederstrand.github.io/exchangelib/#oauth-authentication

The mentioned link describes that how to use existing oauth access token to access the resources on **The Exchange Web Services (EWS)** but I think there is no information out there on how to get the access tokens.

[microsoftgraph-python](https://pypi.org/project/microsoftgraph-python/), a python wrapper of Microsoft Graph API , can be referred for the sample wrapper functions that are used to obtain the access tokens. 

Thanks

**Comment by ecederstrand** [comment]
Have you granted the app permissions to EWS? See e.g.  https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-627209054
