### ISSUE TITLE
ErrorServerBusy when creating a folder in FMB mailbox

### ISSUE THREAD

**Issue by maktvist** [ecederstrand/exchangelib#872]
Hello.

I faced a problem while creating new folders in FMB mailbox.
This mailbox contains a huge numbers of folders, subfolders and mails.

If I try to create a new folder using this code, I always get **ErrorServerBusy** exception.
```python
credentials = Credentials(user, password)
config = Configuration(server=server, credentials=credentials)
account = Account(primary_smtp_address=address, credentials=credentials, config=config,
                               access_type=DELEGATE)

 folder = Messages(parent=account.msg_folder_root // "Custom Folder", name="Test_Folder")
    folder.save()
```
If I add FaultTolerance to Configuration, it helps, but takes a lot of time, about 15-20 min.

`config = Configuration(server=server, credentials=credentials, theretry_policy=FaultTolerance(max_wait=600))`

Could you please advise how to optimize folder creation in my case?

I'm using: 
Python 3.8.6
exchangelib 3.1.1

Thanks in advance

**Comment by ecederstrand** [comment]
What is `FMB`? Google doesn't giv any obvious answer.

To see what's going on, try [enabling debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting). It's possible that accessing `account.msg_folder_root` triggers fetching all folders. In that case, you'll need to specify the path from `account.root` and down, using the `//` notation.

**Comment by maktvist** [comment]
I mean Shared MailBox. 

This part of code works fine.

`folder = Messages(parent=account.msg_folder_root // "Custom Folder", name="Test_Folder")`

I got an error, when I try to save new folder. 

`folder.save()`

Is there another way to get necessary folder without fetching all folders?

**Comment by ecederstrand** [comment]
If the first line works, then it's probably not fetching all folders.

What kind of error do you get when you try to save? Please post the stack trace.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you find anything in the log output that you think exchangelib could do to improve your use case.

**Comment by maktvist** [comment]
Hello,

Sorry for delay.

I got this error, when i try `folder.save()`

```
Traceback (most recent call last):
  File "C:\Users\Aurora\cldb_cit4/src/run.py", line 23, in main
    main_script.main(logging_run.run_id)
  File "C:\Users\Aurora\cldb_cit4/src\robot\main_script.py", line 26, in main
    create_folder()
  File "C:\Users\Aurora\cldb_cit4/src\robot\mail\email.py", line 55, in create_folder
    customer_folder.save()
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\base.py", line 365, in save
    res = list(CreateFolder(account=self.account).call(parent_folder=self.parent, folders=[self]))
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\base.py", line 631, in parent
    return self.root.get_folder(self.parent_folder_id.id)
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\roots.py", line 70, in get_folder
    return self._folders_map.get(folder_id, None)
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\roots.py", line 171, in _folders_map
    for f in SingleFolderQuerySet(account=self.account, folder=self).depth(
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\queryset.py", line 131, in _query
    for f, complex_f in zip(resolveable_folders, complex_folders):
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\folders\collections.py", line 316, in get_folders
    for f in GetFolder(account=self.account).call(
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\get_folder.py", line 29, in call
    for folder, elem in zip(folders_list, self._pool_requests(
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 541, in _pool_requests
    elems = r.get()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 520, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 70, in _get_elements
    self._handle_backoff(e)
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 209, in _handle_backoff
    raise e
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 66, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 151, in _get_response_xml
    res = self._get_soap_messages(body=body, **parse_opts)
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 258, in _get_soap_messages
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "c:\Users\Aurora\cldb_cit4\venv\lib\site-packages\exchangelib\services\common.py", line 288, in _raise_soap_errors
    raise ErrorServerBusy(msg, back_off=back_off)
exchangelib.errors.ErrorServerBusy: The server cannot service this request right now. Try again later.
```

**Comment by ecederstrand** [comment]
Ok, that's just the server being busy. It's not something exchangelib can do anything about. You can add a retry policy if you want to hide this error from your script and let exchangelib try again automatically.
