### ISSUE TITLE
'WorkingElsewhere' calendar status in 'legacy_free_busy_status' not implemented?

### ISSUE THREAD

**Issue by nohir0** [ecederstrand/exchangelib#88]
Hey

it is possible to set "**WorkingElsewhere**" status in Outlook calender items along with the other:
legacy_free_busy_status: Free
legacy_free_busy_status: Tentative
legacy_free_busy_status: Busy
legacy_free_busy_status: OOF

looks like this is not implemented in your lib?

Traceback (most recent call last):
  File "ews-exchangelib-calendar.py", line 77, in <module>
    main()
  File "ews-exchangelib-calendar.py", line 61, in main
    results.append(get_calendar(participant))
  File "ews-exchangelib-calendar.py", line 41, in get_calendar
    for item in items:
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/queryset.py", line 232, in __iter__
    for val in result_formatter(self._query()):
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/account.py", line 382, in fetch
    yield validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self, folder=folder)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/folders.py", line 1331, in from_xml
    return cls(item_id=item_id, changekey=changekey, account=account, folder=folder, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/folders.py", line 1531, in __init__
    assert v is None or v in self.choices_for_field(k), (v, self.choices_for_field(k))
**AssertionError: (u'WorkingElsewhere', set([u'Tentative', u'NoData', u'Busy', u'Free', u'OOF']))**

thanks for looking into it...

**Comment by ecederstrand** [comment]
Not yet, unfortunately, because that status was introduced in Exchange 2013 and this part of the code doesn't know anything about Exchange versions. It's still a TODO in the code: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/folders.py#L1542

**Comment by ecederstrand** [comment]
For now, you can trick `exchangelib` to accept the new status anyway. Just do this at the top of your code:

```python
CalendarItem.CHOICES['legacy_free_busy_status'].add('WorkingElsewhere')
# Then create your appointment with a 'WorkingElsewhere' status
```
