### ISSUE TITLE
Cannot authenticate using OAuth2

### ISSUE THREAD

**Issue by vatodorov** [ecederstrand/exchangelib#880]
I'm trying to switch to using OAuth2 but hitting into the same issue that has already been described in [#747](https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-626657814)

I followed the example from here https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-627290679 but that returns the error below. If I only use the endpoints as in this comment https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-626657814 I can successfully authenticate.

When using **exchangelib** the authentication is successful, but whatever the next steps is doesn't go through as it is supposed to. During the authentication step I printed the access_token from this line https://github.com/ecederstrand/exchangelib/blob/b790c7a49492304bbeb7f5f7b54b9e653378ea33/exchangelib/protocol.py#L334 and then used it in a GET to https://graph.microsoft.com/v1.0/users/{}/messages and that was successful.

Any idea what the issue might be?

```
from exchangelib import IMPERSONATION, Account, Credentials, OAuth2Credentials, Configuration, OAUTH2, Identity

client_id = <client_id>
client_secret = <client_secret>
tenant_id = <tenant_id>
user = <user@domain.com>

credentials = OAuth2Credentials(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id,
    identity=Identity(primary_smtp_address=user),
)
config = Configuration(
    credentials=credentials,
    auth_type=OAUTH2,
    service_endpoint="https://outlook.office365.com/EWS/Exchange.asmx",
)
account = Account(
    user,
    config=config,
    autodiscover=False,
    access_type=IMPERSONATION
)

{'token_type': 'Bearer', 'expires_in': 3599, 'ext_expires_in': 3599, 'access_token': 'eyJ0e.......Q0PLzfjC_WWV01-YA', 'expires_at': 1616624201.5598578}
{'token_type': 'Bearer', 'expires_in': 3599, 'ext_expires_in': 3599, 'access_token': 'eyJ0e.......0e5LI4K4IDQ', 'expires_at': 1616624202.359624}

Traceback (most recent call last):
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c1b0375811f4>", line 25, in <module>
    access_type=IMPERSONATION
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/account.py", line 125, in __init__
    self.version = self.protocol.version
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/protocol.py", line 427, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/version.py", line 226, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/services/resolve_names.py", line 32, in call
    contact_data_shape=contact_data_shape,
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/services/common.py", line 84, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/services/common.py", line 162, in _get_response_xml
    stream=self.streaming,
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/util.py", line 770, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/Users/valentintodorov/.virtualenvs/py3/lib/python3.7/site-packages/exchangelib/util.py", line 847, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx
```

**Comment by ecederstrand** [comment]
This could be because the OAuth credentials are only valid for the Graph API, and not EWS. You'll have to explicitly grant access to EWS if the credentials don't have that access already.

**Comment by ecederstrand** [comment]
Hi @vatodorov Did you get anywhere with this issue?

**Comment by ecederstrand** [comment]
Closing due t inactivity. Feel free to reopen if you get back to this issue.

**Comment by cmin764** [comment]
Indeed, I feel this were the missing permissions (`EWS.AccessAsUser.All`, `full_access_as_app`) as instructed [here](https://github.com/robocorp/example-oauth-email#microsoft-exchange-outlook), where I got it working. (and had previously the same issue)
