### ISSUE TITLE
Multiple ExtendedProperties fail to parse

### ISSUE THREAD

**Issue by SemaiCZE** [ecederstrand/exchangelib#894]
In Exchange you can have calendar that is synced from internet (ical url). I want to get the url for a specific calendar. My code is following:

```py
class ExternalSharingUrl(ExtendedProperty):
    property_set_id = "F52A8693-C34D-4980-9E20-9D4C1EABB6A7"
    property_name = "ExternalSharingUrl"
    property_type = "String"


class ExternalSharingFolderId(ExtendedProperty):
    property_set_id = "F52A8693-C34D-4980-9E20-9D4C1EABB6A7"
    property_name = "ExternalSharingLocalFolderId"
    property_type = "Binary"

sharing_folder = account.root / "Sharing"

Message.register("sharing_url", ExternalSharingUrl)
Message.register("sharing_folder_id", ExternalSharingFolderId)

for share in sharing_folder.all():
    if share.item_class == "IPM.PublishingSubscription":
        # do something
```

When I specify both extended properties at once, I get an error:
```
Traceback (most recent call last):
  File "/home/petr/Documents/Seznam/sources/calendar-backend/./utils/extest.py", line 97, in <module>
    for share in sharing_folder.all():
  File "/usr/local/lib/python3.9/site-packages/exchangelib/queryset.py", line 273, in __iter__
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/queryset.py", line 348, in _item_yielder
    for i in iterable:
  File "/usr/local/lib/python3.9/site-packages/exchangelib/account.py", line 581, in fetch
    yield from self._consume_item_service(service_cls=GetItem, items=ids, chunk_size=chunk_size, kwargs=dict(
  File "/usr/local/lib/python3.9/site-packages/exchangelib/account.py", line 343, in _consume_item_service
    yield from service_cls(account=self, chunk_size=chunk_size).call(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/services/get_item.py", line 27, in call
    yield BaseFolder.item_model_from_tag(elem.tag).from_xml(elem=elem, account=self.account)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/items/base.py", line 151, in from_xml
    item = super().from_xml(elem=elem, account=account)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/properties.py", line 271, in from_xml
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.FIELDS}
  File "/usr/local/lib/python3.9/site-packages/exchangelib/properties.py", line 271, in <dictcomp>
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.FIELDS}
  File "/usr/local/lib/python3.9/site-packages/exchangelib/fields.py", line 1337, in from_xml
    if self.value_cls.is_property_instance(extended_property):
  File "/usr/local/lib/python3.9/site-packages/exchangelib/extended_properties.py", line 212, in is_property_instance
    xml_obj = ExtendedFieldURI.from_xml(elem=elem.find(ExtendedFieldURI.response_tag()), account=None)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/properties.py", line 271, in from_xml
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.FIELDS}
  File "/usr/local/lib/python3.9/site-packages/exchangelib/properties.py", line 271, in <dictcomp>
    kwargs = {f.name: f.from_xml(elem=elem, account=account) for f in cls.FIELDS}
  File "/usr/local/lib/python3.9/site-packages/exchangelib/fields.py", line 384, in from_xml
    val = self._get_val_from_elem(elem)
  File "/usr/local/lib/python3.9/site-packages/exchangelib/fields.py", line 380, in _get_val_from_elem
    return elem.get(self.field_uri) or None
AttributeError: 'NoneType' object has no attribute 'get'
```

But when I ask for just one of the attributes everything is ok. I also checked the XML request and response with `logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])` and both extended properties are requested and returned.

Request:
```xml
<t:ExtendedFieldURI PropertySetId="f52a8693-c34d-4980-9e20-9d4c1eabb6a7" PropertyName="ExternalSharingLocalFolderId" PropertyType="Binary"/>
<t:ExtendedFieldURI PropertySetId="f52a8693-c34d-4980-9e20-9d4c1eabb6a7" PropertyName="ExternalSharingUrl" PropertyType="String"/>
```

Response:
```xml
<t:ExtendedProperty>
  <t:ExtendedFieldURI PropertySetId="f52a8693-c34d-4980-9e20-9d4c1eabb6a7" PropertyName="ExternalSharingLocalFolderId" PropertyType="Binary"/>
  <t:Value>LgAAAACT/r0YqKJKRr6SCdJHvGkMAQBISlWGGhg7QqYsaRhT14TLAAFnbqwtAAAC</t:Value>
</t:ExtendedProperty>
<t:ExtendedProperty>
  <t:ExtendedFieldURI PropertySetId="f52a8693-c34d-4980-9e20-9d4c1eabb6a7" PropertyName="ExternalSharingUrl" PropertyType="String"/>
  <t:Value>https://neznam.web.com/media/ical/hash/name_moje-skupina.ics</t:Value>
</t:ExtendedProperty>
```

Thanks for looking at this.
-Petr

**Comment by SemaiCZE** [comment]
btw. if anyone is interested into getting/setting external calendar address, see https://blog.lboro.ac.uk/middleware/blog/apps-for-education/programmatically-inserting-internet-calendar-subscriptions-into-outlook-web-access-via-exchange-web-services

**Comment by ecederstrand** [comment]
Thanks for reporting this bug, and the thorough investigation! The referenced commit should fix this.
