### ISSUE TITLE
TransportError / HTTP 404 - FaultTolerance coverage?

### ISSUE THREAD

**Issue by ctu-bcas** [ecederstrand/exchangelib#895]
**Describe the bug**
First, not sure if this is a bug per se or a feature request, maybe it's just an oversight?

Sometimes the exchange server my script is connecting to doesn't behave, and responds with a 404. This causes exchangelib to generate a TransportError.

FaultTolerance is enabled and this catches the majority of transient errors, but not this one. Of course I can catch this error outside of exchangelib, but it feels like this should be covered by FaultTolerance. The error here is also transient; subsequent requests to this mail server will usually work just fine.

**To Reproduce**
I think just trying to connect to a URL that normally gives a 404 response should be enough.

**Expected behavior**
I would like FaultTolerance to also cover TransportError exceptions, and thus gracefully retry the connection in a given amount of time as per the configured behaviour. 

**Log output**
```
Traceback (most recent call last):
  [...]
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/queryset.py", line 273, in __iter__
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/queryset.py", line 348, in _item_yielder
    for i in iterable:
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/account.py", line 581, in fetch
    yield from self._consume_item_service(service_cls=GetItem, items=ids, chunk_size=chunk_size, kwargs=dict(
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/account.py", line 337, in _consume_item_service
    is_empty, items = peek(items)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/folders/collections.py", line 196, in find_items
    yield from FindItem(account=self.account, chunk_size=page_size).call(
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/find_item.py", line 34, in call
    for elem in self._paged_call(
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 641, in _paged_call
    pages = self._get_pages(payload_func, kwargs, expected_message_count)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 607, in _get_pages
    page_elems = list(self._get_elements(payload=payload))
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 203, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 177, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 272, in _get_response_xml
    r, session = self._get_response_and_session(payload=payload, api_version=api_version)
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 234, in _get_response_and_session
    return post_ratelimited(
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/util.py", line 876, in post_ratelimited
    _raise_response_errors(r, protocol)  # Always raises an exception
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/util.py", line 971, in _raise_response_errors
  File "/path/to/project/.venv/lib/python3.8/site-packages/exchangelib/util.py", line 971, in _raise_response_errors
    raise TransportError(
exchangelib.errors.TransportError: Unknown failure in response. Code: 404 headers: {'Content-Type': 'text/html; charset=us-ascii', 'Server': 'Microsoft-HTTPAPI/2.0', 'Date': 'Sun, 18 Apr 2021 03:00:37 GMT', 'X-Cnection': 'close', 'Content-Length': '315', 'Strict-Transport-Security': 'max-age=2592000'} content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>
```

**Additional context**
Python 3.8.5
exchangelib 4.1.0

**Comment by ecederstrand** [comment]
It's a deliberate decision that HTTP 404 are not considered in the retry logic. The reason is that HTTP 404's are usually not recoverable so there's no reason to try again.

Are you saying that you have an Exchange server that sometimes response with an HTTP 404, and sometimes with a valid response? That' pretty broken. Do you have a proxy in front of Exchange that could cause this behaviour?

The logic is located in `exchangelib.util._may_retry_on_error` and is not very easy to override. You *could* do something like this (untested):

```python
import exchangelib.util

tmp = exchangelib.util._may_retry_on_error
def _may_retry_on_error(response, retry_policy, wait):
    if tmp(response, retry_policy, wait):
        return True
    return response.status_code == 404

exchangelib.util._may_retry_on_error = _may_retry_on_error
```

**Comment by ctu-bcas** [comment]
> Are you saying that you have an Exchange server that sometimes response with an HTTP 404, and sometimes with a valid response? That' pretty broken. Do you have a proxy in front of Exchange that could cause this behaviour?

99.99% of the time it's a valid (or recoverable) response. It's impossible to say for sure what is causing the 404, the script only started getting it in the last few days out of a few weeks of operation; I can only speculate that it's downtime due to maintenance. It's an on-premises exchange server under quite heavy load so I imagine it suffers more issues than most. I don't think there's a proxy involved in this case.

Thanks for the tip, and on that note, for a most excellent library!

**Comment by ecederstrand** [comment]
After https://github.com/ecederstrand/exchangelib/commit/882430290a88366c02d7294ccfdd141a1bcdf49d this is easier to customize:

```python
from exchangelib import FaultTolerance, Account, Configuration

class CustomFaultTolerance(FaultTolerance):
    def may_retry_on_error(response, wait):
    if super(). may_retry_on_error(response, wait):
        return True
    return response.status_code == 404


account = Account(config=Configuration(retry_policy= CustomFaultTolerance(), ...), ...)
```

**Comment by ecederstrand** [comment]
I'm closing because I don't think it's a good idea to change the default of raising HTTP 404 immediately, and we now have a supported way of solving this.
