### ISSUE TITLE
OAuth2 Bug?

### ISSUE THREAD

**Issue by michaelmontagne** [ecederstrand/exchangelib#898]
Traceback (most recent call last):
 
I've seen a reference to this previously so upgraded via pip and it still persists?  

```python
 File "<stdin>", line 1, in <module>
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\account.py", line 133, in __init__
    self.version = self.protocol.version
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\protocol.py", line 449, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\resolve_names.py", line 42, in call
    contact_data_shape=contact_data_shape,
 File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 193, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 203, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 177, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 272, in _get_response_xml
    r, session = self._get_response_and_session(payload=payload, api_version=api_version)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 233, in _get_response_and_session
    session = self.protocol.get_session()
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\protocol.py", line 191, in get_session
    self.increase_poolsize()
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\protocol.py", line 161, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\protocol.py", line 259, in create_session
    session = self.create_oauth2_session()
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\protocol.py", line 284, in create_oauth2_session
    raise ValueError('Auth type must be %r for credentials type OAuth2Credentials' % OAUTH2)
ValueError: Auth type must be 'OAuth 2.0' for credentials type OAuth2Credentials
```

**Comment by ecederstrand** [comment]
Can you please post a minimal example that reproduces this error?

It may be that you're trying to use autodiscover for an account on O365. That's not well-tested. There's an example script that should work at https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-627290679

**Comment by michaelmontagne** [comment]
After adjusting the code to match your examples I avoid the OAUTH2 error!  But now a new one that implies I have bad credentials yet I've double checked pretty thoroughly.

from exchangelib import DELEGATE,IMPERSONATION, Credentials, Account, Configuration, Identity,items, ExtendedProperty, Contact, FolderCollection, FaultTolerance, OAuth2Credentials, OAUTH2
from oauthlib.oauth2 import OAuth2Token
useraddress = 'me@my.com'
creds = OAuth2Credentials(client_id="xxx", client_secret="yyy",tenant_id="zzz", identity=Identity(primary_smtp_address=useraddress))
# print (creds)
config = Configuration(service_endpoint='https://outlook.office365.com/EWS/Exchange.asmx', credentials=creds, auth_type=OAUTH2)
# config = Configuration(service_endpoint='https://login.microsoftonline.com/common/oauth2/nativeclient', credentials=creds, auth_type=OAUTH2)
account = Account(useraddress,config=config,autodiscover=False,access_type=IMPERSONATION)

  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 177, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 272, in _get_response_xml
    r, session = self._get_response_and_session(payload=payload, api_version=api_version)
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\services\common.py", line 247, in _get_response_and_session
    timeout=self.timeout or self.protocol.TIMEOUT,
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\util.py", line 876, in post_ratelimited
    _raise_response_errors(r, protocol)  # Always raises an exception
  File "C:\Users\mike\AppData\Roaming\Python\Python37\site-packages\exchangelib\util.py", line 966, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx

**Comment by ecederstrand** [comment]
Have you granted the app permissions to EWS? See e.g.  https://github.com/ecederstrand/exchangelib/issues/747#issuecomment-627209054
