### ISSUE TITLE
Property not valid for object type when iterating over messages on Exchange 2007

### ISSUE THREAD

**Issue by dbreese-keystone** [ecederstrand/exchangelib#909]
**Describe the bug**
When I try to iterate over messages on my Exchange 2007 server, I get `exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type. (field: FieldURI(field_uri='meeting:AssociatedCalendarItemId'))`. 

**To Reproduce**
Connect to Exchange server account (Build 8.3.485.1, autodiscover false, `access_type=DELEGATE`).

Then:

```python
work_folder = my_account.inbox
all_items = work_folder.all()
first = next(all_items[:1])
```

**Expected behavior**
Return the first item in the inbox.

**Log output**
```
Account test@example.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 205, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 568, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 490, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type. (field: FieldURI(field_uri='meeting:AssociatedCalendarItemId'))

Traceback (most recent call last):
  File ".\pac-mailbox.py", line 34, in <module>
    print(next(all_items[:1]))
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\queryset.py", line 273, in __iter__
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\queryset.py", line 348, in _item_yielder
    for i in iterable:
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\account.py", line 581, in fetch
    yield from self._consume_item_service(service_cls=GetItem, items=ids, chunk_size=chunk_size, kwargs=dict(
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\account.py", line 343, in _consume_item_service
    yield from service_cls(account=self, chunk_size=chunk_size).call(**kwargs)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\get_item.py", line 21, in call
    for elem in self._chunked_get_elements(
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 195, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 205, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 568, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Users\dbreese\source\repos\pac-mailbox-python\.venv\lib\site-packages\exchangelib\services\common.py", line 490, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type. (field: FieldURI(field_uri='meeting:AssociatedCalendarItemId'))
```

**Additional context**
Exchangelib 4.2.0
Python 3.8.6

I notice only this one bug regarding this particular field: https://github.com/MicrosoftDocs/office-developer-exchange-docs/issues/94

Not sure if it's related in any way.

**Comment by ecederstrand** [comment]
I can't find any evidence in Microsoft docs that `meeting:AssociatedCalendarItemId` is only supported from a certain Exchange version, but it's possible that it in fact does have the same restriction as AssociatedCalendarItemId  on `ReminderMessageData`.

You can try marking the field as supported from a later Exchange version than the one you're calling. That should tell exchangelib to ignore the field:

```python
from exchangelib import Build
from exchangelib.items.calendar_item import BaseMeetingItem

BaseMeetingItem.associated_calendar_item_id.supported_from = Build(15, 0, 913, 9)

# Your code here
```
