### ISSUE TITLE
Stackoverflow when resolving tois without read permission

### ISSUE THREAD

**Issue by shake0** [ecederstrand/exchangelib#911]
I'm facing a *too many recursions* using version 4.2.0, which is not happening in previous versions. I tried to debug it and from my understanding it seems I don't have permission to read any folder.
I am assuming this by looking at the XML response from resolving Root, where I find that all my *effectiveRights* are false and the error message *No mailbox with such GUID* (which is the same error message previous versions of exchangelib fail with)

What follow is the recursive resolution of *MsgFolderRoot*, starting from `self.tois`

https://github.com/ecederstrand/exchangelib/blob/153faee1044d82a697098330132525f074dd57bc/exchangelib/folders/roots.py#L247

calling the same function here
https://github.com/ecederstrand/exchangelib/blob/153faee1044d82a697098330132525f074dd57bc/exchangelib/folders/roots.py#L223

I'm sorry I can't provide better evidences.

**Comment by ecederstrand** [comment]
Can you please post the stack trace you get with the recursion error?

**Comment by shake0** [comment]
Sorry I can't post on github from work and I can't even send an email to myself.

I had to transcribed the tb manually :facepalm: 

```
Traceback (most recent call last):
  File ".\test.py", line 34, in <module>
    main()
  File ".\test.py", line 29, in main
    for item in account.inbox.all()[:5]:
  File ".env\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File ".env\lib\site-packages\exchangelib\account.py", line 214, in inbox
    return self.root.get_default_folder(Inbox)
  File ".env\lib\site-packages\exchangelib\folders\roots.py", line 247, in get_default_folder
    return self._get_candidate(folder_cls=folder_cls, folder_coll=self.tois.children)
  File ".env\lib\site-packages\exchangelib\folders\roots.py", line 223, in tois
    return self.get_default_folder(MsgFolderRoot)

  [.. squelching 2862 lines repeating L247 and L223 ..]

  File ".env\lib\site-packages\exchangelib\folders\roots.py", line 223, in tois
    return self.get_default_folder(MsgFolderRoot)
  File ".env\lib\site-packages\exchangelib\folders\roots.py", line 227, in get_default_folder
    return super().get_default_folder(folder_cls)
  File ".env\lib\site-packages\exchangelib\folders\roots.py", line 132, in get_default_folder
    return folder_cls.get_distinguished(root=self)
  File ".env\lib\site-packages\exchangelib\folders\base.py", line 764, in get_distinguished
    folder=cls(root=root, name=cls.DISTIGUISHED_FOLDER_ID, is_distinguished=True)
  File ".env\lib\site-packages\exchangelib\folders\base.py", line 449, in resolve
    folders = list(FolderCollection(account=account, folder=[folder]).resolve())
  File ".env\lib\site-packages\exchangelib\folders\collections.py", line 330, in resolve
    additional_fields=additional_fields
  File ".env\lib\site-packages\exchangelib\folders\collections.py", line 397, in get_folders
    shape=ID_ONLY
  File ".env\lib\site-packages\exchangelib\services\get_folder.py", line 32, in call
    shape=shape,
  File ".env\lib\site-packages\exchangelib\services\common.py", line 195, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File ".env\lib\site-packages\exchangelib\services\common.py", line 205, in _get_elements
    yield from self._response_generator(payload=payload)
  File ".env\lib\site-packages\exchangelib\services\common.py", line 179, in _response_generator
    response = self._get_response_xml(payload=payload)
  File ".env\lib\site-packages\exchangelib\services\common.py", line 279, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File ".env\lib\site-packages\exchangelib\services\common.py", line 249, in _get_response
    timeout=self.timeout or self.protocol.TIMEOUT,
  File ".env\lib\site-packages\exchangelib\util.py", line 809, in _post_ratelimited
    stream-stream)

  [ .. requests and python std .. ]

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ecederstrand** [comment]
Thanks for the stack trace! The referenced commit should fix this for you.
