### ISSUE TITLE
Exceptions on MeetingRequest is_read field and decline()

### ISSUE THREAD

**Issue by rajaramsrn** [ecederstrand/exchangelib#915]
**Describe the bug**

Captured couple exceptions on MeetingRequest is_read and decline() that may need fixing. These issues are not blocking me though currently since decline() actually did what I needed.

Background: I just wanted the MeetingRequest messages to be cleanly removed or marked read from inbox even without excluding them by using item_class="IPM.Note" in my filters.

**To Reproduce**

The following query got two MeetingRequest objs

>>> for i in filter_q:
...     print(type(i))
...

<class 'exchangelib.items.calendar_item.MeetingRequest'>
<class 'exchangelib.items.calendar_item.MeetingRequest'>

NOTE 1: is_read is not present for MeetingRequest though the doc using help(MeetingRequest) says it is available from parent. Tried this based on discussion here in [Issue 472](https://github.com/ecederstrand/exchangelib/issues/472 ). Not aware if there are later updates on this topic.

>>> filter_q[0].is_read = True
>>> filter_q[0].save(update_fields=["is_read"])

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items/item.py", line 97, in save
    send_meeting_invitations=send_meeting_invitations
  File "/usr/local/lib/python3.6/site-packages/exchangelib/util.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items/item.py", line 183, in _update
    expect_result=message_disposition != SEND_AND_SAVE_COPY,
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/common.py", line 129, in get
    res = list(self.call(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/update_item.py", line 44, in call
    suppress_read_receipts=suppress_read_receipts,
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/common.py", line 193, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/update_item.py", line 180, in get_payload
    for elem in self._get_item_update_elems(item=item, fieldnames=fieldnames):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/update_item.py", line 91, in _get_item_update_elems
    for field in self._sorted_fields(item_model=item.__class__, fieldnames=fieldnames_copy):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/update_item.py", line 76, in _sorted_fields
    ', '.join("'%s'" % f for f in unique_fieldnames), item_model.__name__))
ValueError: Field name(s) 'is_read' are not valid for a 'MeetingRequest' item

NOTE 2: decline() threw exception. However, it had actually succeeded in removing the meeting request from the inbox. Just this exception

>>> filter_q[0].decline()

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items/calendar_item.py", line 46, in decline
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/exchangelib/util.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items/calendar_item.py", line 374, in send
    send_meeting_invitations=SEND_TO_NONE,
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services/common.py", line 138, in get
    raise ValueError('Expected result length 1, but got %r' % res)

ValueError: Expected result length 1, but got [BulkCreateResult(_id=ItemId(id='AAMGIyY2--snip--L0vAAA=', changekey='Dw--snip--B2VW'), attachments=[]), BulkCreateResult(_id=ItemId(id='AAMk--snip--RAAA=', changekey='CwAA--snip--Vr'), attachments=[])]

**Expected behavior**

Doc on help(MeetingRequest) would need fixing or is_read may have to be populated in order for save(update_fields=["is_read"]) to work. Also the decline() should not throw exception leading to false negative in my case.

**Log output**

Logs/console output in previous section

**Additional context**

exchangelib==4.2.0

**Comment by ecederstrand** [comment]
You shouldn't get the stack trace in `.decline()`. That was fixed in https://github.com/ecederstrand/exchangelib/commit/b1f2f68da3230eb80f9ebcea0659ae5376447f6c and released in exchangelib 4.2.0. Are you sure you got the error with exchangelib 4.2.0?

The referenced commit should fix the issue with the missing `is_read` field.

**Comment by ecederstrand** [comment]
I'm assuming this is fixed. Feel free to reopen if you still have issues.
