### ISSUE TITLE
EWSTimeZone errors out on dateutil.tz.UTC and dateutil local time zones

### ISSUE THREAD

**Issue by laurachan** [ecederstrand/exchangelib#919]
**Describe the bug**
When I try to use EWSTimeZone.from_timezone() on any of dateutil.tz.UTC, dateutil.tz.tzlocal() or dateutil.tz.gettz(), an exception occurs, which means I can't use them for timezone conversions on EWSDateTime instances since EWSDateTime.astimezone() only accepts EWSTimeZone instances.

**To Reproduce**
dateutil.tz.UTC and dateutil.tz.tzlocal() both fail due to an AttributeError:
```
>>> EWSTimeZone.from_timezone(dateutil.tz.UTC)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 268, in from_timezone
    return {
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 255, in from_dateutil
    key = '/'.join(tz._filename.split('/')[-2:])
AttributeError: 'tzutc' object has no attribute '_filename'

>>> EWSTimeZone.from_timezone(dateutil.tz.tzlocal())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 268, in from_timezone
    return {
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 255, in from_dateutil
    key = '/'.join(tz._filename.split('/')[-2:])
AttributeError: 'tzlocal' object has no attribute '_filename'
```

On the other hand, dateutil.tz.gettz() fails with a few nested exceptions:
```
>>> EWSTimeZone.from_timezone(dateutil.tz.gettz())
Traceback (most recent call last):
  File "/usr/lib/python3.9/zoneinfo/_common.py", line 12, in load_tzdata
    return importlib.resources.open_binary(package_name, resource_name)
  File "/usr/lib/python3.9/importlib/resources.py", line 88, in open_binary
    package = _get_package(package)
  File "/usr/lib/python3.9/importlib/resources.py", line 49, in _get_package
    module = _resolve(package)
  File "/usr/lib/python3.9/importlib/resources.py", line 40, in _resolve
    return import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata.zoneinfo.etc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 214, in __new__
    instance = super().__new__(cls, *args, **kwargs)
  File "/usr/lib/python3.9/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key etc/localtime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 268, in from_timezone
    return {
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 256, in from_dateutil
    return cls(key)
  File "/home/laura/venvs/my-project/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 216, in __new__
    raise UnknownTimeZone(e.args[0])
exchangelib.errors.UnknownTimeZone: No time zone found with key etc/localtime
```

**Expected behavior**
Actually, I'd really like it if I could pass a time zone from dateutil.tz straight to EWSDateTime.astimezone() without having to create an EWSTimeZone instance. But if that's not feasible at this time, I'd like to be able to use EWSTimeZone.from_timezone() on the dateutil UTC and local time zones in the same way as a dateutil timezone that was retrieved by name, like in the example from the exchangelib documentation below.
```
dateutil_tz = dateutil.tz.gettz('Europe/Copenhagen')
tz = EWSTimeZone.from_timezone(dateutil_tz)
```

**Log output**
N/A

**Additional context**
The behaviour was reproduced using Python 3.9.2 on Linux and exchangelib 4.3.0, but I will need to support Python 3.8 as well (preferably without a zoneinfo backport).

Thanks!

**Comment by ecederstrand** [comment]
Which version of `dateutil` is this?

**Comment by ecederstrand** [comment]
Regarding the second exception, it seems like `dateutil.tz.gettz()` returns a timezone named `etc/localtime`. That's a really weird timezone and not something exchangelib can work with.

**Comment by ecederstrand** [comment]
I found out how to support `dateutil.tz.UTC`, but for `dateutil.tz.tzlocal()` and `dateutil.tz.gettz()` I think it's simply not possible to find any information in the returned `dateutil` objects that could reliably connect them to official IANA or CLDR timezone names or anything else that Python's `zoneinfo` module understands.

**Comment by laurachan** [comment]
Thanks for the quick reply! I am using dateutil 2.8.1.

Just wondering, are there any plans to support datetime.timezone objects in the future?

**Comment by ecederstrand** [comment]
I don’t think it’s worthwhile because `datetime.timezone` cannot sufficiently represent most actual timezones. From https://docs.python.org/3/library/datetime.html#timezone-objects:

> Objects of this class cannot be used to represent timezone information in the locations where different offsets are used in different days of the year or where historical changes have been made to civil time.

**Comment by laurachan** [comment]
Fair enough. Since it sounds like supporting dateutil's local timezone implementations would be tricky at best, I'll look at alternatives to using dateutil on my end for now. Thanks for looking into this.

**Comment by ecederstrand** [comment]
You’re most welcome. I’ll close the issue since I don’t think dateutil support can be improved.
