### ISSUE TITLE
Proxy Error in Gitlab runner

### ISSUE THREAD

**Issue by Mart1200** [ecederstrand/exchangelib#941]
**Describe the bug**
While trying to connect to the exchange server of my company, i am getting an error:
```
exchangelib.errors.TransportError: HTTPSConnectionPool(host='webmail.*******.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
```
the code is working fine on my local machine. here the code:
```
from datetime import datetime
from datetime import date
import datetime as dt
from exchangelib import Credentials, Account, DELEGATE, Folder, Configuration, CalendarItem, EWSTimeZone
import isodate

import argparse

parser = argparse.ArgumentParser()
 
# Comment this if you dont want to use args
parser.add_argument("-u", "--User", help = "Defines User. Example: YOURUSERNAME")
parser.add_argument("-pw", "--Password", help= "Define the password for your user")
args = parser.parse_args()

from urllib.parse import urlparse
import requests.adapters
from exchangelib.protocol import BaseProtocol

class RootCAAdapter(requests.adapters.HTTPAdapter):
    """An HTTP adapter that uses a custom root CA certificate at a hard coded
    location.
    """
    def cert_verify(self, conn, url, verify, cert):
        cert_file = {
            'Adress': 'Pemfile.pem',
        }[urlparse(url).hostname]
        super().cert_verify(conn=conn, url=url, verify=cert_file, cert=cert)

BaseProtocol.HTTP_ADAPTER_CLS = RootCAAdapter


credentials = Credentials(username=args.User , password=args.Password)
config = Configuration(credentials= credentials, server= 'Adress')
my_account = Account(primary_smtp_address='Adress', credentials= credentials, autodiscover=False, access_type=DELEGATE, config=config)
```
The script is shorten to the relevant parts.

**Expected behavior**
it should connect to the exchange server. The code allready worked and some day it just stopped working and throws the error message.

**Log output**
```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://webmail.***********.com/EWS/Exchange.asmx', Credentials('USERNAME', '********'))'
DEBUG:exchangelib.transport:Requesting b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>USERNAME</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>' from https://webmail.***********.com/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Trying to get service auth type for https://webmail.***********.com/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): webmail.***********.com:443
DEBUG:exchangelib.protocol:No retry: no fail-fast policy
WARNING:exchangelib.protocol:Failed to create cached protocol with key ('https://webmail.***********.com/EWS/Exchange.asmx', Credentials('USERNAME', '********')): HTTPSConnectionPool(host='webmail.***********.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webmail.***********.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/transport.py", line 141, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='webmail.***********.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "coc-calendar.py", line 57, in <module>
    my_account = Account(primary_smtp_address='Martin.Alef@***********.com', credentials= credentials, autodiscover=False, access_type=DELEGATE, config=config)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 126, in __init__
    self.protocol = Protocol(config=config)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 405, in __call__
    raise e
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 400, in __call__
    protocol = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 434, in __init__
    self.config.auth_type = self.get_auth_type()
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 440, in get_auth_type
    service_endpoint=self.service_endpoint, retry_policy=self.retry_policy, api_versions=API_VERSIONS, name=name
  File "/usr/local/lib/python3.6/site-packages/exchangelib/transport.py", line 155, in get_service_authtype
    raise TransportError(str(e)) from e
exchangelib.errors.TransportError: HTTPSConnectionPool(host='webmail.***********.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
DEBUG:exchangelib.protocol:Server webmail.***********.com: Closing sessions
```

**Additional context**
The script is running inside a gitlab runner inside a docker image with python 3.6
**What i have tried**
I allready did ```ping -c exchange.server``` inside the docker image of the gitlab runner. And it received a normal answer.

**Comment by ecederstrand** [comment]
While your proxy server may be responding to ping, it is seemingly refusing TCP connections on port 443. I'll have to talk to your sysadmins about that. There's nothing exchangelib can do about it.

**Comment by Mart1200** [comment]
Ok thank u, will update my progress

**Comment by ecederstrand** [comment]
Closing, but please post your findings here, and feel free to reopen if there's anything we can improve in exchangelib.
