### ISSUE TITLE
Failed to send out the mail with attachment even the size is not so big.

### ISSUE THREAD

**Issue by elaineCoder** [ecederstrand/exchangelib#942]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, describe how other clients like Outlook or OWA behave.
when calling the exchangelib to send out a mail with attachment, request connection ERROR happened as below error message:

```python
No handlers could be found for logger "exchangelib.services.common"
Traceback (most recent call last):
  File "pick_release_exception.py", line 88, in <module>
    main()
  File "pick_release_exception.py", line 83, in main
    email(html)
  File "pick_release_exception.py", line 65, in email
    m.send()
  File "/usr/lib/python2.7/site-packages/exchangelib/items.py", line 692, in send
    res = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=send_meeting_invitations)
  File "/usr/lib/python2.7/site-packages/exchangelib/items.py", line 287, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "/usr/lib/python2.7/site-packages/exchangelib/account.py", line 397, in bulk_create
    send_meeting_invitations=send_meeting_invitations,
  File "/usr/lib/python2.7/site-packages/exchangelib/account.py", line 392, in <genexpr>
    i if isinstance(i, Exception)
  File "/usr/lib/python2.7/site-packages/exchangelib/account.py", line 310, in _consume_item_service
    for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 523, in _pool_requests
    elems = r.get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
requests.exceptions.SSLError: HTTPSConnectionPool(host='mail.deckers.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError('The write operation timed out',),))
```

**To Reproduce**
If applicable, add the shortest possible script that reproduces the error.
below code to call the api to send out the mail

```python
account = Account(
    primary_smtp_address = email_user_name,
    credentials = creds,
    autodiscover=False,
    config=config,access_type=DELEGATE,
)
subject_title = "Pick Release Exception Report " + str(current_date)
m = Message(
    account=account,
    subject=subject_title,
    body = HTMLBody(html),
    to_recipients = [Mailbox(email_address =to) for to in l_recipients],
    cc_recipients=[Mailbox(email_address =cc) for cc in l_cc_recipients],
)
attchF = FileAttachment(
    name='Pick_Release_Exception_Report_'+str(current_date)+'.xlsx',
    content=open(output_file_abspath,'rb').read(),
)
m.attach(attchF)
m.send()
```

**Expected behavior**
expected the mail could be sent out successfully with the attachment

**Log output**
If applicable, add relevant output from [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) .
as the error message show as above

**Additional context**
For example, Python and exchangelib versions.

**Comment by ecederstrand** [comment]
This is just a timeout on the server commotion. That's pretty common for busy Exchange servers.

You should either catch the timeout exception and try again, or use the built-in fault-tolerance support: https://ecederstrand.github.io/exchangelib/#fault-tolerance

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think something could be improved in exchangelib.
