### ISSUE TITLE
problem creating Message

### ISSUE THREAD

**Issue by yeyeric** [ecederstrand/exchangelib#943]
hello,

I'm using python 3.8 and AWS LAMBDA.

Something very strange is happening when I'm trying to send some emails using exchangelib.

My method is like this:

```python
class MicrosoftExchange:
    def __init__(self, username: str = settings.exchange_email_login, password: str = settings.exchange_email_password):
        print('IN MicrosoftExchange.init')
        credentials = Credentials(username, password)
        config = Configuration(
            service_endpoint='https://outlook.office365.com/EWS/Exchange.asmx',
            credentials=credentials,
            auth_type='basic'
        )
        self.account = Account(
            primary_smtp_address=username,
            autodiscover=False,
            config=config,
            access_type=DELEGATE
        )

    def send_mail(self, email_from, email_tos, email_ccs, email_bccs, email_subject, email_html_body, attachments=None,
                  replace_line_break=True):
        time.sleep(0.1)
        print('SEND MAIL - START')
        email_html_body = email_html_body.replace('\n', '<br>') if replace_line_break else email_html_body
        m = Message(
            account=self.account,
            folder=self.account.sent,
            author=email_from,
            to_recipients=email_tos,
            cc_recipients=email_ccs,
            bcc_recipients=email_bccs,
            subject=email_subject,
            body=HTMLBody(email_html_body)
        )
        print('SEND MAIL - Message created')

        if attachments:
            for attachment_name, attachment_content in attachments:
                file = FileAttachment(name=attachment_name, content=attachment_content)
                m.attach(file)
        print('SEND MAIL - Attachments created')

        m.send_and_save()
        print('SEND MAIL - END')
```

My code is always crashing when creating the Message (so before Message created being printed). What is strange is that it raises an exception, and then my app would try again to call the method, which will get processed properly next time until the end (so message is correctly sent, and put in my sent folder). The only thing annoying is that it's always like this and raises error in my app as follows:

```python
EWS https://outlook.office365.com/EWS/Exchange.asmx, account my_email@email.com: Exception in _get_elements: Traceback (most recent call last):  File "/opt/python/cached_property.py", line 70, in __get__    return obj_dict[name]KeyError: 'sent'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/opt/python/cached_property.py", line 70, in __get__    return obj_dict[name]KeyError: 'root'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/opt/python/exchangelib/services/common.py", line 84, in _get_elements    response = self._get_response_xml(payload=payload)  File "/opt/python/exchangelib/services/common.py", line 150, in _get_response_xml    r, session = post_ratelimited(  File "/opt/python/exchangelib/util.py", line 770, in post_ratelimited    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception  File "/opt/python/exchangelib/util.py", line 849, in _raise_response_errors    raise response.headers['TimeoutException']  File "/opt/python/exchangelib/util.py", line 714, in post_ratelimited    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT,  File "/opt/python/requests/sessions.py", line 590, in post    return self.request('POST', url, data=data, json=json, **kwargs)  File "/opt/python/requests/sessions.py", line 542, in request    resp = self.send(prep, **send_kwargs)  File "/opt/python/requests/sessions.py", line 655, in send    r = adapter.send(request, **kwargs)  File "/opt/python/requests/adapters.py", line 498, in send    raise ConnectionError(err, request=request)requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) | [WARNING] 2021-06-29T15:58:05.172Z 44840d8e-d106-4e87-85ed-506e72782fb8 EWS https://outlook.office365.com/EWS/Exchange.asmx, account my_email@email.com: Exception in _get_elements: Traceback (most recent call last): File "/opt/python/cached_property.py", line 70, in __get__ return obj_dict[name] KeyError: 'sent' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/python/cached_property.py", line 70, in __get__ return obj_dict[name] KeyError: 'root' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/python/exchangelib/services/common.py", line 84, in _get_elements response = self._get_response_xml(payload=payload) File "/opt/python/exchangelib/services/common.py", line 150, in _get_response_xml r, session = post_ratelimited( File "/opt/python/exchangelib/util.py", line 770, in post_ratelimited _raise_response_errors(r, protocol, log_msg, log_vals) # Always raises an exception File "/opt/python/exchangelib/util.py", line 849, in _raise_response_errors raise response.headers['TimeoutException'] File "/opt/python/exchangelib/util.py", line 714, in post_ratelimited r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=protocol.TIMEOUT, File "/opt/python/requests/sessions.py", line 590, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/opt/python/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/opt/python/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/opt/python/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

How should I do to avoid this problem? I'm afraid if I put a try/except that it'll ignore the problem and process as if it were OK but it's not properly initiated.

Thanks for your help

**Comment by ecederstrand** [comment]
Your server is closing the connection unexpectedly (`requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`).

If this happens consistently, it could be due to a firewall or other security measure. If it's only intermittent, you can configure a retry policy in exchangelib (see https://ecederstrand.github.io/exchangelib/#fault-tolerance).

**Comment by ecederstrand** [comment]
Closing, but feel free to reopen if you think there's anything we can improve in exchangelib.
