### ISSUE TITLE
An object within a change description must contain one and only one property to modify

### ISSUE THREAD

**Issue by futilestudio** [ecederstrand/exchangelib#958]
I'm trying to update an existing contact. The contact has one Home telephone number. I'm trying to update this contact so it has no Home phone. Instead, it should have one Business phone +44987654321.

The problem is that after calling `save` method, it throws the error at the bottom of this issue.

What I did is - I changed `contact.phone_numbers` to a list of two `PhoneNumber` instances. 

```
exchange_contact = ...
business = PhoneNumber(label='BusinessPhone',phone_number='+44987654321')
home = PhoneNumber(label='HomePhone',phone_number='')
exchange_contact.phone_numbers = [business,home]
exchange_contact.save(update_fields=['phone_numbers'])
```

Error:

```
WARNING:exchangelib.services.common:Account XXX@XXX.DE: Exception in _get_elements: Traceback (most recent call last):
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 216, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 585, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 507, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorIncorrectUpdatePropertyCount: An object within a change description must contain one and only one property to modify.
WARNING:exchangelib.services.common:Account XXX@XXX.DE: Exception in _get_elements: Traceback (most recent call last):
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 216, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 585, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 507, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorIncorrectUpdatePropertyCount: An object within a change description must contain one and only one property to modify.

Traceback (most recent call last):
  File ...
    c...
  File ...
    exchange_contact_updated.save(update_fields=changed_fields,conflict_resolution=ALWAYS_OVERWRITE)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/items/item.py", line 93, in save
    item_id, changekey = self._update(
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/util.py", line 38, in wrapper
    return f(self, *args, **kwargs)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/items/item.py", line 177, in _update
    return UpdateItem(account=self.account).get(
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 134, in get
    res = list(self.call(**kwargs))
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/update_item.py", line 38, in call
    for elem in self._chunked_get_elements(
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 198, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 216, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 585, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/milano/.virtualenvs/XXX/lib/python3.9/site-packages/exchangelib/services/common.py", line 507, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorIncorrectUpdatePropertyCount: An object within a change description must contain one and only one property to modify.

```

Do you have an idea of what's wrong?

**Comment by ecederstrand** [comment]
Thanks for the bug report!

The exception happens because you can't update the home phone number to an empty value.

However, there's a bug where the original home phone number cannot be removed. Here's an example:

```python
business = PhoneNumber(label='BusinessPhone', phone_number='456')
home = PhoneNumber(label='HomePhone', phone_number='123')
contact = Contact(folder=a.contacts, display_name='Foo', phone_numbers=[home]).save()
contact.phone_numbers = [business]
contact.save(update_fields=['phone_numbers'])
contact.refresh()
print(contact.phone_numbers)  # Prints both phone numbers
```

I'm not yet sure how it can be fixed.

**Comment by ecederstrand** [comment]
https://github.com/ecederstrand/exchangelib/commit/fbe392160f4f4ae9cdad7a3a092ecccb4d9548e0 fixes the first issue by raising an exception if `phone_number` is empty.
