### ISSUE TITLE
Python recursion error when checking calendar you have no access to

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#965]
Hi :)

Encountered a bug where a service account is processing user calendars from a list of emails. Not all users have granted the service account access to their calendar, so need to check for access before proceeding.

To this end I connect to the mailbox and use `account.calendar.all().exists()`. If the service account does have permission, this returns right away. If it does not have permission, I get a rather confusing Python recursion error, shown below.

I would expect it to simply fail with a permission error, or a null return from the function, maybe a timeout. Something that can be quickly handled and recovered from. The error itself is originating deep inside other packages, so perhaps they are being sent an object they cannot process? Is there any way to catch this lack of access before and return a permission denied error somehow?

Thanks :)

```
RecursionError: maximum recursion depth exceeded while calling a Python object
Retry: 0
Waited: 10
Timeout: 120
Session: 26165
Thread: 8148
Auth type: <requests.auth.HTTPBasicAuth object at 0x000001958604A370>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x000001958603DDF0>
Allow redirects: False
Streaming: False
Response time: 0.07799999974668026
Status code: 503
Request headers: {'X-AnchorMailbox': '***@***.com'}
Response headers: {}
Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/><t:TimeZoneContext><t:TimeZoneDefinition Id="UTC"/></t:TimeZoneContext></s:Header><s:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:FolderId"/><t:FieldURI FieldURI="folder:ChildFolderCount"/><t:FieldURI FieldURI="folder:EffectiveRights"/><t:FieldURI FieldURI="folder:FolderClass"/><t:FieldURI FieldURI="folder:DisplayName"/><t:FieldURI FieldURI="folder:ParentFolderId"/><t:FieldURI FieldURI="folder:PermissionSet"/><t:FieldURI FieldURI="folder:TotalCount"/><t:FieldURI FieldURI="folder:UnreadCount"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="msgfolderroot"><t:Mailbox><t:EmailAddress>***@***.com</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></s:Body></s:Envelope>'
Response XML: b''
Account ***@***.com: Exception in _get_elements: Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 203, in _get_elements
    yield from self._response_generator(payload=payload)
  File "D:\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 177, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "D:\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 272, in _get_response_xml
    r, session = self._get_response_and_session(payload=payload, api_version=api_version)
  File "D:\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 234, in _get_response_and_session
    return post_ratelimited(
  File "D:\Python\Python39\lib\site-packages\exchangelib\util.py", line 809, in post_ratelimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False, timeout=timeout,
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "D:\Python\Python39\lib\http\client.py", line 331, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "D:\Python\Python39\lib\http\client.py", line 225, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "D:\Python\Python39\lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "D:\Python\Python39\lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "D:\Python\Python39\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "D:\Python\Python39\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ecederstrand** [comment]
Hmm, from the stack trace I can't see where the recursion error is happening. I would expect `account.calendar.all().exists()` to raise `ErrorAccessDenied` if the connecting user does not have access to the folder.

If you can't see it from the debug output, can you try adding a breakpoint and stepping through the code to see how the recursion is happening?

**Comment by RossK1** [comment]
That's what I would expect too, but getting this weird recursion error.

Below is the portion of the debug log for the attempted check. It seems to repeat the same process until finally hitting the recursion limit. The below is two of the repeated entry blocks. It seems that in each case it gets `The specified object was not found in the store., The process failed to get the correct properties.` and `ErrorItemNotFound` errors and maybe (?) exchangelib doesn't recognize what it is saying `No retry: wrong status code 200`. Is this what EWS throws back when trying to access a calendar object it can't see? Is there a way to catch that response and just raise an error rather than it getting stuck in this retry recursion loop?

Thanks :)

```
DEBUG:exchangelib.util:No retry: wrong status code 200
DEBUG:exchangelib.util:Session 25763 thread 11916: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server outlook.office365.com: Releasing session 25763
DEBUG:exchangelib.version:API version "Exchange2016" worked but server reports version "V2018_01_08". Using "Exchange2016"
DEBUG:exchangelib.folders.roots:Searching default <class 'exchangelib.folders.known_folders.MsgFolderRoot'> folder in full folder list
DEBUG:exchangelib.folders.roots:Requesting distinguished <class 'exchangelib.folders.known_folders.MsgFolderRoot'> folder explicitly
DEBUG:exchangelib.services.common:Processing chunk 1 containing 1 items
DEBUG:exchangelib.services.common:Calling service GetFolder
DEBUG:exchangelib.services.common:Trying API version Exchange2016
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session immediately
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session 25763
DEBUG:exchangelib.util:Session 25763 thread 11916: retry 0 timeout 120 POST'ing to https://outlook.office365.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 25763
Thread: 11916
Auth type: <requests.auth.HTTPBasicAuth object at 0x0000024CC3AA6250>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000024CC3AA6160>
Allow redirects: False
Streaming: False
Response time: 0.0940000000409782
Status code: 200
Request headers: {'User-Agent': 'exchangelib/4.1.0 (python-requests/2.25.1)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': '***@***.com', 'Cookie': 'exchangecookie=874a503f4e744496aadde75fb0e83c82', 'Content-Length': '1211', 'Authorization': 'Basic YXV0b21hdGlvbnN2Yy5zZXJ2aWNlQHBlcmtpbmVsbWVyLmNvbTpUdXJudGhpc29uMiE='}
Response headers: {'Cache-Control': 'private', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/10.0', 'request-id': 'a83a5efc-26e9-2319-1586-c6ba3c8261c2', 'X-CalculatedFETarget': 'CY4PR06CU003.internal.outlook.com', 'X-BackEndHttpStatus': '200, 200', 'Set-Cookie': 'exchangecookie=874a503f4e744496aadde75fb0e83c82; path=/; secure', 'X-FEProxyInfo': 'CY4PR06CA0065.NAMPRD06.PROD.OUTLOOK.COM', 'X-CalculatedBETarget': 'CY4PR03MB2967.namprd03.prod.outlook.com', 'X-RUM-Validated': '1', 'x-EwsHandler': 'GetFolder', 'X-AspNet-Version': '4.0.30319', 'X-BeSku': 'Gen9', 'X-DiagInfo': 'CY4PR03MB2967', 'X-BEServer': 'CY4PR03MB2967', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '200', 'X-FEServer': 'CY4PR06CA0065, MN2PR20CA0060', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 19 Aug 2021 15:29:46 GMT'}
DEBUG:exchangelib.util.xml:Request XML: [36m<?xml version='1.0' encoding='utf-8'?>[39;49;00m
[94m<s:Envelope[39;49;00m
    [36mxmlns:s=[39;49;00m[33m"http://schemas.xmlsoap.org/soap/envelope/"[39;49;00m
    [36mxmlns:m=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/messages"[39;49;00m
    [36mxmlns:t=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m[94m>[39;49;00m
  [94m<s:Header[39;49;00m[94m>[39;49;00m
    [94m<t:RequestServerVersion[39;49;00m [36mVersion=[39;49;00m[33m"Exchange2016"[39;49;00m[94m/>[39;49;00m
    [94m<t:TimeZoneContext[39;49;00m[94m>[39;49;00m
      [94m<t:TimeZoneDefinition[39;49;00m [36mId=[39;49;00m[33m"UTC"[39;49;00m[94m/>[39;49;00m
    [94m</t:TimeZoneContext>[39;49;00m
  [94m</s:Header>[39;49;00m
  [94m<s:Body[39;49;00m[94m>[39;49;00m
    [94m<m:GetFolder[39;49;00m[94m>[39;49;00m
      [94m<m:FolderShape[39;49;00m[94m>[39;49;00m
        [94m<t:BaseShape[39;49;00m[94m>[39;49;00mIdOnly[94m</t:BaseShape>[39;49;00m
        [94m<t:AdditionalProperties[39;49;00m[94m>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:FolderId"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:ChildFolderCount"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:EffectiveRights"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:FolderClass"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:DisplayName"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:ParentFolderId"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:PermissionSet"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:TotalCount"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:UnreadCount"[39;49;00m[94m/>[39;49;00m
        [94m</t:AdditionalProperties>[39;49;00m
      [94m</m:FolderShape>[39;49;00m
      [94m<m:FolderIds[39;49;00m[94m>[39;49;00m
        [94m<t:DistinguishedFolderId[39;49;00m [36mId=[39;49;00m[33m"msgfolderroot"[39;49;00m[94m>[39;49;00m
          [94m<t:Mailbox[39;49;00m[94m>[39;49;00m
            [94m<t:EmailAddress[39;49;00m[94m>[39;49;00m***@***.com[94m</t:EmailAddress>[39;49;00m
            [94m<t:RoutingType[39;49;00m[94m>[39;49;00mSMTP[94m</t:RoutingType>[39;49;00m
            [94m<t:MailboxType[39;49;00m[94m>[39;49;00mMailbox[94m</t:MailboxType>[39;49;00m
          [94m</t:Mailbox>[39;49;00m
        [94m</t:DistinguishedFolderId>[39;49;00m
      [94m</m:FolderIds>[39;49;00m
    [94m</m:GetFolder>[39;49;00m
  [94m</s:Body>[39;49;00m
[94m</s:Envelope>[39;49;00m
Response XML: [36m<?xml version='1.0' encoding='utf-8'?>[39;49;00m
[94m<s:Envelope[39;49;00m
    [36mxmlns:s=[39;49;00m[33m"http://schemas.xmlsoap.org/soap/envelope/"[39;49;00m[94m>[39;49;00m
  [94m<s:Header[39;49;00m[94m>[39;49;00m
    [94m<h:ServerVersionInfo[39;49;00m
    [36mxmlns:h=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m
    [36mxmlns:xsd=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema"[39;49;00m
    [36mxmlns:xsi=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema-instance"[39;49;00m [36mMajorVersion=[39;49;00m[33m"15"[39;49;00m [36mMinorVersion=[39;49;00m[33m"20"[39;49;00m [36mMajorBuildNumber=[39;49;00m[33m"4415"[39;49;00m [36mMinorBuildNumber=[39;49;00m[33m"24"[39;49;00m [36mVersion=[39;49;00m[33m"V2018_01_08"[39;49;00m[94m/>[39;49;00m
  [94m</s:Header>[39;49;00m
  [94m<s:Body[39;49;00m[94m>[39;49;00m
    [94m<m:GetFolderResponse[39;49;00m
    [36mxmlns:m=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/messages"[39;49;00m
    [36mxmlns:xsd=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema"[39;49;00m
    [36mxmlns:xsi=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema-instance"[39;49;00m
    [36mxmlns:t=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m[94m>[39;49;00m
      [94m<m:ResponseMessages[39;49;00m[94m>[39;49;00m
        [94m<m:GetFolderResponseMessage[39;49;00m [36mResponseClass=[39;49;00m[33m"Error"[39;49;00m[94m>[39;49;00m
          [94m<m:MessageText[39;49;00m[94m>[39;49;00mThe specified object was not found in the store., The process failed to get the correct properties.[94m</m:MessageText>[39;49;00m
          [94m<m:ResponseCode[39;49;00m[94m>[39;49;00mErrorItemNotFound[94m</m:ResponseCode>[39;49;00m
          [94m<m:DescriptiveLinkKey[39;49;00m[94m>[39;49;00m0[94m</m:DescriptiveLinkKey>[39;49;00m
          [94m<m:Folders[39;49;00m[94m/>[39;49;00m
        [94m</m:GetFolderResponseMessage>[39;49;00m
      [94m</m:ResponseMessages>[39;49;00m
    [94m</m:GetFolderResponse>[39;49;00m
  [94m</s:Body>[39;49;00m
[94m</s:Envelope>[39;49;00m
DEBUG:exchangelib.util:No retry: wrong status code 200
DEBUG:exchangelib.util:Session 25763 thread 11916: Useful response from https://outlook.office365.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server outlook.office365.com: Releasing session 25763
DEBUG:exchangelib.version:API version "Exchange2016" worked but server reports version "V2018_01_08". Using "Exchange2016"
DEBUG:exchangelib.folders.roots:Searching default <class 'exchangelib.folders.known_folders.MsgFolderRoot'> folder in full folder list
DEBUG:exchangelib.folders.roots:Requesting distinguished <class 'exchangelib.folders.known_folders.MsgFolderRoot'> folder explicitly
DEBUG:exchangelib.services.common:Processing chunk 1 containing 1 items
DEBUG:exchangelib.services.common:Calling service GetFolder
DEBUG:exchangelib.services.common:Trying API version Exchange2016
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session immediately
DEBUG:exchangelib.protocol:Server outlook.office365.com: Got session 25763
DEBUG:exchangelib.util:Session 25763 thread 11916: retry 0 timeout 120 POST'ing to https://outlook.office365.com/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 25763
Thread: 11916
Auth type: <requests.auth.HTTPBasicAuth object at 0x0000024CC3AA6250>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000024CC3AA6160>
Allow redirects: False
Streaming: False
Response time: 0.0940000000409782
Status code: 200
Request headers: {'User-Agent': 'exchangelib/4.1.0 (python-requests/2.25.1)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': '***@***.com', 'Cookie': 'exchangecookie=874a503f4e744496aadde75fb0e83c82', 'Content-Length': '1211', 'Authorization': 'Basic YXV0b21hdGlvbnN2Yy5zZXJ2aWNlQHBlcmtpbmVsbWVyLmNvbTpUdXJudGhpc29uMiE='}
Response headers: {'Cache-Control': 'private', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/10.0', 'request-id': '9a9cb121-8ad3-944e-8b4f-5c4c41f5a15f', 'X-CalculatedFETarget': 'CY4PR22CU002.internal.outlook.com', 'X-BackEndHttpStatus': '200, 200', 'Set-Cookie': 'exchangecookie=874a503f4e744496aadde75fb0e83c82; path=/; secure', 'X-FEProxyInfo': 'CY4PR22CA0036.NAMPRD22.PROD.OUTLOOK.COM', 'X-CalculatedBETarget': 'CY4PR03MB2967.namprd03.prod.outlook.com', 'X-RUM-Validated': '1', 'x-EwsHandler': 'GetFolder', 'X-AspNet-Version': '4.0.30319', 'X-BeSku': 'Gen9', 'X-DiagInfo': 'CY4PR03MB2967', 'X-BEServer': 'CY4PR03MB2967', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '200', 'X-FEServer': 'CY4PR22CA0036, MN2PR20CA0060', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 19 Aug 2021 15:29:46 GMT'}
DEBUG:exchangelib.util.xml:Request XML: [36m<?xml version='1.0' encoding='utf-8'?>[39;49;00m
[94m<s:Envelope[39;49;00m
    [36mxmlns:s=[39;49;00m[33m"http://schemas.xmlsoap.org/soap/envelope/"[39;49;00m
    [36mxmlns:m=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/messages"[39;49;00m
    [36mxmlns:t=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m[94m>[39;49;00m
  [94m<s:Header[39;49;00m[94m>[39;49;00m
    [94m<t:RequestServerVersion[39;49;00m [36mVersion=[39;49;00m[33m"Exchange2016"[39;49;00m[94m/>[39;49;00m
    [94m<t:TimeZoneContext[39;49;00m[94m>[39;49;00m
      [94m<t:TimeZoneDefinition[39;49;00m [36mId=[39;49;00m[33m"UTC"[39;49;00m[94m/>[39;49;00m
    [94m</t:TimeZoneContext>[39;49;00m
  [94m</s:Header>[39;49;00m
  [94m<s:Body[39;49;00m[94m>[39;49;00m
    [94m<m:GetFolder[39;49;00m[94m>[39;49;00m
      [94m<m:FolderShape[39;49;00m[94m>[39;49;00m
        [94m<t:BaseShape[39;49;00m[94m>[39;49;00mIdOnly[94m</t:BaseShape>[39;49;00m
        [94m<t:AdditionalProperties[39;49;00m[94m>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:FolderId"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:ChildFolderCount"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:EffectiveRights"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:FolderClass"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:DisplayName"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:ParentFolderId"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:PermissionSet"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:TotalCount"[39;49;00m[94m/>[39;49;00m
          [94m<t:FieldURI[39;49;00m [36mFieldURI=[39;49;00m[33m"folder:UnreadCount"[39;49;00m[94m/>[39;49;00m
        [94m</t:AdditionalProperties>[39;49;00m
      [94m</m:FolderShape>[39;49;00m
      [94m<m:FolderIds[39;49;00m[94m>[39;49;00m
        [94m<t:DistinguishedFolderId[39;49;00m [36mId=[39;49;00m[33m"msgfolderroot"[39;49;00m[94m>[39;49;00m
          [94m<t:Mailbox[39;49;00m[94m>[39;49;00m
            [94m<t:EmailAddress[39;49;00m[94m>[39;49;00m***@***.com[94m</t:EmailAddress>[39;49;00m
            [94m<t:RoutingType[39;49;00m[94m>[39;49;00mSMTP[94m</t:RoutingType>[39;49;00m
            [94m<t:MailboxType[39;49;00m[94m>[39;49;00mMailbox[94m</t:MailboxType>[39;49;00m
          [94m</t:Mailbox>[39;49;00m
        [94m</t:DistinguishedFolderId>[39;49;00m
      [94m</m:FolderIds>[39;49;00m
    [94m</m:GetFolder>[39;49;00m
  [94m</s:Body>[39;49;00m
[94m</s:Envelope>[39;49;00m
Response XML: [36m<?xml version='1.0' encoding='utf-8'?>[39;49;00m
[94m<s:Envelope[39;49;00m
    [36mxmlns:s=[39;49;00m[33m"http://schemas.xmlsoap.org/soap/envelope/"[39;49;00m[94m>[39;49;00m
  [94m<s:Header[39;49;00m[94m>[39;49;00m
    [94m<h:ServerVersionInfo[39;49;00m
    [36mxmlns:h=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m
    [36mxmlns:xsd=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema"[39;49;00m
    [36mxmlns:xsi=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema-instance"[39;49;00m [36mMajorVersion=[39;49;00m[33m"15"[39;49;00m [36mMinorVersion=[39;49;00m[33m"20"[39;49;00m [36mMajorBuildNumber=[39;49;00m[33m"4415"[39;49;00m [36mMinorBuildNumber=[39;49;00m[33m"24"[39;49;00m [36mVersion=[39;49;00m[33m"V2018_01_08"[39;49;00m[94m/>[39;49;00m
  [94m</s:Header>[39;49;00m
  [94m<s:Body[39;49;00m[94m>[39;49;00m
    [94m<m:GetFolderResponse[39;49;00m
    [36mxmlns:m=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/messages"[39;49;00m
    [36mxmlns:xsd=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema"[39;49;00m
    [36mxmlns:xsi=[39;49;00m[33m"http://www.w3.org/2001/XMLSchema-instance"[39;49;00m
    [36mxmlns:t=[39;49;00m[33m"http://schemas.microsoft.com/exchange/services/2006/types"[39;49;00m[94m>[39;49;00m
      [94m<m:ResponseMessages[39;49;00m[94m>[39;49;00m
        [94m<m:GetFolderResponseMessage[39;49;00m [36mResponseClass=[39;49;00m[33m"Error"[39;49;00m[94m>[39;49;00m
          [94m<m:MessageText[39;49;00m[94m>[39;49;00mThe specified object was not found in the store., The process failed to get the correct properties.[94m</m:MessageText>[39;49;00m
          [94m<m:ResponseCode[39;49;00m[94m>[39;49;00mErrorItemNotFound[94m</m:ResponseCode>[39;49;00m
          [94m<m:DescriptiveLinkKey[39;49;00m[94m>[39;49;00m0[94m</m:DescriptiveLinkKey>[39;49;00m
          [94m<m:Folders[39;49;00m[94m/>[39;49;00m
        [94m</m:GetFolderResponseMessage>[39;49;00m
      [94m</m:ResponseMessages>[39;49;00m
    [94m</m:GetFolderResponse>[39;49;00m
  [94m</s:Body>[39;49;00m
[94m</s:Envelope>[39;49;00m
DEBUG:exchangelib.util:No retry: wrong status code 200
```

**Comment by ecederstrand** [comment]
We seem to be recursing in `Root.get_default_folder()` but I've read the code over and over and cannot see why this happens. The returned `ErrorItemNotFound` exception is supposed to be handled.

Can you upgrade to the latest exchangelib and add a breakpoint in `Root.get_default_folder()` and try to find out how this method is called again and again with `folder_cls=MsgFolderRoot`?

**Comment by RossK1** [comment]
Was running on version 4.1.0. Updated to the latest (4.5.0) and it appears to be handling the error properly now without getting stuck in a recursion loop. I'll test in the full process today and report back, but it's looking good :)
```
Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'calendar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\***\testing_exchangelib.py", line 73, in <module>
    account = confirm_calendar_access('***@***.com')
  File "C:\***\testing_exchangelib.py", line 56, in confirm_calendar_access
    account.calendar.all().exists()
  File "D:\Python\Python39\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "D:\Python\Python39\lib\site-packages\exchangelib\account.py", line 182, in calendar
    return self.root.get_default_folder(Calendar)
  File "D:\Python\Python39\lib\site-packages\exchangelib\folders\roots.py", line 254, in get_default_folder
    return self._get_candidate(folder_cls=folder_cls, folder_coll=self.children)
  File "D:\Python\Python39\lib\site-packages\exchangelib\folders\roots.py", line 274, in _get_candidate
    raise ErrorFolderNotFound('No usable default %s folders' % folder_cls)
exchangelib.errors.ErrorFolderNotFound: No usable default <class 'exchangelib.folders.known_folders.Calendar'> folders
```

**Comment by RossK1** [comment]
Yup, looks good. The recursion error does not appear to happen in version 4.5.0 :)

Thanks, @ecederstrand !
