### ISSUE TITLE
Send_and_Save() not working for the mailboxes created using powershell-exchange online package

### ISSUE THREAD

**Issue by PrajjawalBanati** [ecederstrand/exchangelib#968]
**Describe the bug**
I tried to create mailboxes using Powershell exchange online module and the mailboxes were showing in the exchange admin center. Then I created a message object for each email I did use a new message object (by running them in a for loop). It's actually showing one Exception that is:-
`ErrorNonExistentMailbox('The SMTP address has no mailbox associated with it.')`
If I am able to login to the mailbox using outlook then how come it is showing that the following SMTP address has no mailbox associated. With older versions, we never received such errors. 

**To Reproduce**
Try to create an online exchange mailbox using powershell. Then run send_and_save() function for the same.

**Expected behavior**
It should send a mail to the mailbox

**Log output**
```
Exception in send_email_online_mailbox(): No valid version headers found in response (ErrorNonExistentMailbox('The SMTP address has no mailbox associated with it.'))
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\version.py", line 229, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\resolve_names.py", line 52, in _elems_to_objs
    for elem in elems:
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 210, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 228, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 194, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 321, in _get_response_xml
    return self._get_soap_messages(body=body, **parse_opts)
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 418, in _get_soap_messages
    self._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Program Files\Python38\lib\site-packages\exchangelib\services\common.py", line 455, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorNonExistentMailbox: The SMTP address has no mailbox associated with it.
```

**Additional context**
Python using 3.8
Exchangelib using 4.5.0

**Comment by ecederstrand** [comment]
I assume this is a problem that needs to be fixed o the server. Feel free to reopen if you think anything can be improved in exchangelib.
