### ISSUE TITLE
Intermittent crashes - out of memory

### ISSUE THREAD

**Issue by psychameleon** [ecederstrand/exchangelib#99]
90% of the time i run the script it fails, but sometimes it works.I don't know if it's the Exchange server, or what is the issue. Thank you in advance! 

# 1st kind of error:
```sh
WS https://x.x.x.x/EWS/Exchange.asmx, account gnoc.reporting@xx.com: Exception in _get_elements: Traceback (most recent call last):
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 75, in _get_elements
   response = self._get_response_xml(payload=payload)
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 124, in _get_response_xml
   soap_response_payload = to_xml(r.text, encoding=r.encoding or 'utf-8')
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\util.py", line 182, in to_xml
   processed = text.lstrip(BOM).encode(encoding or 'utf-8')
emoryError

raceback (most recent call last):
 File "EmailGrabber.py", line 87, in <module>
   for item in account.inbox.filter(q):
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\queryset.py", line 163, in __iter__
   for val in result_formatter(self._query()):
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\account.py", line 381, in fetch
   for i in GetItem(account=self).call(items=ids, folder=validation_folder, additional_fields=only_fields):
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 419, in _pool_requests
   elems = r.get()
 File "C:\local\Python35-32\lib\multiprocessing\pool.py", line 608, in get
   raise self._value
 File "C:\local\Python35-32\lib\multiprocessing\pool.py", line 119, in worker
   result = (True, func(*args, **kwds))
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 399, in <lambda>
   lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 75, in _get_elements
   response = self._get_response_xml(payload=payload)
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 124, in _get_response_xml
   soap_response_payload = to_xml(r.text, encoding=r.encoding or 'utf-8')
 File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\util.py", line 182, in to_xml
   processed = text.lstrip(BOM).encode(encoding or 'utf-8')
emoryError
```
# 2nd kind of error:
```sh
Fallback to lxml processing of faulty XML
EWS https://x.x.x.x/EWS/Exchange.asmx, account gnoc.reporting@xx.com: Exception in _get_elements: Traceback (most recent call last):
  File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\util.py", line 184, in to_xml
    return fromstring(processed)
  File "C:\local\Python35-32\lib\xml\etree\ElementTree.py", line 1344, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: out of memory: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 75, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\services.py", line 124, in _get_response_xml
    soap_response_payload = to_xml(r.text, encoding=r.encoding or 'utf-8')
  File "C:\local\Python35-32\lib\site-packages\exchangelib-1.7.6-py3.5.egg\exchangelib\util.py", line 191, in to_xml
    root = parse(BytesIO(processed), magical_parser)
  File "src\lxml\lxml.etree.pyx", line 3427, in lxml.etree.parse (src\lxml\lxml.etree.c:81101)
  File "src\lxml\parser.pxi", line 1828, in lxml.etree._parseDocument (src\lxml\lxml.etree.c:118056)
  File "src\lxml\parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:118325)
  File "src\lxml\parser.pxi", line 1736, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:117005)
  File "src\lxml\parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:111249)
  File "src\lxml\parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:105093)
  File "src\lxml\parser.pxi", line 706, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:106801)
  File "src\lxml\parser.pxi", line 646, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:105947)
  File "<string>", line 0
lxml.etree.XMLSyntaxError: <no detail available>
```

**Comment by ecederstrand** [comment]
Indeed it seems you're running into memory issues. Probably you're trying to receive a very large amount of data.

As a first step, try fetching less data, either by tightening your search filter (e.g. a smaller date range) or only requesting the fields you need (`qs.filter(...).only('start', 'end', 'subject', ...)`)

**Comment by psychameleon** [comment]
thanks ! eventually i managed to create a better filter, it seems date_received__range works better:
solution:

dt = datetime.datetime.now()
dt.replace(tzinfo=pytz.utc)
year, month, day = dt.today().year, dt.today().month, dt.today().day
q =  account.inbox.filter(datetime_received__range=(tz.localize(EWSDateTime(year, month, day - 1)),tz.localize(EWSDateTime(year, month, day+1))),subject__contains=SubjectSearch)

( filers only today )
before i used datetime_received__gt  and somehow it filtered all the mails.

THank you!
Cheerio!
