### ISSUE TITLE
Latest version incompatible with AWS Lambda

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#997]
I believe this is documented somewhere on StackOverflow, but couldn't find a ticket in here.
If the latest version of Exchangelib (4.5.2 at the time of writing) is used in a layer in AWS Lambda, it fails to import with the error below. The solution on SO was to downgrade way back to 3.2 and that "fixes" it.
I totally understand that Lambda integration testing is not part of the CI for development of the package, but is there any roadmap to resolve this issue?

Thanks :)

```
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 11, in <module>
from exchangelib import Credentials, Account, Configuration, DELEGATE, HTMLBody, Message
File "/opt/python/lib/python3.9/site-packages/exchangelib/__init__.py", line 3, in <module>
from .account import Account, Identity
File "/opt/python/lib/python3.9/site-packages/exchangelib/account.py", line 12, in <module>
from .folders import Folder, AdminAuditLogs, ArchiveDeletedItems, ArchiveInbox, ArchiveMsgFolderRoot, \
File "/opt/python/lib/python3.9/site-packages/exchangelib/folders/__init__.py", line 16, in <module>
from .roots import Root, ArchiveRoot, PublicFoldersRoot, RootOfHierarchy
File "/opt/python/lib/python3.9/site-packages/exchangelib/folders/roots.py", line 17, in <module>
class RootOfHierarchy(BaseFolder, metaclass=EWSMeta):
File "/opt/python/lib/python3.9/site-packages/exchangelib/folders/roots.py", line 26, in RootOfHierarchy
_subfolders_lock = Lock()
File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implemented
```

**Comment by ecederstrand** [comment]
In the stack trace above, Lambda is complaining about `multiprocessing.Lock`, so that would have to be available or have a viable workaround. Same goes for `multiprocessing.RLock`.

**Comment by ecederstrand** [comment]
I just realized that we're importing `Lock` from the `threading` module everywhere else than this one place. There's no reason to use a multiprocessing-safe lock here, so I changed the import. A thread-safe lock is sufficient.

Can you test exchangelib in AWS Lambda with the referenced patch (5eb9c1160f66ce6a0727ce244c4109d2cf2b53f1)?

**Comment by RossK1** [comment]
Definitely a more elegant solution changing to threading.Lock :wink:

I just did a quick test in Lambda and with that change it appears to work (imports without complaining and is able to connect to an account and send an email).

Nice fix. Thank you!
